### ISSUE TITLE
schedule and repeat local notification

### ISSUE THREAD

**Issue by assafb81** [wix/react-native-notifications#100]
Hi,
I am using RN 0.45.1 and I want to add push notifications (local!!)

1. Is there support for schedule notification in Android, or only in iOS?
2. is there support for notification repetition in iOS and Android? I want the notifications to repeat (if the user ignore or swipe out) the notification and if he click on the notification the notification repetition will be cancelled.

Thanks

**Comment by gchiacchio** [comment]
Hi,
I'd say it's better if the repetition could be set as 'day', 'week', 'month', etc. And not automatically canceled. If the user clicks on the notification the app can handle that and cancel the notification repetition if needed.
Thanks

**Comment by assafb81** [comment]
thanks for the reply.
currently I set the notification with repeat and indeed when the user click on the notification I cancel the notification in 'onNotification' function.
I've encountered a problem that the repeat period in iOS can't be customize, for example 3 minutes or 3.5 minutes, etc...

**Comment by assafb81** [comment]
any update?
can I customize notifications repeat period in iOS? set the repeat period to 3 minutes?
