### ISSUE TITLE
Crash app when recieve Notification in IOS 14

### ISSUE THREAD

**Issue by nqam1904** [wix/react-native-notifications#1009]
Hello! I am experiencing an issue when receiving notifications on an iPhone device with iOS 14 or 15. When I push a real device into the background, I encounter the issue as shown in the image. After building the app on TestFlight, if the app is in the foreground and a notification arrives, it crashes the app in the foreground. On Android 13, it doesn't show in the foreground on all devices. Can you please assist me with this issue?

<img width="1508" alt="image" src="https://github.com/wix/react-native-notifications/assets/45457185/28580c58-c226-4a97-90d7-68ffcd084167">

"react-native-notifications": "^5.1.0",
"react-native": "^0.69.6",

**Comment by nqam1904** [comment]
No one cares about me :<

**Comment by msabree** [comment]
Seems to be caused by calling `completion`. I just commented it out to get by for now.

`
  Notifications.events().registerNotificationReceivedForeground(
    (notification: Notification) => {
      console.log(
        `Notification received in foreground: ${notification.title} : ${notification.body}`,
      );
      // calling this crashes the app :(
      //completion({alert: false, sound: false, badge: false});
    },
  );

  Notifications.events().registerNotificationOpened(
    (notification: Notification) => {
      console.log(`Notification opened: ${notification.payload}`);
      // calling this crashes the app :(
      //completion();
    },
  );
`

**Comment by omartamer-git** [comment]
Any updates on this? I am facing this issue as well.

**Comment by poojagupta-trilogy** [comment]
Any update on this, I am also facing this issue.

**Comment by ceebows** [comment]
Also have issue with. completion handler seems to crash app when i receive a notification in foreground.
iOS is setup according to documentation.

it used to work.

package.json
```
"react-native": "^0.73.2",
"react-native-notifications": "^5.1.0",
```
I am using react navigation as well.
code example (pretty much the same as documentation) inside my main component which is several layers deep inside stack navigators and a navigationcontainer:
```
Notifications.registerRemoteNotifications();

 Notifications.events().registerNotificationReceivedForeground((notification, completion) => {
     console.log(`Notification received in foreground: ${notification.title} : ${notification.body}`);
     completion({
         alert: true,
         sound: true,
         badge: false
     });
 });

 Notifications.events().registerNotificationOpened((notification, completion) => {
     console.log(`Notification opened: ${notification.payload}`);
     completion();
 });
```

**Comment by nqam1904** [comment]
I have successfully fixed it because I initialized twice in React Native, so it caused an error. But I switched to using react-native-push-notification, which is stable and resolves the issue I was facing. Thank you, everyone, for your attention. I request to close the issue here.

**Comment by katwal-dipak** [comment]
This issue still exist, app crashes randomly  when `Notifications.events().registerNotificationReceivedForeground` event is triggred. Not calling `completion` avoids the crash, as a temporary solution.
