### ISSUE TITLE
When I click on the notification on my android app, entire app reloads

### ISSUE THREAD

**Issue by PulasthiAbey** [wix/react-native-notifications#1039]
I have a React Native app with RN version `"react-native": "0.72.7"`, and use `react-native-notification` with version `^5.1.0` for my notification service for both Android and iOS applications.

The notification service works fine in iOS without any issues. The notification service for the Android app has some problems.

I am dealing with a reloading issue for Android versions 11 and above. Following is the scenario for the bug.

### Steps

- Open the Android app and keep it in the background

- Receive notification for the app and click on the notification from the notification center

- The app will open but the entire application gets reloaded

### Accepted Criteria

- The app should not reload when clicking on the push notifications

Can anybody give me some sense into why this is happening?

**Comment by alex-crookes** [comment]
What do you have in your Manifest for hte Launch mode of the Activity? If it's `singleTask` (default, IIRC), you maybe able to try `SingleTop`

**Comment by PulasthiAbey** [comment]
@alex-crookes I tried the `SingleTop`

>Android resource linking failed
`error: 'SingleTop' is incompatible with attribute launchMode (attr) enum [singleInstance=3, singleInstancePerTask=4, singleTask=2, singleTop=1, standard=0]`

I am getting this when I try `SingleTop`. I am using `singleTask` at the moment

**Comment by PulasthiAbey** [comment]
Found a solution for this in a patch for `react-native-notification`.

Find the [patch here](https://gist.github.com/ilight/be7141f45f15e39b6fccfe46ca6e3829)

**Comment by PulasthiAbey** [comment]
Resolved
