### ISSUE TITLE
'React/RCTBridgeDelegate.h' file not found

### ISSUE THREAD

**Issue by ianlenehan** [wix/react-native-notifications#108]
I can not get my project to build, as it keeps failing on this error. 

<img width="358" alt="screen shot 2017-08-20 at 10 08 25 pm" src="https://user-images.githubusercontent.com/16395755/29494736-2247d2ce-85f4-11e7-99bc-eaeccf54ccc1.png">

I have RNNotifications.xcodeproj linked, I have libRNNotifications.a in Link Binary With Libraries and I have added the relevant path to the Header Search Paths (there are also a couple of other entries in there I have seen suggested whilst trying to figure this out). 
<img width="246" alt="screen shot 2017-08-20 at 10 13 41 pm" src="https://user-images.githubusercontent.com/16395755/29494783-dd1e75b2-85f4-11e7-9809-49e6b8b8646d.png">

<img width="600" alt="screen shot 2017-08-20 at 10 10 02 pm" src="https://user-images.githubusercontent.com/16395755/29494754-8a1b03b2-85f4-11e7-8da2-d03fe2a225a6.png">
<img width="507" alt="screen shot 2017-08-20 at 10 10 43 pm" src="https://user-images.githubusercontent.com/16395755/29494757-8ed775de-85f4-11e7-80eb-b0cf41383c30.png">

I've basically spent my entire weekend trying to get OneSignal to work and couldn't, so I am now trying this library and am also getting stuck. Would be awesome if someone could help. Thanks!

**Comment by nedmac101** [comment]
I am getting same error when trying to build. Any fix?
