### ISSUE TITLE
setRegistrationTokenUpdateListener does not return the deviceToken

### ISSUE THREAD

**Issue by seanlau555** [wix/react-native-notifications#109]
I am moving from react-native-push-notification to this one because of the conflict of the RNN-RNPN. However, it does not work in my case. PendingNotifications.getInitialNotification returns undefined and NotificationsAndroid.setRegistrationTokenUpdateListener does not returns deviceToken. 
I can see the result and correct response in Android monitor Logging (App initialized => publishing existing token (dc5oJgMT-qw:APA ...). But, I cannot get any response from JS. What can I do with that? 
I also try the example of this one.
https://github.com/chrise86/rn-notification-navigation
It gives me the same result.

**Comment by seanlau555** [comment]
I found a solution by removing the ReactNativeHost in MainApplication. I don't know why but it works anyway.

Then, the second question is when the device receive A and B notices (A first, then B), tapping or opening B notice will return A. The result is difficult to control using this library. 

I suggest you guest can take the reference of react-native-push-notification. It makes thing simpler, more directly and result oriented.

**Comment by arcollector** [comment]
did you find a solution when tappening on B notification case?

**Comment by GHACCT** [comment]
The token did exist and the event emitter did got called the method below, but it could likely be due to context issue that the event was not received by the JS listener.

    protected void sendTokenToJS() {
        final ReactInstanceManager instanceManager = ((ReactApplication) mAppContext).getReactNativeHost().getReactInstanceManager();
        final ReactContext reactContext = instanceManager.getCurrentReactContext();
        Log.d("reactContext", String.valueOf(reactContext != null && reactContext.hasActiveCatalystInstance())); // logs true
        // Note: Cannot assume react-context exists cause this is an async dispatched service.
        if (reactContext != null && reactContext.hasActiveCatalystInstance()) {
            reactContext.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class).emit(TOKEN_RECEIVED_EVENT_NAME, sToken);
        }
    }

**Comment by arcollector** [comment]
I solved this issue by calling  `NotificationsAndroid.refreshToken();` before           `NotificationsAndroid.setRegistrationTokenUpdateListener(this.onPushRegistered);`

**Comment by kholiavko-roman** [comment]
Does anybody can share an example please ?
I download example by **seanlau555**, inserted next code to `app.js`:

```
NotificationsAndroid.refreshToken();

NotificationsAndroid.setRegistrationTokenUpdateListener(onPushRegistered);

function onPushRegistered(token) {
  console.log('token is');
  console.log(token);
}
```

but I didn`t see the token in console.

**Comment by Thadeu** [comment]
+1

**Comment by Daadler6** [comment]
Has anyone been able to find a fix for this? Without being able to grab the device token on Android this renders the library almost useless. Below is my code.

```
import PropTypes from 'prop-types';
import { Children, Component } from 'react';
import { isAndroid, isIos } from 'react-native-device-detection';
import NotificationsIOS, { NotificationsAndroid } from 'react-native-notifications';

/**
 * Notifications Provider handles all push notification functionality of the app
 * See https://github.com/wix/react-native-notifications for docs
 */
class NotificationsProvider extends Component {
  componentDidMount() {
    if (isIos) {
      NotificationsIOS.requestPermissions();
      NotificationsIOS.addEventListener('remoteNotificationsRegistered', token => console.log(`My Token ${token}`));
    } else if (isAndroid) {
      console.log('******* COMPONENT MOUNTED ******* ');
      NotificationsAndroid.setRegistrationTokenUpdateListener((deviceToken) => {
        console.log(`Push-notifications registered! ${deviceToken}`);
      });

      // On Android, we allow for only one (global) listener per each event type.
      NotificationsAndroid.setNotificationReceivedListener((notification) => {
        console.log(`Notification received on device ${notification.getData()}`);
      });

      NotificationsAndroid.setNotificationOpenedListener((notification) => {
        console.log(`Notification opened by device user ${notification.getData()}`);
      });
    }
  }

  componentWillUnmount() {
    if (isIos) {
      NotificationsIOS.removeEventListener('remoteNotificationsRegistered');
    }
  }

  render() {
    return Children.only(this.props.children);
  }
}

NotificationsProvider.propTypes = {
  children: PropTypes.object.isRequired
};

export default NotificationsProvider;
```

**Comment by arcollector** [comment]
dont use RNN as if it was a Component thing
initialize it before React Native start (AppRegistry.registerComponent)

**Comment by Daadler6** [comment]
@arcollector even so. Wouldn't calling ``` NotificationsAndroid.refreshToken();```  cause the token to be refreshed and thus ```setRegistrationTokenUpdateListener``` would be fired?

**Comment by arcollector** [comment]
it doesnt matter, token will always be the same, token only changes when app is unistalled and isntalled again

**Comment by Daadler6** [comment]
I understand. The issue is that the following code is never being hit no matter where in the app it is placed. I am only able to receive the token by looking through the Android Studio Logs

```   NotificationsAndroid.refreshToken();
      NotificationsAndroid.setRegistrationTokenUpdateListener((deviceToken) => {
        console.log(`Push-notifications registered! ${deviceToken}`);
      });
```

**Comment by lucadegasperi** [comment]
Same here, that code is never hit.

**Comment by Daadler6** [comment]
Looks like it’s an issue for sure. I’ll see if we can pinpoint the problem and open a PR

**Comment by Daadler6** [comment]
@lucadegasperi @Thadeu I solved it by writing native code.... despite I have never written Java in my life lol.

In the GcmToken.js file located in the com.wix.reactnativenotifications directory do the following steps.

import the following

```
import com.wix.reactnativenotifications.core.AppLifecycleFacade;
import com.wix.reactnativenotifications.core.AppLifecycleFacadeHolder;
```

and the following line below "final protected Context mAppContext;"

``` final protected AppLifecycleFacade mAppLifecycleFacade = AppLifecycleFacadeHolder.get();```

it should look like this

```
public class GcmToken implements IGcmToken {

    final protected Context mAppContext;
    final protected AppLifecycleFacade mAppLifecycleFacade = AppLifecycleFacadeHolder.get();

    protected static String sToken;
```

Then overwrite the sendTokenToJs() method as follows:

```
 protected void sendTokenToJS() {
        final ReactContext reactContext = mAppLifecycleFacade.getRunningReactContext();

        // Note: Cannot assume react-context exists cause this is an async dispatched service.
        if (reactContext != null && reactContext.hasActiveCatalystInstance()) {
            reactContext.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class).emit(TOKEN_RECEIVED_EVENT_NAME, sToken);
        }
```

Enjoy your push notification token sent to the Javascript! Please let me know if this works for you guys as I am willing to open a PR to ensure no one has to go through this again.

 @lidanh: Is Wix actively supporting this package? Would you like me to open a PR with the code above to get this bug closed?

**Comment by Thadeu** [comment]
@Daadler6 I'll test, I'll give you a feedback as soon as possible.

Thanks.

**Comment by Daadler6** [comment]
One thing to note as well. I refresh the token... this might not be necessary depending on where you have the listener in your application. 

```
    NotificationsAndroid.refreshToken();
      NotificationsAndroid.setRegistrationTokenUpdateListener((deviceToken) => {
        console.log(`Push-notifications registered! ${deviceToken}`);
      });
```

**Comment by jameshedaweng** [comment]
Is anyone looking at this issue?
I see the same problem here, and haven't been able to get a solution either. One interesting phenomenon that I see is, initially the token is never sent to the JS part. But if the Android app crashed for whatever reason, the token appears.

**Comment by charles001636** [comment]
@Daadler6 Thanks! it works for me.
I forked it to prevent overwrite while running npm/yarn.

**Comment by rickycpadilla** [comment]
After setting up the **Google Play store in my emulator** _and_ adding
`NotificationsAndroid.refreshToken();`
I was finally able to log my device token.

**Comment by ronilitman** [comment]
@Daadler6 Unfortunately this does not work for me, any other suggestions?

**Comment by Daadler6** [comment]
@ronilitman - ended up using https://github.com/zo0r/react-native-push-notification. Much much easier to work with on IOS and Android (especially if you are using Expo)

**Comment by youssefatti** [comment]
@ronilitman Could you check in your android/gradles.properties if android.enableAapt2=false

**Comment by ronilitman** [comment]
@youssefatti Looks like this is working. thank you!

**Comment by ronilitman** [comment]
@youssefatti As I see Aapt1 is going to be deprecated until the end of 2018, so is it ok to use it still?

**Comment by youssefatti** [comment]
@ronilitman yes you can use it for now. i will looking for remove it later. Alternatives !! no clue for now

**Comment by dbelchev** [comment]
@youssefatti Have you figured this out? :)

This will become a serious issue with some of the following Gradle upgrades! I don't know who maintain the package to make a mention in the comment.

**Comment by youssefatti** [comment]
@dbelchev not yet, and im afraid to going througth this issue. and i will need to update my app very soon. i will keep you in touch if any changes

**Comment by msantang78** [comment]
Awesome @MattHaugen that solved it!
Thanks!

**Comment by youssefatti** [comment]
@MattHaugen thanks it works

**Comment by lxcid** [comment]
@MattHaugen excellent debugging and information! Many thanks!
