### ISSUE TITLE
Unified API between iOS and Android

### ISSUE THREAD

**Issue by m-vdb** [wix/react-native-notifications#112]
Hi there,

I'm in the process of choosing a library to perform push notifications. I'm currently under iOS only but in the future I think I'll need Android. So I thought that I should use an additional layer on top of React Native's [PushNotificationIOS](https://facebook.github.io/react-native/docs/pushnotificationios.html) because there is currently no official support for Android notifications from FB guys. I'm seduced by your solution because the project seems very active and you support both platforms, but I'm concerned about the difference between APIs to send such notifications. So I'm wondering if there is a plan to unify both API and if not, I'm wondering why 😄 

Thanks!

**Comment by ntomallen** [comment]
This would definitely be very nice. My solution was to create a `notify.ios.js` file and another `notify.android.js` file. ([See here.](https://facebook.github.io/react-native/docs/platform-specific-code.html#platform-specific-extensions))

_`notify.ios.js`:_
```js
import NotificationsIOS from 'react-native-notifications'
export default function Notify (title, message) {
  NotificationsIOS.localNotification({
    alertBody: message,
    alertTitle: title,
    silent: true
  })
}
```

_`notify.android.js`:_
```js
import { NotificationsAndroid } from 'react-native-notifications'
export default function Notify (title, message) {
  NotificationsAndroid.localNotification({
    title: title,
    body: message
  })
}
```

I only needed local notifications for my use case, and I only needed to set the body and title. This allows me to have the same API for iOS and android when I want to show a basic local notification.
