### ISSUE TITLE
RNNotificationsPackage.java:29: error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by hungdev** [wix/react-native-notifications#118]
Your example it run ok. but when i create new project and follow guide it run error like this
/Users/mac/Desktop/Demo/PNDemo/node_modules/react-native-notifications/android/src/main/java/com/wix/reactnativenotifications/RNNotificationsPackage.java:29: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:reactnativenotifications:compileReleaseJavaWithJavac FAILED
<img width="608" alt="screen shot 2017-08-29 at 10 56 51 am" src="https://user-images.githubusercontent.com/12009276/29803879-ec86b9f0-8ca8-11e7-9117-136cf0fdfe7f.png">

Pakage.json

  "dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.47.2",
    "react-native-notifications": "^1.1.16"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "3.0.1",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  },

}

**Comment by jbolter** [comment]
I believe this is due to a breaking change in RN 0.47+

Same issue here in another lib:
https://github.com/react-native-community/react-native-linear-gradient/pull/193/files?diff=split

**Comment by kaloncheung124** [comment]
Should we downgrade to RN 0.46 for now then?

**Comment by malashkevich** [comment]
Hello! Any solution here?

**Comment by kaloncheung124** [comment]
It's referenced here: https://github.com/wix/react-native-notifications/issues/99

And it seems there's already a PR for it, but nobody's merged it in.

**Comment by lidanh** [comment]
We're working on prioritizing the issues and will provide solutions soon. sorry for the inconvenience.

**Comment by zeedt** [comment]
I resolved this issue by removing the Override annotation, run gradlew clean and  react-native run-android.

**Comment by KrantiKadam** [comment]
@lidanh 
Please inform here, if this fix regarding this issue is merged in main repo and available as npm install...
Thanks!

**Comment by tombailey** [comment]
@lidanh this is an Android/Java issue not iOS. Also, any update on merging the PR? (https://github.com/wix/react-native-notifications/pull/96)
