### ISSUE TITLE
Android Interactive Notifications

### ISSUE THREAD

**Issue by mistyleaf** [wix/react-native-notifications#12]
Hi! Thank you for this awesome project. We're currently using the iOS version and it works really great so far. I was just wondering if you'll also be adding Interactive Notifications feature for Android, and if so what an ETA might be? Can also help you guys beta test if needed.

**Comment by dininski** [comment]
Hi @mistyleaf, you can check out https://github.com/wix/react-native-notifications/issues/4 along with the android branch as it seems that thanks to @amitdwix it is making great progress.

**Comment by lidanh** [comment]
Hi @mistyleaf and thanks for the warm words!  We're working on more advanced features for android, and you're more than welcome to help us and submit PRs.

**Comment by d4vidi** [comment]
Hi all, thanks for the positive feedback! :-)
Our Android code is in fact already highly extensible! While lacking description in our README, it does enable users to apply any feature specified by the [Android notification's native API](https://developer.android.com/guide/topics/ui/notifiers/notifications.html) over the incoming notifications. I'll update the README soon to explain how this can be easily done.

**Comment by dininski** [comment]
Great! One more thing - when could we expect local notifications as this is crucial for my use case. Unfortunately I am not very well versed in Android, otherwise I would be already submitting a PR.

**Comment by d4vidi** [comment]
I'm pretty certain we'll get it sometime next week.

**Comment by d4vidi** [comment]
@dininski Please check out [this new wiki](https://github.com/wix/react-native-notifications/wiki/Android-Customizations) which explains how to customize the notifications. There's no JS API to support customizations (e.g. interactive notifications) but natively, everything is supported.

**Comment by varungupta85** [comment]
hi @d4vidi, I have been closely following this project as I plan to use it once you guys have support for local notifications for Android. One of the features I currently use in my app is notification actions. I have gone through the wiki and understand how could one achieve customizations within the Android notifications and really like the API as it allows a user to support all kind of notifications related workflows that Android supports. My question is that would I be able to send events to the JS side when a user clicks on any actions? I am not sure if I will be able to do that right now. I guess that may be one of the ways the user would want to handle the action from the user by sending an event to the JS side and the JS side can take appropriate actions for the user action.

**Comment by dininski** [comment]
@varungupta85 this is something I am also actively looking forward to. From what I have seen in RN there is currently no simple way to have a notification for music control for an android app, other than writing a lot of Java code to implement the notification as well as the bridge yourself. This seems pretty crippled in terms of functionality for the android version of RN. I have no doubt that the guys will have something that can solve this! Once again thanks @d4vidi for your awesome work so far!

**Comment by d4vidi** [comment]
So currently local notification _are_ [supported on Android](https://github.com/wix/react-native-notifications#android-4) (in 1.1.4). But unlike on iOS, the API doesn't attempt at allowing for customizations inherently. Instead, it is simply an endpoint that forwards your data object (e.g. a _title_ and _message_) onto the same process as of receiving a *remote* push notification.
Adding customization is therefore up to the user - the way you override the `PushNotification` (as [explained by the wiki](https://github.com/wix/react-native-notifications/wiki/Android-Customizations#customizing-notifications-layout)) will determine which notification(s) will be posted.

While this approach is super flexible, I'm currently inspecting ways for providing convenience flows for posting action buttons (and perhaps even the Android 7+ reply).

**Comment by kaelumania** [comment]
How do I implement a JS callback to detect if a user selected a notification action (similar to iOS)?

**Comment by sabbiu** [comment]
What's the current progress for interactive-notifications for Android? I am looking for a push notification with action button.
As per @d4vidi , this [wiki](https://github.com/wix/react-native-notifications/wiki#customizing-notifications-layout) contains the customization in the case for Android. But, I couldn't quite figure it out. Can you guide me to a working project implementing interactive push notification for android?
Also, if you have added this feature, then please guide me to the example.
BTW, great project.
