### ISSUE TITLE
Help with setting up FCM for android on client side

### ISSUE THREAD

**Issue by kaloncheung124** [wix/react-native-notifications#121]
I'm a little confused by step 1 under **Receiving push notifiations** for Android. If I already have a Sender ID and a Server API key, do I also follow [this tutorial completely](https://code.tutsplus.com/tutorials/how-to-get-started-with-push-notifications-on-android--cms-25870) to setup Play Services (including making the RegistrationService)?

Or if I already have these, do I just proceed to step 2?

**Comment by kaloncheung124** [comment]
I think I figured it out by looking at their examples. All step 1 is saying is that you need to get a sender ID and server API key.

**Comment by MWalid** [comment]
Uh, wasted 4 hours trying to get it to work, from the [installation](https://github.com/wix/react-native-notifications/blob/master/docs/installation.md#step-2-add-sender-id-to-manifest-file): `// IMPORTANT: Leave the trailing \0 intact!!!`, my bad! I just don't usually read the comments!
