### ISSUE TITLE
Not getting Notification Received - Foreground/Background/opened events on iOS(, because of jsIsReady = NO)

### ISSUE THREAD

**Issue by KrantiKadam** [wix/react-native-notifications#122]
Refer: RNNotificationsBridgeQueue.m

- (instancetype)init
{
    actionsQueue = [NSMutableArray new];
    notificationsQueue = [NSMutableArray new];
    actionCompletionHandlers = [NSMutableDictionary new];
    **self.jsIsReady = NO;**

    return self;
}

Query: Why jsIsReady is hardcoded as NO? 
If  I change this manually to YES, I able to get all 3 events on receiving PN for iOS in my react-native app. But If we keep this as is.. PN events not get fired, it's only add notification to Q (Ref. + (void)didReceiveRemoteNotification:(NSDictionary *)notification from file RNNotification.m).

Please let me know, is it safe to change this hardcoding of  "jsIsReady" flag?

**Comment by KrantiKadam** [comment]
Is anyone facing same issue?

**Comment by KrantiKadam** [comment]
Thanks for providing fix alexandermtang. When this will be available through npm install? Is there any plan to push this changes to main repo?

**Comment by johnzim** [comment]
@KrantiKadam  This is in the docs - it should probably be a little more clear but it's easy to miss:

You have to call `NotificationsIOS.consumeBackgroundQueue()` - this gets all the previously delivered notifications AND sets `jlsisready` to `YES`

The reason for this is that, if you didn't adopt this approach, you could end up with undelivered notifications as a result of JS still being in a loading state when the IOS app itself isn't.
 
https://github.com/wix/react-native-notifications/blob/master/docs/notificationsEvents.md#background-queue-important---please-read
