### ISSUE TITLE
Unable to use "setRegistrationTokenUpdateListener" for Android PN support

### ISSUE THREAD

**Issue by KrantiKadam** [wix/react-native-notifications#125]
1. I followed the steps given for android react-native-notification support "https://github.com/wix/react-native-notifications"

2. Getting exception at line: 
Notifications.setRegistrationTokenUpdateListener((deviceToken) => {
                console.log('Push-notifications registered!'+ deviceToken)
            });

3. TypeError: Cannot read property 'setRegistrationTokenUpdateListener' of undefined...

Is anyone got success to use this listener method?

**Comment by arcollector** [comment]
import {  NotificationsAndroid} from 'react-native-notifications';

**Comment by KrantiKadam** [comment]
@arcollector 
I already did this. 
1. I am using this library for both iOS and Android.. 
2. So there is common import line and as per platform specific check, I did added platform specific token registration code and required listeners. For iOS it works fine, but android it giving the mentioned error...  Cannot read property 'setRegistrationTokenUpdateListener' 
3. I also tried finding this property reference in notifications-library code of android... unable to find the same.

**Comment by nolan-m** [comment]
You import is not working as you think.  Please post some code of how you are including this with the platform specific logic.

```
import { NotificationsAndroid} from 'react-native-notifications';

NotificationsAndroid.setRegistrationTokenUpdateListener((deviceToken) => {
    console.log('Push-notifications registered!'+ deviceToken)
});
```

The above should work fine.

**Comment by KrantiKadam** [comment]
@nolan-m
Please see my code snippet below:

//Inside App.js
import React, { Component } from "react";
import Notifications from 'react-native-notifications';
import { Platform } from 'react-native';


class App extends Component{
.
.
.
componentDidMount()
    {
       console.log("App > componentDidMount: ");
        
         //Register for PN   
       if(Platform.OS === 'ios')
       {
           Notifications.addEventListener('remoteNotificationsRegistered', this.onPushRegistered.bind(this));
           Notifications.addEventListener('remoteNotificationsRegistrationFailed', this.onPushRegistrationFailed.bind(this));         
           Notifications.requestPermissions();
       }
      else if(Platform.OS === 'android')
       {
           Notifications.setRegistrationTokenUpdateListener((deviceToken) => {
               console.log('Push-notifications registered!'+ deviceToken)
           });

           // On Android, we allow for only one (global) listener per each event type.
            Notifications.setNotificationReceivedListener((notification) => {
                console.log("Notification received on device"+ notification.getData());
            });

          Notifications.setNotificationOpenedListener((notification) => {
               console.log("Notification opened by device user"+ notification.getData());
           });
       }
}//end of componentDidMount

.
.
.

}
----------------------------------------------------------

Also I verified required linking in side android code, that also looks fine as mentioned in installations steps.

Please let me know, if you see any issue in my code while using Andorid specific notification methods.

**Comment by nolan-m** [comment]
You are not importing the library correctly.  Please see the docs.

https://github.com/wix/react-native-notifications#register-to-push-notifications

`import NotificationsIOS,  {NotificationsAndroid}  from 'react-native-notifications';`

**Comment by KrantiKadam** [comment]
@nolan-m 
Thanks for point out that. I changed the import statement as per your suggestion and instructions given at library link. Now my app receives deviceToken for Android too. I will change that import naming for iOS as well though it's working correctly for now.
I wondered how it was working with import as 'Notification' for iOS. Do you have any hint? 

Thanks a lot !!!

**Comment by nolan-m** [comment]
@KrantiKadam 

If you go back and read through the docs, you will see this library exports the iOS methods by default.  In your original import statement, you were only getting the iOS side.   When a file has a default export it doesn't matter what variable you use when importing it.   You could even do
`import BlahBlahSomethingNotification from 'react-native-notifications';`  The Android side need to be specifically imported.



This is breakdown of how to import each set of functionality.  Hopefully it will clear things up.

Import only iOS
`import NotificationsIOS from 'react-native-notifications';`

Import only Android
`import { NotificationsAndroid } from 'react-native-notifications';`

Import both iOS and Android
`import NotificationsIOS, { NotificationsAndroid } from 'react-native-notifications';`

**Comment by KrantiKadam** [comment]
@nolan-m 
Thanks for the clarification, now I got the reason for these different export ways. 
Closing this issue now!!!

Thanks and regards,
Kranti
