### ISSUE TITLE
All Notifications of the App getting cleared when I click one notification (Android)

### ISSUE THREAD

**Issue by ravirajn22** [wix/react-native-notifications#126]
This issue happens only on android, when I have more than one notification for the App and if I click any one, then all other notifications of the App is getting cleared automatically. What could be the problem or should I add any flags etc ?

Checked on 
Android 4.4 and 5.0
React-Native 0.43.0-rc.4
React-Navigation  1.0.0-beta.11

**Comment by Lastin** [comment]
In your custom notification class extending `PushNotification`, returned by `getPushNotification(...)`, override function `onOpened`, so it looks like this:
```
@Override
public void onOpened() {
    digestNotification();
}
```

**Comment by ravirajn22** [comment]
@Lastin thanks for the reply I will try your solution and respond back.

**Comment by Lastin** [comment]
@ravirajn22 You will have to make your notifications work however.
In `com.wix.reactnativenotifications.core.NotificationIntentAdapter` function `createPendingNotificationIntent` uses flag [**`PendingIntent.FLAG_ONE_SHOT`**](https://developer.android.com/reference/android/app/PendingIntent.html#FLAG_ONE_SHOT) when calling `PendingIntent.getService` which causes the pending intent with same hash [(see)](https://developer.android.com/reference/android/app/PendingIntent.html#toString()) to not be able to run activity more than once.
**Solution:**
Use [`PendingIntent.FLAG_UPDATE_CURRENT`](https://developer.android.com/reference/android/app/PendingIntent.html#FLAG_UPDATE_CURRENT) flag instead

**Comment by kaloncheung124** [comment]
This caused an issue for me. When I received multiple notifications, tapping on any notification would always bring up most recently received notification. Instead, I followed the advice here: https://stackoverflow.com/questions/28091784/multiple-pending-intents

So now my createPendingNotifications method in core/NotificationIntentAdapter looks like this:

    public static PendingIntent createPendingNotificationIntent(Context appContext, Intent intent, PushNotificationProps notification) {
        intent.putExtra(PUSH_NOTIFICATION_EXTRA_NAME, notification.asBundle());
        intent.setAction(Long.toString(System.currentTimeMillis()));
        return PendingIntent.getService(appContext, PENDING_INTENT_CODE, intent, PendingIntent.FLAG_ONE_SHOT);
    }
And it seems to work as intended.

**Comment by ravirajn22** [comment]
@kaloncheung124 is there a possibility of solving this problem through java, but without making any changes to the library directly. Like overriding functions of library etc. I thought of overriding getCTAPendingIntent() where createPendingNotificationIntent() is called, but don't know if it creates any side effects.

**Comment by mfekim** [comment]
@ravirajn22 Maybe my comment in the following issue can help you : https://github.com/wix/react-native-notifications/issues/143#issuecomment-361987796

**Comment by kaloncheung124** [comment]
@ravirajn it looks like @mfekim has a great solution that doesn't require overwriting the library. If you still end up wanting to modify the library though, here's the commit with my full solution: https://github.com/kaloncheung124/react-native-notifications/commit/1f10e052a526dcdecdaa000e32ca087f77936049

**Comment by ravirajn22** [comment]
@kaloncheung124 and @mfekim I ended up overriding the getCTAPendingIntent() and onOpened(). Thanks for your help.
