### ISSUE TITLE
Schedule notification on android

### ISSUE THREAD

**Issue by RobertHeim** [wix/react-native-notifications#127]
Hi,

fireDate is not supported on Android. 

1) Are there any plans to support it?

2) Any suggestions on how to schedule it currently?

Best

**Comment by daialogue** [comment]
Hi @RobertHeim,  did you manage to solve this by yourself?
Is there already an answer for this question?

**Comment by RobertHeim** [comment]
@daialogue We used https://github.com/zo0r/react-native-push-notification and implemented our own scheduling algorithm using local notifications from that lib.

**Comment by cinder92** [comment]
any update about this?

**Comment by CheapSeth** [comment]
I am curious too, I just finished the setup and assumed the same API would work on both platforms, but setting fireDate on Android does not work.

**Comment by daveyleo** [comment]
Same problem for me.  Any plans?
