### ISSUE TITLE
silent remote push notification

### ISSUE THREAD

**Issue by johnwnowlin** [wix/react-native-notifications#128]
Is it possible and is there an example of a remote push notification that is not automatically displayed in the notification area by the OS, but is instead only sent to the setNotificationReceivedListener call back function?

**Comment by calcazar** [comment]
I stumbled upon this as well and found something interesting as I was looking through WIX's source and found this tidbit of code

`    
@Override
    public void onReceived() throws InvalidNotificationException {
        postNotification(null);
        notifyReceivedToJS();
        if (mAppLifecycleFacade.isAppVisible()) {
            notifiyReceivedForegroundNotificationToJS();
        }
    }
`

Looking at the above code snippet under PushNotication.JAVA you can see that postNotification is being called on received. Even if we send a silent/noisy push, postNotification will always be called. If you want to fix it, you would have to change the above to:

`
@Override
    public void onReceived() throws InvalidNotificationException {
        notifyReceivedToJS();
        if (mAppLifecycleFacade.isAppVisible()) {
            notifiyReceivedForegroundNotificationToJS();
        } else {
            postNotification(null);
        }
    }
`

Is this something we want to do? If so I can create a PR for it but this seems like it would be a breaking change for those relying on silent pushes to display on the Android side of things..

**Comment by calcazar** [comment]
@lidanh @d4vidi 

Would you guys have any ideas on why Android was coded to show silent pushes to begin with?
