### ISSUE TITLE
Check Permissions

### ISSUE THREAD

**Issue by sticknor** [wix/react-native-notifications#13]
Hi! First off, I'm very appreciative for this package!
I'm using it on an iOS project for now, and on Android in the next couple of weeks.

I was wondering if there will be a checkPermissions method, or even something along the lines of permissionsDidChange...

Thanks!
Sam

**Comment by lidanh** [comment]
Not yet, but you're more than welcome to PR :)

**Comment by hammadj** [comment]
Submitted a PR for this: #36
