### ISSUE TITLE
Build failed on Android

### ISSUE THREAD

**Issue by gsdias** [wix/react-native-notifications#131]
Hello guys,

I'm having an issue with this component

`:app:transformClassesWithJarMergingForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/iid/zzc.class`

If I comment this component it builds fine, but once I use it, I get the above error.

Can anyone help me find the solution for this?

**Comment by Titozzz** [comment]
You have conflicting version of play services with your packages
Happens when you have multiple depedencies... You can fix it like that

compile (project(':react-native-device-info')){
        exclude group: "com.google.android.gms"
    }
    compile (project(':react-native-maps')) {
        exclude group: "com.google.android.gms"
    }
    compile(project(":react-native-google-signin")){
        exclude group: "com.google.android.gms"
    }
    compile 'com.google.android.gms:play-services-base:11.4.2'
    compile 'com.google.android.gms:play-services-maps:11.4.2'
    compile 'com.google.android.gms:play-services-gcm:11.4.2'
    compile 'com.google.android.gms:play-services-auth:11.4.2'

**Comment by frangeris** [comment]
For future references, using [FCM](https://firebase.google.com/docs/cloud-messaging/):

```
    compile (project(':react-native-notifications')) {
      exclude group: 'com.google.android.gms';
    }
    compile "com.google.firebase:firebase-messaging:11.8.0"
```

@d4vidi Close this plz...

**Comment by jrods** [comment]
I am running into this issue with installing version 1.3.0 but using the exclude group does not work for me.
