### ISSUE TITLE
Abstraction Layer on NotificationsIOS and NotificationsAndroid

### ISSUE THREAD

**Issue by kaelumania** [wix/react-native-notifications#138]
Do you plan to add an abstraction layer above NotificationsIOS and NotificationsAndroid to cover both platforms with a single codebase? Or are both systems to much different?

**Comment by pietro909** [comment]
We implemented a mediator in our codebase, and it overall contains ~100 lines of JS.
I wish we could integrate a solution like this also in the package.

**Comment by kaelumania** [comment]
@pietro909 could you post an example how you did that? Do you support custom actions both on ios and android?
