### ISSUE TITLE
Enhance cancelLocalNotification API

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-notifications#14]
In `react-native` `cancelLocalNotification` API, we can cancel a local notification based on the `userInfo` object that was provided when the notification was scheduled. So, I don't need to remember the notification ID for some event in order to cancel the notification.

In the current API in this package, I need to remember the notification ID for the notification of some event if I want to cancel it in future which is kind of a hassle. I can't even just have a map to map the event ID to notification ID because when the app is closed, the in-memory map will be flushed. So, I need to maintain this info in `AsyncStorage`. We can't also provide the notification ID when the notification is scheduled so that we can just have an algorithm to compute the notification ID for an event based on some properties of the event which will compute a same and unique notification ID for an event every time.

The use case is very common in reminders/alarms kind of apps where user schedules to be notified sometime in the future for some event but then changes the time of the event or cancel the event itself.

I think the API provided by `react-native` `PushNotificationIOS` to cancel local notification is very accommodating where we can just provide a `userInfo` object to cancel the notification and if there is any scheduled notification with the same `userInfo` object, it will be canceled. I think we should have something similar here too.

**Comment by lidanh** [comment]
I agree, we will support both
