### ISSUE TITLE
ios instructions should have NotificationsIOS.consumeBackgroundQueue()

### ISSUE THREAD

**Issue by roocell** [wix/react-native-notifications#142]
couldn't get any notifications (like onNotificationReceivedBackground() for example)

until I added this in my constructor
    NotificationsIOS.requestPermissions();
    NotificationsIOS.consumeBackgroundQueue();  // added

**Comment by ChakirMrabet** [comment]
This is **PRETTY CRITICAL**, I've spent 2 days scratching my head trying to figure out why the library wasn't working on iOs, until I added the two lines from @roocell .

This should be in the documentation.

Thanks.

**Comment by allthetime** [comment]
@roocell @ChakirMrabet either one of you can modify the doc and put in a pull request!
