### ISSUE TITLE
Example project doesn't build

### ISSUE THREAD

**Issue by rsml** [wix/react-native-notifications#144]
Steps to reproduce:
```
git clone https://github.com/wix/react-native-notifications.git
cd react-native-notifications/example
npm install
react-native run-ios
```

Error message:
```
Check dependencies
Argument list too long: recursive header expansion failed at /Users/ross/react-native-notifications/example/ios/../node_modules/react-native-notifications/example/node_modules/escodegen-wallaby/node_modules/source-map/test.
```

This is because xcode does not support file paths that are too long.

I tried to globally rename "react-native-notifications" to "rnn", but now I'm receiving a new error on this line in RNNotifications.m: 
`#import "RCTBridge.h"`

The error message is:  `'RCTBridge.h' file not found`

Is anyone else able to get the example app working on iOS?

I'm using:
```
node 8.3.0
npm 5.3.0
```

Also, the example app is using react-native@0.38.0 and react@15.4.1. Has anyone been able to get interactive notifications working on a newer version of react-native? I'm hoping to use them with react-native@0.48.3.

**Comment by minhphung210** [comment]
same issuse
