### ISSUE TITLE
Android open blank white screen after open the app from pressing the notification from the notification center

### ISSUE THREAD

**Issue by ko100v** [wix/react-native-notifications#150]
I have followed the installation guide and manage to recieve a notifications from GCM actually i'm using **AWS SNS** as notification sender connected to my backend.

# The issue: 
When the notification is opened from the notification center, i'm waiting a NotificationOpen listener to be fired up, but instead a blank white screen is opened and nothing happen until i press the back button. Then the app navigate somehow ... to the previous open screen and then the NotificationOpen listener is fired up. I have even set AppState listener to check the appState but unfortunately it doesn't fired up until i press the back button too. 
Does anyone know from where this blank white screen is opened and how i can prevent it ? or at least have code control  so i can remove it ... 

# The AWS SNS PAYLOAD
{
"GCM": "{ \"data\": { \"title\": \"title\", \"body\": \"body\" } }"
}

# The Notification Payload
{
body : "body"
google.message_id : "0:1510055040567680%159408c5f9fd7ecd"
google.sent_time : 1510055040556
title : "title"
}

**Comment by chrise86** [comment]
@ko100v how did you resolve your issue?
