### ISSUE TITLE
Not Receiving Push Notification when app is killed on android device

### ISSUE THREAD

**Issue by java-developer188** [wix/react-native-notifications#151]
I am currently working with RN0.44 , everything working fine on emulator , however on physical android device i am only able to receive push notification (remote) when app is running or at least it is in background, but when i kill the app i am unable to receive notifications.

I have also checked the settings for my app but no luck.

**Comment by kunall17** [comment]
@java-developer188 Have you found a solution to this, as I'm facing this problem too.

I think this is because of the new android changes?
Which android are you using?

**Comment by java-developer188** [comment]
No not yet, i was busy in some other stuff,but  I need it working,expecting some assistnce here, and currently i m using android6.0 

And yes u r ryt new version is giving issue otherwise i tested on older version it is working fine there

**Comment by faketon** [comment]
i use fcm and android 7.0 
it works fine but notification twice.
i have probelm with this

**Comment by undef1ned** [comment]
Check this https://github.com/wix/react-native-notifications/issues/170
