### ISSUE TITLE
Local Notification related queries: un-cancellable or action callback??

### ISSUE THREAD

**Issue by sabbiu** [wix/react-native-notifications#154]
I wanted to know if the following features are available?

1.  Can we push a notification that cannot be cleared by the user? And, receive a callback when user taps it, and then cancel it in the program itself.
2. I looked into [this wiki](https://github.com/wix/react-native-notifications/wiki/Android:-working-with-RNN), but couldn't quite figure it out. Do you have project implementing such custom notification that you can guide me to? I wanted to know, how do I run a callback function once the action is clicked/tapped.

This context for this question is:
The app is performing some background task. And, when the user minimizes the app, the notification must be shown saying, 'Task is running...'. And, then user shall be able to tap the notification or press an action button to get into the app.. (considering that, there is no other way of clearing the notification... but, when the user kills the app, then the notification can be cancelled)

**Comment by manawaraquevix** [comment]
I am also looking to receive a callback when user taps local notification. I am not able to figure out from wiki.

**Comment by miquelferrandiz** [comment]
I had this issue and believe it stems from that the notification payload is JSON stringified, and JSON stringify isn't compatible with function types.

So when trying to pass in a callback function to userInfo, it was returned as null. Not sure if this is the same issue you are experiencing though.

The solution for me was to define a dictionary with callback function corresponding to the notification category, then look up that callback function using the notification category upon receiving the notification.

**Comment by zoobibackups** [comment]
any solution for this
