### ISSUE TITLE
I recently updated Android Studio to 3.0.1 and am now running into "Permission name C2D_MESSAGE is not unique" errors

### ISSUE THREAD

**Issue by smokinjoe** [wix/react-native-notifications#158]
I've updated a bit of my project and have run into these set of errors:

```
Error:(10) Error: Permission name C2D_MESSAGE is not unique (appears in both ${applicationId}.permission.C2D_MESSAGE and ${applicationId}.permission.C2D_MESSAGE) [UniquePermission]

Error:Execution failed for task ':app:lintVitalRelease'.
> Lint found fatal errors while assembling a release target.
  To proceed, either fix the issues identified by lint, or modify your build script as follows:
  ...
  android {
      lintOptions {
          checkReleaseBuilds false
          // Or, if you prefer, you can continue to check for errors in release builds,
          // but continue the build even when errors are found:
          abortOnError false
      }
  }
  ...
```

I have frankly no idea how to resolve this as the issues exist in `projectName/node_modules/react-native-notifications/android/src/main/AndroidManifest.xml`

Before I start messing with those files I'd like to throw out the problem here to see if maybe I need to update or perhaps roll-back to an older version of the package.

Let me know if there's anything else that I could provide to possibly help (only other significant action I've done is updating to High Sierra).

**Comment by koansang** [comment]
+1 same issue..

**Comment by whhotw** [comment]
+1

**Comment by fbaskara** [comment]
+1 
same issue here.

**Comment by Jp3rd** [comment]
I only have this issue when I try to build a production version of the app.

**Comment by qiixiao** [comment]
+1

**Comment by bernabe9** [comment]
+1

**Comment by enerdevelop** [comment]
You must find file like lint-results-release-fatal.xml or lint-results-release-fatal.html in project folders (use file explorer).
There are full description about current error.

**Comment by mo3tafatayebi** [comment]
+1

**Comment by noushinsoft** [comment]
i have this problem too

**Comment by cisplRejjak** [comment]
Same problem
