### ISSUE TITLE
iOS Notification Actions not fired from "dead" state

### ISSUE THREAD

**Issue by lucadegasperi** [wix/react-native-notifications#159]
I'm using the latest version of this package and I'm encountering a problem with notification actions on iOS when the app is in the "dead" state, when it's in background everything works fine.

If I attach the remote debugger to the app, when waking up from the "dead" state the app seems to bypass the fact that a notification action was pressed.

Any clue on what might be causing this?
I've attached my notification event listeners outside the component and straight into the index.ios.js file.

**Comment by krzysztof-miemiec** [comment]
I have the same issue, actions aren't triggered when app is turned off.
