### ISSUE TITLE
notificationReceivedBackground didn't fire

### ISSUE THREAD

**Issue by waynehong** [wix/react-native-notifications#16]
I have run the example, notificationReceivedForeground and notificationOpened work fine.But notificationReceivedBackground didn't fire, is there any possible reason cause this?

**Comment by guns2410** [comment]
Having similar issues.

**Comment by devLaaziz** [comment]
+1

**Comment by d4vidi** [comment]
You're on Android/iOS?

**Comment by devLaaziz** [comment]
on android

**Comment by d4vidi** [comment]
Android API is slightly different (for example, no distinction between foreground and background). Please have a look at: https://github.com/wix/react-native-notifications#android-3

**Comment by srijan02420** [comment]
@d4vidi notificationReceivedBackground never fired for ios.

**Comment by lidanh** [comment]
@srijan02420 Are you sure? I just received a remote notification by sending a push notification when the app was in background.

**Comment by srijan02420** [comment]
I am receiving the notification but onBackgroundNotificationRecevied is not
getting called.

**Comment by sticknor** [comment]
Hello, this is related:

In both the example project and my own, onNotificationReceived() is not fired for Android. 
To my understanding, this function should be called when the notification is received, even if the user has not interacted with it. As soon as it shows up in the notification center.

I am using local notifications and haven't changed any code in the example I am running.

**Comment by tristanbbq** [comment]
@lidanh @srijan02420 same here, `notificationReceivedForeground` is fired but not `notificationReceivedBackground`, on iOS 😞

**Comment by srijan02420** [comment]
@tristanbbq @lidanh any luck?

**Comment by tristanbbq** [comment]
@srijan02420 nope 😞

**Comment by tristanbbq** [comment]
@srijan02420 what about you? any luck with this? still not getting `notificationReceivedBackground` event to get called when receiving the push notification for iOS

**Comment by srijan02420** [comment]
I ended up using VoIP rather than APNS.
Via VoIP you can receive silent notifications, and it wakes up app even if
it's in a killed state.

**Comment by guns2410** [comment]
@srijan02420, what did you use for sending out VOIP notifications? I saw one signal and urban airship not supporting PUSHKIT.

**Comment by srijan02420** [comment]
@guns2410 I am using Django. I used https://github.com/jleclanche/django-push-notifications for implementing VoIP. It works same as APNS as far as backend is concerned. You just need to generate VoIP certificate from apple developer console.

**Comment by d4vidi** [comment]
As explained in a comment I made a while ago regarding this issue, please refer to: https://github.com/wix/react-native-notifications#android-3.
On Android, there's no distinction between foreground and background. If you wish to query for the trigger-notification that potentially caused the app to launch, apply a query to [getInitialNotification()](https://github.com/wix/react-native-notifications#android-4). Thanks!

**Comment by tristanbbq** [comment]
@d4vidi thanks for the details. Just to be clear, there are two different issues here. Previous comments were about iOS

**Comment by alaingoldman** [comment]
Having similar issues.

**Comment by ricms93** [comment]
I'm having the same issues in iOS, handler for notification received background is never triggered.

**Comment by ericwhitefield** [comment]
I have the same issue on iOS. Sending a pushKit notification using a .p8 key - the appdelegate.m function "didReceiveIncomingPushWithPayload" does in fact get called, even if the app is closed. This is excellent, however, no react native handlers are run on this event.

Sending APN notifications does fire the react native handlers as long as the app is in foreground or background. So APN is successful.

What is the expected behavior for pushKit? I intend to open the app for an incoming voip call. Is that beyond the scope of this project? Should I be adding my own code to didReceiveIncomingPushWithPayload in objC to bring the app into the foreground?

**Comment by ravirajn22** [comment]
'notificationReceivedBackground' is not called on IOS, any solution would be helpful ...

**Comment by saudpunjwani101** [comment]
Any progress so far?

**Comment by ericwhitefield** [comment]
I was thinking about this problem in an Android sort of way. For iOS the right choice for my situation was to use CallKit.

I realize this doesn't solve the issue above, but for voip I didn't need to solve it. Hope this helps someone.

**Comment by nathnat** [comment]
Sorry for reopening the subject but I have the same problem : notificationReceivedBackground didn't fired.
