### ISSUE TITLE
Extra 0 causing MismatchSenderId on Android

### ISSUE THREAD

**Issue by KrisBraun** [wix/react-native-notifications#164]
My sender ID is set in `AndroidManifest.xml` as:
```
      <meta-data android:name="com.wix.reactnativenotifications.gcmSenderId" android:value="930984384327\0"/>
```
Sending to the device ID generated yields a `MismatchSenderId` error from FCM. Debugging in `GcmToken.java`, `getSenderIdFromManifest()` is returning `"9309843843270"` -- note the extra trailing `0`. If I hardcode the value as `"930984384327"` in the Java code, everything works.

How can I set a value in `AndroidManifest.xml` so it doesn't have the trailing `0`? Removing the trailing `\0` (`null`) doesn't work -- it causes `getSenderIdFromManifest()` to return `null`.

**Comment by BhadraSoft** [comment]
Hi @KrisBraun,

Can you please try setting up your `AndroidManifest.xml` file by providing gcm_sender_id as a string resource. 

`      <meta-data android:name="com.wix.reactnativenotifications.gcmSenderId" android:value="@string/your_gcm_id"/>
`

`<string>930984384327</string>`

Thanks

**Comment by KrisBraun** [comment]
Yes! That works. 

Any idea why adding the value directly as described in the readme failed for me? Just wondering if there's anything to fix or document so that the next person doesn't hit the same issue. 

This solution is fine for me. Thank you for taking the time to suggest it!

**Comment by maxhawkins** [comment]
I also had this problem. The @BhadraSoft fix worked for me.

**Comment by akrumel** [comment]
Android installation instructions "Step #2" should be updated to reflect correct manifest configuration settings.

**Comment by yakimant** [comment]
Removing trailing 0 helps:
https://github.com/wix/react-native-notifications/issues/245
