### ISSUE TITLE
Android: Opening notification while app is in background reinitializes the app

### ISSUE THREAD

**Issue by swellingt0n** [wix/react-native-notifications#165]
RN: 0.44
RNN: 1.1.17

When i fire a remote or localnotification and it is sitting in the notification bar, press the home button, then open the notification, the app reinitializes rather than simply come back to the foreground. It does not crash.

 This does not happen when I simply press the home button and then bring it back to the foreground.

I am not sure if this would be fixed by #71, @Benjamin-Dobell could you please give this behavior a glance?

**Comment by Benjamin-Dobell** [comment]
@swellingt0n Probably. #71 addresses lots of related functionality, I would suggest giving it a try.

**Comment by swellingt0n** [comment]
Added launchMode="singleTask" to my AndroidManifest.xml as found here:

https://stackoverflow.com/questions/39657029/react-native-android-several-apps-instances-running-at-the-same-time-as-result
