### ISSUE TITLE
Library doesn't always call notification opened listener with correct notification

### ISSUE THREAD

**Issue by kaloncheung124** [wix/react-native-notifications#166]
If I receive multiple notifications without clicking on any of them, then I click on one of them, it always calls my listener with the first notification I've received. Has anyone else run into this issue?

**Comment by kaloncheung124** [comment]
I followed the advice here: https://stackoverflow.com/questions/28091784/multiple-pending-intents

So now my createPendingNotifications method in core/NotificationIntentAdapter looks like this:

```java
    public static PendingIntent createPendingNotificationIntent(Context appContext, Intent intent, PushNotificationProps notification) {
        intent.putExtra(PUSH_NOTIFICATION_EXTRA_NAME, notification.asBundle());
        intent.setAction(Long.toString(System.currentTimeMillis()));
        return PendingIntent.getService(appContext, PENDING_INTENT_CODE, intent, PendingIntent.FLAG_ONE_SHOT);
    }
```

**Comment by ravirajn22** [comment]
Yes, I am facing this issue in Android. Multiple notifications seem to work correctly on iOS.
