### ISSUE TITLE
Overriding Android system Notification

### ISSUE THREAD

**Issue by Jp3rd** [wix/react-native-notifications#168]
Hi, How do I override the default android notification received from FCM using local notification?
and some how, when the listener gets trigger, there will be 2 local notifications appearing.

```
NotificationsAndroid.setNotificationReceivedListener((notification) => {
    console.tron.log('Notification received on device')
    console.tron.log(notification.getData())
    NotificationsAndroid.localNotification({
      title: 'Local notification',
      body: 'This notification was generated by the app!',
      extra: 'data'
    })
  })

```

**Comment by ShongSu** [comment]
If your FCM notification's payload has `notification` key, the Android system will handle and generate a system notification in your system tray. Instead, you may put your `notification` payload to your `data` payload.

**Comment by Jp3rd** [comment]
@ShongSu  I noticed that the problem was because of line 60 in `PushNotification` of this library. once I commented that out, it works as I expected. thanks anyway!
