### ISSUE TITLE
Issue while installing

### ISSUE THREAD

**Issue by bhumit1709** [wix/react-native-notifications#17]
I get following error when I try to install this in my project, What could be wrong?

├── UNMET PEER DEPENDENCY react@15.2.1
├── react-native-communications@2.0.0  extraneous
├── react-native-grid-view@0.4.1  extraneous
├─┬ react-native-notifications@1.1.4 
│ ├── core-js@1.2.7 
│ └── uuid@2.0.3 
└── react-native-push-notification@2.0.2  extraneous

npm WARN react-addons-shallow-compare@15.3.2 requires a peer of react@^15.3.2 but none was installed.
What could be wrong?

**Comment by d4vidi** [comment]
Which error are you referring to, exactly?
Also, please refrain from using both `react-native-notifications` and `react-native-push-notification` in the same project.

**Comment by bhumit1709** [comment]
Ok I removed react-native-push-notification but I get following error after linking with Android studio

 `Compilation is not supported for following modules: react-native-notifications. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.`
