### ISSUE TITLE
Cannot find complete AndroidManifest instructions (trying to do remote notifications)

### ISSUE THREAD

**Issue by Noitidart** [wix/react-native-notifications#170]
From the README - https://github.com/wix/react-native-notifications/blob/master/docs/installation.md#step-1-subscribe-to-googles-gcm - I was linked to complete guide here - https://developers.google.com/cloud-messaging/android/client?configured=true

The manifest here has `<uses-permission android:name="android.permission.WAKE_LOCK" />` and:

```
        <receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="com.example.gcm" />
            </intent-filter>
        </receiver>
        <service
            android:name="com.example.MyGcmListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>
        <service
            android:name="com.example.MyInstanceIDListenerService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.gms.iid.InstanceID" />
            </intent-filter>
        </service>
        <service
            android:name="gcm.play.android.samples.com.gcmquickstart.RegistrationIntentService"
            android:exported="false">
        </service>
```

However I cannot find anywhere in the README or example app - https://github.com/wix/react-native-notifications/blob/master/example/android/myapplication/src/main/AndroidManifest.xml

Where it shows us how to do this for react-native-notifications. May you please point me in direction to set my manifest up correctly, I am a bit confused. Or do I not need it?

**Comment by undef1ned** [comment]
Im not sure I've figured it out completely, just faced the same problem and, hope, resolved it few minutes ago. At least I've received the message sent from the FCM console

**android/app/build.gradle**

> dependencies {
>     compile project(':reactnativenotifications')
>     compile "com.google.android.gms:play-services-gcm:11.8.0"
> }
> 
> apply plugin: 'com.google.gms.google-services'

android/build.gradle
 
>    dependencies {
>         classpath 'com.google.gms:google-services:3.1.0'

**android/app/src/main/AndroidManifest.xml**
Just replace **[YOUR_APP_ID]** and **[YOUR_SENDER_ID]** with your data!
>     <permission
>         android:name="[YOUR_APP_ID].permission.C2D_MESSAGE"
>         android:protectionLevel="signature" />
>     <uses-permission android:name="[YOUR_APP_ID].permission.C2D_MESSAGE" />
>    <uses-permission android:name="android.permission.WAKE_LOCK" />
>     <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
> .....
>    <application
>       android:name=".MainApplication"
>       android:allowBackup="true"
>       android:label="@string/app_name"
>       android:icon="@mipmap/ic_launcher"
>       android:theme="@style/AppTheme">
>         <receiver
>             android:name="com.google.android.gms.gcm.GcmReceiver"
>             android:exported="true"
>             android:permission="com.google.android.c2dm.permission.SEND" >
>             <intent-filter>
>                 <action android:name="com.google.android.c2dm.intent.RECEIVE" />
>                 <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
>                 <category android:name="[YOUR_APP_ID].gcm" />
>             </intent-filter>
>         </receiver>
>         <service
>             android:name="com.wix.reactnativenotifications.gcm.GcmMessageHandlerService"
>             android:exported="false" >
>             <intent-filter>
>                 <action android:name="com.google.android.c2dm.intent.RECEIVE" />
>             </intent-filter>
>         </service>
>         <service
>             android:name="com.wix.reactnativenotifications.gcm.GcmInstanceIdListenerService"
>             android:exported="false">
>             <intent-filter>
>                 <action android:name="com.google.android.gms.iid.InstanceID" />
>             </intent-filter>
>         </service>
>         <service
>             android:name="com.wix.reactnativenotifications.gcm.GcmInstanceIdRefreshHandlerService"
>             android:exported="false"
>             />
> .....
>        <meta-data android:name="com.wix.reactnativenotifications.gcmSenderId" android:value="[YOUR_SENDER_ID]\0"/>

Also,  I've placed **google-services.json** (obtained from FCM console) in **android/app** folder

I think this configuration is still incomplete, but I got it working few minutes ago (the message was logged by **NotificationsAndroid.setNotificationReceivedListener** so now I can go sleep and continue tomorrow :)

**Comment by Noitidart** [comment]
Thank you so much @undef1ned for sharing this! I will try this out. I actually was never able to figure it out. I will update you on how it goes! :)

**Comment by undef1ned** [comment]
@Noitidart Spent just another day trying to configure it. Finally it works as expected. 

Just few things:

1. You need to use GCM, not the FCM. This lib works with FCM but somehow incomplete, so you think everything is fine except just some minor things... But actually you're looking completely in the wrong direction.. Yesterday I was able to get the deviceToken and to get the message when the app was in foreground, using FCM console and GCM app, and background/killed state was not working at all.

2. Making it work with react-native-navigation is just another pain in the ass, but seems it's working now. If needed of course. Was getting crash when the app was in killed state but this fix works fine https://github.com/wix/react-native-notifications/issues/124#issuecomment-355581022 

3. google-services.json file is not needed to make it work, just because its about FCM, not GCM

4. There are RN libraries which implement FCM, I'd choose one of them, but I depend on the react-native-navigation which does not allow to use any notifications lib available

5. Documentation of the react-native-notifications really s*cks

**Comment by Noitidart** [comment]
Wow thank you so so much for that!!! I would have never figured it out, this is my first time doing push notifications.

What do you maybe we should try out this lib - https://github.com/evollu/react-native-fcm

It seems dedicated to FCM. I would never have thought to do GCM, Googles docs completely said not to use it.
