### ISSUE TITLE
FCM Integration Android

### ISSUE THREAD

**Issue by jankowskip** [wix/react-native-notifications#173]
Hello, 
Can someone tell me how to integrate this libary with FCM, there is no word about it in Docs. 
I followed: https://firebase.google.com/docs/cloud-messaging/android/client  because GCM is getting depracated. 
and: https://github.com/wix/react-native-notifications/blob/master/README.md
But got stuck on Step #2: Add Sender ID to Manifest File is there something equivalent for FCM to this:
  `<meta-data android:name="com.wix.reactnativenotifications.gcmSenderId" android:value="1234567890\0"/>`
Right now im getting: 
`java.lang.IllegalStateException: Sender ID not found in manifest. Did you forget to add it as the value of a 'com.wix.reactnativenotifications.gcmSenderId' meta-data field?`

Thanks in advance

**Comment by ShongSu** [comment]
Try this branch https://github.com/Benjamin-Dobell/react-native-notifications/tree/android-overhaul

**Comment by jankowskip** [comment]
Thank you for answer i have seen <a href="https://github.com/wix/react-native-notifications/pull/71">Benjamin PR</a> But had to be sure there is no other way since for some reason its still not merged.

**Comment by Noitidart** [comment]
@ShongSu I get stuck on step 2 "Integrate Firebase in your native Android project." here: https://github.com/Benjamin-Dobell/react-native-notifications/tree/android-overhaul#receiving-push-notifications


Is there any advice you can provide? Because we are RN we don't have a native android project.

**Comment by Noitidart** [comment]
Would be awesome if there was a medium article or something step by step for push notification newbies and FCM :(

**Comment by AugustoAleGon** [comment]
I will give it a shot... @Noitidart

**Comment by BenWildeman** [comment]
@AugustoAleGon did you?

**Comment by AugustoAleGon** [comment]
@BenWildeman I do have completed successfully the integration. I still have to work on the article. What do you need?
