### ISSUE TITLE
Notification not receiving in Android 7.0 and above.

### ISSUE THREAD

**Issue by Jp3rd** [wix/react-native-notifications#181]
I tested on Android 6.0 and it works. Anyone knows what the problem?

**Comment by brookemitchell** [comment]
Could be related to #175 ? Android 8+ needs a notification channel now.

**Comment by Jp3rd** [comment]
@brookemitchell but I have this issue in Android 7.0 too, any ideas?

**Comment by Jp3rd** [comment]
It says here that, Android 8.0 onwards we should use FCM, rather than GCM.

https://developers.google.com/cloud-messaging/android/client

**Comment by Jp3rd** [comment]
@brookemitchell hi, my bad. I change the targetSDKVersion and it works now.
