### ISSUE TITLE
Android - 'Initial notification was:', 'N/A'

### ISSUE THREAD

**Issue by RuairiOliver** [wix/react-native-notifications#183]
Hi,

Has anyone come up against this issue before when the app is launched from pressing a notification? 

Android - 'Initial notification was:', 'N/A'

Works fine when the app is open but can't get the initial notification. I'm using wix react native navigation which is really good but has caused serious issues for push notifications for me (previously used the react native FCM library).

I followed the guide here for setup instructions with the navigation library.
https://github.com/wix/react-native-notifications/wiki/Android:-working-with-RNN

Also strangely when the app is open the notification content in the system bar is empty but I can get the content from within the app.

Any help appreciated.

Thanks

**Comment by RuairiOliver** [comment]
Just to add if I receive a notification while the app is running, ignore it, kill the app and then press the notification then PendingNotifications.getInitialNotification() is populated. If the notification is received while the app is dead and I press it then no data is there

**Comment by undef1ned** [comment]
Check this thread https://github.com/wix/react-native-notifications/issues/170  may-be it will help you

**Comment by cristianonescu** [comment]
@RuairiOliver 
did you solved this? I have the same issue.
PendingNotifications.getInitialNotification() is empty

#238
