### ISSUE TITLE
What is the proper way to integrate with react-native-navigation?

### ISSUE THREAD

**Issue by witalobenicio** [wix/react-native-notifications#189]
We just don't have any docs on how to integrate with RNN.
Where to subscribe to Notifications? And if we call another "startTabBasedApp"

**Comment by 3210jr** [comment]
There is a gist here: https://github.com/wix/react-native-notifications/wiki/Android:-working-with-RNN 
The gist is also kind of confusing to me. 
Hopefully there will be examples soon.
