### ISSUE TITLE
README file "Upcoming: local notifications, background-state Rx queue (iOS equivalent)" yet commit says you support android local notifications..

### ISSUE THREAD

**Issue by mcmatan** [wix/react-native-notifications#19]
README file "Upcoming: local notifications, background-state Rx queue (iOS equivalent)" yet commit says you support android local notifications, did you forget you forget to update README file, or is local notifications not supported on android yet?

And thanks for this great library, starting integration with it now...

**Comment by d4vidi** [comment]
Local notifications **are** supported, so you're right - the readme is outdated. Best of luck, we'll try our best to help out!

**Comment by sticknor** [comment]
Hi! Thanks for adding this support. 

I was wondering if there is a way to set a custom sound and fire date for these Android local notifications.

**Comment by mcmatan** [comment]
Great thanks for the quick response, I've assigned a pull request with the README file update, chears.
