### ISSUE TITLE
Not able to use in Android. Undefined is not a function

### ISSUE THREAD

**Issue by witalobenicio** [wix/react-native-notifications#190]
undefined is not a function (evaluating '_reactNativeNotifications.NotificationsAndroid.addEventListener('remoteNotificationsRegistered', _this.onPushRegistered.bind(_this))')

I get this error when trying to use in Android.
Did all the steps and nothing seems to fix it.

**Comment by isyiwang** [comment]
Looking at the API, it looks like the method to use now is `setNotificationOpenedListener` instead of `addEventListener`.
