### ISSUE TITLE
Not compatible with targetSdkVersion 26 (Android Oreo)

### ISSUE THREAD

**Issue by felixmohnert** [wix/react-native-notifications#194]
**What doesn't work?**

The actual notifications do not show up in the system. The method `onNotificationReceived` is being called correctly though. No further error output, just no notification.

**What could be the reason for that behaviour?**

The issue seems to be related to a missing `setChannelId` call.
https://stackoverflow.com/a/43093261

**Comment by hedshafran** [comment]
To support Android Oreo a notification_channel need to be created.

**Comment by brookemitchell** [comment]
Related to https://github.com/wix/react-native-notifications/issues/175 . Creating a channel id in a custom layout fixed it

**Comment by adrienthiery** [comment]
In case someone still hits that problem, you can fix it by adding the following code in your Notification custom layout (`CustomPushNotification.java` in the `  @Override protected Notification.Builder getNotificationBuilder(PendingIntent intent) {` method for me) :

```
String CHANNEL_ID = "notifications";// The internal id of the channel.
String CHANNEL_NAME = "Notifications";// The public name of the channel.

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
    NotificationChannel channel = new NotificationChannel(CHANNEL_ID,
                                                          CHANNEL_NAME,
                                                          NotificationManager.IMPORTANCE_DEFAULT);

    final NotificationManager notificationManager = (NotificationManager) mContext.getSystemService(Context.NOTIFICATION_SERVICE);
    notificationManager.createNotificationChannel(channel);

    builder.setChannelId(CHANNEL_ID);
}
```
