### ISSUE TITLE
undefined is not an object (evaluating ' RNNotifications.postLocalNotification')

### ISSUE THREAD

**Issue by ysq1051838264** [wix/react-native-notifications#195]
undefined is not an object (evaluating ' RNNotifications.postLocalNotification')

**Comment by ysq1051838264** [comment]
android

**Comment by hedshafran** [comment]
Post your JS file..

**Comment by michelepapale1996** [comment]
I have the same problem. Did you solve it, @ysq1051838264 ?

**Comment by faizqadri234** [comment]
+1

anyone resolved it ?
