### ISSUE TITLE
Is there a cancelLocalNotifications() or cancelAllLocalNotifications() function?

### ISSUE THREAD

**Issue by jan-happy** [wix/react-native-notifications#2]
Great to have an alternative to PushNotificationIOS which is too buggy for me. But I am missing the above mentioned functions. 
Could you help me?

**Comment by lidanh** [comment]
Hi,
Thanks! Glad to hear that.
I can work on it this week, and you're more than welcome to PR :)

Lidan.

**Comment by jan-happy** [comment]
I ended up using PushNotificationIOS.cancelAllNotifications(), works fine.

**Comment by lidanh** [comment]
@jan-happy I've added those functions, `cancelLocalNotifications` is a bit different than PushNotificationsIOS' one. hope you'll find it useful!

https://www.npmjs.com/package/react-native-notifications#cancel-local-notification
