### ISSUE TITLE
display notification when application state is "dead"

### ISSUE THREAD

**Issue by Crash--** [wix/react-native-notifications#20]
Hi guys, 

I'm moving from React Native Push Notification to this lib because RNPN doesn't work well with React-Native-Navigation... 

I can receive notification if my application is in "dead" state. The icon is added to the system top bar and I got a vibration, that's all. How to display it with its content as the other apps do? 

Here is an exemple of what we can do (without no code modification / addition) with RNPN. 
![screenshot_2016-12-27-15-26-09](https://cloud.githubusercontent.com/assets/1107936/21501802/4f1ceea0-cc4b-11e6-8355-6dc535037b85.png)

Is it something we can do with Wix RN-Notifications? Or do we need to customize Notification Classes etc?

**Comment by kristikristo** [comment]
Same issue in here.

**Comment by Crash--** [comment]
It seems that this type of notification is called `Heads-up notifications` on Android (https://developer.android.com/guide/topics/ui/notifiers/notifications.html#Heads-up) but the default behavior is just to have an icon :/ 

We can definitely set a higher priority and so on, but not sure how we can display this banner on the home screen

**Comment by d4vidi** [comment]
Is this still relevant?

**Comment by Crash--** [comment]
Just aded :

```java
   super(context, bundle, appLifecycleFacade, new AppLaunchHelper(), new JsIOHelper());
```

Seems to work as expected. Can you update the wiki? 

Also, if we can have some leads to have the behavior described in the first post, it'll be very helpful since I added an Hight priority but I still have no banner with my Push :(

**Comment by d4vidi** [comment]
Sure, thank you!

**Comment by kaloncheung124** [comment]
Any updates on this?

**Comment by kaloncheung124** [comment]
I was able to make a head-up notification appear by adding 

`// Set high priority for notification
        builder.setPriority(PRIORITY_HIGH);`

to the class:

```java
public class PushNotificationBanner extends PushNotification {

    public PushNotificationBanner(Context context, Bundle bundle, AppLifecycleFacade appLifecycleFacade, AppLaunchHelper appLaunchHelper, JsIOHelper jsIoHelper) {
        super(context, bundle, appLifecycleFacade, appLaunchHelper, jsIoHelper);
    }

    @Override
    protected Notification.Builder getNotificationBuilder(PendingIntent intent) {
        final Resources resources = mContext.getResources();

        // First, get a builder initialized with defaults from the core class.
        final Notification.Builder builder = super.getNotificationBuilder(intent);

        // Set our custom overrides --

        // Enable 'extended' layout (extends on down-stroke gesture):
        final Notification.BigTextStyle extendedNotificationStyle =
                new Notification.BigTextStyle()
                        .bigText(mNotificationProps.getBody()); // "4:15 - 5:15 PM\nBig Conference Room"
        builder.setStyle(extendedNotificationStyle);

        // Set custom-action icon.
        builder.setSmallIcon(R.drawable.ic_launcher);

        // Set high priority for notification
        builder.setPriority(PRIORITY_HIGH);

        return builder;
    }
}
```
