### ISSUE TITLE
IOS: clearing one notification clears all notifications from notification tray

### ISSUE THREAD

**Issue by awchang56** [wix/react-native-notifications#202]
I am using scheduled local notifications only, no push notifications. When a user has the app in the background and receives a new local notification and the tap the notification, the app launches and brings them to the expected page. However, it clears all other notifications in the notification pull-down tray even if they haven't been interacted with yet. Is this default behavior on ios? This also happens if you swipe left on the notification and tap clear, all other notifications get cleared as well. I haven't been able to find anywhere in the JS or Obj-C code where that behavior is implemented. Any suggestions would be greatly appreciated.

**Comment by andrewzey** [comment]
I too am having this exact issue.

**Comment by reimertz** [comment]
This is just a guess but maybe we need to set an id to each notification to prevent?

**Comment by Winglonelion** [comment]
It exactly what this library do when you open a notification. I met this issues and some others. 

https://github.com/wix/react-native-notifications/blob/2c71cd91925474bd57df174f2e57e0788456697f/android/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java#L64-L68

https://github.com/wix/react-native-notifications/blob/2c71cd91925474bd57df174f2e57e0788456697f/android/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java#L159-L162

I'm working on a fork to improve the features of android version.

I just completed schedule and repeatInterval  for Ios and Android. Hope to have a Pull request soon ...
