### ISSUE TITLE
The local notification is not visible

### ISSUE THREAD

**Issue by googlecomvn** [wix/react-native-notifications#203]
I have follow the instruction to install the lib in Xcode 9. I use local notification for my app and run in simulator iPhone 6 and run in real device iPhone 7 but the notification is not visible. Please help me
My snippet code to show notification

_let localNotification = NotificationsIOS.localNotification({
    	alertBody: "Local notificiation!",
    	alertTitle: "Local Notification Title",

        silent: false,
    	category: "SOME_CATEGORY",
    	userInfo: { }
    });_

**Comment by axlalvaro** [comment]
Same here, local notification not showing.
I am testing in an iPhone X, iOS 11.
The event notificationReceivedForeground does fire though.

**Comment by reimertz** [comment]
Can confirm this as well. Though it was my own fault at first causing a race condition since I remove old notifications before pushing a new one.

**Comment by hoangvuanhdevelopervn** [comment]
I really don't know how to show local notification, document is so difficult to understand and follow

**Comment by googlecomvn** [comment]
Hi Axlalvaro
Does your tips allow to show notification on the mode foreground?

**Comment by axlalvaro** [comment]
@googlecomvn yes!

**Comment by googlecomvn** [comment]
Hi Axlalvaro
Thanks, I will try

**Comment by googlecomvn** [comment]
Hi Axlalvaro
Has error with this following line in AppDelegate.m

[RNNotifications didReceiveLocalNotification:localNotification];

In Xcode 9.2 has error: 
Unknown receiver 'RNNotification'; did you mean 'UNNotification'?

**Comment by axlalvaro** [comment]
@googlecomvn Did you put the required methods in your AppDelegate.m?, as indicated here:

> https://github.com/wix/react-native-notifications/blob/master/docs/installation.md

You have to add the methods specified in the link in the iOS section and import:
`#import "RNNotifications.h"`

I just copied a piece of my AppDelegate.m, not the whole.

**Comment by googlecomvn** [comment]
Hi axlalvaro
The Notification is now working. But when the app is suspended or closed, the notification is not working. Do you have any suggestion to this scenario

**Comment by Rob117** [comment]
It would be really awesome to get an update on this, because it seems like the latest build is broken. Is there a way to merge the code @axlalvaro wrote into the project?

**Comment by googlecomvn** [comment]
After searching around I have a simple solution at last (I tested on my iphone 7) :
add this following method into AppDelegate.m 

- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification
         withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
{
  NSLog( @"Handle push from foreground" );
  // custom code to handle push while app is in the foreground
  completionHandler(UNNotificationPresentationOptionAlert);
}

**Comment by ItsNoHax** [comment]
@axlalvaro Your solution isn't 100% working though, they do show but when I click on push notification it doesn't trigger onNotificationOpened.

**Comment by axlalvaro** [comment]
@ItsNoHax You are right! I had more code in my project. I just edited my code above. Let me know if it works (it does for me)!

**Comment by ItsNoHax** [comment]
Will let you know tomorrow morning! Very much appreciated!

**Comment by ItsNoHax** [comment]
@axlalvaro I'm getting 'No known class method for selector 'didNotificationOpen:'

**Comment by axlalvaro** [comment]
@ItsNoHax Umm, I can't remember what I did, it was a long time ago, but reading the RNNNotifications.m, it does have the didNotificationOpen method. So I guess I just added it to the RNNotifications.h file. I updated my comment above with this line. Hope it finally works!

**Comment by ItsNoHax** [comment]
@axlalvaro  But that means every time you clean/reinstall your node_modules that change will disappear? :/

**Comment by axlalvaro** [comment]
@ItsNoHax Yes, sad moment. I just can't think of any other way of achieving this in a fast way (no PRs), because the method didNotificationOpen is not exposed in the .h :(

**Comment by ItsNoHax** [comment]
@axlalvaro So with your changes the push notifications are showing but when I press them they are not triggering in the notificationOpened listeners :/

**Comment by axlalvaro** [comment]
@ItsNoHax Does it stop at didReceiveNotificationResponse in AppDelegate.m if you set a breakpoint?

**Comment by ItsNoHax** [comment]
@axlalvaro Not sure but it looks like it also broke handling normal push notifications too. They aren't triggering my notificationOpened listeners either now 0.0

Do you have discord?

**Comment by ItsNoHax** [comment]
So I managed to make it work partly through your solution, I used https://github.com/ds300/patch-package to make the function available in the header file (without having to make a fork or keep changes locally).

Also for the  following method didReceiveNotificationResponse I had to make sure I pass the userInfo object of the formatted message to didNotificationOpen. If you pass the whole formatted message the listener get's a wrongly formatted notification.

@axlalvaro

**Comment by AugustoAleGon** [comment]
I have the same issue. Local notifications doesn't work for me...

**Comment by manojeeva** [comment]
> After searching around I have a simple solution at last (I tested on my iphone 7) :
> add this following method into AppDelegate.m
> 
> * (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification
>   withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
>   {
>   NSLog( @"Handle push from foreground" );
>   // custom code to handle push while app is in the foreground
>   completionHandler(UNNotificationPresentationOptionAlert);
>   }

I tried this one but notification not received in the foreground. Do I need to install PushNotificationIOS to work? 
Background notifications are fine.
Running in IOS 13.3
