### ISSUE TITLE
Android: unclear instructions on Android customization

### ISSUE THREAD

**Issue by jstansbe** [wix/react-native-notifications#204]
I've got the package added, updated android files (ie gradle), and have successfully got a local notification to show up on my device and emulator!!

I was looking forward to updating the notification icon/image (appears on the left side of the notification), colors, and so on... but I just don't know how to proceed. When looking at [https://github.com/wix/react-native-notifications/blob/master/docs/localNotifications.md#-android](https://github.com/wix/react-native-notifications/blob/master/docs/localNotifications.md#-android) I can see {title, body, extra} as properties i can set... but nothing else? When I went to the wiki [https://github.com/wix/react-native-notifications/wiki/Android:-Layout-Customization](https://github.com/wix/react-native-notifications/wiki/Android:-Layout-Customization) I saw java code that looked pretty straight forward but i have no idea where to place this file and how to include it... 

Any info/instructions is appreciated!

```
  "dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.2",
    "react-native-notifications": "^1.1.19"
  },
```

**Comment by sircEUNHO** [comment]
I hope someone would clearly define the instruction on how to add the icon. the instruction is too vague it gave us the codes but not where to put it or do we need to define packages on those codes too. I hope someone can give us a public repo on how to change the icon on android. It will be a big help for us and also for the react native notification community.

**Comment by oscar-omana** [comment]
Someone needs to do something similar to this https://wix.github.io/react-native-navigation/#/
for this package. Would be greatly appreciated and would prevent this kind of 'issues' being opened.
