### ISSUE TITLE
Should this library support FCM?

### ISSUE THREAD

**Issue by henrikra** [wix/react-native-notifications#206]
I got this email today

![image](https://user-images.githubusercontent.com/12229968/38599855-b5045532-3d6a-11e8-9fc5-f4326035856d.png)

So looks like GCM is going to die. And to my knowledge this library is using only GCM. What you guys think?

**Comment by mattyx96** [comment]
UP

**Comment by Liroo** [comment]
GCM is not going to die, GMC is going to disappear.
Another package is already supporting FCM ([react-native-firebase](https://github.com/invertase/react-native-firebase)), I think this package needs to be active until GCM server closed.

After this, depends on wix, if they want to create a new package or full refactor this one...

**Comment by ebaynaud** [comment]
It seems that library was recently migrated from GCM to FCM.
