### ISSUE TITLE
Building without Play Services?

### ISSUE THREAD

**Issue by Rudloff** [wix/react-native-notifications#207]
Hello,

It seems that this library can't be built for Android without Play Services:
```
   > A problem occurred configuring project ':reactnativenotifications'.
      > You have not accepted the license agreements of the following SDK components:
        [Google Repository].
```

The Play Services dependency prevents any app using this library from being included in free software repositories like [F-Droid](https://f-droid.org/).

Would it be possible to have an option to build without the `play-services-gcm` dependency? (Even if it means that only local notifications would work.)

**Comment by hotlittlewhitedog** [comment]
Hi all, 
Why is used Play Service for notifications?!

**Comment by Winglonelion** [comment]
Push notification feature does not necessary with our application. Thus, i planning to remove it from my Fork. Maybe it will complete on last week.

**Comment by jnnkB** [comment]
@Winglonelion Do you have any updates on this?
