### ISSUE TITLE
[Question]: Is there an Android equivalent implementation for IOS `fireDate`?

### ISSUE THREAD

**Issue by omerman** [wix/react-native-notifications#209]

**Comment by omerman** [comment]
Nope.. decided to use https://github.com/zo0r/react-native-push-notification instead.
It has scheduled notifications api for both Android and IOS..

**Comment by oneEyedSunday** [comment]
ooh, i'm currently playing around with it in a branch, was starting to consider rolling up some native code. Thanks. Hopefully theres better support
