### ISSUE TITLE
unable to resolve path to module

### ISSUE THREAD

**Issue by EEimer** [wix/react-native-notifications#210]
Hey guys,
I tried different versions and different projects.
I always get the same error: 
<img width="626" alt="bildschirmfoto 2018-04-26 um 12 44 17" src="https://user-images.githubusercontent.com/3017213/39301537-a99e6782-494f-11e8-99b8-44060ca2ea9d.png">

I have this problem only with this library. 
Any idea? Im the only one? 

Thanks in advance
Emanuel

**Comment by brianjd** [comment]
@EEimer It is because the package has platform specific exports (`index.ios.js`, `index.android.js`).  You have to review your linting configuration, and add the `.android.js` and `.ios.js` extensions to your `import/resolver` configuration.
