### ISSUE TITLE
[Question] permissions for notifications in AndroidManifest.xml

### ISSUE THREAD

**Issue by vojeda** [wix/react-native-notifications#211]
Hi, I think I have the module installed correctly but I can not get the token in the setRegistrationTokenUpdateListener method (it does not give an error, but it does not enter), I assume it is because I do not have the android file properly configured. Does anyone know which parameters are the ones that must be set in AndroidManifest.xml for permissions?

Thanks!!

**Comment by tarikmlaco** [comment]
I have the same problem. Did you manage to solve it in any way?

**Comment by ronilitman** [comment]
@vojeda @tarikmlaco  Same issue. Did you find a solution?
