### ISSUE TITLE
Local notifications "Everyday at 7:00am"

### ISSUE THREAD

**Issue by safaiyeh** [wix/react-native-notifications#214]
Currently, the library helps with scheduling specific timed local notifications..

is there functionality to implement

"Everyday at 7:00AM"
"Every Monday and Sunday at 6:00PM"

Do these until canceled?

**Comment by JSafaiyeh** [comment]
Thanks.

Code architecture wise, every time a local notification fires. On receive check if notification should be fired again at a later date then schedule another notification?

Does this sound like the correct way to implement?

**Comment by Winglonelion** [comment]
Oh, finaly i know your mean. 

My fork from this repo has been implement schedule and repeat features both on Android and Ios, but it not ready to be share. 

I will work hard for complete it as soon as possible.

Hope for introduce it to you in a near time.

You can try this PR first, i start from this:  https://github.com/wix/react-native-notifications/pull/157

**Comment by akhilsanker** [comment]
Hi @Winglonelion ,

Is this feature is available in new version(2.0.0)? Is yes, how can we implement this?

Thanks
