### ISSUE TITLE
Display notification in Foreground

### ISSUE THREAD

**Issue by WeiLiangTan** [wix/react-native-notifications#216]
Hi, may I know how to show remote notification and local notification while the app is in foreground?

**Comment by juanjoslopezv** [comment]
This is also happening for me:

AppDelegate.h
@interface AppDelegate : UIResponder <UIApplicationDelegate, PKPushRegistryDelegate, UNUserNotificationCenterDelegate>


AppDelegate.m


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
....

UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  center.delegate = self;
...
return YES;
}

//Called when a notification is delivered to a foreground app.
-(void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
{
  NSLog(@"User Info : %@",notification.request.content.userInfo);
  completionHandler(UNAuthorizationOptionSound | UNAuthorizationOptionAlert | UNAuthorizationOptionBadge);
}

But this is not being fired
-(void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler

**Comment by huyvm** [comment]
Hi everybody,
You can check here, this is my solution: https://github.com/wix/react-native-notifications/issues/302
