### ISSUE TITLE
unable to build on android RN 55

### ISSUE THREAD

**Issue by oisco** [wix/react-native-notifications#222]
I have recently upgraded my project to react native 55 and am unable to build on android (works fine on ios). When installing `    "react-native-notifications": "^1.1.19",` and trying to build I am presented with the following error:

 'org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':react-native-notifications:compileDebugJavaWithJavac'.

Caused by: java.io.FileNotFoundException: /Users/oisin/app/node_modules/react-native-notifications/android/build/intermediates/javaPrecompile/debug/annotationProcessors.json (No such file or directory) `

Android version: `6.0.1 API 23`
React native version: `0.55.4`

**Comment by oisco** [comment]
This was a problem with my android environment. Once I updated my gradle version react native notifications build folder was generated correctly

**Comment by reidisaki** [comment]
Have the same issue. same version. gradle plugin 3.1.4 and gradle 4.4
