### ISSUE TITLE
Importing both iOS & Android breaks iOS

### ISSUE THREAD

**Issue by milesmatthias** [wix/react-native-notifications#224]
if I do this:

```js
import { NotificationsIOS, NotificationsAndroid } from "react-native-notifications";
```

it works in Android, but iOS says `undefined is not an object` for `_reactNotifications.NotificationsIOS.addEventListener`.

Switching it to just

```js
import NotificationsIOS from "react-native-notifications";
```

makes it work in iOS.

Switching it to separate `x.ios.js` and `x.android.js` works too.

**Comment by delia-m** [comment]
You can do like 
```
import NotificationsIOS, { NotificationsAndroid } from 'react-native-notifications';
```
