### ISSUE TITLE
Android notification is not generating any sound or vibration

### ISSUE THREAD

**Issue by sunsay00** [wix/react-native-notifications#230]
When Android receive a notification.  The message shows up but there's no sound or vibration.

**Comment by oscar-omana** [comment]
If you want to use default sound of the device, you should use: "sound": "default". on the notification payload.

**Comment by sunsay00** [comment]
Thanks for the response but I don't know where am i suppose to set that.  Do you mind pointing me to the right place?  I am still very new with react-native and andriod.

**Comment by oscar-omana** [comment]
Sorry for the late response, depends from where you're sending the notification. if you're sending it directly from FCM then just follow this answer [https://stackoverflow.com/a/44304089/5482431]

If you're using something else to send the notification information to FCM, then the dictonary which you're sending should have  "sound": "default"

**Comment by sunsay00** [comment]
It's working now.  Thanks.

**Comment by ItsNoHax** [comment]
@sunsay00 Don't forget to close the issue.
