### ISSUE TITLE
[Android] Always get all Push-Notifications however you start the App

### ISSUE THREAD

**Issue by ulfgebhardt** [wix/react-native-notifications#232]
On Android ```getInitialNotification()``` contains the one Notification you clicked or no Notifiation at all if you start the App manually and Pushs are present.

On the other Hand all Notifications are cleared whatsoever.

Since we use Pushs as Data-Transport for Privacy reasons we need them all.

Our Solution can be found here: https://github.com/wix/react-native-notifications/pull/231

We would appreciate if you guys can look into this and make the required changes to the Library to meet our requirements. The PR is not ment to be merged - its just something working for us at the moment.

We would <3 to see this awesome library to be enhanced for our requirements.

Grüße Ulf & [Team DEMOCRACY](https://www.democracy-deutschland.de)

**Comment by juanmagalhaes** [comment]
+1
