### ISSUE TITLE
Android push token that module returns sometimes invalid

### ISSUE THREAD

**Issue by rsnay** [wix/react-native-notifications#235]
In an Android app using this module, we get reports of some users not being able to receive push notifications. Through backend logging, this is due to FCM sometimes returning a "token not registered" message. In one case, I cleared a tester's token from the database, and when the app re-initialized, got the newest token, and uploaded it, FCM still was unable to send a notification to it. Yet the same code and setup works for many other users. 

Has anyone else experienced this, where an android push token returned from this module is sometimes invalid?

What are some things I should check?

**Comment by JustinKasad** [comment]
I am experiencing the same issue.  Currently using an Google Pixel 2 XL (8.1)

setRegistrationTokenUpdateListener returns a device token, but that token returns a Not Registered error when sending a push.

**Comment by yudhis8** [comment]
+1
