### ISSUE TITLE
While android app is in background or dead remote notifications are doubled.

### ISSUE THREAD

**Issue by cristianonescu** [wix/react-native-notifications#237]
While android app is in background(or dead) remote notifications are doubled, I tested with local notifications before and everything worked..
This issue happens only on android, ios works fine.

**Comment by cristianonescu** [comment]
SOLVED!
Avoid using fcm and gcm in the same project. Use just one of them, either fcm or gcm.
Consult your gradle files for this.

**Comment by mtumiati** [comment]
Hi, I get the same error but I'm using only FCM. Could you share your gradle files?

**Comment by rcristianonescu** [comment]
Hello @mtumiati ,
Meanwhile I switched to `react-native-push-notification-ce`.

I find it much stable!

**Comment by mtumiati** [comment]
Thank you very much @rcristianonescu!
I will try it for sure!
