### ISSUE TITLE
[ANDROID] setNotificationOpenedListener not triggered when app is in background

### ISSUE THREAD

**Issue by cristianonescu** [wix/react-native-notifications#238]
Hello,

I have this issue.
If I have the app in foreground and I receive a notification, pressing the notification will trigger setNotificationOpenedListener. - **As expected, works fine!**

But if my app is dead or in background, if I receive a notification and I press it, the setNotificationOpenedListener is not triggered. - **Not the expected behaviour**

What can cause this? How can I fix this? Thanks!

**Comment by uday5162** [comment]
I am facing the same issue.
@cristianonescu  have you found any alternative?
