### ISSUE TITLE
Support for React Native 0.40

### ISSUE THREAD

**Issue by MichielDeMey** [wix/react-native-notifications#24]
It looks like they changed the location of the header files in 0.40, is this something we can support?
https://github.com/facebook/react-native/releases/tag/v0.40.0

**Comment by MichielDeMey** [comment]
Should be fixed in https://github.com/wix/react-native-notifications/issues/24.

**Comment by d4vidi** [comment]
Ouch. We hope to iron this out soon.

**Comment by lanceharper** [comment]
@MichielDeMey Thanks for submitting this. I hope it gets merged soon!

**Comment by chrissm79** [comment]
@MichielDeMey I added a comment about keeping backwards compatibility (< 0.40.0)
