### ISSUE TITLE
Notification Not Working

### ISSUE THREAD

**Issue by skhizerabass** [wix/react-native-notifications#245]
Below is the exception i found in my logcat . 

>  java.lang.Exception: FATAL: Failed to fetch a fresh new token, instanceId=dhL1f6J8CNA
>         at com.wix.reactnativenotifications.gcm.GcmToken.getNewToken(GcmToken.java:99)
>         at com.wix.reactnativenotifications.gcm.GcmToken.refreshToken(GcmToken.java:77)
>         at com.wix.reactnativenotifications.gcm.GcmToken.onAppReady(GcmToken.java:66)
>         at com.wix.reactnativenotifications.gcm.GcmInstanceIdRefreshHandlerService.onHandleIntent(GcmInstanceIdRefreshHandlerService.java:23)
>         at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
>         at android.os.Handler.dispatchMessage(Handler.java:102)
>         at android.os.Looper.loop(Looper.java:148)
>         at android.os.HandlerThread.run(HandlerThread.java:61)
>      Caused by: java.io.IOException: INVALID_SENDER
>         at com.google.android.gms.iid.zzaf.zzi(Unknown Source)
>         at com.google.android.gms.iid.InstanceID.zze(Unknown Source)
>         at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
>         at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
>         at com.wix.reactnativenotifications.gcm.GcmToken.getNewToken(GcmToken.java:95)
>         at com.wix.reactnativenotifications.gcm.GcmToken.refreshToken(GcmToken.java:77) 
>         at com.wix.reactnativenotifications.gcm.GcmToken.onAppReady(GcmToken.java:66) 
>         at com.wix.reactnativenotifications.gcm.GcmInstanceIdRefreshHandlerService.onHandleIntent(GcmInstanceIdRefreshHandlerService.java:23) 
>         at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66) 
>         at android.os.Handler.dispatchMessage(Handler.java:102) 
>         at android.os.Looper.loop(Looper.java:148) 
>         at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Cholern** [comment]
Try change
 `android:value="your_sender_id\0" `
to
`  android:value="your_sender_id\"`
in AndroidManifest.xml

**Comment by skhizerabass** [comment]
@Cholern  Yes, It is working. Thanks a lot
