### ISSUE TITLE
iOS Interactive / Actionable Notifications callback not working

### ISSUE THREAD

**Issue by appstart-lt** [wix/react-native-notifications#248]
Hello. I've been struggling with implementing Interactive / Actionable Notifications on iOS.

**react-native-cli: 2.0.1
react-native: 0.55.4**

I've done everything as said in docs/advancedIos.md and the callback doesn't work. If I set the NotificationAction activationMode to "foreground", the application comes from background to foreground, when action button is clicked, but still - callback isn't fired.

I've also tried testing **example** application (iPhone 5 (iOS 10.3.3) and iPhone 5s (iOS 11.4)), but it doesn't even show the notification. I call localNotification function, and console prints: Notification Received Foreground: {"_data":{}}

**Comment by arneson** [comment]
@appstart-lt Did you get anywhere on this? I'm having the same issue.

**Comment by dafivius** [comment]
@arneson 
```
- (void)application:(UIApplication *)application handleActionWithIdentifier:(NSString *)identifier forLocalNotification:(UILocalNotification *)notification withResponseInfo:(NSDictionary *)responseInfo completionHandler:(void (^)(void))completionHandler
{
  [RNNotifications handleActionWithIdentifier:identifier forLocalNotification:notification withResponseInfo:responseInfo completionHandler:completionHandler];
}

- (void)application:(UIApplication *)application handleActionWithIdentifier:(NSString *)identifier forRemoteNotification:(NSDictionary *)userInfo withResponseInfo:(NSDictionary *)responseInfo completionHandler:(void (^)(void))completionHandler
{
  [RNNotifications handleActionWithIdentifier:identifier forRemoteNotification:userInfo withResponseInfo:responseInfo completionHandler:completionHandler];
}
```

just added at completionHandler: **(void (^)(void))** as Xcode recommends. Everything began to work well. Ive spent a day to figure whats wrong, xcode made a solution by itself. Hope it helps.

**Comment by arneson** [comment]
@dafivius 
Great, thanks!
I got that working last week too, but my problem was deeper. I am using firebase for notifications and that sdk hogged those events and they were not triggering in AppDelegate. 

So that could be a warning for other people as well.

**Comment by trip41** [comment]
Not necessarily suggesting this fix (because I don't completely understand it's consequences) but I was able to get handlers to actually fire by removing the following `if` block on line 433 in `RNNotifications.m`:

```
// if ([RNNotificationsBridgeQueue sharedInstance].jsIsReady == YES) {
    [[NSNotificationCenter defaultCenter] postNotificationName:RNNotificationActionTriggered 
                                          object:self
                                          userInfo:info];
// }
```

**Comment by athomaj** [comment]
Foe me the handleActionWithIdentifier wasn't triggered because I had the onesignal library installed. Once removed, everything started to work smoothly.
Hope this can help some people.
