### ISSUE TITLE
How can I get new token  ?

### ISSUE THREAD

**Issue by reza-mazarlou** [wix/react-native-notifications#253]
I want in my react application , get new FCM token for each login and expire old token when logout.
I can registered and get successfully token with this example code : 

```
  onNotificationRegister(token) {
         console.log("FCM Token: ", token);
     }

login(){
NotificationsAndroid.setRegistrationTokenUpdateListener(this.onNotificationRegister);
}
```
but I cant get new token or expire old token .

 I try with `NotificationsAndroid.refreshToken();`   but give me last token 
and alos try with `NotificationsAndroid.clearRegistrationTokenUpdateListener();` but give me last token 

How can I get new token and expire old token ?

**Comment by jacquesdev** [comment]
Your device is responsible for assigning a token, and so if you refresh it, and it is still giving you the same one, it means it's still valid for the device, and that is all that is needed.
