### ISSUE TITLE
Background and foreground app is breaking event listeners

### ISSUE THREAD

**Issue by bhushansethi** [wix/react-native-notifications#256]
I am trying to use react-native-notifications with react-native-navigation on Android device
When app is foreground, everything works fine
When app goes to background for first time, still everything works fine.
However, when app comes back to foreground from background , its breaking all the event listeners related to notification 
After that onNotificationReceived, onNotificationOpened doesn't get call.
I am adding listeners  on my top level component just before creating Navigation

**Comment by odradek123** [comment]
Did you fix this? I'm having the same problem :(
