### ISSUE TITLE
Is this still maintained ? if not can we find new set of maintainers ?

### ISSUE THREAD

**Issue by ravirajn22** [wix/react-native-notifications#258]
This is a great lib for push notifications, but lately, there is hardly any traction from the maintainers. If previous maintainers are not available, then can we find a new set of maintainers?. 

 @d4vidi
@gran33  
@lidanh
@amitdwix  
@radko93

Help pls

**Comment by elkinjosetm** [comment]
+1

**Comment by radko93** [comment]
I'm not a maintainer so can't help out here.

**Comment by d4vidi** [comment]
@bruchim

**Comment by ronilitman** [comment]
+1
