### ISSUE TITLE
should I change minSdkVersion to 19

### ISSUE THREAD

**Issue by xralphack** [wix/react-native-notifications#263]
error messages as following:

Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library

Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 19,

**Comment by st167566** [comment]
嗯，是的，我也遇到这个问题，要

**Comment by cassianomon** [comment]
Yes, it worked when I updated minSdkVersion to 19

**Comment by RyanThomas73** [comment]
I looked and found the [PR from July](https://github.com/wix/react-native-notifications/commit/cb77df5a4d3b5d2e48f6abaeb9acb60c8cfd2149#diff-7ae5a9093507568eabbf35c3b0665732) where this was changed to min sdk version 19 and I don't see any signature changes that require minimum sdk version 19. If there was no reason for this change can it be changed back to min sdk version 16 which is the default for react native projects.

The distribution page for sdk versions shows that Jelly Bean (sdk v16, v17, and v18) still accounts for about ~3% of devices which is not trivial.
https://developer.android.com/about/dashboards/

**Comment by ulfgebhardt** [comment]
I second that request - we had complains about this.
The Developer console show ~1000 Devices less supported.

**Comment by diegolmello** [comment]
@ulfgebhardt I needed to update in order to work.
If you can open a PR making sure it still works with min SDK 16, even better.

**Comment by jsamr** [comment]
@diegogenao it would be very nice to revert this please ... cannot use this library and loose 1k supported devices.

**Comment by ulfgebhardt** [comment]
There is a fix proposed here https://github.com/wix/react-native-notifications/pull/304

**Comment by slavikdenis** [comment]
Lets hope this gets merged and released :)

**Comment by ulfgebhardt** [comment]
still not merged - therefore still an issue

**Comment by bnjmnjns** [comment]
overzealous stale bot, chill.
