### ISSUE TITLE
Set badge icon when app is closed

### ISSUE THREAD

**Issue by jahicDario** [wix/react-native-notifications#264]
Hi,

Is there a way to set badge icon when app is closed? Event onNotificationReceived is triggering only when app is in foreground or background, but I need to set number of notifications on icon when user receive notification and his app is closed. 

Thank you.

**Comment by yosukapro** [comment]
I'm having the same issue, does anyone have an idea on this ?

**Comment by ShaneMatthias** [comment]
I am not receiving push notifications when the app is killed. Anyone know why? It works correctly when the app is in the foreground and background.

**Comment by beulahpt** [comment]
try adding the following in AppDelegate.m

- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler {
    completionHandler(UNNotificationPresentationOptionBadge | UNNotificationPresentationOptionSound | UNNotificationPresentationOptionAlert);
}

**Comment by aflahkp** [comment]
I found a way to do this. Appending a field "badge" in notification payload while sending the push from backend (in my case it was sent from a cloud function).

`
var payload = {
      notification: {
        title: valueObject.user.name,
        body: valueObject.text,
        sound: "default",
       badge:'10',
      },
      data: {
        title: title,
        message: message
      },
    };
`
