### ISSUE TITLE
Push Kit notifications not receiving when app kill and reopen the app

### ISSUE THREAD

**Issue by sganti564** [wix/react-native-notifications#265]
Environment: IOS
Notification Type: PushKit Voip
RN: 0.51.0
React: 16.0.0
"react-native-notifications": "^1.1.19"
"react-native-navigation": "^1.1.458"

I am receiving notification using push kit (voip) in all the modes (background and foreground) until I kill or close the app. Once I kill or close the app completely and reopen then none of the messages are being delivered and shown. Didn't find any thing in the device console logs as well. Can someone please help me with this issue. I am stuck with this issue from a week now.

**Comment by ko100v** [comment]
Hey did you find a solution to this ? I'm facing the same problem

**Comment by sganti564** [comment]
hey, I think you need to call consumeBagroundQueue() before loading the app each time. That will resolve the issue.
