### ISSUE TITLE
[Question] Show image preview

### ISSUE THREAD

**Issue by gperdomor** [wix/react-native-notifications#28]
Hi...

It's possible render an image preview in the notification?

**Comment by lidanh** [comment]
I assume you're talking about android notifications, am I right?

**Comment by gperdomor** [comment]
@lidanh no, iOS notifications

**Comment by lidanh** [comment]
Is it possible natively?

**Comment by gperdomor** [comment]
Yes ==> https://developer.apple.com/videos/play/wwdc2016/708/

**Comment by rogchap** [comment]
Any update on this?

**Comment by thuynt99** [comment]
Any exactly answer for that?

**Comment by jussi80** [comment]
For iOS you have to implement Notification Service Extension. It's around 30 minutes task to do and rather straight forward.
[Here](https://www.raywenderlich.com/8277640-push-notifications-tutorial-for-ios-rich-push-notifications#toc-anchor-006) is one good tutorial which show how to show image preview in Push Notification.
