### ISSUE TITLE
[iOS] NotificationsIOS.getInitialNotification() always returning undefined notifications

### ISSUE THREAD

**Issue by bashySet** [wix/react-native-notifications#280]
I am tying to consume notification in iOS when app is not active. Notification receives fine, click notification also opens app fine. However, I am unable to get notification information in app. 

NotificationsIOS.getInitialNotification() is always returning notification undefined and notificationOpened listener is not getting called.

Following is my code:

```javascript
NotificationsIOS.addEventListener("notificationOpened",  myNotificationOpened);
NotificationsIOS.requestPermissions();
NotificationsIOS.consumeBackgroundQueue();
 NotificationsIOS.getInitialNotification()
    .then((notification) => {
       console.log("Pending notification: " + notification);
      // PROBLEM: notification get always undefined here
    });
```
Steps to reproduce:
1-Kill the app
2-Send push notification
3-Click the notification
4-App opens, look at logs for getInitialNotification. Pending notification is always undefined. Also, myNotificationOpened is not getting called

OS: iOS 11.2.6
Phone/Simulator: Physical iPhone
react-native-notifications: 1.1.20

**Comment by bashySet** [comment]
I have found the solution. Actually I didn't need to use getInitialNotification at all. notificationOpened listener was not working due to launchOptions not passed. 
Found solution here: https://github.com/wix/react-native-notifications/issues/35#issuecomment-305022626

**Comment by nvnk3** [comment]
I still have this issue, with latest vesions.
    "react-native-navigation": "^6.4.0",
    "react-native-notifications": "^3.1.4",

**Comment by hassan-kiffgo** [comment]
having same issue 
"react-native-router-flux": "^4.0.6",
"react-native-notifications": "^3.4.2",
