### ISSUE TITLE
[iOS] Foreground notifications never triggers notificationOpened listener

### ISSUE THREAD

**Issue by bashySet** [wix/react-native-notifications#281]
When app is in background or killed, notificationOpened listener is getting called fine. However, when app is in foreground, notificationOpened listener is not getting called. 
notificationReceivedForeground is getting called when notification receives in foreground and again get called when user clicks the notification. I couldn't find the way to differentiate between two as notification object is getting is exactly same. 

Following is my code:

```javascript
function someFunction() {
NotificationsIOS.addEventListener("notificationReceivedForeground", myNotificationReceivedForeground);
NotificationsIOS.addEventListener("notificationOpened",  myNotificationOpened);
NotificationsIOS.requestPermissions();
NotificationsIOS.consumeBackgroundQueue();
}

function myNotificationReceivedForeground(myNotification: any) {
// Called once when notification receives in foreground 
// Called again when notification get clicked
// myNotification is exactly same is both of the cases
}

function myNotificationOpened(myNotification: any) {
// PROBLEM: Did not get called when user clicks notification and app is in foreground 😞 
// Called fine when user clicks notification when app is in background or killed
}


```
Steps to reproduce:
1-Launch the app and make sure its in foreground
2-Send push notification
3-Click the notification
4-myNotificationOpened is not getting called

OS: iOS 11.2.6
Phone/Simulator: Physical iPhone
react-native-notifications: 1.1.20

**Comment by tusharnetset** [comment]
Same issue :(

**Comment by shawerestart** [comment]
check RNNotifications.m file
if it have this function
```
+ (void)didNotificationOpen:(NSDictionary *)notification
{
    [[NSNotificationCenter defaultCenter] postNotificationName:RNNotificationOpened
                                                        object:self
                                                      userInfo:notification];
}
```


add this line before end on RNNotifications.h file:
```
    + (void)didNotificationOpen:(NSDictionary *)notification;
```
