### ISSUE TITLE
[Android] Fcm support Default FirebaseApp is not initialized in this process

### ISSUE THREAD

**Issue by AugustoAleGon** [wix/react-native-notifications#285]
I got the following error after trying a migration:

`Default FirebaseApp is not initialized in this process bundleID. Make sure to call FirebaseApp.initializeApp(Context) first.`

**Comment by yogevbd** [comment]
Published new version with this fix: `react-native-notifications@1.2.2`.
Can you please confirm this solves the issue?

**Comment by AugustoAleGon** [comment]
@yogevbd let me try it today...

**Comment by AugustoAleGon** [comment]
@yogevbd . One quick question. I already have my configuration for the previous version of the GCM on Android. I just changing add to the `build.gradle` this:
```    // implementation 'com.google.android.gms:play-services-gcm:16.0.0'
    implementation 'com.google.firebase:firebase-messaging:17.3.0'
```
And also add the file `google.services.json` to the folder `app`.

**Comment by AugustoAleGon** [comment]
I got the same error. @yogevbd

**Comment by AugustoAleGon** [comment]
I could solve the problem. But after sending a test message. I didn't receive nothing.

**Comment by AugustoAleGon** [comment]
Sorry to bother you @yogevbd . But after testing the version `1.2.1` it works. Version `1.2.2` didn't work for me.

**Comment by AugustoAleGon** [comment]
But it works partially. If I am sending a message from the server. I received just the Title and not the notification text. Please fix this.

**Comment by AugustoAleGon** [comment]
@ramonrovirosa Thanks appreciate it. That was what I did. I had other problem with another library but that was the way I solved. Have tested sending a message from firebase messaging? I received the title but not the body of the message. Do you have the same problem?

**Comment by ramonrovirosa** [comment]
I was able to send a successful test message with a title/body using the Firebase Message Composer https://console.firebase.google.com/project/_/notification.

**Comment by AugustoAleGon** [comment]
@ramonrovirosa you save my day. For some reason the last version wasn't working, but your configuration works!

**Comment by AugustoAleGon** [comment]
@yogevbd I got a weird behaviour. After 5 - 10mins push notifications stop working. I am using algo `react-native-navigation`.

**Comment by Kikketer** [comment]
Any chance any of this would end up in the examples?  I'm moving to react 58.4 and I'm getting the same issue.  I've added the changes that @ramonrovirosa showed but I'm not sure what to do with the `google.services.json`.  Their docs aren't entirely clear: https://developers.google.com/android/guides/google-services-plugin

And an example I found was mind boggling:
https://github.com/firebase/quickstart-android/blob/master/mock-google-services.json

**Comment by Ilario17** [comment]
You should reopen this issue, with the version 1.2.52 this bug is already here

**Comment by bradser** [comment]
I was able to resolve by adding the below line to my dependencies, instead of the 'firebase-core' reference, as that caused some Gradle versioning issues for me:

`implementation "com.google.firebase:firebase-messaging:17.3.0"`

This is the same version of firebase-messaging that's in the project itself.

**Comment by roysG** [comment]
Still happens in the last version, any updates?

**Comment by tbrennanupgrade** [comment]
I succeeded using https://github.com/Benjamin-Dobell/react-native-notifications/tree/android-overhaul, referenced in #300. I had to follow all the steps, including registering the app with FCM.

**Comment by ebaynaud** [comment]
Thanks for all the advices. I can summarize what I did to fix this error using wix/react-native-notifications v1.5.0 (latest version today).

This project migrated from GCM to Firebase and you need to perform these steps:
- [Setup Firebase](https://firebase.google.com/docs/android/setup) following the 4 steps of Option 1. 
- You will get a file called `google-services.json` to add to your `android/app` folder => `android/app/google-services.json`.
- In step 4, you added `implementation 'com.google.firebase:firebase-core:16.0.8'`, replace it with `implementation "com.google.firebase:firebase-messaging:17.3.0"` instead.

Your setup should looks now like:

**package.json**
```
...
  "dependencies": {
...
    "react-native-notifications": "^1.5.0",
...
```
**build.gradle**
```
...
buildscript {
...
    dependencies {
...
        classpath 'com.google.gms:google-services:4.2.0'
...
```
**app/build.gradle**
```
...
dependencies {
    ...
    implementation "com.google.firebase:firebase-messaging:17.3.0"
    ...
}
...
apply plugin: 'com.google.gms.google-services'
```

That should definitely be documented but no time for a PR now.

**Comment by canozgen9** [comment]
Using google-services version 4.3.3 fixed the problem for me.

build.gradle (project level)

```gradle
buildscript {
  dependencies {
     classpath("com.google.gms:google-services:4.3.3")
  }
}
```


**react-native version:** 0.62.18
**react-native-notifications version:** 3.2.2

**Comment by williamdes** [comment]
I am using `com.google.gms:google-services:4.3.15` and `com.google.gms:google-services:4.4.2` was causing this error.
See: https://github.com/firebase/firebase-android-sdk/issues/4693#issuecomment-2269362295
