### ISSUE TITLE
Method invocation 'onPostRequest' may produce 'java.lang.NullPointerException'

### ISSUE THREAD

**Issue by suswari** [wix/react-native-notifications#296]
Hi, 
I am trying to get a local notification on Android and I see the below error when I run the device:

D/ReactNativeNotifs: Native method invocation: postLocalNotification
E/unknown:ReactNative: Exception in native call
    java.lang.NullPointerException: Attempt to invoke interface method 'int com.wix.reactnativenotifications.core.notification.IPushNotification.onPostRequest(java.lang.Integer)' on a null object reference
        at com.wix.reactnativenotifications.RNNotificationsModule.postLocalNotification(RNNotificationsModule.java:102)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:751)
      .
      .
Any idea, what could have been wrong?

notificationservice.js:

/*

*/
import {NotificationsAndroid} from 'react-native-notifications';

const postNotification = () => {
  let localNotification = NotificationsAndroid.localNotification({
    body: "My first notification",
    title: "test title",
  });
};

module.exports = postNotification;

**Comment by ywongweb** [comment]
Same problem here
"react-native-notifications": "1.2.52",

**Comment by nickelbob** [comment]
Any news on this? I'm also experiencing it. Thanks!

**Comment by bradser** [comment]
I worked around it by passing in an empty string for the 'google.message_id' value when calling localNotification(). I didn't try running instead against https://github.com/wix/react-native-notifications/pull/71, but I would hope that would resolve the issue.

**Comment by sstano** [comment]
> I worked around it by passing in an empty string for the 'google.message_id' value when calling localNotification(). I didn't try running instead against #71, but I would hope that would resolve the issue.

Great, thanks! Just to make it crystal-clear, the property is supposed to be called "google.message_id":
```
NotificationsAndroid.localNotification({
    "title": "Local notification",
    "body": "This notification was generated by the app!",
    "extra": "data",
    "google.message_id": "" // <-- Adding this line fixed the problem
});
```

**Comment by wlaurance** [comment]
Add the `google.message_id` worked for me as well. 🤷‍♂

**Comment by MewX** [comment]
Has anyone tried iOS yet? Is this on iOS as well?
