### ISSUE TITLE
On tap of a notification does not open the App

### ISSUE THREAD

**Issue by michelepapale1996** [wix/react-native-notifications#297]
Hi, 
when I tap on a notification in background, the app is not opened and the notification disappears. Then, if I open the app, the event listener fires (and I can see the alert).

```
NotificationsAndroid.setNotificationOpenedListener((notification) => {
    console.log("Notification opened by device user", notification);
    alert(JSON.stringify(notification))
});
```
How can I do in order to open the app on tapping of the notification?

**Comment by huyvm** [comment]
Hi, you can check here, my solution: https://github.com/wix/react-native-notifications/issues/301
