### ISSUE TITLE
React Native Notification not working in foregroud in ios

### ISSUE THREAD

**Issue by tusharnetset** [wix/react-native-notifications#299]
Hii 
Foregroud notifications are not working in ios .

**Comment by huyvm** [comment]
Hi tusharnetset,
Can you check here, this is my solution: https://github.com/wix/react-native-notifications/issues/302

**Comment by yogevbd** [comment]
Fixed in latest version. Follow the changes in [notification events doc](https://github.com/wix/react-native-notifications/blob/master/docs/notificationsEvents.md)
Basically all you have to do is to call the listener completion block with `{ alert: true }`
```js
onNotificationReceivedForeground(notification, completion) {
	completion({alert: true, sound: false, badge: false});
	console.log("Notification Received - Foreground", notification);
}
```
