### ISSUE TITLE
[Android] Documentation out of date

### ISSUE THREAD

**Issue by BenWildeman** [wix/react-native-notifications#300]
This plugin recently went through changes to migrate from GCM to FCM, but there hasn't been any documentation changes specifying the correct way of using this with FCM.

**Comment by ramonrovirosa** [comment]
@BenWildeman  This is my configuration that worked. Hopefully it helps https://github.com/wix/react-native-notifications/issues/285#issuecomment-459178520

**Comment by huyvm** [comment]
Or you can check full docs here: https://github.com/Benjamin-Dobell/react-native-notifications/tree/android-overhaul

**Comment by ebaynaud** [comment]
https://github.com/wix/react-native-notifications/issues/285#issuecomment-490185339

**Comment by BenWildeman** [comment]
still no updated docs

**Comment by yogevbd** [comment]
Fixed
