### ISSUE TITLE
NSMutalbe Dictionary cannot be converted to date 

### ISSUE THREAD

**Issue by munsifhayat** [wix/react-native-notifications#305]
I am getting this issue after upgrading to react native 0.58

React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 57.71 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.2 - /usr/local/opt/node@10/bin/node
      npm: 6.4.1 - /usr/local/opt/node@10/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.5 => 0.58.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

![Simulator Screen Shot - iPhone X - 2019-03-20 at 15 43 40](https://user-images.githubusercontent.com/17729299/54678458-fdc69080-4b26-11e9-8613-906fa41ce806.png)

**Comment by matheusbaumgart** [comment]
Same here, how did you solve it? Couldn't find any documentation for the date format and it's not accepting the basic ones.

**Comment by waynedunkley** [comment]
Anyone that lands here looking for the same answer. parsing the Date object to ISOString works for me.

Example using `date-fns`

```
import { Notifications } from 'react-native-notifications'
import addSeconds from 'date-fns/addSeconds'

Notifications.postLocalNotification({
  body: 'Local notification!',
  title: 'Local Notification Title',
  sound: 'chime.aiff',
  silent: false,
  category: 'SOME_CATEGORY',
  userInfo: {},
  fireDate: addSeconds(new Date(), 5).toISOString(),
})
```
