### ISSUE TITLE
Google Cloud Messaging

### ISSUE THREAD

**Issue by lutakyn** [wix/react-native-notifications#306]
We are all aware that GCM is deprecated but your doc is outdated. It still has GCM in the Manifest file for Android. Can you please update us on how to use the Firebase with the app for notifications

**Comment by huyvm** [comment]
Hi lutakyn, you can check full docs here: https://github.com/Benjamin-Dobell/react-native-notifications/tree/android-overhaul

**Comment by FrankSalad** [comment]
@huyvm that branch uses a really old version of the firebase dependency, is it the latest and greatest?

**Comment by huyvm** [comment]
@FrankSalad It good work with this version. You can try with latest version.

**Comment by yogevbd** [comment]
Updated the docs. closing
