### ISSUE TITLE
pushKitRegistered is not a supported event type for RNNotifications

### ISSUE THREAD

**Issue by skumarcm** [wix/react-native-notifications#307]
I am using RNNotifications version 1.3.0
All regular notifications work perfectly.

But "pushKitRegistered" event is not registered on iOS platform.
It gives the following error while adding the event listener:

'pushKitRegistered` is not a supported event type for RNNotifications. Supported events are: `remoteNotificationsRegistered`, `remoteNotificationsRegistrationFailed`, `notificationReceivedForeground`, `notificationReceivedBackground`, `notificationOpened`

**Comment by skumarcm** [comment]
It looks like some of the events are not included in the supported events list in RNNotifications.m file.
The supported events as per the latest version of the file (committed 3 days ago) are as below:

- (NSArray<NSString *> *)supportedEvents
{
    
    return @[ RNNotificationsRegistered,
              RNNotificationsRegistrationFailed,
              RNNotificationReceivedForeground,
              RNNotificationReceivedBackground,
              RNNotificationOpened];
    
}


This does not include the "pushKitRegistered" along with a few other events

**Comment by JinChengSu** [comment]
I got this error after update RNNotification to RNNRotuer in appDelegate.m

**Comment by JinChengSu** [comment]
![noti](https://user-images.githubusercontent.com/44343877/54996159-8485dc80-5003-11e9-979a-7288d4189433.png)
Can remove error but can't get pushkit token

**Comment by sophieevnex** [comment]
@JinChengSu It looks as though this update is being reverted and will hopefully fix this issue. https://github.com/ravirajn22/react-native-notifications/commit/dbd628fbaea09e4442e62d7e782796be23df582f

**Comment by sophieevnex** [comment]
I think it is the same issue as here https://github.com/wix/react-native-notifications/issues/33. I just followed what @mlanter said and it fixed it for me:

> I ran into this issue as well and fixed it by making sure to do Step 3 of the [Linking guide](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking).
> 
> Specifically I added `$(SRCROOT)/../node_modules/react-native-notifications/RNNotifications`

**Comment by sorin-f-wiredelta** [comment]
Hi @skumarcm !
Are you using this package with the new FCM or with the old GCM ?

**Comment by JinChengSu** [comment]
I am using react-native-firebase

**Comment by skumarcm** [comment]
> Hi @skumarcm !
> Are you using this package with the new FCM or with the old GCM ?

I am using neither FCM nor GCM for iOS devices.
I use Apple pushkit service to send voip push notifications to iOS device. 

However, I use FCM for android devices which is not related to the issue that is mentioned above.

**Comment by JinChengSu** [comment]
I tried to get token by using pushkit.
But can't get token by using react-native-notification

**Comment by basitsattar** [comment]
Hi, any update about this issue?

**Comment by Frindecent** [comment]
having same issue. was anyone able to resolve this?
