### ISSUE TITLE
Migrating from GCM to FCM

### ISSUE THREAD

**Issue by llostris** [wix/react-native-notifications#308]
We're performing a migration to FCM of our app. We were previously using react-native-notifications 1.1.20, and now are trying to use 1.3.0.

I tried to follow the installation steps from https://github.com/Benjamin-Dobell/react-native-notifications/ which were linked in #300. 

Updated `build.gradle`:
```
    compile(project(':react-native-notifications')) {
        exclude group: 'com.google.firebase', module: 'firebase-messaging'
    }
    compile "com.google.firebase:firebase-core:11.6.0"
    compile "com.google.firebase:firebase-messaging:11.6.0"
```

Google Services version: `com.google.gms:google-services:3.1.2`

Our app was already integrated with firebase, we've got a `google-services.json` file in the app.

When trying to run the app, the following error occurs:
```
E/AndroidRuntime: FATAL EXCEPTION: IntentService[FcmInstanceIdRefreshHandlerService]
    Process: com.myeatclub, PID: 16456
    java.lang.NoSuchMethodError: No virtual method getInstanceId()Lcom/google/android/gms/tasks/Task; in class Lcom/google/firebase/iid/FirebaseInstanceId; or its super classes (declaration of 'com.google.firebase.iid.FirebaseInstanceId' appears in /data/app/com.myeatclub-_oSG0b6IhoWpSy4gTW8MOQ==/split_lib_dependencies_apk.apk)
        at com.wix.reactnativenotifications.gcm.FcmToken.refreshToken(FcmToken.java:73)
        at com.wix.reactnativenotifications.gcm.FcmToken.onAppReady(FcmToken.java:63)
        at com.wix.reactnativenotifications.gcm.FcmInstanceIdRefreshHandlerService.onHandleIntent(FcmInstanceIdRefreshHandlerService.java:23)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```
(Same thing happens when trying to upgrade to latest firebase libraries.

Any idea what's causing this?

**Comment by sorin-f-wiredelta** [comment]
@llostris Hi,
May I ask what have you done to solve this, please?
I am assuming you managed to get it solved since you closed the issue.

**Comment by llostris** [comment]
So I realised this is caused by react-native-device-info requiring the GCM library
 Haven't solved it yet I'm afraid, I'm not sure if firebase-messaging and GCM can coexist in the same app?

**Comment by sorin-f-wiredelta** [comment]
@llostris as far as I read, they cannot, that's true, because they integrated Cloud Messaging in Firebase basically -> FCM.
