### ISSUE TITLE
[Android] Attempt to invoke interface method 'void com.wix.reactnativenotifications.core.notification.IPushNotification.onReceived()' on a null object reference

### ISSUE THREAD

**Issue by marudy** [wix/react-native-notifications#310]
Hey guys,

I am getting this error in production but I haven't been able to reproduce it on my tests. We are using a 3rd party platform/SDK that sends the push notifications and I'm not sure how they have been using it in order to get this exception.

Can you suggest what might be causing that and/or a way to fix it?

Thanks,
Tasos

**Comment by nemr-maher** [comment]
i'm having the exact same issue , using the code in the example file for android https://github.com/wix/react-native-notifications/blob/master/example/index.android.js
:
![Screenshot_20190404-155425_RoomzzzMobile](https://user-images.githubusercontent.com/30926789/55566039-d1983b80-56f2-11e9-8bc7-025c46f2c2ba.jpg)

**Comment by avishayhajbi** [comment]
+1

**Comment by ebaynaud** [comment]
Got this error (through Bugsnag) everytime I publish my app to Google Play when they are performing some basic checks:

```
java.lang.NullPointerExceptionFcmInstanceIdListenerService.java:29
Attempt to invoke interface method 'void com.wix.reactnativenotifications.core.notification.IPushNotification.onReceived()' on a null object reference
FcmInstanceIdListenerService.java:29com.wix.reactnativenotifications.gcm.FcmInstanceIdListenerService.onMessageReceived	
Unknown:60com.google.firebase.messaging.FirebaseMessagingService.zzd	
Unknown:2com.google.firebase.iid.zzc.run	
ThreadPoolExecutor.java:1113java.util.concurrent.ThreadPoolExecutor.runWorker	
ThreadPoolExecutor.java:588java.util.concurrent.ThreadPoolExecutor$Worker.run	
Unknown:6com.google.android.gms.common.util.concurrent.zza.run	
Thread.java:818java.lang.Thread.run
```

They are using a device named "WindsongAOB" for theses tests and I guess it has no device token. This error should be catche in react-native-notifications.

**Comment by khasky** [comment]
+1
