### ISSUE TITLE
iOS: linker error since 1.3.0 update

### ISSUE THREAD

**Issue by will-helms** [wix/react-native-notifications#315]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RNNRouter", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in libRNNotifications.a(RNNotifications.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I get this error no matter what I have tried to do to fix it. I followed the new documentation exactly what it says to do.

**Comment by drbarto** [comment]
Same here, however for me it's the first attempt to get this lib working in a fresh react-native project. I added a reference to `RCTPushNotification.xcodeproj` and linked against `libRCTPushNotification.a`, but get mentioned linker error. (Tried in Xcode 9.4.1 and 10.1 with legacy and new build system).

**Comment by will-helms** [comment]
So I found out that if you go to the RNNotifications.xcodeproj -> RNNotifications Target -> Compile Sources -> move RNNRouter.m above the other 2 sources it fixes this issue. This needs to be fixed but this will work for now.

**Comment by yogevbd** [comment]
Fixed in latest version
