### ISSUE TITLE
[WIP] iOS deprecated API replacement -  Breaking -  Interactive / Actionable Notifications

### ISSUE THREAD

**Issue by RajanJS** [wix/react-native-notifications#316]
After [WIP] iOS deprecated API replacement changes,  Interactive / Actionable Notifications featuring is not working; 

First thing; 

RNNotificationActionReceived is not included in the supportedEvents

```
- (NSArray<NSString *> *)supportedEvents
{
    
    return @[ RNNotificationsRegistered,
              RNNotificationsRegistrationFailed,
              RNNotificationReceivedForeground,
              RNNotificationReceivedBackground,
              RNNotificationOpened];
    
}
```

Second,

> No known class method for selector 'handleActionWithIdentifier:forLocalNotification:withResponseInfo:completionHandler:'

After adding,
```
// Required for the notification actions.
- (void)application:(UIApplication *)application handleActionWithIdentifier:(NSString *)identifier forLocalNotification:(UILocalNotification *)notification withResponseInfo:(NSDictionary *)responseInfo completionHandler:(void (^)())completionHandler
{
  [RNNotifications handleActionWithIdentifier:identifier forLocalNotification:notification withResponseInfo:responseInfo completionHandler:completionHandler];
}

- (void)application:(UIApplication *)application handleActionWithIdentifier:(NSString *)identifier forRemoteNotification:(NSDictionary *)userInfo withResponseInfo:(NSDictionary *)responseInfo completionHandler:(void (^)())completionHandler
{
  [RNNotifications handleActionWithIdentifier:identifier forRemoteNotification:userInfo withResponseInfo:responseInfo completionHandler:completionHandler];
}
```

Does it require a different approach after the updates or the Interactive / Actionable Notifications is not supported by this library anymore?

**Comment by RajanJS** [comment]
@aboelbisher Can you please help me.

**Comment by RoderickJDunn** [comment]
@RajanJS I ran into those issues to. Please see my PR (#318) - those changes seem to fix those issues and get NotificationActions functional again.

**Comment by Luckygirlllll** [comment]
I can't add actionable notifications in IOS project, please take a look at my issue https://github.com/wix/react-native-notifications/issues/324

**Comment by Luckygirlllll** [comment]
@RajanJS @RoderickJDunn What is updates regarding this issue? Did you make it work?

**Comment by RajanJS** [comment]
@Luckygirlllll 

> As my issue title states, In **[WIP] iOS deprecated API replacement** there are changes which are breaking the **Interactive / Actionable Notifications** feature. I tried adding the missing **RNNotificationActionReceived**  in the **supportedEvents** but it didn't work. 

So, if you don't want those new updates, and in need of actionable notification to work please use the old version before **[WIP] iOS deprecated API replacement** updates.

In my case, I get it working with version **1.2.6**.

"react-native-notifications": "1.2.6"

**Comment by Luckygirlllll** [comment]
@RajanJS How does AppDelegate.m file should look like in version 1.2.6?

**Comment by RoderickJDunn** [comment]
You need to implement `didReceiveNotificationResponse` in your AppDelegate.m in order for notification actions to work. Remove the old `handleActionWithIdentifier:identifier` methods and add the following.

```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler
{
  [[RNNRouter sharedInstance] userNotificationCenter:center didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
}
```

See this link for an example of how the full AppDelegate.m should look. 
https://github.com/wix/react-native-notifications/blob/498dd34b70f4a4f4897d68a108ede51ccaaf9a5b/example/ios/NotificationsExampleApp/AppDelegate.m

**Comment by yogevbd** [comment]
Fixed in latest version. closing
