### ISSUE TITLE
iOS - notificationReceivedBackground event triggered when app is in the foreground

### ISSUE THREAD

**Issue by calcazar** [wix/react-native-notifications#317]
Not entirely sure why this is happening but at the moment my app if the app is in the foreground and I send a push notification via VOIP the following three events are triggered

notificationReceivedForeground
notificationReceivedBackground
notificationOpened

If the app is in the foreground, I would have expected for the Foreground event to be the only event fired..

Can anyone help explain to me why?

**Comment by rodrigofeijao** [comment]
+1

**Comment by jclough96** [comment]
Created a PR to fix this. Works locally on my machine [320](https://github.com/wix/react-native-notifications/pull/320)

**Comment by rodrigofeijao** [comment]
Have tried on mine and it works like a charm. I am wondering when those PRs will be picked up from someone with merge rights?

**Comment by rodrigofeijao** [comment]
@artald I guess this should have been included on the `1.4.0`, no?

**Comment by jclough96** [comment]
@rodrigofeijao doesn't seem to have been included.
