### ISSUE TITLE
Push Token is never sent to JS on Android. 

### ISSUE THREAD

**Issue by sachin-sable** [wix/react-native-notifications#32]
I have been trying this since past 2 days. I have also tried debugging in library source code. But in the file GcmToken.java, sendTokenToJS() method is getting called. But "reactContext" is coming null. Following is my code. 
` mReactRootView = new ReactRootView(this.getApplicationContext());
   mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setBundleAssetName("index.android.bundle")
                .setJSMainModuleName("index.android")
                .addPackage(new MainReactPackage())
                .addPackage(new ReactAppCallbackModules())
                .addPackage(new WebViewBridgePackage())
                .addPackage(new ReactNativeContacts())
                .addPackage(new AndroidKeyboardAdjustPackage(this))
                .addPackage(new RNNotificationsPackage(getApplication()))
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();

 mReactRootView.startReactApplication(mReactInstanceManager, "ReactApp", null);
`
**My Application Class has code**
`
     private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        @Override
        protected boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.<ReactPackage>asList(
                    new MainReactPackage(),
                    new RNNotificationsPackage(CoreApplication.this)
            );
        }
    };

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
    }
`
The only change in this is I am starting a React Application on specific Activity, that is my HomeActivity. Rest other activities such as Login, etc are written in Native Android.

Can someone please help?

**Comment by pennersr** [comment]
I am not sure, but possibly this is caused by the fact that the token received event triggers in Java while the JS engine is not running yet, causing the event to get lost. You might want to give an explicit `NotificationsAndroid.refreshToken()` token a try as it should re-trigger sending the token to JS.

**Comment by sachin-sable** [comment]
@pennersr : Thank you for the reply. I was on vacation. I tried your suggestion today but it is not affecting anything. I have debugged the source code of React native pushnotification and the point where it sends the token to JS has React context null.  
Filename: GcmToken.java
Method : sendTokenToJS()
Line :  final ReactContext reactContext = instanceManager.getCurrentReactContext();

Here the reactContext is always coming null. :(

**Comment by d4vidi** [comment]
@sachin-sable please try to check whether this log appears when the app is loaded / device is run:
`GCM is refreshing token... instanceId=<instance-id>`

**Comment by sachin-sable** [comment]
@d4vidi Yes. I have checked both the points. And I am getting the log which you mentioned with instanceId and a Token.

Now I have even tried running Example app given. It's same case with Example app too. onPushRegistered() is never called.

**Comment by d4vidi** [comment]
I see. In that case, have you tried calling `NotificationsAndroid.refreshToken()` explicitly when your *react native* activity (app) is ready? Please try to do so, and try to look up a log that says: `Manual token refresh => ...`.

Also, can you copy&paste the log that says "App initialized => ..." (token excluded)

**Comment by sachin-sable** [comment]
@d4vidi : Thank you for your attention on this.
I have tried following: 

Implemented the `ReactInstanceManager.ReactInstanceEventListener` and overridden the following method,
```javascript
@Override
public void onReactContextInitialized(ReactContext context) {
       
        if(context!=null) {
            context.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                    .emit("refreshtoken", null);
        }
}
```

I had the even listener in my js code for above event. There I called the refreshToken method:

```javascript
    DeviceEventEmitter.addListener("refreshtoken", () => {
         NotificationsAndroid.refreshToken();

    });
```

Following are the logs:

```javascript
-ReactNativeNotifs:Running application "ReactApp" with appParams: {"initialProps":{"APP_NAME”:”ReactApp”,”USER_ID”:1},”rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON

-ReactNativeNotifs:App initialized => asking for new token
-ReactNativeNotifs:GCM is refreshing token... instanceId=cRmglHPl_u0
-GCM has a new token: instanceId=cRmglHPl_u0, token=cRmglHPl_u0:AP…

…..



-ReactNativeNotifs: Native method invocation: refreshToken()
-ReactNativeNotifs: Manual token refresh => publishing existing token (cRmglHPl_u0:AP…)

```

**Comment by d4vidi** [comment]
In that case, I would double check that you're properly setting up the main react activity and the app, either as described by [react native's android bootstrap guide](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html), or by inheriting `ReactActivity` and implementing `ReactApplication`in your react activity and application, respectively.
I'm saying this because it appears as though your react instance manager is properly aware of the current react context...

Another question: are you using Wix' `react-native-navigation`?

**Comment by sachin-sable** [comment]
Nopes. I am not using Wix' react-native-navigation. 

Please see my code in activity and application classes.
```java
private void initReactView(){
        mReactRootView = new ReactRootView(this.getApplicationContext());
        mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setBundleAssetName("index.android.bundle")
                .setJSMainModuleName("index.android")
                .addPackage(new MainReactPackage())
                .addPackage(new RNNotificationsPackage(getApplication()))
                .addPackage(new ReactAppCallbackModules())
                .addPackage(new WebViewBridgePackage())
                .addPackage(new ReactNativeContacts())
                .addPackage(new AndroidKeyboardAdjustPackage(this))
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
        mReactInstanceManager.addReactInstanceEventListener(this);
 }

private void startReactApplication() {
        Bundle launchOptions = new Bundle();
        launchOptions.putString("APP_NAME", getString(R.string.app_name).replace("\n", " "));
        launchOptions.putLong("USER_ID", AppUser.loadFromContext(this).ID);
        mReactRootView.startReactApplication(mReactInstanceManager, "ReactApp", launchOptions);
}


```

and my onCreate() has : 
```java
if (SDK_INT >= Build.VERSION_CODES.M && !Settings.canDrawOverlays(this)) {
            Intent intent = new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION, Uri.parse("package:" + getPackageName()));
            startActivityForResult(intent, OVERLAY_PERMISSION_REQ_CODE);
        } else {
            startReactApplication();
}
```

I have also added the package inclusion in Application class:

```java
private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        @Override
        protected boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.<ReactPackage>asList(
                    new MainReactPackage(),
                    new RNNotificationsPackage(CoreApplication.this)
            );
        }
    };

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
    }

    @Override
    public IPushNotification getPushNotification(Context context, Bundle bundle, AppLifecycleFacade facade, AppLaunchHelper defaultAppLaunchHelper) {
        return new MyPushNotification(context,bundle,facade,defaultAppLaunchHelper);
    }
```

 If I don't add package inclusion in Activity, it gives me following exception:

```java
com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'RNNotifications.refreshToken')
```

**Comment by sachin-sable** [comment]
@d4vidi Thank you for your time. I have implemented my own GcmToken class by implementing IGMToken interface but without sending token to js. I send token to JS when my react context is initialised in ** onReactContextInitialized**.

Thanks.

**Comment by d4vidi** [comment]
Sorry to hear we couldn't work it out.

**Comment by seanlau555** [comment]
I am facing the same problem too. Everything gives the correct response.
1. App initialized => publishing existing token (eL9jaDEM...
2. Manual token refresh => publishing existing token (eL9jaDEMJxU:APA91bF ..
However, it always responses null reactContext in sendTokenToJS.
( ReactNativeNotifs: send token reactContext: null )
react-native-navigation : 1.1.193
react-native-notifications : 1.1.14

**Comment by wojteg1337** [comment]
for me adding android.enableAapt2=false in gradle.properties fixed the problem
