### ISSUE TITLE
[ios] RNNotifications.h not found

### ISSUE THREAD

**Issue by andybbtt11** [wix/react-native-notifications#33]
I manually linked everything:  Imported library (xcodeproj), added the .a to Link Binary with Libraries, and added $(SRCROOT)/../node_modules/react-native-notifications/RNNotifications to header search paths for dev and release.

I am still getting 
![screen shot 2017-01-27 at 5 02 28 pm](https://cloud.githubusercontent.com/assets/1443791/22390730/6eb9b188-e4b2-11e6-8231-9870e7d7ce97.png)

when trying to import into appDelegate.m

Did I miss something?

I am using React Native 0.38.0 with RNN experimental.185.  Full AppDelegate:
![screen shot 2017-01-27 at 5 03 52 pm](https://cloud.githubusercontent.com/assets/1443791/22390761/9938737c-e4b2-11e6-920d-89d95f12e6b6.png)

**Comment by andybbtt11** [comment]
Was adding files to wrong target.  thanks.

**Comment by razerduy** [comment]
@andybbtt11 
How do you fix it? I use react-native link, then config PushNotificationIOS on react native docs, then i get the issue when i import RNNotification.h.

**Comment by mlanter** [comment]
I ran into this issue as well and fixed it by making sure to do Step 3 of the [Linking guide](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking).  

Specifically I added `$(SRCROOT)/../node_modules/react-native-notifications/RNNotifications`

**Comment by AndreiCalazans** [comment]
Just in case anyone is still a bit stuck with this try my answer here, it better points out the solution.
https://stackoverflow.com/a/48673626/7727213

**Comment by robfrancis** [comment]
Incase anyone has this issue in 2022, the linking path was slightly different for me.

`$(SRCROOT)/../node_modules/react-native-notifications/lib/ios`

**Comment by RGkevin** [comment]
@robfrancis thanks. Works for me in 2023

**Comment by cengizhanhakan** [comment]
This is still happening in 2023
