### ISSUE TITLE
The project is Dead? (It's not!)

### ISSUE THREAD

**Issue by brayanL** [wix/react-native-notifications#332]
I'm looking for a react native push notifications library, but this library have a lot of a open issues, it seems that nobody is helping to maintain this library.. If this library is being abandoned please write it in the readme of your repository please.

I have a question which library i could to use? or should write native code for push notifications? i don't know if facebook o instagram they have a custom personal libraries for to do that and don't share it with community.

**Comment by aschenkel** [comment]
@brayanL don't think so, there was a big release about a month ago 😆  

https://github.com/wix/react-native-notifications/releases/tag/v1.4.0

**Comment by yogevbd** [comment]
We're working hard on bringing it back to life asap.
We already updated the iOS native part to use the latest iOS SDK and now working on stabilize the Android part.
The next version will have more test coverage and many bug fixes.
Stay tuned 🎉

**Comment by kaloncheung124** [comment]
Good luck @yogevbd, looks like you're doing tons of commits, so thanks for working on bring this back!

**Comment by juddey** [comment]
Yay! @yogevbd to the rescue! :)

**Comment by diegolmello** [comment]
Thanks, @yogevbd!

**Comment by yelkamel** [comment]
great ! :)

**Comment by HoangTrung** [comment]
Great to hear this.
