### ISSUE TITLE
APNs token to FCM token

### ISSUE THREAD

**Issue by mzupek** [wix/react-native-notifications#334]
I can get the device token just fine from the apple device, but when I send the APN token to firebase using the message composer and nothing happens, when I send the android token I get a push notification ? I am guessing I have to install the firebase native library and figure out how to have it generate a FCM token from the APNs token I get back? Unless firebase is supposed to convert them? Any help is appreciated.

**Comment by freerider7777** [comment]
Hi! Did you find a solution?

**Comment by puremana** [comment]
A function to get the FCM token would be incredibly helpful
