### ISSUE TITLE
[IOS] Events don't work when user tap on notification

### ISSUE THREAD

**Issue by narefyev91** [wix/react-native-notifications#335]
Hello,
I did everything which mentioned in documentation regarding register and getting push notification. When my app killed and i get notification, everything is going right - user tap on notification, and I get inside onNotificationOpened. All this events are done in App.js.
Next way - application is loaded and goes in a background - send push notification - open it - and nothing happened - no console.log from onNotificationReceivedBackground, onNotificationOpened.

My App Delegate
// Copyright 2015-present 650 Industries. All rights reserved.
#import "RNNotifications.h"
#import "AppDelegate.h"
@import UserNotifications;

@interface AppDelegate() <UNUserNotificationCenterDelegate>
@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (void)applicationWillEnterForeground:(UIApplication *)application
{
  [super applicationWillEnterForeground:application];
}

#pragma mark - Background Fetch

- (void)application:(UIApplication *)application performFetchWithCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
{
  [super application:application performFetchWithCompletionHandler:completionHandler];
}

#pragma mark - Handling URLs

- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [super application:app openURL:url options:options];
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
  return [super application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
}

// Required to register for notifications
- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings
{
    [RNNotifications didRegisterUserNotificationSettings:notificationSettings];
}

- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
    [RNNotifications didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}

// Required for the notification event.
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification {
    [RNNotifications didReceiveRemoteNotification:notification];
}

// Required for the localNotification event.
- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification
{
    [RNNotifications didReceiveLocalNotification:notification];
}

// Required for the notification actions.
- (void)application:(UIApplication *)application handleActionWithIdentifier:(NSString *)identifier forLocalNotification:(UILocalNotification *)notification withResponseInfo:(NSDictionary *)responseInfo completionHandler:(void (^)())completionHandler
{
    [RNNotifications handleActionWithIdentifier:identifier forLocalNotification:notification withResponseInfo:responseInfo completionHandler:completionHandler];
}

- (void)application:(UIApplication *)application handleActionWithIdentifier:(NSString *)identifier forRemoteNotification:(NSDictionary *)userInfo withResponseInfo:(NSDictionary *)responseInfo completionHandler:(void (^)())completionHandler
{
    [RNNotifications handleActionWithIdentifier:identifier forRemoteNotification:userInfo withResponseInfo:responseInfo completionHandler:completionHandler];
}

- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler {
    completionHandler(UNNotificationPresentationOptionBadge | UNNotificationPresentationOptionAlert | UNNotificationPresentationOptionSound);
}

@end

Maybe I missed something? The same happened when app in foreground, no console.logs appears. Maybe it could be problem - because I ejected from expo and use ExpoKit - but when the app killed - and I receive message all is triggers fine - that's mean that ExpoKit doesn't influence on this issue. Some ideas?

**Comment by huyvm** [comment]
Hello, you can check here, my solution: https://github.com/wix/react-native-notifications/issues/302

**Comment by yogevbd** [comment]
Fixed in `2.0.3`. You can easily migrate using the instructions in our [changelog file](https://github.com/wix/react-native-notifications/blob/master/CHANGELOG.md)

Also see the full [installation guide](https://github.com/wix/react-native-notifications/blob/master/docs/installation.md)
