### ISSUE TITLE
App crashes on android 

### ISSUE THREAD

**Issue by maamounapprise** [wix/react-native-notifications#337]
I tried to install react-native-notifications on android and it crashes before the app renders giving this error:
Default FirebaseApp is not initialized in this process com.myApp Make sure to call FirebaseApp.initializeApp(Context) first

**Comment by maamounapprise** [comment]
I managed to resolve the crashing issue by following this [https://github.com/wix/react-native-notifications/issues/285#issuecomment-490185339](url)

**Comment by lodev09** [comment]
If you don't plan to upgrade to android x yet, I suggest downgrading your RN Notifications to `1.1.23` (77f672cd3716dae8b91478f3fea2d1b24cd54838). This is the most recent GCM version of this package.
