### ISSUE TITLE
Use UserNotifications.framework on iOS 10 and above

### ISSUE THREAD

**Issue by LeoNatan** [wix/react-native-notifications#34]
The currently used local and remote notification APIs are deprecated on iOS 10, but also, the new API allows more features, such as titles, subtitles and attachments in local and remote notifications, which were not possible using the old APIs. The framework should be updated with the UserNotifications.framework support.

**Comment by morrislaptop** [comment]
@LeoNatan I've noticed that https://github.com/evollu/react-native-fcm and https://github.com/a289459798/react-native-mipush appear to use UserNofications.framework, have you tried them?

**Comment by npomfret** [comment]
I'd wait until react-native upgrades to 10 else it won't be compatible with a lot of deployments.

**Comment by LeoNatan** [comment]
The idea is not to stop using the old APIs; it's to use both, depending on OS version.

**Comment by morrislaptop** [comment]
`I'd wait until react-native upgrades to 10`

What do you mean by this?
