### ISSUE TITLE
AutoLinking in React 0.60 causes error in PackageList

### ISSUE THREAD

**Issue by Kikketer** [wix/react-native-notifications#345]
I have a fresh React-Native 0.60 project and have this dependency included.  After syncing the gradle files, it appears that the generated `PackageList.java` file creates the list of dependency constructors (that we used to have to manually do) but `RNNotificationsPackage` needs a parameter to work correctly.

react-native-notifications version: 2.0.0
react-native version: 0.60.3

The generated code looks like this:
```
  public ArrayList<ReactPackage> getPackages() {
    return new ArrayList<>(Arrays.<ReactPackage>asList(
      new MainReactPackage(),
      new RNNotificationsPackage() // This throws an error since it requires the application param
    ));
  }
```

Which throws an error since the constructor needs the application.

**Comment by maddijoyce** [comment]
Unfortunately, my fork is a little too messed up to create a pull request, but this can be fixed by adding a `react-native.config.js` file to the package with the following:
```javascript
module.exports = {
  dependency: {
    platforms: {
      android: {
        packageInstance: "new RNNotificationsPackage(this.getApplication())"
      }
    }
  }
};
```

**Comment by Kikketer** [comment]
Thank you, I actually did something pretty similar:
```
module.exports = {
  dependencies: {
    'react-native-notifications': {
      platforms: {
        android: null // disable Android platform, other platforms will still autolink if provided
      }
    }
  }
}
```

Based on the documentation: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library

**Comment by Agupane** [comment]
I resume both solutions into one that worked for me:
```
module.exports = {
  dependencies: {
    'react-native-notifications': {
      platforms: {
        android: {
          packageInstance: 'new RNNotificationsPackage(this.getApplication())'
        }
      }
    }
  }
}
```
