### ISSUE TITLE
consumeBackgroundQueue not working (iOS 10.2)

### ISSUE THREAD

**Issue by hammadj** [wix/react-native-notifications#35]
I'm using this package along side wix/react-native-navigation, and I have my notification handlers set up in the root App class's constructor as follows:

```js
// notice that this is just a simple class, it's not a React component
export default class App {
  constructor() {
    NotificationsIOS.addEventListener('remoteNotificationsRegistered', this.onPushRegistered.bind(this));
    NotificationsIOS.addEventListener('remoteNotificationsRegistrationFailed', this.onPushRegistrationFailed.bind(this));
    NotificationsIOS.addEventListener('notificationReceivedForeground', this.onNotificationReceivedForeground.bind(this));
    NotificationsIOS.addEventListener('notificationReceivedBackground', this.onNotificationReceivedBackground.bind(this));
    NotificationsIOS.addEventListener('notificationOpened', this.onNotificationOpened.bind(this));
    NotificationsIOS.requestPermissions();
    NotificationsIOS.consumeBackgroundQueue();

// ...rest of the code
```

However, when the app launches from a cold state after pressing a notification, there is never anything sent to the notification handlers. Any insight onto why this isn't working? Is it something to do with react-native-navigation?

**Comment by Lughino** [comment]
Same problem here!

**Comment by tnortman** [comment]
+1

**Comment by enahum** [comment]
not working in IOS 10.3.1, any news?

**Comment by d4vidi** [comment]
@enahum which version of RNN are you using?

**Comment by enahum** [comment]
@d4vidi im on RNN 1.1.72

**Comment by lodev09** [comment]
Same here :)

**Comment by elliotstokes** [comment]
It seems to fire the correct event and correctly enters the code on the native side but the premise always resolves with null on getInitialNotification.

**Comment by enahum** [comment]
I really don't know anything about Objective-C but I'm wondering if this has anything to do with it https://github.com/wix/react-native-navigation/blob/master/ios/RCCManager.m#L41

**Comment by d4vidi** [comment]
@bruchim Could you possibly help these guys out? They're using <2 navigation version.

**Comment by jbolter** [comment]
I'm having the same problem and am also using react-native-navigation < v2.  Scratching my head here trying to figure out why these handlers don't seem to be called.

**Comment by jbolter** [comment]
Ok guys I solved it... I think the react-native-navigation docs could definitely be updated for iOS to include this tidbit.

"launchOptions" is not passed to the bridge if you use the default AppDelegate example from the react-native-navigation docs.

You need to use this to start the app (passing launchOptions) so that the push notification that was pressed is available to the bridge.

`[[RCCManager sharedInstance] initBridgeWithBundleURL:jsCodeLocation launchOptions:launchOptions];`

Once the launchOptions are passed to the bridge you should see the `notificationOpened` handler is firing as expected.

**Comment by enahum** [comment]
I can confirm that the solution form @jbolter works as a charm. Thanks my friend
