### ISSUE TITLE
startMonitorNotifications No Know class method for selector

### ISSUE THREAD

**Issue by methce** [wix/react-native-notifications#353]
Trying to implement package in my project, I see that the installation file was updated 4 days ago, so I'm hoping it might be a typo:

 Then, to enable notifications support add the following line at the top of your AppDelegate.m
	[RNNotifications startMonitorNotifications]; // -> Add this line
This startMonitorNotifications accuses No Know class method for selector.

I'm using CocoaPods for installation.

react-native: 0.58.6
react-native-notification: 1.4.0

**Comment by yogevbd** [comment]
How do you import `RNNotifications.h`?
I couldn't reproduce so it sounds like xcode caching issue, Try removing `DerivedData` folder and try rebuild the project

**Comment by jonmnoj** [comment]
I had this problem a few days ago trying to integrate 1.5.0. 
The setup guide is for the current version 2.0.3, startMonitorNotifications doesn't seem to exist for older versions.
I just updated to the most recent version which didn't throw this error.

**Comment by methce** [comment]
@jonmnoj yeah, updating to 2.0.3 solve the problem, for some reason npm wasn`t pulling the latest version, thx 4 the help :D
