### ISSUE TITLE
'React/RCTEventEmitter.h' file not found

### ISSUE THREAD

**Issue by HoangTrung** [wix/react-native-notifications#360]
<img width="869" alt="Screen Shot 2019-08-13 at 4 47 11 PM" src="https://user-images.githubusercontent.com/1860834/62932401-3de62280-bdea-11e9-8548-caf7f9fc8003.png">

`"dependencies": {`
        ` "react": "16.8.6",`
        ` "react-native": "0.60.4",`
        `"react-native-notifications": "^2.0.6"`
 ` },`

**Comment by amarjeet89** [comment]
Any luck, Did you got fix for this issue?

**Comment by Guiro44** [comment]
Hello,
Having the same issue,
how did you fix it please? (@amarjeet89 or @HoangTrung )
Thanks

**Comment by HoangTrung** [comment]
@Guiro44 
I downgraded my reactive version.
"react-native": "0.59.8",
"react-native-notifications": "^2.0.6",

**Comment by chika-kasymov** [comment]
I fixed that by changing the path to source files in the **./node_modules/react-native-notifications/react-native-notifications.podspec** file.
Initially it was `s.source_files   = 'RNNotifications/*.{h,m}''`, I changed it to `s.source_files   = 'lib/ios/*.{h,m}'`.
PS: Also I didn't use manual linking. Since my RN version is **0.60.5** I did run `pod install` in **./ios** directory and the library was installed successfully.

**Comment by bkarst** [comment]
Shouldn't have to downgrade React to fix this. Are there any viable solutions to this?

**Comment by Guiro44** [comment]
Hi,
Thanks for you answers.
@bkarst , You can try to fix it by doing:
- add the library as target (under scheme, +, check the library)
- select the library as project,
- go to Build Phases
- search header search paths
- Change this with real paths of your headers

**Comment by wilkuintheair** [comment]
Same issue.
I've found out that a folder pointed in the Header Search Paths property contains the RCTEventEmmiter.h file but it's under node_modules/react-native/React/Modules/ folder. When I changed the import @HoangTrung mentioned, to React/Modules/RCTEventEmitter.h I got different errors :D But i guess this RCTEventEmitter part got compiled properly.
Maybe this will lead someone to some solution.

**Comment by jakecronin** [comment]
Worked for me by using pods instead, however I am on react-native 0.60.5

I unlinked the library and added this line to podfile:
`pod 'react-native-notifications', :path => '../node_modules/react-native-notifications'`

**Comment by mirhat** [comment]
@jakecronin I have tried adding it with pods but than I get "RNNotifications.h" not found

**Comment by jsina** [comment]
here is my workaround on these version of packages:
```
"react-native-notifications": "^2.0.6",
"react": "16.9.0",
"react-native": "0.61.2",
```
I follow this link for adding Manual linking:
**hint:**  for ``` Header Search Paths``` setting I've add ```"${PODS_CONFIGURATION_BUILD_DIR}/react-native-notifications"``` separately on _Debug_ and _Release_ `(don't forget the double quotation arount the path)`
also before running go to ```ios``` folder and run ```pod install``` again

**Comment by markkdev** [comment]
> Worked for me by using pods instead, however I am on react-native 0.60.5
> 
> I unlinked the library and added this line to podfile:
> `pod 'react-native-notifications', :path => '../node_modules/react-native-notifications'`

Been at it for days, this worked for me.

yarn add react-native-notifications

followed direction to add to AppDelegate.m

added the following line to my pod file

ran pod install 

App build succeeded

**Comment by xgenem** [comment]
Issue still unresolved.

**Comment by rmtry** [comment]
Did you have this inside of your `Podfile`?
`pod 'RNEventEmitter', :path => "../node_modules/react-native-events"`

**Comment by savdev-ua** [comment]
having same issue in 2023
