### ISSUE TITLE
consumeBackgroundQueue is not a function

### ISSUE THREAD

**Issue by HoangTrung** [wix/react-native-notifications#362]
<img width="336" alt="Screen Shot 2019-08-14 at 11 08 47 AM" src="https://user-images.githubusercontent.com/1860834/62993984-e8f6ea80-be83-11e9-995b-e6d8b6a912a3.png">

`"react": "16.8.3",`
    `"react-native": "0.59.8",`
    `"react-native-notifications": "^2.0.6",`

**Comment by yogevbd** [comment]
Please refer to: https://github.com/wix/react-native-notifications/issues/365
This function was removed and no longer needed in the latest version
