### ISSUE TITLE
TypeScript Typings

### ISSUE THREAD

**Issue by johndturn** [wix/react-native-notifications#373]
Are there any plans for including typings in order to use this package in a TypeScript project?

**Comment by yogevbd** [comment]
Yes. Take a look at [V3](https://github.com/wix/react-native-notifications/commits/v3)

**Comment by johndturn** [comment]
Ah, great! Is there a rough timeline / roadmap for V3? Anything that we can help with?

**Comment by yogevbd** [comment]
All that left is to finish the documentation! 
You can start migrate to the new `3.0.0-alpha.0` version. The API changed a bit and there is more consistency between iOS and Android. Take a look at the [new documentation](https://wix.github.io/react-native-notifications/docs/general-api)

Thanks!

**Comment by johndturn** [comment]
Great! Thanks for the info!
