### ISSUE TITLE
new RNNotificationsPackage() required: Application found: no arguments

### ISSUE THREAD

**Issue by TchernyavskyDaniil** [wix/react-native-notifications#374]
I have some error, Android, RN 60 4
![изображение](https://user-images.githubusercontent.com/29048318/64703704-a7bf1e00-d4b5-11e9-8e47-e3f1d1679fbb.png)

new RNNotificationsPackage(MainApplication.this) or new RNNotificationsPackage(), nothing helps

```
package com.someapp;

import android.app.Application;
import android.util.Log;

import com.facebook.react.PackageList;
import com.facebook.hermes.reactexecutor.HermesExecutorFactory;
import com.facebook.react.bridge.JavaScriptExecutorFactory;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;
import com.wix.reactnativenotifications.RNNotificationsPackage;

import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      packages.add(new RNNotificationsPackage(MainApplication.this));
      return packages;
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}
```

Can you explane me, what's wrong?

**Comment by ArekChr** [comment]
RN60 creates autolinking packages with no arguments, to ignore that put this in root folder:


```
// react-native.config.js
module.exports = {
  dependencies: {
    'react-native-notifications': {
      platforms: {
        android: null, // disable Android platform, other platforms will still autolink if provided
      },
    },
  },
};

```

**Comment by TchernyavskyDaniil** [comment]
> RN60 creates autolinking packages with no arguments, to ignore that put this in root folder:
> 
> ```
> // react-native.config.js
> module.exports = {
>   dependencies: {
>     'react-native-notifications': {
>       platforms: {
>         android: null, // disable Android platform, other platforms will still autolink if provided
>       },
>     },
>   },
> };
> ```

And how can I test notification on Android emul after then ?

**Comment by ArekChr** [comment]
> > RN60 creates autolinking packages with no arguments, to ignore that put this in root folder:
> > ```
> > // react-native.config.js
> > module.exports = {
> >   dependencies: {
> >     'react-native-notifications': {
> >       platforms: {
> >         android: null, // disable Android platform, other platforms will still autolink if provided
> >       },
> >     },
> >   },
> > };
> > ```
> 
> And how can I test notification on Android emul after this ignore?

Please just follow docs

**Comment by TchernyavskyDaniil** [comment]
> > > RN60 creates autolinking packages with no arguments, to ignore that put this in root folder:
> > > ```
> > > // react-native.config.js
> > > module.exports = {
> > >   dependencies: {
> > >     'react-native-notifications': {
> > >       platforms: {
> > >         android: null, // disable Android platform, other platforms will still autolink if provided
> > >       },
> > >     },
> > >   },
> > > };
> > > ```
> > 
> > 
> > And how can I test notification on Android emul after this ignore?
> 
> Please just follow docs


Maybe I don’t understand something, but after that it’s impossible to test the notification on the android?

**Comment by ArekChr** [comment]
> > > > RN60 creates autolinking packages with no arguments, to ignore that put this in root folder:
> > > > ```
> > > > // react-native.config.js
> > > > module.exports = {
> > > >   dependencies: {
> > > >     'react-native-notifications': {
> > > >       platforms: {
> > > >         android: null, // disable Android platform, other platforms will still autolink if provided
> > > >       },
> > > >     },
> > > >   },
> > > > };
> > > > ```
> > > 
> > > 
> > > And how can I test notification on Android emul after this ignore?
> > 
> > 
> > Please just follow docs
> 
> Maybe I don’t understand something, but after that it’s impossible to test the notification on the android

Could you clarify? Why it's impossible?

**Comment by ArekChr** [comment]
Please follow that [https://github.com/realm/realm-js/issues/2460#issue-470162630](url)

**Comment by TchernyavskyDaniil** [comment]
> Please follow that [https://github.com/realm/realm-js/issues/2460#issue-470162630](url)

Ok, i will try, thanks

**Comment by bdrobinson** [comment]
I think the change in `react-native.config.js` mentioned above just disables autolinking. That then means you have manually link it – by adding the usual lines in `settings.gradle`, `app/build.gradle`, and manually adding `new RNNotificationsPackage(MainApplication.this)` to the package list in `MainApplication.java`, more or less as you would have done in RN < 0.60.
