### ISSUE TITLE
Scheduled Notification in Android Local Notification

### ISSUE THREAD

**Issue by EarvinJay** [wix/react-native-notifications#377]
Hello, Is scheduled notification not supported in android  ? I've tried fireDate property but it's not working. Can you advise ? 

Thanks,

**Comment by paldepind** [comment]
I find the documentation to be a bit unclear regarding this. But, based on other issues it appears to be unsupported. #209, #127.

**Comment by tangtai** [comment]
so does the scheduled notification work?

**Comment by andrewtremblay-pear** [comment]
fireDate is still an iOS-only variable and the Android NotificationManager has no built in scheduling behavior, so any logic that would be needed to make this work would need to be in the native Package. https://github.com/wix/react-native-notifications/search?q=fireDate&unscoped_q=fireDate

If this is not work that will be done soon, the readme should be updated to express that scheduled local notifications are not possible on android to avoid repeat issues like this in the future.

**Comment by matheusbaumgart** [comment]
Also waiting on this, any estimate?

**Comment by andrewtremblay** [comment]
If this is the only feature you want and are willing to make a switch, other push-notification repos have this feature: 
https://github.com/zo0r/react-native-push-notification

**Comment by arberK** [comment]
Are there any plans for this feature for those who want to decide which library to use ?

**Comment by andrewtremblay-pear** [comment]
Renewing the stale message because I believe this issue should be given attention by a moderator of this repo. 

It is very important that all platforms be given feature parity wherever possible. The ability to schedule notifications without a remote service managing them is core to many applications. At the very least the documentation of this repo should reflect that this feature is missing.

**Comment by arnaudambro** [comment]
Interested too !

**Comment by JaioSkura** [comment]
Here same. Very needed feature

**Comment by netusco** [comment]
so there is a clear need for it, anybody listening?

**Comment by hannojg** [comment]
This needs to come to android too!

**Comment by robwafle** [comment]
Switch to flutter ;) flutter_local_notifications is awesome.

**Comment by yannickpschroeder** [comment]
Still looking for that feature
