### ISSUE TITLE
[Android] getInitialNotification not working

### ISSUE THREAD

**Issue by CristianOspina** [wix/react-native-notifications#378]
I have installed the latest version of this package. I have made the link manually on Android according to the guide.

Everything works: `NotificationsAndroid.setNotificationOpenedListener`, `NotificationsAndroid.setRegistrationTokenUpdateListener`, etc. and in iOS also everything is fine.

But `PendingNotifications.getInitialNotification()` always return _N/A (false)_, so I can't get the payload when a notification is openen and the app was closed. 

I use:
```
"react-native": "0.60.5",
"react-native-navigation": "^3.1.2",
"react-native-notifications": "^2.1.0"
```

Any ideas what could be wrong?

**Comment by CristianOspina** [comment]
The workaround in https://github.com/wix/react-native-notifications/issues/326#issuecomment-507371366 works but only when the app is killed. Is the app is active in background I still can't get the notification.

**Comment by yogevbd** [comment]
Can't reproduce it in our example project and it also doesn't reproduce in our production app. can you elaborate? maybe it's something with the payload itself?

**Comment by rgommezz** [comment]
Can confirm what @jakubkoci stated. 

`PendingNotifications.getInitialNotification()` works as expected when sending a test push notification through a HTTP POST request instead of the firebase console.

**Comment by CristianOspina** [comment]
Right. It works now. Sorry for the delay and thank you!

**Comment by itsmelion** [comment]
Thanks @jakubkoci , helped alot..

Any idea how to deal with this in Admin SDK environment ?
cuz my current
`sendMulticast({
  notification: { ... }
  data: { ... }
  android: { notification, data }
  // or anything else
})`

**Comment by itsmelion** [comment]
Ok, got it.
I just had to delete the notification nodes

**Comment by uday5162** [comment]
I tried deleting the notification node which is working fine.
But unable to get notification image after removing.
any idea?
