### ISSUE TITLE
Android Simulator getInitialNotification returns undefined

### ISSUE THREAD

**Issue by Elf2707** [wix/react-native-notifications#38]
When app is in foreground all works as expected, but then app is in background and it receives notification and user taps it app goes to foreground, but getInitialNotification returns undefined. I use android-gcm to send messages to the app.

**Comment by Elf2707** [comment]
I found the reason. If I have both notification and data payload in message and app is in the background it only displays notification in status bar, but doesn't pass anything to getInitialNotification. Service method onMessageReceived doesn't get called. If I put all field (sound, title, body, icon) from notification payload to data payload and send only data payload onMessageReceived works well for background and foreground and getInitialNotification returns notification. More useful info here [https://developers.google.com/cloud-messaging/concept-options#target](url)

**Comment by d4vidi** [comment]
Good call.
Indeed, this is the weird yet well-known behavior of the default handler. It got me confused as well when I first started integrating GCM.

**Comment by cristianonescu** [comment]
@Elf2707 link expired. Can you please describe this in detail? Thanks!
