### ISSUE TITLE
cannot find symbol error while run android please solve it 

### ISSUE THREAD

**Issue by Jagadhissh** [wix/react-native-notifications#385]
![image](https://user-images.githubusercontent.com/41655170/65736915-6015d480-e0fa-11e9-9f26-4967837e7585.png)

 error: cannot find symbol
    public static NotificationManagerCompat from(@NonNull Context context) {
                  ^

react-native 0.59 
    "react-native-navigation": "^2.22.1",
    "react-native-notifications": "^2.1.3",

**Comment by huyvm** [comment]
@Jagadhissh Hello, You can try remove node_modules and reinstall npm install, cd path/your-project/android, ./gradlew clean, ./gradlew installDebug

**Comment by yogevbd** [comment]
Please refer to the additional step needed in version `^2.1.0`: https://github.com/wix/react-native-notifications/blob/master/CHANGELOG.md#breaking-change

It was needed for `react@0.60` support.

**Comment by izaa** [comment]
@yogevbd what steps? The link is not working anymore

**Comment by yogevbd** [comment]
Follow [this installation step](https://github.com/wix/react-native-notifications/blob/v2/docs/installation.md#step-5-rnnotifications-and-react-native-version).
