### ISSUE TITLE
How to create schedule Local Notification on Android?

### ISSUE THREAD

**Issue by BondGoat** [wix/react-native-notifications#39]
Hi there,

I want to create an schedule local notification on Android, I tried 'fireDate' parameter like iOS, but it does not work. Can anyone give me some hint?

Thanks in advance.

**Comment by d4vidi** [comment]
Hi,
unfortunately, this feature is not supported on Android.
Consider using Android's [JobScheduler](https://developer.android.com/reference/android/app/job/JobScheduler.html) (or assign a PR :-) )
