### ISSUE TITLE
multiple and confusing documentations

### ISSUE THREAD

**Issue by AmmarRajab** [wix/react-native-notifications#393]
Hi, first of all thank you for this library it's really important especially the React-Native-Firebase notifications module is not yet published making this library the best choice, but there's some confusion:  
# Installation link
## In GitHub repo:  
The installation command is  
`npm install react-native-notifications@^2.0.6 --save `  
Clearly installing old release  

## npm
`npm install react-native-notifications --save`  
Which installs the latest version published in the releases.  

# API
In **GitHub** repo you're using `NotificationsIOS.localNotification` and `NotificationsAndroid.localNotification` for local notifications.  

In the documentation page in ** npm ** you're using `Notifications.postLocalNotification`  

# Linking
In the **GitHub** you provide instructions to handle different versions of react native

In **npm** docs no mention for these notes or precise steps of linking especially with the new React auto linking feature.  

I think you got the point .. would you please make this more clear , which version should we use and which docs should we follow

**Comment by jsina** [comment]
same problem

**Comment by jsina** [comment]
@AmmarRajab
here is my workaround on these version of packages:
```
"react-native-notifications": "^2.0.6",
"react": "16.9.0",
"react-native": "0.61.2",
```
I follow this link for adding Manual linking:
**hint:**  for ``` Header Search Paths``` setting I've add ```"${PODS_CONFIGURATION_BUILD_DIR}/react-native-notifications"``` separately on _Debug_ and _Release_ `(don't forget the double quotation arount the path)`
also before running go to ```ios``` folder and run ```pod install``` again

**Comment by matheusbaumgart** [comment]
The problem remains
