### ISSUE TITLE
React Native 0.60+ Autolinking feature is required

### ISSUE THREAD

**Issue by TheMisir** [wix/react-native-notifications#397]
It's 2019, but Wix packages require manual linking. Autolinking will help me and many developers like me to easily integrate this lib without the need to write any native code.

**Comment by rendomnet** [comment]
Literally only Wix packages require manual linking in my project. All other are already supporting autolinking.

**Comment by itsmelion** [comment]
the problem is the documentation/main-branch now seems confusing _(kindo abandoned)_
Probably due the efforts being mainly on v3 now.

**Comment by lonnylot** [comment]
Bump

@itsmelion is there anywhere to find out the progress of v3?

**Comment by itsmelion** [comment]
@lonnylot Well, i dont know any thing very conclusive from them, like release dates, progress percentage), twitter, but at least you can try clicking on 

> **Watch** > Releases-only

dropdown _(near the Star/Fork buttons)_ so you may get all releases notifications, and see if they change from beta to RC(release candidates) etc..

or `yarn info react-native-notifications versions` from time to time, see if anything pops-up
😞

**Comment by TheMisir** [comment]
RIP.

**Comment by fgreinus** [comment]
[Possible workaround (for now)](https://github.com/wix/react-native-notifications/issues/430#issuecomment-573208679)

If somebody is interested...

**Comment by gluons** [comment]
This issue keep closing by the annoying bot.

This is important issue. Please reopn.

**Comment by TheMisir** [comment]
Stupid bot.
