### ISSUE TITLE
Trying out 3.0.0-beta.1

### ISSUE THREAD

**Issue by sdcooke** [wix/react-native-notifications#399]
I'm not sure how ready it is but since I'm migrating to `react-native-notifications` I figured I should give it a go (particularly given it looks like the APIs have been merged). I've found a few issues that I think I've managed to fix by patching the package - some I know how to fix, some I don't. Let me know if you want me to put together a PR with these changes (should I PR to the `v3` branch?). Hopefully this is useful to you, apologies if it's just wasting time!

### Documentation change

In the new documentation it says to call `Notifications.requestPermissions()` but `Notifications.registerRemoteNotifications()` seems to be the correct call.

### Use of "Proxy"

The hermes JS engine doesn't support proxies, and might not in the future (https://github.com/facebook/hermes/issues/33). Since it's only used for a relatively minor feature (in NotificationsAndroid.ts and NotificationsIOS.ts) in this package a simple fix is to do something like:

```javascript
if (Platform.OS !== "android") {
    Object.getOwnPropertyNames(NotificationsAndroid.prototype).forEach(propertyName => {
        if (propertyName !== "constructor") {
            this[propertyName] = () => {};
        }
    });
}
```

### Android building

One of the paths in `lib/android/app/build.gradle` is wrong:

```
-    def reactNativePackageJson = packageSlurper.parse file('../../../node_modules/react-native/package.json')
+    def reactNativePackageJson = packageSlurper.parse file('../../../../../node_modules/react-native/package.json')
```

And I couldn't compile without changing:

```
-    implementation "com.google.firebase:firebase-messaging:17.3.0"
+    implementation "com.google.firebase:firebase-messaging:20.0.0"
```

I was able to get auto linking working by adding:

```
    dependencies: {
        "react-native-notifications": {
            platforms: {
                android: {
                    sourceDir: path.join(__dirname, "node_modules/react-native-notifications/lib/android/app"),
                    folder: path.join(__dirname, "node_modules/react-native-notifications/lib"),
                    packageImportPath: "import com.wix.reactnativenotifications.RNNotificationsPackage;",
                    packageInstance: "new RNNotificationsPackage(this.getApplication())"
                }
            }
        }
    }
```

to my `react-native.config.js`. Note: the use of `MainApplication.this` suggested in the docs did not work but changing to `this.getApplication()` seemed to fix that. As far as I can tell there's no way to include this config with the package. Possibly using `rnpm` in package.json but that is being deprecated.

### Platform difference

Lastly `Notifications.registerRemoteNotificationsRegistered` provides `{deviceToken: string}` on iOS and just a string on Android.

**Comment by sdcooke** [comment]
Some more additional things I've found trying to get notifications working on Android:

In `NativeEventsReceiver.ts` on Android it should be `new Notification(response)` - I haven't tried iOS yet but I'm assuming that's correct as `new Notification(response.notification)` given the previous difference I found.

Also I've found that I need to include a "pushNotification" key in my remote push notification data for it to be passed to the javascript when opening from the notification (because of the way `NotificationIntentAdapter.canHandleIntent` is used on `onNewIntent`). I'm not sure if that's ideal - maybe checking for the `google.message_id` key would be better? It looks like the "pushNotification" key is related to local notifications.

**Comment by sdcooke** [comment]
Also it is confusing that it seems the only way to avoid notifications showing up (a blank notification in my case) when the app is in the foreground is to comment `postNotification(null);` in `onReceived()` in `PushNotification.java`.

**Comment by sdcooke** [comment]
Continuing to add to this issue with my findings - now I'm moving on to iOS!

There's inconsistency in the library about using `setBadgeCount` and `setBadgesCount` (same with `getBadgeCount` and `getBadgesCount`). I think probably the correct solution is to rename the native iOS code to use singular "Badge" rather than "Badges".

**Comment by jpgarcia** [comment]
@sdcooke Thank you for the detailed steps! I'm also struggling with the same stuff you mention in this thread.

I could get the **Android** device token and also receive a notification on device's notification center (I'm using `firebase-admin` library from the server to send notifications)

Anyway I'm not being able to get the `registerRemoteNotificationReceived` nor the `registerRemoteNotificationOpened` callbacks from the app.

Did you also follow the steps [described here](https://github.com/wix/react-native-notifications/wiki/Android:-working-with-RNN) to receive the notification callbacks in the app or it just worked with the stuff auto-linking does?

BTW for IOS I could get almost the flow working but the notification actions (`NotificationAction` / `NotificationCategory`) Did you find a workaround for this?

**Comment by stefnnn** [comment]
+1 for not using «Proxy» as it is also not supported on iOS 9 and below.

**Comment by Kenpa** [comment]
Thanks to you @sdcooke, I was able to build for android and iOS. But I still encounter some issues, for example I cannot make `getInitialNotification` work... It always returns `undefined` for me.
Did you also face this problem ?

**Comment by ken0x0a** [comment]
@sdcooke Thank you for sharing!!
I should definitely see your documents.
