### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by veedeo** [wix/react-native-notifications#4]
Hey guys, first of all thanks for your contribution, this is a brilliant peace of code and very usefull for RN comunity.
While iOS version looks complete, the lack of Android is very frustrating.
Do you have any plans to support Android and if so, when do you think it will be available for beta testing?

**Comment by lidanh** [comment]
Hi @veedeo, we're working on the Android version and it will be available soon. stay tuned!

**Comment by andreasbhansen** [comment]
Any updates? 😄

**Comment by nicolabortignon** [comment]
Hi @lidanh thanks for the work on this! 
I saw the android branch, anything you need help with?

**Comment by dininski** [comment]
Do you plan on supporting notification templates in Android?

**Comment by lidanh** [comment]
Hey, sorry for the delayed response, was on vacation.
The plan is to fully support android notifications, same as iOS.  it takes time, but we're on it.

I'll check the status of the android version and keep you updated here.

Thanks,
Lidan

**Comment by lidanh** [comment]
I'm happy to announce that thanks to @amitdwix, we've added Android support!
Currently it's still basic support (receive remove notifications), but we're on it and new features will be released soon.   You're more than welcome to help us and PR!

FYI- @dininski @nicolabortignon @andreasbhansen @veedeo @oriharel
