### ISSUE TITLE
The Notification icon is not App icon

### ISSUE THREAD

**Issue by BondGoat** [wix/react-native-notifications#40]
Hi there,

How to configure the icon of Notification to App icon?

Thanks.

**Comment by Elf2707** [comment]
As I understand in Android it sets app icon by default, but here is the thing in Android after Lollipop and according to Material design guidelines notification icon should have only two colors transparent and not transparent. System displays it like alpha channel if you have transparent pixel it will be transparent if not pixel will be white or color you setup for icon. There is setLargeIcon function but this icon will only appear in notification banner not in the status bar. Any way to customize your notification use this doc https://github.com/wix/react-native-notifications/wiki/Android-Customizations#customizing-notifications-layout
