### ISSUE TITLE
IOS 13 & silent background notification to replace PushKit 

### ISSUE THREAD

**Issue by johanschram** [wix/react-native-notifications#400]
Hi ! 

A quick question. Since a few years, I've been using PushKit to handle silent background notification in my app, but since IOS 13, it's no longer possible if you're not using PushKit for "Real VOIP", which I'm not (but for my defense, its was super convenient and reliable) ...
Well, if thus been wondering if this library is planning to implement silent background notification : 
User receive a background notification, it wakes up the app, it does what ever it has to do, and goes back to sleep. 
Or maybe it's already supported ?  But in this case, I didn't see anything the docs related to it... 

For now, I build the app with Xcode 10 to avoid this issue, but that will not last for long...

**Comment by guosim** [comment]
Same issue here!

**Comment by barak109** [comment]
Same
