### ISSUE TITLE
Customizable Actions

### ISSUE THREAD

**Issue by guanw** [wix/react-native-notifications#407]
Basically looking at similar issue as #139, we are trying to implement notification with customized action, something like this screenshot 
![image](https://user-images.githubusercontent.com/7311035/68730625-3e35bb80-059b-11ea-8306-470e5de497c5.png)

Is there any way to do it on the js level or it has to come down to native android/ios code? Thanks for any response in advance.

**Comment by movie4** [comment]
Is there any information on this?
