### ISSUE TITLE
IOS `notificationOpened` event not trigger when user click the pushnotifications and the app is in background 

### ISSUE THREAD

**Issue by lamyuho** [wix/react-native-notifications#412]
when my IOS app is on the background and the user clicks the pushNotification the `notificationOpened` never triggers what event should I use when the app is on the background?
I know when the app needs to launch I should use `NotificationsIOS.getInitialNotification()` but the app now is only on the background so I can't use that one right? Thank you for your help

**Comment by phamhien2102** [comment]
> when my IOS app is on the background and the user clicks the pushNotification the `notificationOpened` never triggers what event should I use when the app is on the background?
> I know when the app needs to launch I should use `NotificationsIOS.getInitialNotification()` but the app now is only on the background so I can't use that one right? Thank you for your help

I also faced this!!!

**Comment by tukaEmad** [comment]
I also faced this!

**Comment by hbarylskyi** [comment]
same problem. 

react-native-notifications: master
react-native: 0.61.5

**Comment by alexichristakis** [comment]
confirmed working on v3 beta

**Comment by lamyuho** [comment]
@alexichristakis Sorry I try the v3 beta, however, the problem still exist on Ios

**Comment by Mukhammadali** [comment]
The same problem, still not working with react-native: 0.61.5

**Comment by Hel5ing** [comment]
Same problem on Android device

**Comment by hbarylskyi** [comment]
I've moved to react-native-firebase. very straightforward, works from the box, while with this library I had many issues with installation, setup and features (like the feature described in this issue, which does not work).
