### ISSUE TITLE
[Question] Local notifications supported on Android?

### ISSUE THREAD

**Issue by lb90** [wix/react-native-notifications#413]
Hi! Just asking, because I see that in `readme.md`:

> _Upcoming: local notifications, background-state Rx queue (iOS equivalent)_

Are they supported?  
Thanks!

**Comment by tkreis** [comment]
https://github.com/wix/react-native-notifications/blob/master/docs/localNotifications.md
Further down in the document it has a link to an example code snippet on how to handle local android notifications.

**Comment by lb90** [comment]
Hi! That's very useful, thanks!
