### ISSUE TITLE
[ANDROID] getInitialNotification returns null with apk install

### ISSUE THREAD

**Issue by fenyoapa** [wix/react-native-notifications#414]
PendingNotifications.getInitialNotification() works fine in dev mode (react-native run-android) but returns null if I install my project's apk (gradlew assembleRelease) and the app is in background/killed and I tap on a notification.
I use NotificationsAndroid.localNotification to create the notification which is triggered by a websocket call (I don't know if it matters).
I don't use Firebase.
There is also a splash screen created by this tutorial: https://medium.com/handlebar-labs/how-to-add-a-splash-screen-to-a-react-native-app-ios-and-android-30a3cec835ae.
I'm googling for many days but can't get it work.
I tried (with others) these answers:
https://github.com/invertase/react-native-firebase/issues/1331
https://github.com/wix/react-native-notifications/issues/326#issuecomment-507371366
https://github.com/crazycodeboy/react-native-splash-screen/issues/289#issuecomment-502406454

react-native: 0.60.4
React.version: 16.8.6

[MainActivity.java.txt](https://github.com/wix/react-native-notifications/files/3882878/MainActivity.java.txt)

[MainApplication.java.txt](https://github.com/wix/react-native-notifications/files/3882881/MainApplication.java.txt)

[SplashActivity.java.txt](https://github.com/wix/react-native-notifications/files/3882879/SplashActivity.java.txt)

[AndroidManifest.xml.txt](https://github.com/wix/react-native-notifications/files/3882880/AndroidManifest.xml.txt)

Have somebody any idea?
Thank you

**Comment by NachosSs** [comment]
Same problem here. It also doesn't work in dev mode=> Initial notification was: N/A
Did you find a solution ?

**Comment by fenyoapa** [comment]
Yes I solved it but I don't remember what was it exactly. I attached relevant files so you can compare it with yours
[myapp.zip](https://github.com/wix/react-native-notifications/files/3994163/myapp.zip)
. Let me know if this solve the problem for you.

**Comment by NachosSs** [comment]
Thanks for sharing but i didn't manage to solve this problem with your sample :(. I use react native firebase v6.  I create an issue #428.
