### ISSUE TITLE
Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback.

### ISSUE THREAD

**Issue by narefyev91** [wix/react-native-notifications#416]
Get this message when receiving voip pushes, I know that it related to iOS 13 and Xcode 11, but I have not the latest version of current library v2.0.3 - Could some one clarify - that this is already fixed?

**Comment by johanschram** [comment]
I had the same problem. 
From my small tests, This is only related to building with Xcode 11 and using pushKit when you’re not suppose to ( not for VOIP). It has nothing to do with the version of this library. For now, if you’re using pushKit for regular notification, you can build with Xcode 10 to avoid this or remplace Voip notification by regular notification. If you use pushKit for VoIP then, just don’t forget to trigger the needed callback.

**Comment by danghung24031992** [comment]
I had the same problem.

**Comment by matannavon** [comment]
I having the same problem

**Comment by sanjaypojo** [comment]
Same problem!

**Comment by HVHMobileDeveloper** [comment]
Did someone solve it?

**Comment by matannavon** [comment]
I've mange to solve this issue by switching the notifications library to [react-native-voip-push-notification](https://github.com/react-native-webrtc/react-native-voip-push-notification) and using also [react-native-callkeep](https://github.com/react-native-webrtc/react-native-callkeep)

**Comment by DaveLomber** [comment]
basically, what we need is to call

```
[RNCallKeep reportNewIncomingCall: uuid
                             handle: handle
                         handleType: @"generic"
                           hasVideo: NO
                localizedCallerName: callerName
                    supportsHolding: YES
                       supportsDTMF: YES
                   supportsGrouping: YES
                 supportsUngrouping: YES
                        fromPushKit: YES
                            payload: extra
              withCompletionHandler: completion];
```
when receive a voip push

like here https://github.com/react-native-webrtc/react-native-callkeep#pushkit

There should be a same way with this lib somehow

**Comment by DaveLomber** [comment]
What I did so far at what seems to work well:

https://github.com/wix/react-native-notifications/issues/473#issuecomment-1181620174
