### ISSUE TITLE
Reply Notification

### ISSUE THREAD

**Issue by djorkaeffalexandre** [wix/react-native-notifications#421]
How can I do reply with a http post when iOS notification is replied by action?
I make a `fetch` but when app is killed and you reply a notification this not works..

**Comment by djorkaeffalexandre** [comment]
Ok, I used a background task on native code of `didReceiveNotificationResponse` to handle request when user reply a notification. thanks.

**Comment by linhCrystal** [comment]
Hi @djorkaeffalexandre, how do you add reply text input?
