### ISSUE TITLE
Migration from react-native-firebase: notification appears blank

### ISSUE THREAD

**Issue by xchwarze** [wix/react-native-notifications#425]
The notification appears blank (no title and no body)
I tried to set android/app/src/main/AndroidManifest.xml like this:
>
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@mipmap/${ic_launcher}" />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@string/default_notification_color" />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="@string/default_notification_channel_id" />

and android/app/src/main/res/values/strings.xml
> 
    <string name="default_notification_color">#f57922</string>
    <string name="default_notification_channel_id" translatable="false">channel_01</string>

This config work ok in react-native-firebase

**Comment by socceroos** [comment]
My only thought is that your `ic_launcher` icon isn't compatible.
I know it seems counter-intuitive since the icon worked before, but have you tried running it through `File->New->Image Asset` in Android Studio? You'll be able to see there if your icon shows as a blank square or if it's rendered correctly.

I recently had to change my icon so that it was compatible (transparent background with outline of icon).

**Comment by xchwarze** [comment]
@socceroos thanks for the tip!

**Comment by kmute90** [comment]
I also have this problem, but it is unrelated to the icon in my opinion, beacuase the icon is the only thing that appears!
I only have this problem with foreground notification, if the app is closed or hidden, then the title and body appears, but if the app is opened, only an empty notification appears :P

**Comment by AlejandroRod** [comment]
I had the same problem and found to some information about Notification and Data message types, link [here](https://firebase.google.com/docs/cloud-messaging/concept-options).

I tried adding the `data` key into de JSON with the `title` and `body` of the notification and then when the app is in the foreground you will also see the info as if it was on the background

Example:
```
{
    ...
    "notification": { 
        "title": "Title example",
        "body": "Content of the notification"
    },
    "data": {
        "title": "Title example",
        "body": "Content of the notification"
    }
}
```

**Comment by Mande3p** [comment]
Facing the same issue, any solution for this?

**Comment by tousdan** [comment]
AljandroRod's solution worked for me, thanks a lot.

**Comment by xchwarze** [comment]
<sarcasm>**this stale bot is very useful**</sarcasm>
