### ISSUE TITLE
Integration with React Native Firebase V6. Initial Notification on Android is undefined

### ISSUE THREAD

**Issue by spaquis** [wix/react-native-notifications#428]
Hi,
I integrate your librairy with react native firebase v6 (cloud messaging).
I receive the notification on Android, but when i click on it, the notification is undefined (PendingNotifications.getInitialNotification()) :
`Initial notification was: N/A`

I made no change on AndroidManifest.xml (Autolinking)
When app is opened, the "notificationOpenListener" work correctly

Could you help me ?
Thanks

**Comment by Aurelienlajoinie** [comment]
Got the same problem and have to add some native workaround to make it work  :s

**Comment by NachosSs** [comment]
Hi @Aurelienlajoinie ,
Could you share your native workaround plz ?

**Comment by Aurelienlajoinie** [comment]
I use something like this in MainActivity.java:

```
    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        setIntent(intent);
        // .....
        handleReactNativeNotifications();
    }
```

 ```
 public void handleReactNativeNotifications() {
        Bundle intent = this.getIntent().getExtras();
        if (intent != null && (intent.getBoolean(LAUNCH_FROM_PUSH_FLAG) == true
            || intent.get("google.message_id") != null)) {
            WritableMap params =  Arguments.fromBundle(intent);
            sendEventToJavaScript(mReactInstanceManager.getCurrentReactContext(), NOTIFICATION_OPENED_EVENT_NAME, params);
        }
    }
```

And the flag is set in my custom PushNotification class:

public class FirebaseCloudMessagingPushNotification extends PushNotification {
    public FirebaseCloudMessagingPushNotification(Context context, Bundle bundle, AppLifecycleFacade appLifecycleFacade, AppLaunchHelper appLaunchHelper, JsIOHelper jsIoHelper) {
        super(context, bundle, appLifecycleFacade, appLaunchHelper, jsIoHelper);
    }

    @Override
    protected Notification.Builder getNotificationBuilder(PendingIntent intent) {
        final Resources resources = mContext.getResources();
        Bundle intentBundle =  mNotificationProps.asBundle();
        RemoteMessage remoteMessage = new RemoteMessage(intentBundle);
        final Notification.Builder builder = super.getNotificationBuilder(intent);

        // Set Notification content
        builder.setContentTitle(remoteMessage.getNotification().getTitle());
        builder.setContentText(remoteMessage.getNotification().getBody());

        Intent notificationIntent = new Intent(mContext, MainActivity.class);
        notificationIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        notificationIntent.putExtras(intentBundle);
        notificationIntent.putExtra(LAUNCH_FROM_PUSH_FLAG, true);
        PendingIntent pendingIntent = PendingIntent.getActivity(mContext, 0, notificationIntent,
                PendingIntent.FLAG_ONE_SHOT);
        builder.setContentIntent(pendingIntent);

        return builder;
    }
}

**Comment by NachosSs** [comment]
Thanks for sharing this @Aurelienlajoinie . I finally decided to downgrade react native firebase to v5 but I will try your solution on a sample project :)

**Comment by efstathiosntonas** [comment]
@Aurelienlajoinie can you please share the whole MainActivity.java?

**Comment by Aurelienlajoinie** [comment]
@efstathiosntonas my workaround doesn't work anymore with version 3.1.1 :s i have to find another solution.

**Comment by efstathiosntonas** [comment]
Thanks, if you manage to find a solution it would be great to post it here :)

**Comment by nates-dennis** [comment]
have the same issue selecting a notification from cold start launches the app but gives a null initial notification

**Comment by LRNZ09** [comment]
I also have this issue with version `3.1.2`

**Comment by stevenyap** [comment]
I also have this issue on version `3.1.2`

**Comment by abhaynpai** [comment]
I also have this issue on version `3.1.2`

**Comment by abhaynpai** [comment]
@efstathiosntonas - Were you able to come up with a solution to this issue?
