### ISSUE TITLE
[v3] calling getDeliveredNotifications throws error

### ISSUE THREAD

**Issue by alexichristakis** [wix/react-native-notifications#429]
When I try to get the delivered notifications from the notification tray on iOS I receive the bridge error:

```
RNBridgeModule.getDeliveredNotifications` was called with 0 arguments but expects 1 arguments. If you haven't changed this method yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.
reactConsoleErrorHandler @ ExceptionsManager.js:126
console.error @ YellowBox.js:63
logToConsole @ RCTLog.js:47
logIfNoNativeHook @ RCTLog.js:30
__callFunction @ MessageQueue.js:436
(anonymous) @ MessageQueue.js:111
__guard @ MessageQueue.js:384
callFunctionReturnFlushedQueue @ MessageQueue.js:110
(anonymous) @ `RNDebuggerWorker.js:2
```

In JS the function is called as:
```
const notifications = Notifications.ios.getDeliveredNotifications();
```

`notifications` is returned as null. It seems the callback to pass the notification objects back across the bridge isn't supplied properly?

**Comment by ragamufin** [comment]
I am getting the same problem when calling `getBadgeCount`

`RNBridgeModule.getBadgeCount was called with 0 arguments but expects 1 arguments. If you haven't changed this method yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.`

**Comment by songsterq** [comment]
@ragamufin I sent #468 to fix getBadgeCount.

**Comment by bakerac4** [comment]
FWIW, Im not sure this should be closed. Im on `3.1.1` and still seeing the error described above. I am unable to get delivered notifications

**Comment by szhigunov** [comment]
@yogevbd This issue isn't solved. #468 refers to a problem with `getBadgeCount`.
