### ISSUE TITLE
installation - PushNotificationIOS needed?

### ISSUE THREAD

**Issue by ranjeev75** [wix/react-native-notifications#43]
Do we need to install `PushNotificationIOS` if we're using the `react-native-notifications` library. I'm presuming we don't need to because it's not mentioned in the installation guide?

**Comment by kyryloz** [comment]
Hi. I've faced with the same question. You've closed this issue, did you find the answer?

**Comment by arcollector** [comment]
all methods are inside `import NotificationsIOS from 'react-native-notifications';`
