### ISSUE TITLE
Does the module work with react-native 61.5

### ISSUE THREAD

**Issue by movie4** [wix/react-native-notifications#430]
Hello!
Does the module work with react-native 61.5?

Use react-native-notifications 2.1.7

**Comment by IacoCesar** [comment]
Work?

**Comment by movie4** [comment]
no... user other packages

**Comment by fgreinus** [comment]
You can fix that (for now) by disabling auto-linking for react-native-notifications in react-native.config.js like this: 

<img width="510" alt="Screenshot 2020-01-10 at 22 16 07" src="https://user-images.githubusercontent.com/1236785/72186990-ce0ab100-33f6-11ea-8f6b-fbc56f57823d.png">

When you add this (for me with 0.61.5) you can just link it manually again.

**Comment by movie4** [comment]
> fgreinus 

this works in android, but i could not work it on ios

**Comment by fgreinus** [comment]
iOS worked for me out of the box. You could try adding iOS to the config,
just like Android.

Arkadiy Zamaraev <notifications@github.com> schrieb am Sa., 11. Jan. 2020,
09:31:

**Comment by Aurelienlajoinie** [comment]
It works for me in v3.0.0-beta.4 :) (firebase v5)

**Comment by Bilal-Abdeen** [comment]
Try the installation instructions, which are at issue #396 or the PR #434

**Comment by marcin-zbijowski** [comment]
You can use autolinking with changes in react-native.config.js:

```
module.exports = {
    // ...
    dependencies: {
        'react-native-notifications': {
            platforms: {
                android: {
                    packageInstance: 'new RNNotificationsPackage(this.getApplication())'
                }
            }
        }
    }
    // ...
};
```
