### ISSUE TITLE
🔥  [V3][ANDROID] TypeError: Cannot read property 'identifier' of undefined

### ISSUE THREAD

**Issue by Aurelienlajoinie** [wix/react-native-notifications#435]
Hello, 
i'm using v3.0.0-beta.4 with a RN 0.61.5 application and i face a problem on notification open callback. The library is throwing the error:  "TypeError: Cannot read property 'identifier' of undefined".
I try to find the problem and found that in this piece of TS code:

```
  public registerRemoteNotificationOpened(callback: (notification: Notification, completion: () => void, actionResponse?: NotificationActionResponse) => void): EmitterSubscription {
    return this.emitter.addListener('notificationOpened', (response, completion) => {
      const action = response.action ? new NotificationActionResponse(response.action) : undefined
      callback(this.notificationFactory.fromPayload(response.notification), completion, action);
    });
  }
```

```response``` contain the notification object but not a ```notification``` subobject so ```response.notification``` is undefined which is used to create the NotificationAndroid object

```
  constructor(payload: object) {
    this.payload = payload;
    this.identifier = this.payload.identifier; // Throw error here
  }
```

Thanks in advance for your help !

**Comment by ErangaD** [comment]
@Aurelienlajoinie Did you find a fix? I am having the same issue.

**Comment by Aurelienlajoinie** [comment]
@ErangaD i've no more the problem upgrading to v3 but i've also downgrade react-native-firebase to v5 so i don't know where exactly the problem was :s
