### ISSUE TITLE
Cannot receive VoiP push notifications on iOS 13

### ISSUE THREAD

**Issue by matannavon** [wix/react-native-notifications#438]
After updating my device to iOS 13 i get the following error when receiving voip notification: 

` Apps receving VoIP pushes must post an incoming call (via CallKit or IncomingCallNotifications) in the same run loop as   pushRegistry:didReceiveIncomingPushWithPayload:forType:[withCompletionHandler:] without delay.
 *** Assertion failure in -[PKPushRegistry _terminateAppIfThereAreUnhandledVoIPPushes], /BuildRoot/Library/Caches/com.apple.xbs/Sources/PushKit/PushKit-37/PKPushRegistry.m:343
 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback.'`

How can i solve this one?

**Comment by jordanyaker** [comment]
I'm seeing the same thing.

**Comment by matannavon** [comment]
Im still having issues accepting VoIP calls when app is in the background.
I've came across this presentation that mentions the new way to handle VoIP push calls on iOS 13 including a code example:
https://developer.apple.com/videos/play/wwdc2019/707/?time=557
But i'm having trouble integrating it to the library.

Any help?

**Comment by oscar-gallog** [comment]
Any idea how to fix this? I'm having the same issue

**Comment by sanjaypojo** [comment]
Any fixes for this?

**Comment by kmiterror** [comment]
This is a iOS 13 limitation for Voip notifications. You are suppose to use voip notifications to notify about ehm incoming voip call, nothing else. 
Apple wants your app to show  CallKit UI right after receiving voip notification. If it won't happen app will crash. 
Showing  CallKit UI means that a default iOS callscreen will cover your app.
Something like this:
![image](https://user-images.githubusercontent.com/4394164/76678130-b2c64880-65d5-11ea-9dc0-9d9978802e49.png)

I'm not into react-native but from what I found library below should make your life easier:
https://www.npmjs.com/package/react-native-callkit

Before implementing this, keep in mind that if your app uses voip notifications for something else than voip calls it will be rejected in the app review process.
