### ISSUE TITLE
local notification doesn't show up

### ISSUE THREAD

**Issue by nicolasburtey** [wix/react-native-notifications#441]
I tried following up the instructions from this page: https://wix.github.io/react-native-notifications/docs/notifications-events, but there is no notification from iOS.

I'm using `alert: true` as this is mentioned in the doc,

Maybe the documentation might not be up to date for v3?

**Comment by nicolasburtey** [comment]
nevermind, I didn't know we had to ask for permission before for local notifications.

**Comment by bhaskardabhi** [comment]
@nicolasburtey I am having same issue Can you let me know what is process to ask for permission? I have added push notifications as Push Notifications in Capabilities still its not showing notification
