### ISSUE TITLE
[v2] When app is in foreground notification is blank

### ISSUE THREAD

**Issue by Mande3p** [wix/react-native-notifications#442]
You can not see notification's title or description:
<img width="421" alt="Screen Shot 2020-01-16 at 10 14 17 AM" src="https://user-images.githubusercontent.com/4300504/72494637-86e34c80-384a-11ea-9743-8b714078b957.png">

Works fine when app is in background or killed:
<img width="422" alt="Screen Shot 2020-01-16 at 10 14 57 AM" src="https://user-images.githubusercontent.com/4300504/72494642-8945a680-384a-11ea-8567-844370622e4d.png">

This is the data i receive:
<img width="428" alt="Screen Shot 2020-01-16 at 10 28 18 AM" src="https://user-images.githubusercontent.com/4300504/72494796-fe18e080-384a-11ea-949c-90a1d1303820.png">

Tested on android version 7.1 and 9.0

**Comment by IljaDaderko** [comment]
Same behaviour observed in v3.1.1

**Comment by anthowm** [comment]
I got this bug too in v3.1.1. Is there something we can do ?

**Comment by kehers** [comment]
This is still an issue in v3.1.2

**Comment by Priceincoding** [comment]
same bug

**Comment by JimmySorza** [comment]
> This is still an issue in v3.1.2

related https://github.com/wix/react-native-notifications/issues/456

**Comment by JimmySorza** [comment]
maybe this help: 
https://github.com/wix/react-native-notifications/pull/496
