### ISSUE TITLE
[V3] Incorrect iOS Documentation

### ISSUE THREAD

**Issue by ManAnRuck** [wix/react-native-notifications#458]
currently the installation documentation for iOS is confusing & does not work

https://wix.github.io/react-native-notifications/docs/getting-started
here is just missing a line for the `AppDelegate.m`
here I need additional add `#import "RNNotifications.h"`

and

calling the constructor https://wix.github.io/react-native-notifications/docs/getting-started#register-for-notification-events needs also to call `super(props)`

https://wix.github.io/react-native-notifications/docs/installation-ios
here in step one I should link a file which has another path 
`+ pod 'ReactNativeNotifications', :podspec => '../node_modules/react-native-notifications/ReactNativeNotifications.podspec'

**Comment by yogevbd** [comment]
Thanks for letting us know.
The getting started guide created last week and it assumes you don't need those other manual iOS and Android installation parts because RN60+ supports auto linking .
Will update the docs to be more clear.

**Comment by ShaneMatthias** [comment]
Is the documentation up to date yet?

**Comment by robertqin86** [comment]
This is the correct pod spec. The one that yogevbd provided was wrong. 

`pod 'react-native-notifications', :podspec => '../node_modules/react-native-notifications/react-native-notifications.podspec'`
