### ISSUE TITLE
Android Local Notification sound

### ISSUE THREAD

**Issue by JosephMulder** [wix/react-native-notifications#460]
I'm trying to get Android's Local notification to have no sound when run. The IOS documentation has something to mute it, but Android does not. I'm using the [wiki's custom notification](https://github.com/wix/react-native-notifications/wiki/Android:-Layout-Customization), but that is using Notification.Builder which sound control doesn't work for anything over Oreo on android.

**Comment by victorighalo** [comment]
Had same issue running my Android emulator. All i did to get the sound restored was to shutdown the emulator and start it up again.
