### ISSUE TITLE
Android - Check for Permissions 

### ISSUE THREAD

**Issue by Bilal-Abdeen** [wix/react-native-notifications#464]
On iOS, the following command can be used to check if the user has granted the app to receive notifications. 

`Notifications.ios.checkPermissions();`

Is there a similar command for Android? 

In version 2, there was the command `NotificationsAndroid.isRegisteredForRemoteNotifications();`

**Comment by Naavukarasan** [comment]
In Android, You don't need to check for push notification permission.
See here,
https://stackoverflow.com/questions/37294076/push-notifications-gcm-permission-at-runtime
