### ISSUE TITLE
_reactNativeNotifications.Notifications.android.refreshToken is not a function

### ISSUE THREAD

**Issue by Bilal-Abdeen** [wix/react-native-notifications#465]
On the documentation (https://wix.github.io/react-native-notifications/docs/android-api), it says: 
the following command can be used to "**Request a new token for sending push notifications.**"
`Notifications.android.refreshToken();`

Q1. when I tried to use it, I got the following error message. 
`TypeError: _reactNativeNotifications.Notifications.android.refreshToken is not a function`

My Code: 
```javascript
import { Notifications} from 'react-native-notifications';
// .....

// Step 1: Register this app to receive notifications -> Works fine 
Notifications.registerRemoteNotifications(); 

// Step 2: Get the device token -> Works fine 
Notifications.events().registerRemoteNotificationsRegistered( (event) => { 
	console.log("deviceToken:", event.deviceToken);
});

// Step 3: Get device token Updates -> TypeError: _reactNativeNotifications.Notifications.android.refreshToken is not a function
Notifications.android.refreshToken(); 
```

After some trial and error, the error disappeared when I changed the code (above) to the following. However, I am not sure if this is actually the right command! 
`Notifications.android.commands.refreshToken();`

Q2. Should this command be used to request **a "NEW" token** (as the documentation says), or to request receiving any **"UPDATES" on the token?**

Q3. How does this command work? How is the new token received? Is the following code correct? Adding an example to the documentation would be highly appreciated! 
`Notifications.android.commands.refreshToken( (newToken) => console.log("newToken:", newToken) );`

Q4. (Bonus Question) In order to check receiving an updaed token, **how can I force (for testing purposes) changing the device's token (on an emulator/simulator or a physical iOS/Android device)?**

**Comment by yogevbd** [comment]
Hey, first of all, thanks for your contributions! it helps a lot.
Second, you are right, `Notifications.android.refreshToken()` has been replaced with: `Notifications.registerRemoteNotifications()` . 
The main reason for those lately changes is that we wanted to recreate this library with simple and similar API for Android and iOS.

Q2:  `registerRemoteNotifications` will request any updated token from the system. you should call it on each app launch and notify your server accordingly.

Q3. Just use [registerRemoteNotifications](https://wix.github.io/react-native-notifications/docs/general-api#registerremotenotifications) and listen to [remoteNotificationRegistered](https://wix.github.io/react-native-notifications/docs/general-events#registerremotenotificationsregistered) event.

Q4. Here at Wix we mock `react-native-notifications` using jest. You can mock `registerRemoteNotificationRegistered` event.

**Comment by rnnyrk** [comment]
When I use `Notifications.registerRemoteNotifications();` on Android the error `null in not an object (evaluating 'this.nativeCommandsModule.refreshToken')`. Seems related. How to fix this? Runing latests versions

**Comment by JaioSkura** [comment]
> When I use `Notifications.registerRemoteNotifications();` on Android the error `null in not an object (evaluating 'this.nativeCommandsModule.refreshToken')`. Seems related. How to fix this? Runing latests versions

Same here

**Comment by ShaneMatthias** [comment]
> When I use `Notifications.registerRemoteNotifications();` on Android the error `null in not an object (evaluating 'this.nativeCommandsModule.refreshToken')`. Seems related. How to fix this? Runing latests versions

Same! Please help!

**Comment by puremana** [comment]
Are you running this on a simulator? You can't do push notifications on simulators. You can use something like [react-native-device-info](https://github.com/react-native-community/react-native-device-info) to check.

**Comment by humbkr** [comment]
> Q4. Here at Wix we mock react-native-notifications using jest. You can mock registerRemoteNotificationRegistered event.

Could you give a configuration example? I struggle to mock the lib.

**Comment by porfidev** [comment]
> > When I use `Notifications.registerRemoteNotifications();` on Android the error `null in not an object (evaluating 'this.nativeCommandsModule.refreshToken')`. Seems related. How to fix this? Runing latests versions
> 
> Same here. Any fix?

It is happen to me, I am on Android  9 - Xiaomi A1M1 instead a simulator (which file do you need ?)

**Comment by princefishthrower** [comment]
For anyone who may find this, this was a good starting point for what we were using in our `jest.setup.js` to mock what we were using in our app from `react-native-notifications`:

```js
jest.mock('react-native-notifications', () => {
  return {
    Notifications: {
      getInitialNotification: jest.fn(() => Promise.resolve()),
      registerRemoteNotifications: jest.fn(),
      events: () => {
        return {
          registerRemoteNotificationsRegistered: jest.fn(),
          registerRemoteNotificationsRegistrationFailed: jest.fn(),
          registerNotificationReceivedForeground: jest.fn(),
          registerNotificationReceivedBackground: jest.fn(),
          registerNotificationOpened: jest.fn(),
        };
      },
    },
  };
});
```

Hope it helps.
