### ISSUE TITLE
[V3] No way to unregister callbacks.

### ISSUE THREAD

**Issue by jcarioti** [wix/react-native-notifications#474]
Currently I see no way to unregister callbacks. This causes hot reloading to register more and more Notification event handlers during debugging.

It looks like the NativeEventsReceiver handles all the event listeners, but doesn't expose anything for removing these event listeners. Is there a way to unregister these callbacks or does NativeEventsReceiver need to be modified to make this happen?

**Comment by simonasdev** [comment]
`EventsRegistry` functions return react-native's `EmitterSubscription`, which has a function `remove`, to remove the event listener

**Comment by rnnyrk** [comment]
@simonasdev Can you supply an example on how to implement this? Facing the same issue unfortunately

**Comment by simonasdev** [comment]
Doesn't this work for you?
```javascript
componentDidMount() {
    Notifications.registerRemoteNotifications()

    this.notificationReceivedForeground = Notifications.events().registerNotificationReceivedForeground(() => {
      //...
    })
}

componentWillUnmount() {
    this.notificationReceivedForeground.remove()
}
```

**Comment by zabojad** [comment]
This will not unregister the device from receiving notifications when the app is not running, am I right? I so, how to do that?
