### ISSUE TITLE
"registerNotificationReceivedForeground and registerNotificationReceivedBackground" are not fired while receiving remote push notification 

### ISSUE THREAD

**Issue by rathish-ganesh** [wix/react-native-notifications#475]

**Comment by rynatk** [comment]
I have this same exact issue, only with iOS. I have seen a number of people reporting this same exact thing through the open github issues.

I've literally spent days on this to no avail.

**Comment by Mavenic** [comment]
Any solution yet, facing the same issue on android

**Comment by Mephala** [comment]
Same issue.

**Comment by fedu44** [comment]
Same
