### ISSUE TITLE
[Feature Request] How to display iOS push notifications in the foreground

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-notifications#476]
Hi @yogevbd,

While this isn't the responsibility of the library, I am curious how we could get push notifications to show in the foreground. This was a somewhat popular request in V1 of this library and it's blocking our upgrade from V1 -> V3.

**Comment by chakrihacker** [comment]
Check the documentation on subscribing notifications

**Comment by simonasdev** [comment]
see 'Example' in https://wix.github.io/react-native-notifications/docs/notifications-events

**Comment by ItsNoHax** [comment]
Maybe I wasn't clear enough initially.

What I need to achieve is that push notifications show while the app is opened in the foreground. This was initially achieved in AppDelegate.m using:
```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler
{
  [RNNotifications didReceiveRemoteNotification: formatUNNotification(notification)];
  
  completionHandler(UNNotificationPresentationOptionAlert);
}
```

and using patch-package to expose a function in RNNotifications.h:

```diff
++ (void)didNotificationOpen:(NSDictionary *)notification;
```
