### ISSUE TITLE
[IOS] App not coming to foreground when clicked on one of the action buttons.

### ISSUE THREAD

**Issue by tarun29061990** [wix/react-native-notifications#477]
Notification coming fine but when I click on one of the action button app not coming to foreground but code is getting executed in onNotificationOpened callback. Please help ?

My Code:-

```
        Notifications.registerRemoteNotifications();

        let acceptAction = new NotificationAction({
            activationMode: "foreground",
            title: "Accept",
            identifier: "Accept",
            destructive: true
        });
          
        let rejectAction = new NotificationAction({
            activationMode: "background",
            title: "Reject",
            identifier: "Reject"
        });

        let notificationActionCategories = new NotificationCategory(
            identifier= "FLOATING_LEAD",
            actions= [acceptAction, rejectAction]
        );

        Notifications.setCategories([notificationActionCategories]);

        Notifications.events().registerNotificationReceivedForeground((notification: Notification, completion) => {
            console.log(`Notification received in foreground: ${notification.title} : ${notification.body}`);
            completion({alert: false, sound: false, badge: false});
        });
        Notifications.events().registerNotificationReceivedBackground((notification: Notification, completion) => {
            console.log(`Notification received in foreground: ${notification.title} : ${notification.body}`);
            completion({alert: false, sound: false, badge: false});
        });
      
        Notifications.events().registerNotificationOpened((notification: Notification, completion) => {
            console.log(`Notification opened: ${notification.payload}`);
            completion();
        });
```

**Comment by LuisRodriguezLD** [comment]
I know this isn't the place, but how did you manage to get the actions to show up on the notification? I've been struggling for a while now

**Comment by tarun29061990** [comment]
@LuisRodriguezLD  Hi very sorry for the late reply .... 
Just define the categories as I have defined above in the code. Then when the notification arrives in IOS you have to long press the notification to get the notification action buttons.

**Comment by spamws** [comment]
Hi
You should changes that code with this :

```
let acceptAction = new NotificationAction("Accept", "foreground","Accept",false);
let rejectAction = new NotificationAction("Reject", "background", "reject");
let notificationActionCategories = new NotificationCategory("EXAMPLE_CATEGOR",[acceptAction, rejectAction]);
Notifications.setCategories([notificationActionCategories]);
```

But after this work, i can`t get actionIdentifire

**Comment by nvnk3** [comment]
Hello, how do you capture response from NotifcationAction button? how to add a callback function?

**Comment by nvnk3** [comment]
how can we capture  this NotificationAction on onNotificationOpened() when app is dead.

**Comment by nvnk3** [comment]
> Hi
> You should changes that code with this :
> 
> ```
> let acceptAction = new NotificationAction("Accept", "foreground","Accept",false);
> let rejectAction = new NotificationAction("Reject", "background", "reject");
> let notificationActionCategories = new NotificationCategory("EXAMPLE_CATEGOR",[acceptAction, rejectAction]);
> Notifications.setCategories([notificationActionCategories]);
> ```
> 
> But after this work, you can`t get action button that clicked.
> I think this is for older version and this version not support interactive notification support!

**Comment by nvnk3** [comment]
Hi, how can we capture this NotificationAction on onNotificationOpened() when app is dead???. It works fine when app is foreground and background.

**Comment by dlavrantonis** [comment]
So does the current version. (4.3.1) support actionable notifications? I see nothing mentioned in the documentation.
