### ISSUE TITLE
When the app is on the background, the "registerNotificationReceivedBackground" event is not fired

### ISSUE THREAD

**Issue by Moreno97** [wix/react-native-notifications#478]
Using the last version, `3.1.1`, when the app is on the background, the `registerNotificationReceivedBackground` event is not fired.

The documentation says it's supported but it's not working (https://wix.github.io/react-native-notifications/docs/general-events#registernotificationreceivedbackground)

```
Notifications.events().registerNotificationReceivedBackground(
  (
    notification: Notification,
    completion: (response: NotificationCompletion) => void,
  ) => {
    console.log('Notification Received - Background', notification.payload);

    // Calling completion on iOS with `alert: true` will present the native iOS inApp notification.
    completion({
      alert: false,
      sound: false,
      badge: false,
    });
  },
);
```

Besides this, the `registerNotificationReceivedForeground` event is working as expected.

**Comment by mikaarefyev** [comment]
@Moreno97 does registerNotificationReceivedBackground works when app is killed?

**Comment by Moreno97** [comment]
Hello @mikaarefyev, it's not working when the app is killed by the user. No events fired (though the notification is received correctly).

**Comment by mikaarefyev** [comment]
> Hello @mikaarefyev, it's not working when the app is killed by the user. No events fired (though the notification is received correctly).

I checked in native code and seems guys didn't implement this method

**Comment by nates-dennis** [comment]
For background push notifications (not cold start) this worked for me [445](https://github.com/wix/react-native-notifications/issues/445)

**Comment by javierbustamante** [comment]
as @Moreno97 registerNotificationReceivedBackground isn't working as expected...

**Comment by beulahpt** [comment]
Same issue. Need solution.

**Comment by pg07codes** [comment]
@Moreno97 any updates ? this still seems to not work as intended

**Comment by biggydbs** [comment]
any updates ?

**Comment by sanatChoubey** [comment]
Hey any update ?

**Comment by BabakYaghoobi** [comment]
any update ?

**Comment by yannickpschroeder** [comment]
any updates ?

**Comment by arnabadhikari2009** [comment]
the same issue When the app is killed after clicking the notification from the tray it not triggered Notifications.events().registerNotificationOpened.. is there any way to trigger this event to route specific screens from notification.

**Comment by mrjaxi** [comment]
Are there any changes? on iOS, the register Notification Received Background doesn't work, I can't get data from the push when the app is in the background

**Comment by maimai886** [comment]
any updates ?

**Comment by van8tka** [comment]
any updates :-D????
