### ISSUE TITLE
Android unable to sync gradle

### ISSUE THREAD

**Issue by kohchenggee** [wix/react-native-notifications#479]
I tried to install react-native-notifications v3.1.1 and everytime i tried to sync gradle, I receive:

> ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :reactnativenotifications.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :reactnativenotifications.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :reactnativenotifications.
> Show Details
> Affected Modules: app

I have tried methods like renaming reactnativenotifications to react-native-notifications but issue persist. When I tried to clean the project and rebuild, I receive this msg:

> Cannot choose between the following variants of project :reactnativenotifications:
>   - reactNative59DebugApiElements
>   - reactNative60DebugApiElements
> All of them match the consumer attributes:
>   - Variant 'reactNative59DebugApiElements' capability SRXProperty:reactnativenotifications:unspecified:
>       - Unmatched attributes:
>           - Required RNN.reactNativeVersion 'reactNative60' but no value provided.
>           - Found RNNotifications.reactNativeVersion 'reactNative59' but wasn't required.
>           - Found com.android.build.api.attributes.VariantAttr 'reactNative59Debug' but wasn't required.
>       - Compatible attributes:
>           - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
>           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
>           - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
>   - Variant 'reactNative60DebugApiElements' capability SRXProperty:reactnativenotifications:unspecified:
>       - Unmatched attributes:
>           - Required RNN.reactNativeVersion 'reactNative60' but no value provided.
>           - Found RNNotifications.reactNativeVersion 'reactNative60' but wasn't required.
>           - Found com.android.build.api.attributes.VariantAttr 'reactNative60Debug' but wasn't required.
>       - Compatible attributes:
>           - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
>           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
>           - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
I have also tried to delete the .idea folder and resync but issue persists
Any Idea how can I solve this issue?  Thank you
react-native version: 0.61.5, react version: 16.9.0

**Comment by flexbox** [comment]
For people who lands here and needs (like me 😅) to create a release today I found a quick fix by downgrading https://github.com/wix/react-native-notifications/issues/391#issuecomment-586321501
