### ISSUE TITLE
App crash when local notification is shown when app is in foreground on iOS

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-notifications#480]
I am trying to migrate from `PushNotificationIOS` to this package because it uses the new `UserNotifications` framework from iOS. I followed the steps in the documentation and added a sample notification to my app. When I try to show the sample notification and the app is in foreground, the app crashes with message `TypeError: undefined is not an object (evaluating 'this.alert.title')`. If I set a `fireDate` and keep the app in background when the notification arrives, then I see the notification and app doesn't crash. I used the below code to post the local notification

```
      let someLocalNotification = Notifications.postLocalNotification({
        fireDate: Date.now() + 5000,
        body: 'Local notificiation!',
        title: 'Local Notification Title',
        sound: 'chime.aiff',
        userInfo: {}
      })
```

**Comment by tegozen** [comment]
same problem

**Comment by calderaro** [comment]
i have the same problem when trying to use postLocalNotification

`
Notifications.postLocalNotification({
          body: 'Local notificiation!',
          title: 'Local Notification Title',
          sound: 'default',
          silent: false
        });
`

i get TypeError: Cannot read property 'title' of undefined

**Comment by RyanSadowski** [comment]
I'm getting this error in the example app

**Comment by tegozen** [comment]
all problems solved in https://github.com/zo0r/react-native-push-notification work on android and ios. Enable foreground https://github.com/react-native-community/react-native-push-notification-ios/issues/63

**Comment by tyleralves** [comment]
Just created a pull request to fix this. Since it seems like PRs are not being reviewed at this time, here is a patch that you can apply using `patch-package`:

[react-native-notifications+3.1.2.patch.txt](https://github.com/wix/react-native-notifications/files/4351807/react-native-notifications%2B3.1.2.patch.txt)

**Comment by el-lsan** [comment]
Facing this issue!
would be great to have https://github.com/wix/react-native-notifications/pull/537 merged !

**Comment by jkol36** [comment]
i'm getting the same error!

**Comment by JulioOrellana** [comment]
My app keep crashing when receiving notification on foreground!

**Comment by BELHAJDEV** [comment]
Check if you registered for foreground notifications multiple times
