### ISSUE TITLE
Unable to cancel a notification on iOS

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-notifications#481]
I use below code to show a local notification

```
      let someLocalNotification = Notifications.postLocalNotification({
        fireDate: Date.now() + 5000,
        body: 'Local notificiation!',
        title: 'Local Notification Title',
        sound: 'chime.aiff',
        userInfo: {}
      })
```
When I print `someLocalNotification`, it is `undefined`. When I use `Notifications.cancelLocalNotification(someLocalNotification)` to cancel the notification, the app crashes with an error `Exception '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]' was thrown while invoking cancelLocalNotification on target RNBridgeModule with params (
    "<null>"
)`

Also, in the documentation, I see that I can also pass my own notification ID while scheduling the notification and then later use that to cancel the notification also. But I found that `postLocalNotification` expects a `Number` as the ID and the `cancelLocalNotification` expected a `String`. So, I wasn't sure how to provide my own ID that I can later use to cancel the notification if needed.

**Comment by tststs** [comment]
same issue on android. `postLocalNotification` always returns `undefined`.

**Comment by LuisRodriguezLD** [comment]
You can use your own ID, use numbers when creating but strings when deleted, at least that worked for me

**Comment by varungupta85** [comment]
@LuisRodriguezLD Is the parameter passed to `cancelLocalNotification` string representation of the number passed as ID to `postLocalNotification`?

**Comment by LuisRodriguezLD** [comment]
@varungupta85 yes. that is correct

**Comment by JaioSkura** [comment]
Hi!
That works yeah! thanks. But what is the point of creating notifications with a Number and cancelling those with a string?
