### ISSUE TITLE
When the app is closed notification is not retrieved by the event

### ISSUE THREAD

**Issue by vignalbrice** [wix/react-native-notifications#482]
In React Native 0.61.5 
and react-native-notificationsv3.1.1

We try all events of the documentation, but we can't retrieved notification object when the app is closed,
We used registerNotificationOpened() function to get all new notifications on background app.
But when the app is closed, Which event must we use  ?
We also try to used getInitialNotification() function but it returns "undefined" when the app is closed/background/foreground ?

**Comment by xcxooxl** [comment]
android doesnt have getInitialNotificartion, But you can fix this problem in android
by natively extending the PushNotification class and overriding the digestNotification method

```
    @Override
    protected void digestNotification(){
        super.digestNotification();
        final ReactInstanceManager mReactInstanceManager = ((ReactApplication) mContext.getApplicationContext()).getReactNativeHost().getReactInstanceManager();
        Yad2PushNotification self = this;
        final ReactInstanceManager.ReactInstanceEventListener listener = new ReactInstanceManager.ReactInstanceEventListener() {
            public void onReactContextInitialized(ReactContext validContext) {
                mReactInstanceManager.removeReactInstanceEventListener(this);
                self.notifyOpenedToJS();
            }
        };
        mReactInstanceManager.addReactInstanceEventListener(listener);
    }
```
This will wait untill react has loaded and then pass the event normally, I'm not a native developer lol so this is what I came up with, @yogevbd maybe you should look into this.

**Comment by rnnyrk** [comment]
Experiencing the same isse. @xcxooxl Can you eleborate on how / where to implement this native code?

**Comment by rnnyrk** [comment]
@xcxooxl I'd try to add it in my `MainApplication.java` where `RNNotificationsPackage` is included as well. Unfortunately my app crashed afterwards. Any way you can share an example?
