### ISSUE TITLE
[Android] unable to sync gradle 

### ISSUE THREAD

**Issue by ViTenorio** [wix/react-native-notifications#485]
react-native 0.59.8,
react-native-notifications 3.1.1,

> Task :react-native-notifications:compileReactNative59DebugJavaWithJavac FAILED

error: cannot find symbol @NonNull
```java
    public static NotificationManagerCompat from(@NonNull Context context)
```                                                                                       

  symbol:   class NonNull
  location: class NotificationManagerCompatFacade

at react-native-notifications/lib/android/app/src/reactNative59/NotificationManagerCompatFacade.java

I saw that in the master the problem has already been fixed, but I think the package has not been published

**Comment by GazzaHazza** [comment]
Im also getting this, ive just updated to `3.1.2` but no luck. Any suggestions?

**Comment by ViTenorio** [comment]
> Im also getting this, ive just updated to `3.1.2` but no luck. Any suggestions?

I updated to 3.1.2 and worked, maybe removing and adding again to node modules?

**Comment by GazzaHazza** [comment]
Giving it ago now! Thanks.
