### ISSUE TITLE
[Android] Notification Channel Support?

### ISSUE THREAD

**Issue by fosteruk** [wix/react-native-notifications#488]
Does react-native-notifications have support for notification channels? 

It doesn't seem to be working for me. 

I configured the notification channels in my app (https://developer.android.com/training/notify-user/channels.html) and when I send a notification, either from FCM console, or from firebase-admin NodeJS the notification is received by a notification channel named "Channel Name", rather than the one specified when sending the notification.

Debugging, I can the notification data as received by the app  (Notifications.events().registerNotificationReceivedForeground()) contains the correct notification channel id ("gcm.notification.android_channel_id").

Is there something I need to configure to get react-native-notifications to receive notification via the correct channel or is it simply not supported?

**Comment by manojeeva** [comment]
Me too looking for this.
For me, it simply shows "Channel Name"  in the android notification settings.
I'm trying to use the local notification.
Get data from firebase and show it as a local notification.

**Comment by JaioSkura** [comment]
Any fix for this?

**Comment by alexbuicescu** [comment]
I created a PR addressing this issue, you can find it here #535
