### ISSUE TITLE
Not receiving firebase console notification on IOS

### ISSUE THREAD

**Issue by pani7** [wix/react-native-notifications#489]
Hi, i can get my RN app on IOS platform to work properly. I am getting fcm token inside Notifications.events.registerRemoteNotificationsRegistered, but when i am testing push notifications from firebase console, nothing is happening, the device is not getting push.

I installed react-native-notifications properly, on android i am receiving push from console, in componentDidMount i am calling:
` await this.registerForPushNotifications();
    await this.registerNotificationEvents();`

registerForPushNotifications:

`registerForPushNotifications = async () => {
    const doesFcmTokenAlreadyExist = await AsyncStorage.getItem('fcmToken');

    if (!doesFcmTokenAlreadyExist) {
      await Notifications.registerRemoteNotifications();
      const { registerDeviceForPushNotifications, isDeviceRegisteredForPush } = this.props;
      //request permissions and request fcm token

      Notifications.events().registerRemoteNotificationsRegistered(event => { 
        if (!isDeviceRegisteredForPush) {
          //here i am registering for push notifications with my backend
          this.setState({ fcmToken: event.deviceToken }, () => {
            registerDeviceForPushNotifications(event.deviceToken, isAndroid ? 2 : 1);
          });
        }
      });
    }
  };`

registerNotificationEvents:

`registerNotificationEvents = () => {
    Notifications.events().registerNotificationReceivedForeground((notification, completion) => {
      console.log('received in foreground', notification.payload);
      completion({ alert: true, sound: true, badge: false });
    });

    Notifications.events().registerNotificationOpened((notification, completion) => {
      console.log('opened:', notification, completion);
      this.openNotificationsScreen();
      completion();
    });
    Notifications.events().registerNotificationReceivedBackground((notification, completion) => {
      console.log('Notification Received - Background', notification.payload);
      // Calling completion on iOS with `alert: true` will present the native iOS inApp notification.
      this.openNotificationsScreen();
      completion({ alert: true, sound: true, badge: false });
    });
  };`

also i called after upper 2 methods:

`    const initialNotification = await Notifications.getInitialNotification();
    if (initialNotification) {
      console.log('initial notifiaction: ', initialNotification);
    }
`
but initialNotification is undefined.

NotificationsReceivedForeground gets triggered if i try to send notification locally, but background notification is not reaching device. What i am missing? 
I activated in xcode remote notifications in background mode and added push notifications in capabilities, added .p12 certificate to firebase console APNs certificate

**Comment by avinashlng1080** [comment]
What is the status for this issue ?

**Comment by luisfuertes** [comment]
Any update about this?

**Comment by rynatk** [comment]
in the same boat :/

**Comment by Flouwrian** [comment]
also having the same issue

**Comment by sadikyalcin** [comment]
Having the same issue.

**Comment by saczuac** [comment]
Same issue
