### ISSUE TITLE
De-Register remote notifications?

### ISSUE THREAD

**Issue by fosteruk** [wix/react-native-notifications#490]
When a user logs in to my app I send the notification registration token to my server. So I can send the app notifications related to their account.

When the user logs out of the app, I need some way to either de-register the device or renew the registration token that the previous token no longer sends to this app.

The API doesn't appear to provide this functionality. Is this something that can be added?

**Comment by LuisRodriguezLD** [comment]
I don't think this is possible, not even in native. Your best approach is to delete that token from your database and just not send notifications to that token
