### ISSUE TITLE
[v3][Android] Foreground notification icon doesn't use icon color

### ISSUE THREAD

**Issue by patrickyin** [wix/react-native-notifications#494]
Once I added
```
<meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/colorAccent" />
```
to AndroidManifest.xml`, the background notification icon color works well. But the foreground notification icon is still grey color.

**Comment by bossajie** [comment]
Did anyone fix this? I am also having a trouble setting the background color of icon, even I already added it on the Manifest.
