### ISSUE TITLE
FR: Allow Subscribing To Topics

### ISSUE THREAD

**Issue by puremana** [wix/react-native-notifications#503]
**Feature Request**

Using [Firebase (Google Cloud Messaging)](https://firebase.google.com/docs/cloud-messaging/js/send-multiple), the only way to send to all devices without storing device tokens is to send to a topic which an app can subscribe to.

Implementing this (for both iOS and Android) will help everyone who is using Firebase to send push notifications. None of the other popular free packages aside from React Native Firebase v4 and v5 (outdated) seem to be allowing you to subscribe to topics on both iOS and Android, so you could captalize on that market.

Please consider this request. Thank you.

**Comment by tingzhouu** [comment]
Is there any way to subscribe to the topic using this library?

**Comment by puremana** [comment]
> Is there any way to subscribe to the topic using this library?

No way that I know of. We just ended up sending to 20 ID's at a time in our backend I think

**Comment by vishalambre** [comment]
I managed to get this done overriding the `FcmToken` class

```
class CustomFcmToken(appContext: Context) : FcmToken(appContext) {

    companion object {
        private val topics = listOf("global")
    }

    override fun refreshToken() {
        super.refreshToken()
        subscribeToTopics()
    }

    private fun subscribeToTopics() {
        topics.forEach {
            try {
                FirebaseMessaging.getInstance().subscribeToTopic(it)
            } catch (e: IOException) {
                //no-op
            }
        }
    }
}
```

And then using it in the main application like this: 
```
public class MainApplication extends Application implements ReactApplication, INotificationsFcmApplication {
@Override
    public IFcmToken getFcmToken(Context context) {
        return new BikewaleFcmToken(this);
    }
}
```

Hope this helps :)

**Comment by itsam** [comment]
@vishalambre Thanks... I assume this is just for Android, right? Any ideas for iOS?

**Comment by vishalambre** [comment]
> @vishalambre Thanks... I assume this is just for Android, right? Any ideas for iOS?

Yeah for Android, no idea about iOS

**Comment by MuhammedKpln** [comment]
Any progress about topics?

**Comment by Rushiraj-karm** [comment]
@puremana 
is subscribe to topic feature added ?
