### ISSUE TITLE
[ANDROID] registerNotificationReceivedBackground is not triggered when the app is killed.

### ISSUE THREAD

**Issue by ShaneMatthias** [wix/react-native-notifications#505]
`Notifications.events().registerNotificationReceivedBackground()` **is** triggered when the app is in the foreground and in the background but **not** when the app is killed.

```
'react-native': 0.61
'react-native-notificiations': 3.1.2
```

**Comment by siliconsocket** [comment]
When App is killed you need to obtain the payload with this:

```
async componentDidMount() {
    const notification: Notification = await Notifications.getInitialNotification()
    console.log('initial', notification)
  }
```

**Comment by ShaneMatthias** [comment]
@siliconsocket how do you trigger the app to wake up and start processing the notification?

**Comment by siliconsocket** [comment]
> @siliconsocket how do you trigger the app to wake up and start processing the notification?

I just received the push notification even when app is killed, then tap on it and app starts again and I recover the payload with componentDidMount() method in my main component.

**Comment by ShaneMatthias** [comment]
I see. I don't receive push notifications when the app is killed, and only when the app is killed.

**Comment by ldh1428a** [comment]
> When App is killed you need to obtain the payload with this:
> 
> ```
> async componentDidMount() {
>     const notification: Notification = await Notifications.getInitialNotification()
>     console.log('initial', notification)
>   }
> ```

In my case notification object was always thrown **undefined**... 😢😢😢😢

**Comment by ldh1428a** [comment]
> > When App is killed you need to obtain the payload with this:
> > ```
> > async componentDidMount() {
> >     const notification: Notification = await Notifications.getInitialNotification()
> >     console.log('initial', notification)
> >   }
> > ```
> 
> In my case notification object was always thrown `undefined`... 😢😢😢😢
> 
> **My Code**
> 
> ```
> useEffect(()=>{
>  Notifications.getInitialNotification().then(notification=>{
>   console.log(notification);
>  }).catch(error=>{
>  console.log(error);
> });
> },[]);
> ```

I solved this problem ! don't use `useEffect` call `getInitialNoitification()` function in `App.js`

**Comment by ferprez** [comment]
How did you resolve this issue @ldh1428a ? I have the same, getInitialNotitication always resolves me to undefined.. no matter if i call it from componentDidMount

**Comment by ldh1428a** [comment]
@ferprez did you call `componentDidMount` in `App.js(or Top of components)` ? `getInitialNotification` must be called first in your app.

**Comment by ldh1428a** [comment]
> How did you resolve this issue @ldh1428a ? I have the same, getInitialNotitication always resolves me to undefined.. no matter if i call it from componentDidMount

I same result `undefined` if app was been killed.. 

Application was `background` state `getInitialNotification()` return `notification` data, but app was `dead(killed)` state always return to `undefined`... 😢

**Comment by roshan-p** [comment]
Any solutions ? I always get undefined too from getInitialNotification();
and registerNotificationOpened(),registerNotificationReceivedForeground() did not trigger when it is called I have no idea what to do now. I'm using the latest version.

**Comment by anisimov74** [comment]
@alexbuicescu  you did great job regarding channels in Android, may be you can help us with this problem?
I also can't  get something from `getInitialNotification()` when app in `dead(killed)` mode.

**Comment by alexbuicescu** [comment]
Hi, from my knowledge, you can't process normal notifications while the app is killed. For that you need to send silent notifications (or data notifications, they are the same thing). Also, at the moment react-native-notifications does not support this. I use react-native-firebase for this.

Regarding the getInitialNotification, I'm not sure how to debug this issue, but I can look into it. It also bothers me that this is not working.

**Comment by anisimov74** [comment]
@alexbuicescu thank you for the quick response! Did I understand you right that for the particular case when app is **killed/dead** you are using **react-native-firebase** and this library for others?

**Comment by alexbuicescu** [comment]
Exactly

**Comment by anisimov74** [comment]
@alexbuicescu sorry for bothering you, but are you able to get the remoteNotification param in [react-native-firebase](https://rnfirebase.io/messaging/notifications#handling-interaction) `messaging().getInitialNotification().then(remoteNotification => ...)` when you press the notification in the drawer? I'm always getting `undefined`.
All in vain without this functionality :(

**Comment by DovletAmanov** [comment]
is this issue resolved?

**Comment by ryanmcclure4** [comment]
@alexbuicescu I'm trying to use @react-native-firebase alongside this library to handle notifs when the app is killed (as you mentioned you did). I've noticed that when I install @react-native-firebase it doesn't allow react-native-notifications to handle the notifications, because only one "com.google.firebase.MESSAGING_EVENT" service will get triggered and it essentially stops at the @react-native-firebase project. How did you get around this?
