### ISSUE TITLE
Property 'Proxy' doesn't exist, js engine: hermes

### ISSUE THREAD

**Issue by OnlineGoa** [wix/react-native-notifications#506]
- On updating the react-native-notification package from 2.1.6 to 3.1.2 **Property 'Proxy' doesn't exist, js engine: hermes** error is encountered. 

- This updated version works fine for iOS app except when the app is in background and when the notification is received the following function doesn't get triggered.

 **Notifications.events().registerNotificationReceivedBackground((notification: Notification, completion: (response: NotificationCompletion) => void) => {
      console.log("Notification Received - Background", notification.payload);

      // Calling completion on iOS with `alert: true` will present the native iOS inApp notification.
      completion({alert: true, sound: true, badge: false});
        });**

**Comment by radko93** [comment]
Duplicate of #455
