### ISSUE TITLE
iOS cannot receive first push notification when open in foreground

### ISSUE THREAD

**Issue by samchan1995** [wix/react-native-notifications#508]
Version: 3.1.2
RN version: 0.61.5

Using this version and lines from documentation

```
Notifications.events().registerNotificationReceivedForeground((notification: Notification, completion: (response: NotificationCompletion) => void) => {
      console.log("Notification Received - Foreground", notification.payload);

      // Calling completion on iOS with `alert: true` will present the native iOS inApp notification.
      completion({alert: true, sound: true, badge: false});
        });
```

I can only see the push notification alert starts from 2nd push notification, but not the first one.

**Comment by samchan1995** [comment]
My current fix:

1. Downgrade to 3.1.1
2. In AppDelegate.m
- make it conform to UNUserNotificationCenterDelegate
- add a line `[RNNotifications addNativeDelegate:self];` in didFinishLaunchingWithOptions
- add a function:
```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler {
    completionHandler(UNNotificationPresentationOptionBadge | UNNotificationPresentationOptionSound | UNNotificationPresentationOptionAlert);
}
```

**Comment by samchan1995** [comment]
BTW, I think the file causing this issue should be RNNotificationCenterMulticast.m

**Comment by roni-castro** [comment]
I am also facing the exactly same problem on  react-native-notifications: 3.1.2 and react-native 0.60

**Comment by zoftify** [comment]
Hi @samchan1995, the issue is still there :( Can you please share the way you solved that?

Much appreciated!

**Comment by ALPNP** [comment]
The @samchan1995 implementation works for me on version 3.1.1. Do you still need the AppDelegate file ?

RN version: 0.61.4

**Comment by focux** [comment]
It's also happening to me but I don't think that downgrade should be the solution. I'll try to track down this.

**RN version:** 0.61.5
**RN Notifications:** 3.1.4

**Comment by focux** [comment]
To fix this bug in RN notifications 3.1.4, go first to `RNNotificationsStore.m`, then find the initializer and apply this changes (you can also apply this patch using `patch-package`):

```diff
 diff --git a/node_modules/react-native-notifications/lib/ios/RNNotificationsStore.m b/node_modules/react-native-notifications/lib/ios/RNNotificationsStore.m
index d5e953a..18075da 100644
--- a/node_modules/react-native-notifications/lib/ios/RNNotificationsStore.m
+++ b/node_modules/react-native-notifications/lib/ios/RNNotificationsStore.m
@@ -16,8 +16,13 @@ + (instancetype)sharedInstance {
 
 - (instancetype)init {
     self = [super init];
-    _actionCompletionHandlers = [NSMutableDictionary new];
-    _presentationCompletionHandlers = [NSMutableDictionary new];
+    if (!_actionCompletionHandlers){
+        _actionCompletionHandlers = [NSMutableDictionary new];
+    }
+    
+    if (!_presentationCompletionHandlers) {
+        _presentationCompletionHandlers = [NSMutableDictionary new];
+    }
     return self;
 }
```

I won't put together a PR because it seems that the maintainers are not accepting/reviewing PRs, nevertheless, if @yogevbd is willing to review it, I'll be glad to do it.

**Comment by cmrigney** [comment]
Any updates on this? I'm experiencing the same issue.

**Comment by nerdmv** [comment]
> My current fix:
> 
> 1. Downgrade to 3.1.1
> 2. In AppDelegate.m
> 
> * make it conform to UNUserNotificationCenterDelegate
> * add a line `[RNNotifications addNativeDelegate:self];` in didFinishLaunchingWithOptions
> * add a function:
> 
> ```
> - (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler {
>     completionHandler(UNNotificationPresentationOptionBadge | UNNotificationPresentationOptionSound | UNNotificationPresentationOptionAlert);
> }
> ```

this is actually worked :/

**Comment by fedu44** [comment]
Same problem

**Comment by lukeramsden** [comment]
Not stale. Is fix live yet?

**Comment by kostiantyn-solianyk** [comment]
When you set this - `[RNNotifications addNativeDelegate:self];` you will not be able to get notification from event listener `Notifications.events().registerNotificationOpened`
