### ISSUE TITLE
'RNNotifications.h' file not found after updating this package to latest

### ISSUE THREAD

**Issue by nihp** [wix/react-native-notifications#512]
Unable to build the app after upgrading the package to the latest version.

I have used this.

```
-    "react-native-notifications": "^2.0.6",
+    "react-native-notifications": "^3.1.2",
```

How can i fix this?

**Comment by nihp** [comment]
Fixed above by adding 

node_modules/react-native-notifications/lib/ios


Getting 
![Screenshot 2020-02-26 at 12 21 51 PM](https://user-images.githubusercontent.com/36992338/75319900-84d1cc00-5893-11ea-8c0c-d5eb147b957a.png)

**Comment by hunterlong** [comment]
This is still an issue.

**Comment by sundardsTechMind** [comment]
This is still an issue with Xcode 14.3.1
