### ISSUE TITLE
Unhandled JS Exception: Undefined is not an object (evaluating '_reactNativeNotifications.default.addEventListener')

### ISSUE THREAD

**Issue by nihp** [wix/react-native-notifications#513]
Unable to build the app 

Unhandled JS Exception: undefined is not an object (evaluating '_reactNativeNotifications.default.addEventListener')

![Screenshot 2020-02-26 at 12 21 51 PM](https://user-images.githubusercontent.com/36992338/75320933-c3688600-5895-11ea-8b1b-b11ef5f65157.png)

**Comment by beulahpt** [comment]
We need to use Notifications.events() instead of addEventListener
