### ISSUE TITLE
Not receiving notifications from firebase on IOS

### ISSUE THREAD

**Issue by avinashlng1080** [wix/react-native-notifications#515]
Hello,

We are not receiving push notifications on iOS devices.

We do get the APNS token and I did convert it to FCM token.  

Still, manual push notifications from POST is not being delivered to the device.

I notice that the below issue has also been reported here.

Please let me know if you have a solution for the below.  It is very urgent.

https://support.wix.com/en/article/6-january-2020-wix-mobile-app-push-notifications-are-not-being-sent-to-ios-devices

**Comment by radko93** [comment]
I use react-native-firebase to register for notifications and this library to handle incoming notifications and everything works just fine.

**Comment by anmolpandeyy** [comment]
> I use react-native-firebase v6 to register for notifications and this library to handle incoming notifications and everything works just fine.

Even I've been using this library with react-native-firebase which apparently is working fine on android, I followed the given examples in the documentation itself but for some reason the notification listeners are not receiving notifications on IOS but are receiving on android, could you provide a code snippet as to how did you implement it to handle IOS notifications?

**Comment by Aleksandern** [comment]
- install and setup firebase following instructions from https://invertase.io/oss/react-native-firebase/v6/messaging
- use react-native-permissions instead of the firebase’s permission functions
- install and setup react-native-notifications following instructions https://wix.github.io/react-native-notifications/docs/getting-started

‘getToken’ doesn’t work on the first run (I used a pause  between checking permissions code and firebase code)

**Comment by Aleksandern** [comment]
@alexbuicescu 
This is how it looks in my case. Background and foreground  notifications work okay.

1. I don't have `FirebaseAppDelegateProxyEnabled` in my Info.plist
2. AppDelegate.m:
```
#import <Firebase.h>
#import "RNNotifications.h"

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  
  [RNNotifications startMonitorNotifications];
}

- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  [RNNotifications didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}

- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error {
  [RNNotifications didFailToRegisterForRemoteNotificationsWithError:error];
}
```

3. Podfile
```
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
```

4. react-native

```
import messaging from '@react-native-firebase/messaging';
import { Notifications } from 'react-native-notifications';
import {
  requestNotifications,
  RESULTS,
} from 'react-native-permissions';

import {
  sleep,
} from 'hz';

export default class HzService {
  constructor(options) {
    this.messaging = messaging();
    this.init();
  }

  async init() {
    let token;

    try {
      const permission = await requestNotifications(['alert', 'badge', 'sound']);

      if (permission.status !== RESULTS.GRANTED) {
        return;
      }
    } catch (err) {
      return;
    }

    try {
      const register = await this.messaging.registerForRemoteNotifications();

      if (!register) {
        return;
      }
    } catch (err) {
      return;
    }

    if (!this.token) {
      await sleep(5000);
    }

    try {
      token = await this.messaging.getToken();
    } catch (err) {
      // empty
    }

    this.onTokenRecieved(token);
  }

  onTokenRecieved(token) {
    if (!token) {
      return;
    }

    // code to store token

    this.attachListeners();
  }

  attachListeners() {
    this.onTokenRefreshListener = this.messaging.onTokenRefresh((fcmToken) => {
      this.callbacks.updateToken(fcmToken);
    });

    Notifications.registerRemoteNotifications();

    Notifications.getInitialNotification()
      .then((notif) => {
          this.callbacks.onNotificationOpened(notif);
      })
      .catch(() => {
        // empty
      });

    Notifications.events().registerNotificationReceivedForeground((notif, completion) => {
       this.callbacks.onNotificationForeground(notif);

      completion();
    });

    Notifications.events().registerNotificationOpened((notif, completion) => {
        this.callbacks.onNotificationOpened(notif);

      completion();
    });
  }

  removeListeners() {
    if (this.onTokenRefreshListener) {
      this.onTokenRefreshListener();
    }
  }
}

```

**Comment by alexbuicescu** [comment]
After more investigation I found out that **Expo** is overriding `[[UNUserNotificationCenter currentNotificationCenter] setDelegate:_notificationCenterMulticast]` with its own delegate.

I used `NSLog(@"delegate is: %@", [UNUserNotificationCenter currentNotificationCenter].delegate)` in **didFinishLaunchingWithOptions** and **didRegisterForRemoteNotificationsWithDeviceToken**. To my surprise it printed 2 different objects and knowing this I moved the expo initialiser and now everything works as expected (even the code from my first comment works). In case others come with troubles from expo, this is my **AppDelegate.m** now:
```objective-c
#import "AppDelegate.h"
#import <Firebase/Firebase.h>
#import "RNNotifications.h"

@import Firebase;

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    // call Expo here so it doesn't overwrite notifications
    [super application:application didFinishLaunchingWithOptions:launchOptions];
    
    if ([FIRApp defaultApp] == nil) {
        [FIRApp configure];
    }

    [RNNotifications startMonitorNotifications];
    // for debug purposes:
    NSLog(@"delegate is: %@", [UNUserNotificationCenter currentNotificationCenter].delegate);

    // do not call Expo here because it would overwrite notifications
    // return [super application:application didFinishLaunchingWithOptions:launchOptions];
    return YES;
}

 - (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
    // for debug purposes:
    NSLog(@"delegate is: %@", [UNUserNotificationCenter currentNotificationCenter].delegate);

    [RNNotifications didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
 }

 - (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error {
    [RNNotifications didFailToRegisterForRemoteNotificationsWithError:error];
 }

@end
```

**Comment by bsonmez** [comment]
it fixed in
```    
"@react-native-firebase/app": "6.4.0-rc1",
"@react-native-firebase/messaging": "6.4.0-rc1",
```

**Comment by Aleksandern** [comment]
@bsonmez 
What is fixed?

**Comment by bsonmez** [comment]
> @bsonmez
> What is fixed?

Not receiving fcmToken

**Comment by anmolpandeyy** [comment]
> > @bsonmez
> > What is fixed?
> 
> Not receiving fcmToken

can you tell me how can I actually follow this, I changed some code after forking it from this repo how can i reuse it in my own project?

https://stackoverflow.com/questions/60774753/how-to-change-npm-scoped-package-to-a-github-repo

Can you please look it once? its a small question which Im unable to find solution of!

**Comment by alexbuicescu** [comment]
@anmolpandeyy this is what works for me:
1. fork the repo
2. remove `lib/dist/` from **.gitignore**
3. run `npm run build`
4. commit and push to github
5. use it as follows in package.json: `https://github.com/<my-account-name-here>/react-native-notifications#<commit-hash-here>`

**Comment by rynatk** [comment]
@anmolpandeyy did you ever get the event handler callbacks to work on iOS?
 
everything works perfectly for me on Android but `registerNotificationOpened`, `registerNotificationReceivedBackground`, and `registerNotificationOpened` call backs are not firing at all for me in iOS.

`getInitialNotification` does work.

**Comment by anmolpandeyy** [comment]
> @anmolpandeyy did you ever get the event handler callbacks to work on iOS?
> 
> everything works perfectly for me on Android but `registerNotificationOpened`, `registerNotificationReceivedBackground`, and `registerNotificationOpened` call backs are not firing at all for me in iOS.
> 
> `getInitialNotification` does work.

No it never worked for me so I just didn't use it, but we don't need it anymore as firebase has given the support for local notifications recently.

**Comment by ramirobg94** [comment]
... other here, no events in IOs.

**Comment by devpascoe** [comment]
was working in 5, migrated from 5 to 6. When i first install my app i can receive push notifications sent by firebase console to my device token. They pop up and display by the OS. After a few minutes my device no longer receives notifications (even by the OS alert up the top).
I am using the default setting to autoconfigure. I have a listener for onTokenRefresh too. hmmm

**Comment by jayzyaj** [comment]
any updates on this?

**Comment by bhaskardabhi** [comment]
Still facing the issue.

**Comment by simgot** [comment]
Still same
