### ISSUE TITLE
How to start `example` on Windows?

### ISSUE THREAD

**Issue by rgetValue** [wix/react-native-notifications#516]
Hello.

How to start `example` app on Windows?

**Comment by supermar1010** [comment]
Any update on this? Struglling as well

**Comment by puremana** [comment]
Never figured it out myself

**Comment by supermar1010** [comment]
I figured it out :)
I had to navigate to the example folder and then execute this `react-native run-ios`. It did not work anyway for me. The local notifications just don't do anything on android. On iOS they only show up in the app.
