### ISSUE TITLE
[v3][Android] Background Notifcation not using Notification Icon

### ISSUE THREAD

**Issue by puremana** [wix/react-native-notifications#517]
If the app is in the background while it receives a notifcation, it will use the app icon in the notification rather than using the notification icon even if it is set.

This issue does not occur when in the foreground.

React Native: 0.61.5
React Native Notifications: 3.1.2

Using FCM

**Comment by alexparlett** [comment]
You need to add 

`<meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_notification_icon" />
            android:resource="@drawable/notification_icon" />`

To your manifest to set the background notification icon.

**Comment by puremana** [comment]
@alexparlett Thank you very much! I believe this should be added to the documentation somewhere and will leave this issue open until this info is easily discoverable.

**Comment by mayooresan** [comment]
Make sure the name of the icon is `notification_icon` else it won't work. Thanks to @tingzhouu
