### ISSUE TITLE
Add Documentation on how to contribute

### ISSUE THREAD

**Issue by puremana** [wix/react-native-notifications#518]
Would appreciate something like a contributing.md file to start working on fixing the issues in this project.

**Comment by ManAnRuck** [comment]
this would be nice!

**Comment by ManAnRuck** [comment]
@bot please do not close this issue

**Comment by puremana** [comment]
I still think this is important

**Comment by ManAnRuck** [comment]
@bot please do not close this issue

any comment from maintainers?

**Comment by guyca** [comment]
Hey guys! Contributing article can be found [here](https://wix.github.io/react-native-navigation/docs/meta-contributing) ❤️
