### ISSUE TITLE
Questions about Silence of Maintainers

### ISSUE THREAD

**Issue by andersonaddo** [wix/react-native-notifications#519]
[react-native-push-notification](https://github.com/zo0r/react-native-push-notification) has been abandoned for a while, so this package is pretty much the only well-done, free and maintained package for RN push notifications now.
It seems like you guys are maintaining the project, because commits are still coming in. But y'alls are so silent in regards to issues and PRs. How come?

**Comment by puremana** [comment]
They aren't maintaining it, hence why all of the PRs to fix and make this useable. It is depressing to look at 50% of the PRs getting closed from stalebot just because the owners don't want to review. I hope someone steps up and becomes more active but I really don't see that happening looking at this history of issues.

**Comment by andersonaddo** [comment]
Hm.
That's very unfortunate - that means there's no free and maintained package for cross-platform React Native push notifications. That's strange, since it's a very important feature for many apps.
[React Native Community](https://github.com/react-native-community) have a maintained package for iOS notifications, hopefully they'll take up one for Android (or, even better, cross platform). I know they were having discussions about that in the past.

**Comment by puremana** [comment]
One solution could be for someone to fork this, make the changes and actively review and respond to PRs and issues. All you would need is to set docs and publish this as a package.

_(Looking at the [license](https://github.com/wix/react-native-notifications/blob/master/LICENSE) I see nothing limiting you from doing this)_

**Comment by 1vanhelsing1** [comment]
Is this package not useable for production apps? I'm running into problems already and I have barely started.

**Comment by andersonaddo** [comment]
Oh it's usable. 
I know there are some issues with linking, but that's about it. Proper looking requires going through a few GitHub issues to see what problems people have run into.

**Comment by roni-castro** [comment]
I think there are some alternatives if you don't intend to have local notifications, like [react-native-firebase](https://invertase.io/oss/react-native-firebase/v6/messaging/quick-start)

**Comment by andersonaddo** [comment]
Yes, but the package doesn't handle notifications in general well anymore because they cut support for it recently.

**Comment by puremana** [comment]
> Yes, but the package doesn't handle notifications in general well anymore because they cut support for it recently.

Yeah, they have a paid package now - [https://github.com/invertase/react-native-firebase/issues/2566#issuecomment-578762231](https://github.com/invertase/react-native-firebase/issues/2566#issuecomment-578762231)

> Is this package not useable for production apps? I'm running into problems already and I have barely started.

You can but you more or less have to look through issues and PR's to piece together a working package. For me this included [https://github.com/wix/react-native-notifications/pull/496](https://github.com/wix/react-native-notifications/pull/496), [https://github.com/wix/react-native-notifications/pull/502](https://github.com/wix/react-native-notifications/pull/502) and [https://github.com/wix/react-native-notifications/issues/517](https://github.com/wix/react-native-notifications/issues/517). There may be more depending on what you're intending to do. My implementation was fairly basic.

**Comment by tattivitorino** [comment]
@puremana not to mention the [#525](https://github.com/wix/react-native-notifications/issues/525) issue which I'm facing right now! I receive the notification on Android but it has no title nor Body. 
:((((
Having a hard time here!

**Comment by puremana** [comment]
@tattivitorino try implementing this PR https://github.com/wix/react-native-notifications/pull/496, I had the same issue

**Comment by tattivitorino** [comment]
@puremana do you think it's safe and ok to use this https://www.npmjs.com/package/patch-package to implement this PR? I've never done it!

**Comment by puremana** [comment]
> @puremana do you think it's safe and ok to use this https://www.npmjs.com/package/patch-package to implement this PR? I've never done it!

Looks good to me

**Comment by tattivitorino** [comment]
@puremana thank you! the PR [#496](https://github.com/wix/react-native-notifications/pull/496) fixed the title and body in the foreground notification, but the icon is not showing! Any insights?

**Comment by puremana** [comment]
> @puremana thank you! the PR [#496](https://github.com/wix/react-native-notifications/pull/496) fixed the title and body in the foreground notification, but the icon is not showing! Any insights?

Is the icon not showing for both the foreground and background. or just the background? This may help - #517

**Comment by luisfuertes** [comment]
I have installed react-native-firebase v6xx with this component.

On Android work (with some errors).
But on iOS i receive notif from firebase console with FCM token with app in bg and closed, but Notifications events arent trigered.

Some idea to fix this?

i can't believe react native i don't have an official component for push notifications. In all my apps push always are a headache.

**Comment by andersonaddo** [comment]
@luisfuertes I suggest you make your own issue for this.
I'd prefer if people only comment on this thread if they're talking about the maintenance of this repo.

**Comment by luisfuertes** [comment]
@andersonaddo its ok
