### ISSUE TITLE
 Interactive notifications action not working 

### ISSUE THREAD

**Issue by somsin** [wix/react-native-notifications#52]
i am using Interactive notifications  for some of my customs notification , 
but my app not launched on press of notification action normally in notification click app is launched but on interactive customs action its not working 
here is my code ,
**[upvoteAction = new NotificationAction({
    activationMode: "background",
    title: "Start ",
    identifier: "UPVOTE_ACTION"
  }, (action, completed) => {
// here i am consuming notification data
    this.onNotificationOpened(action.notification)
    completed();
  });](url)**  

all action are fired that i can see in console but app is not launched , so what is issue

**Comment by scerelli** [comment]
same here on android

**Comment by daominhsangvn** [comment]
use `activationMode: "foreground"` to bring the app up
