### ISSUE TITLE
Can I register to foreground notification without showing notification?

### ISSUE THREAD

**Issue by 5haw4** [wix/react-native-notifications#520]
Is it possible to register to foreground notification without showing a notification to the user?

**Comment by beulahpt** [comment]
yes. You can use

Notifications.events().registerNotificationReceivedForeground((notification: Notification, completion: (response: NotificationCompletion) => void) => {
completion({ alert: false, sound: false, badge: false });
})

**Comment by xoapit** [comment]
i

> yes. You can use
> 
> Notifications.events().registerNotificationReceivedForeground((notification: Notification, completion: (response: NotificationCompletion) => void) => {
> completion({ alert: false, sound: false, badge: false });
> })

it is not working.

**Comment by EmilJL** [comment]
I would also love to figure this out. The solution presented above also didn't work for me.

**Comment by javierbustamante** [comment]
@beulahpt , that solution just work for iOS. I have the same problem.
