### ISSUE TITLE
My android app stop running without error after I setup react-native-notification  

### ISSUE THREAD

**Issue by Emibrown** [wix/react-native-notifications#521]
"react-native": "0.61.5",
 "react-native-notifications": "^3.1.2",

**Comment by puremana** [comment]
No errors whatesoever? I'm using the same versions with my project and didn't have this issue when I installed it. 

Did you follow the Android installation guide? [https://wix.github.io/react-native-notifications/docs/installation-android](https://wix.github.io/react-native-notifications/docs/installation-android)

**Comment by puremana** [comment]
They may be related to #456 or #492, there is a PR  https://github.com/wix/react-native-notifications/pull/496 which may help

**Comment by Emibrown** [comment]
> They may be related to #456 or #492, there is a PR #496 which may help

the notification is not empty. the issue is no notification popup(alert) on android  and I can't set alert action

**Comment by gothraven** [comment]
Same issue
```js
{
  "react-native": "0.61.5",
  "react-native-notifications": "^3.1.2",
}
```
