### ISSUE TITLE
Android doesn't fire callbacks while in background

### ISSUE THREAD

**Issue by scerelli** [wix/react-native-notifications#53]
I noticed that on Android i get notifications but the app doesn't fire setNotificationReceivedListener
setNotificationOpenedListener callbacks if the app is in background. If you keep it on screen it works as expected. Any idea? I use RNN.

**Comment by alaingoldman** [comment]
Same error here for ios.

**Comment by andreipham** [comment]
Same problem on Android.

**Comment by nkov** [comment]
I resolved this problem by sending the payload with key `data` instead of key `notification` as mentioned [here](https://github.com/wix/react-native-notifications/issues/42#issuecomment-299012587).

**Comment by Benjamin-Dobell** [comment]
This is not an issue with `react-native-notifications` but rather a limitation of how GCM/FCM works. #71 somewhat addresses this by explaining this situation in the README. As @nkov has mentioned, if you want your callback to be called when the app is in the background you must send a "data only" push notification.

**Comment by kholiavko-roman** [comment]
How to trigger callback if app was dropped from process on android ?

I tried different scenarios, only with data, with notification, with both, but nothing trigger callback if app killed from process. Anybody found the solution ?

**Comment by Benjamin-Dobell** [comment]
@kholiavko-roman there is no way to achieve this with stock react-native-notifications. The implementation makes a few inaccurate assumptions unfortunately. My pull request addresses this but unfortunately it's not building at the moment due to a bug in Google's fireball plugin.

**Comment by kholiavko-roman** [comment]
Thanks, @Benjamin-Dobell

**Comment by kaloncheung124** [comment]
Having this same issue, has anyone found any solutions?

**Comment by kaloncheung124** [comment]
I had an issue where I wasn't receiving the notifications on background or foreground. Turns out it was because I wasn't setting them in a global scope. Changed to global scope like the [example](https://github.com/wix/react-native-notifications/blob/master/example/index.android.js) does, and now I receive foreground, background, and initial notifications.
