### ISSUE TITLE
I cannot set the default icon of the push notifications in AndroidManifest.xml.

### ISSUE THREAD

**Issue by DivinoMatheus** [wix/react-native-notifications#533]
First I added the following in AndroidManifest.xml

`<meta-data
        android:name="com.google.firebase.messaging.default_notification_icon"
        android:resource="@drawable/ic_stat_ic_notification" />`

I generated all icons in [this platform](http://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=image&source.space.trim=1&source.space.pad=0&name=ic_stat_ic_notification) and put them in the drawable folders.

But the default icon in the app continues that gray square icon.

Please, someone can help me?
![432b963a-37f7-4c57-8144-0928076638ae](https://user-images.githubusercontent.com/27539713/76648185-f620a880-653c-11ea-9fdb-2834014c4e88.jpeg)

Please, someone can help me?

I'm using the following icons in the drawable folders:
[ic_stat_ic_notification.zip](https://github.com/wix/react-native-notifications/files/4330953/ic_stat_ic_notification.zip)

**Comment by tingzhouu** [comment]
My suggestion: Use android studio to generate your notification icon.
`Right click on 'res' folder -> New -> Image Asset`
From what I've tried, it seems that the name of the image must be `notification_icon`

After that, edit your `AndroidManifest.xml` accordingly [here](https://github.com/wix/react-native-notifications/issues/517#issuecomment-594184011).

I have attached some screenshots to help navigate in Android Studio.
<img width="807" alt="generating image asset" src="https://user-images.githubusercontent.com/33824745/77134151-b4de4a80-6aa0-11ea-9b86-41e858898e9b.png">
<img width="506" alt="configuring image asset" src="https://user-images.githubusercontent.com/33824745/77134146-b1e35a00-6aa0-11ea-83b5-9c39878f627a.png">

**Comment by Great-hijack** [comment]
Hi @tingzhouu 
I followed your step, but still see the square icon.
![image](https://user-images.githubusercontent.com/57619523/78808770-7cbf8d00-79f8-11ea-8a7b-63cc5a2dbaa3.png)
What should I do now?

**Comment by Great-hijack** [comment]
I found solution.
Should name notification icon name to "notification_icon" according to the source code.(lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java)
`int iconResId = getAppResourceId("notification_icon", "drawable");`
But if we can set icon via postLocalNotification() function, it will be more helpful.

Anyway Thank you all.

**Comment by theromie** [comment]
I did the same.
Change name to notification_icon and added in drawable but no luck.

**Comment by Great-hijack** [comment]
@theromie 

1. please check the following code is in **AndroidManifest.xml**

```
<meta-data
      android:name="com.google.firebase.messaging.default_notification_icon"
      android:resource="@drawable/notification_icon" />
```

2. following this comment  https://github.com/wix/react-native-notifications/issues/533#issuecomment-601513113

Hope it would be helpful

**Comment by theromie** [comment]
@Great-hijack **Thanks**, It works after creating image from Android Studio

**Comment by jrrcdev** [comment]
I guess this should be add to documentation:

Setting the icon and color:

Drawable folder:
Add your notification icon named as notification_icon.png

colors.xml
`<color name="colorAccent">Your color hex here</color>`

AndroidManifest:

```
<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />
<meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/colorAccent" />
```

**Comment by danielwinkler** [comment]
After 2 hours of trying all sorts of places to put and reference the notification icon, I would strongly be in favor of putting this to the docs
