### ISSUE TITLE
Flow returning error with RN 0.42

### ISSUE THREAD

**Issue by Maxwell2022** [wix/react-native-notifications#54]
running flow check, I have a couple of errors coming up:

react-native: v0.42
react-native-notification: v1.1.9
flow: v0.38.0

<img width="802" alt="screen shot 2017-03-28 at 2 02 48 pm" src="https://cloud.githubusercontent.com/assets/670701/24387288/05b20c3e-13c0-11e7-8d09-d975122e641a.png">

**Comment by AlimovSV** [comment]
Quick fix: `index.ios.js`, line 33 - 49
```
export class NotificationAction {
  options: Object;
  handler: Function;

  constructor(options: Object, handler: Function) {
    this.options = options;
    this.handler = handler;
  }
}

export class NotificationCategory {
  options: Object;

  constructor(options: Object) {
    this.options = options;
  }
}
```

or remove `@flow` in `index.ios.js` header
