### ISSUE TITLE
registerNotificationOpened -> notification.action is empty in iOS

### ISSUE THREAD

**Issue by spamws** [wix/react-native-notifications#541]
Hi
The first argument in below event is notification
` Notifications.events().registerNotificationOpened(notification, completion)`
but when open the app by action buttons, the notification.action is empty in 3.1.2 version.
Anyone solve this to handle actions in this version?

**Comment by songsterq** [comment]
I believe you need https://github.com/wix/react-native-notifications/pull/499 However, I don't have time to make the integration test pass.

**Comment by ronaldjeq2** [comment]
bad bot
