### ISSUE TITLE
Documentation on v6 RNN

### ISSUE THREAD

**Issue by itsam** [wix/react-native-notifications#542]
Hi, thank you for your effort.
Any plans to provide documentation (or a working example) on how to use the library with wix RNN v6?

The documentation is back from 2017 https://github.com/wix/react-native-notifications/wiki/Android:-working-with-RNN and refers to a Gist that doesn't work anymore.
Thank you in advance

**Comment by vovka-s** [comment]
+1
usual android manual doesn't work
adding `packages.add(new RNNotificationsPackage(MainApplication.this));` to `MainApplication.java` leads to crash
