### ISSUE TITLE
Notification Action and Category require position args, not named args

### ISSUE THREAD

**Issue by joshuamckenty** [wix/react-native-notifications#544]
Since the constructor in https://github.com/wix/react-native-notifications/blob/master/lib/src/interfaces/NotificationCategory.ts isn't using destructuring, the docs on how to use NotificationAction and NotificationCategory are incorrect. I got them to work by using positional arguments:

```

  let likedAction = new NotificationAction(
    'LIKERT_1',
    'foreground',
    '\uD83D\uDE00 Strong Yes',
  );

  let neutralAction = new NotificationAction(
    'LIKERT_3',
    'foreground',
    '\uD83D\uDE10 Neutral',
  );

  let dislikedAction = new NotificationAction(
    'LIKERT_5',
    'foreground',
    '\uD83D\uDE41 Strong No',
  );

  let exampleCategory = new NotificationCategory('biff', [
    likedAction,
    neutralAction,
    dislikedAction,
  ]);
```

It would be nice if these were updated to use destructuring (see e.g. https://www.csgpro.com/blog/2016/08/typescript-default-parameters-and-destructuring-as-a-substitute-for-named-parameters/)

**Comment by joshuamckenty** [comment]
As a follow up to this, the callback wrapper is swallowing the action parameter, and the method signatures are wrong. I patched CompletionCallbackWrapper.js so it looks like this:
```
    wrapOpenedCallback(callback) {
        return (notification, _completion, action) => {
            const completion = () => {
                if (react_native_1.Platform.OS === 'ios') {
                    this.nativeCommandsSender.finishHandlingAction(notification.identifier);
                }
            };
            callback(notification, completion, action);
        };
```
The EventsRegistry.d.ts is still wrong (describing registerNotificationOpened as taking a callback with a full response object and a completion object, where the response object includes the notification and the action, etc).

**Comment by nvnk3** [comment]
How to add a callback to NotificationAction ?

**Comment by nvnk3** [comment]
> As a follow up to this, the callback wrapper is swallowing the action parameter, and the method signatures are wrong. I patched CompletionCallbackWrapper.js so it looks like this:
> 
> ```
>     wrapOpenedCallback(callback) {
>         return (notification, _completion, action) => {
>             const completion = () => {
>                 if (react_native_1.Platform.OS === 'ios') {
>                     this.nativeCommandsSender.finishHandlingAction(notification.identifier);
>                 }
>             };
>             callback(notification, completion, action);
>         };
> ```
> 
> The EventsRegistry.d.ts is still wrong (describing registerNotificationOpened as taking a callback with a full response object and a completion object, where the response object includes the notification and the action, etc).

Thanks for your patch!  it just worked fine. Were you able to capture notification on registerNotificationOpened() when app is dead, if so, can you please share us the steps how it can be done. it just works fine when the app is in 'background/foreground', your help will be much appreciated.
