### ISSUE TITLE
Other notifications from notification drawer are vanished after opening the first one on Android

### ISSUE THREAD

**Issue by anisimov74** [wix/react-native-notifications#545]
Hi!
I have several remote notifications on my Android device.
After tapping on the first one the others are just disappear from the notifications drawer.
Any ideas?

**react-native-notifications@^3.1.2**

React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
      Memory: 19.45 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 23.0.1, 25.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10

**Comment by anisimov74** [comment]
I'm suffering from this problem, because my server sending many notifications :(

**Comment by anisimov74** [comment]
My investigation So, in 
`/lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java` method `onOpened()` invokes method `clearAllNotifications()` that removes all notifications.

It seems it's not necessary, because method `getNotificationBuilder` already has a call `setAutoCancel(true)` that does the job.

**Comment by philipheinser** [comment]
@anisimov74 I have the same problem. Do you see any problem just removing the `clearAllNotifications()` call?

**Comment by anisimov74** [comment]
@philipheinser it's a bit strange, but removing mentioned method call fixes problem on Android simulator, but a real device still suffering from this problem.
You can try my fork https://github.com/anisimov74/react-native-notifications.
Just replace `react-native-notifications` to `git://github.com/anisimov74/react-native-notifications.git#e95943d` in `package.json`.
May de you will get different results.

**Comment by philipheinser** [comment]
@anisimov74 For me its also not working in the simulator.

**Comment by philipheinser** [comment]
@anisimov74 Maybe this file has to be adjusted also: https://github.com/wix/react-native-notifications/blob/master/lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notificationdrawer/PushNotificationsDrawer.java

**Comment by anisimov74** [comment]
@philipheinser you're right. Check this out git://github.com/anisimov74/react-native-notifications.git#20ef711

**Comment by anisimov74** [comment]
@yogevbd i've made a PR https://github.com/wix/react-native-notifications/pull/559
