### ISSUE TITLE
Notification Preview pop-up not showing on screen and data notifcation does not receive in lower version android

### ISSUE THREAD

**Issue by Waqas-Jani** [wix/react-native-notifications#546]
Hi thanks in advance : 
i'm using this lib and facing some problem,  notification pop-up does not appear on top screen but just got tone and badge. 
Seocnd issue is that . Data notification from firebase does not receive in lower android version:
Please help me to sovle these problem thanks again

**Comment by vishalkarmal** [comment]
Replace file with 
/node_module/react-native-notification/lib/android/app/src/mail/java/com/wix/reactnativenotifications/core/notification/PushNotification.java


package com.wix.reactnativenotifications.core.notification;

import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.content.Context;
import android.content.Intent;
import android.os.Build;
import android.os.Bundle;
import android.os.Debug;
import android.util.Log;

import com.facebook.react.bridge.Arguments;
import com.facebook.react.bridge.ReactContext;
import com.facebook.react.bridge.WritableMap;
import com.wix.reactnativenotifications.core.AppLaunchHelper;
import com.wix.reactnativenotifications.core.AppLifecycleFacade;
import com.wix.reactnativenotifications.core.AppLifecycleFacade.AppVisibilityListener;
import com.wix.reactnativenotifications.core.AppLifecycleFacadeHolder;
import com.wix.reactnativenotifications.core.InitialNotificationHolder;
import com.wix.reactnativenotifications.core.JsIOHelper;
import com.wix.reactnativenotifications.core.NotificationIntentAdapter;
import com.wix.reactnativenotifications.core.ProxyService;

import static com.wix.reactnativenotifications.Defs.NOTIFICATION_OPENED_EVENT_NAME;
import static com.wix.reactnativenotifications.Defs.NOTIFICATION_RECEIVED_EVENT_NAME;

public class PushNotification implements IPushNotification {

    final protected Context mContext;
    final protected AppLifecycleFacade mAppLifecycleFacade;
    final protected AppLaunchHelper mAppLaunchHelper;
    final protected JsIOHelper mJsIOHelper;
    final protected PushNotificationProps mNotificationProps;
    final protected AppVisibilityListener mAppVisibilityListener = new AppVisibilityListener() {
        @Override
        public void onAppVisible() {
            mAppLifecycleFacade.removeVisibilityListener(this);
            dispatchImmediately();
        }

        @Override
        public void onAppNotVisible() {
        }
    };

    public static IPushNotification get(Context context, Bundle bundle) {
        Context appContext = context.getApplicationContext();
        if (appContext instanceof INotificationsApplication) {
            return ((INotificationsApplication) appContext).getPushNotification(context, bundle,
                    AppLifecycleFacadeHolder.get(), new AppLaunchHelper());
        }
        return new PushNotification(context, bundle, AppLifecycleFacadeHolder.get(), new AppLaunchHelper(),
                new JsIOHelper());
    }

    protected PushNotification(Context context, Bundle bundle, AppLifecycleFacade appLifecycleFacade,
            AppLaunchHelper appLaunchHelper, JsIOHelper JsIOHelper) {
        mContext = context;
        mAppLifecycleFacade = appLifecycleFacade;
        mAppLaunchHelper = appLaunchHelper;
        mJsIOHelper = JsIOHelper;
        mNotificationProps = createProps(bundle);
    }

    @Override
    public void onReceived() throws InvalidNotificationException {
        postNotification(null);
        notifyReceivedToJS();
    }

    @Override
    public void onOpened() {
        digestNotification();
        clearAllNotifications();
    }

    @Override
    public int onPostRequest(Integer notificationId) {
        return postNotification(notificationId);
    }

    @Override
    public PushNotificationProps asProps() {
        return mNotificationProps.copy();
    }

    protected int postNotification(Integer notificationId) {
        final PendingIntent pendingIntent = getCTAPendingIntent();
        final Notification notification = buildNotification(pendingIntent);
        return postNotification(notification, notificationId);
    }

    protected void digestNotification() {
        if (!mAppLifecycleFacade.isReactInitialized()) {
            setAsInitialNotification();
            launchOrResumeApp();
            return;
        }

        final ReactContext reactContext = mAppLifecycleFacade.getRunningReactContext();
        if (reactContext.getCurrentActivity() == null) {
            setAsInitialNotification();
        }

        if (mAppLifecycleFacade.isAppVisible()) {
            dispatchImmediately();
        } else {
            dispatchUponVisibility();
        }
    }

    protected PushNotificationProps createProps(Bundle bundle) {
        return new PushNotificationProps(bundle);
    }

    protected void setAsInitialNotification() {
        InitialNotificationHolder.getInstance().set(mNotificationProps);
    }

    protected void dispatchImmediately() {
        notifyOpenedToJS();
    }

    protected void dispatchUponVisibility() {
        mAppLifecycleFacade.addVisibilityListener(getIntermediateAppVisibilityListener());

        // Make the app visible so that we'll dispatch the notification opening when
        // visibility changes to 'true' (see
        // above listener registration).
        launchOrResumeApp();
    }

    protected AppVisibilityListener getIntermediateAppVisibilityListener() {
        return mAppVisibilityListener;
    }

    protected PendingIntent getCTAPendingIntent() {
        final Intent cta = new Intent(mContext, ProxyService.class);
        return NotificationIntentAdapter.createPendingNotificationIntent(mContext, cta, mNotificationProps);
    }

    protected Notification buildNotification(PendingIntent intent) {
        return getNotificationBuilder(intent).build();
    }

    protected Notification.Builder getNotificationBuilder(PendingIntent intent) {

        String CHANNEL_ID = "channel_01";
        String CHANNEL_NAME = "Channel Name";

        final Notification.Builder notification = new Notification.Builder(mContext)
                .setContentTitle(mNotificationProps.getTitle()).setContentText(mNotificationProps.getBody())
                .setContentIntent(intent).setDefaults(Notification.DEFAULT_ALL).setPriority(Notification.PRIORITY_HIGH)
                .setAutoCancel(true);

        int resourceID = mContext.getResources().getIdentifier("notification_icon", "drawable",
                mContext.getPackageName());
        if (resourceID != 0) {
            notification.setSmallIcon(resourceID);
        } else {
            notification.setSmallIcon(mContext.getApplicationInfo().icon);
        }

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationChannel channel = new NotificationChannel(CHANNEL_ID, CHANNEL_NAME,
                    NotificationManager.IMPORTANCE_HIGH);
            final NotificationManager notificationManager = (NotificationManager) mContext
                    .getSystemService(Context.NOTIFICATION_SERVICE);
            notificationManager.createNotificationChannel(channel);
            notification.setChannelId(CHANNEL_ID);
        }

        return notification;
    }

    protected int postNotification(Notification notification, Integer notificationId) {
        int id = notificationId != null ? notificationId : createNotificationId(notification);
        postNotification(id, notification);
        return id;
    }

    protected void postNotification(int id, Notification notification) {
        final NotificationManager notificationManager = (NotificationManager) mContext
                .getSystemService(Context.NOTIFICATION_SERVICE);
        notificationManager.notify(id, notification);
    }

    protected void clearAllNotifications() {
        final NotificationManager notificationManager = (NotificationManager) mContext
                .getSystemService(Context.NOTIFICATION_SERVICE);
        notificationManager.cancelAll();
    }

    protected int createNotificationId(Notification notification) {
        return (int) System.nanoTime();
    }

    private void notifyReceivedToJS() {
        mJsIOHelper.sendEventToJS(NOTIFICATION_RECEIVED_EVENT_NAME, mNotificationProps.asBundle(),
                mAppLifecycleFacade.getRunningReactContext());
    }

    private void notifyOpenedToJS() {
        Bundle response = new Bundle();
        response.putBundle("notification", mNotificationProps.asBundle());

        mJsIOHelper.sendEventToJS(NOTIFICATION_OPENED_EVENT_NAME, response,
                mAppLifecycleFacade.getRunningReactContext());
    }

    protected void launchOrResumeApp() {
        final Intent intent = mAppLaunchHelper.getLaunchIntent(mContext);
        mContext.startActivity(intent);
    }
}

**Comment by JulioOrellana** [comment]
thanks @vishalkarmal, your solution works for me in foreground but in background popup is still not showing. Do you have any clue?

**Comment by douira** [comment]
Maybe the posted code can be expanded into a proper PR?

**Comment by RocKer004** [comment]
Any updates about this ?

**Comment by MarufSharifi** [comment]
> Replace file with
> /node_module/react-native-notification/lib/android/app/src/mail/java/com/wix/reactnativenotifications/core/notification/PushNotification.java
> 
> package com.wix.reactnativenotifications.core.notification;
> 
> import android.app.Notification;
> import android.app.NotificationChannel;
> import android.app.NotificationManager;
> import android.app.PendingIntent;
> import android.content.Context;
> import android.content.Intent;
> import android.os.Build;
> import android.os.Bundle;
> import android.os.Debug;
> import android.util.Log;
> 
> import com.facebook.react.bridge.Arguments;
> import com.facebook.react.bridge.ReactContext;
> import com.facebook.react.bridge.WritableMap;
> import com.wix.reactnativenotifications.core.AppLaunchHelper;
> import com.wix.reactnativenotifications.core.AppLifecycleFacade;
> import com.wix.reactnativenotifications.core.AppLifecycleFacade.AppVisibilityListener;
> import com.wix.reactnativenotifications.core.AppLifecycleFacadeHolder;
> import com.wix.reactnativenotifications.core.InitialNotificationHolder;
> import com.wix.reactnativenotifications.core.JsIOHelper;
> import com.wix.reactnativenotifications.core.NotificationIntentAdapter;
> import com.wix.reactnativenotifications.core.ProxyService;
> 
> import static com.wix.reactnativenotifications.Defs.NOTIFICATION_OPENED_EVENT_NAME;
> import static com.wix.reactnativenotifications.Defs.NOTIFICATION_RECEIVED_EVENT_NAME;
> 
> public class PushNotification implements IPushNotification {
> 
> ```
> final protected Context mContext;
> final protected AppLifecycleFacade mAppLifecycleFacade;
> final protected AppLaunchHelper mAppLaunchHelper;
> final protected JsIOHelper mJsIOHelper;
> final protected PushNotificationProps mNotificationProps;
> final protected AppVisibilityListener mAppVisibilityListener = new AppVisibilityListener() {
>     @Override
>     public void onAppVisible() {
>         mAppLifecycleFacade.removeVisibilityListener(this);
>         dispatchImmediately();
>     }
> 
>     @Override
>     public void onAppNotVisible() {
>     }
> };
> 
> public static IPushNotification get(Context context, Bundle bundle) {
>     Context appContext = context.getApplicationContext();
>     if (appContext instanceof INotificationsApplication) {
>         return ((INotificationsApplication) appContext).getPushNotification(context, bundle,
>                 AppLifecycleFacadeHolder.get(), new AppLaunchHelper());
>     }
>     return new PushNotification(context, bundle, AppLifecycleFacadeHolder.get(), new AppLaunchHelper(),
>             new JsIOHelper());
> }
> 
> protected PushNotification(Context context, Bundle bundle, AppLifecycleFacade appLifecycleFacade,
>         AppLaunchHelper appLaunchHelper, JsIOHelper JsIOHelper) {
>     mContext = context;
>     mAppLifecycleFacade = appLifecycleFacade;
>     mAppLaunchHelper = appLaunchHelper;
>     mJsIOHelper = JsIOHelper;
>     mNotificationProps = createProps(bundle);
> }
> 
> @Override
> public void onReceived() throws InvalidNotificationException {
>     postNotification(null);
>     notifyReceivedToJS();
> }
> 
> @Override
> public void onOpened() {
>     digestNotification();
>     clearAllNotifications();
> }
> 
> @Override
> public int onPostRequest(Integer notificationId) {
>     return postNotification(notificationId);
> }
> 
> @Override
> public PushNotificationProps asProps() {
>     return mNotificationProps.copy();
> }
> 
> protected int postNotification(Integer notificationId) {
>     final PendingIntent pendingIntent = getCTAPendingIntent();
>     final Notification notification = buildNotification(pendingIntent);
>     return postNotification(notification, notificationId);
> }
> 
> protected void digestNotification() {
>     if (!mAppLifecycleFacade.isReactInitialized()) {
>         setAsInitialNotification();
>         launchOrResumeApp();
>         return;
>     }
> 
>     final ReactContext reactContext = mAppLifecycleFacade.getRunningReactContext();
>     if (reactContext.getCurrentActivity() == null) {
>         setAsInitialNotification();
>     }
> 
>     if (mAppLifecycleFacade.isAppVisible()) {
>         dispatchImmediately();
>     } else {
>         dispatchUponVisibility();
>     }
> }
> 
> protected PushNotificationProps createProps(Bundle bundle) {
>     return new PushNotificationProps(bundle);
> }
> 
> protected void setAsInitialNotification() {
>     InitialNotificationHolder.getInstance().set(mNotificationProps);
> }
> 
> protected void dispatchImmediately() {
>     notifyOpenedToJS();
> }
> 
> protected void dispatchUponVisibility() {
>     mAppLifecycleFacade.addVisibilityListener(getIntermediateAppVisibilityListener());
> 
>     // Make the app visible so that we'll dispatch the notification opening when
>     // visibility changes to 'true' (see
>     // above listener registration).
>     launchOrResumeApp();
> }
> 
> protected AppVisibilityListener getIntermediateAppVisibilityListener() {
>     return mAppVisibilityListener;
> }
> 
> protected PendingIntent getCTAPendingIntent() {
>     final Intent cta = new Intent(mContext, ProxyService.class);
>     return NotificationIntentAdapter.createPendingNotificationIntent(mContext, cta, mNotificationProps);
> }
> 
> protected Notification buildNotification(PendingIntent intent) {
>     return getNotificationBuilder(intent).build();
> }
> 
> protected Notification.Builder getNotificationBuilder(PendingIntent intent) {
> 
>     String CHANNEL_ID = "channel_01";
>     String CHANNEL_NAME = "Channel Name";
> 
>     final Notification.Builder notification = new Notification.Builder(mContext)
>             .setContentTitle(mNotificationProps.getTitle()).setContentText(mNotificationProps.getBody())
>             .setContentIntent(intent).setDefaults(Notification.DEFAULT_ALL).setPriority(Notification.PRIORITY_HIGH)
>             .setAutoCancel(true);
> 
>     int resourceID = mContext.getResources().getIdentifier("notification_icon", "drawable",
>             mContext.getPackageName());
>     if (resourceID != 0) {
>         notification.setSmallIcon(resourceID);
>     } else {
>         notification.setSmallIcon(mContext.getApplicationInfo().icon);
>     }
> 
>     if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
>         NotificationChannel channel = new NotificationChannel(CHANNEL_ID, CHANNEL_NAME,
>                 NotificationManager.IMPORTANCE_HIGH);
>         final NotificationManager notificationManager = (NotificationManager) mContext
>                 .getSystemService(Context.NOTIFICATION_SERVICE);
>         notificationManager.createNotificationChannel(channel);
>         notification.setChannelId(CHANNEL_ID);
>     }
> 
>     return notification;
> }
> 
> protected int postNotification(Notification notification, Integer notificationId) {
>     int id = notificationId != null ? notificationId : createNotificationId(notification);
>     postNotification(id, notification);
>     return id;
> }
> 
> protected void postNotification(int id, Notification notification) {
>     final NotificationManager notificationManager = (NotificationManager) mContext
>             .getSystemService(Context.NOTIFICATION_SERVICE);
>     notificationManager.notify(id, notification);
> }
> 
> protected void clearAllNotifications() {
>     final NotificationManager notificationManager = (NotificationManager) mContext
>             .getSystemService(Context.NOTIFICATION_SERVICE);
>     notificationManager.cancelAll();
> }
> 
> protected int createNotificationId(Notification notification) {
>     return (int) System.nanoTime();
> }
> 
> private void notifyReceivedToJS() {
>     mJsIOHelper.sendEventToJS(NOTIFICATION_RECEIVED_EVENT_NAME, mNotificationProps.asBundle(),
>             mAppLifecycleFacade.getRunningReactContext());
> }
> 
> private void notifyOpenedToJS() {
>     Bundle response = new Bundle();
>     response.putBundle("notification", mNotificationProps.asBundle());
> 
>     mJsIOHelper.sendEventToJS(NOTIFICATION_OPENED_EVENT_NAME, response,
>             mAppLifecycleFacade.getRunningReactContext());
> }
> 
> protected void launchOrResumeApp() {
>     final Intent intent = mAppLaunchHelper.getLaunchIntent(mContext);
>     mContext.startActivity(intent);
> }
> ```
> 
> }

Thank you so much, the solution solved my problem, it worked fine in both mode (background and foreground).
