### ISSUE TITLE
Installation and Setup

### ISSUE THREAD

**Issue by heuism** [wix/react-native-notifications#55]
When i open this page: [linking-libraries-ios](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking)

I wonder to i need to really do the manually linking? or can use automatically?

Secondly, i dont know for sure why this library said open AppDelegate.m and import RNNotifications.h while there is only AppDelegate.swift when i open the Xcode project so i dont know what is the next step to do. I try to import RNNotifications but it seems that is not a right thing.

Please help

**Comment by paulbrittain** [comment]
Your xcode project is using swift while the example is providing you with objective c
