### ISSUE TITLE
iOS registerRemoteNotificationsRegistered didn't trigger the callback

### ISSUE THREAD

**Issue by nesthub** [wix/react-native-notifications#556]
Hello,

Since 3-5 hours, when I am registering my decive with

Notifications.events().registerRemoteNotificationsRegistered(successCallback)

My successCallback is never call.

If I do the registration on simulator, to test the error callback

Notifications.events().registerRemoteNotificationsRegistrationFailed(errorCallback)

Properly call errorCallback.

If I change errorCallback to successCallback on simulator, for test purpose, the successCallback is properly call

Did someone have an idea ? It was working well earlier today

**Comment by hannojg** [comment]
Are you being asked for notification permission on real device? If that's not ahppening it's a good indicator you are missing something.

**Comment by StijnCoolen** [comment]
@nesthub I also seem to be having this problem. `Notifications.events().registerRemoteNotificationsRegistered` is not being called.

**Comment by nesthub** [comment]
@hannojg yes, I check and request the permission before registering

@StijnCoolen I have following the getting started guide, and add the method in AppDelegate.m https://wix.github.io/react-native-notifications/docs/getting-started

Everything was working and after a serie of test it suddently didnt work anymore

**Comment by nesthub** [comment]
This morning I updated all my package, including React, and removed all my cache, including the Pods folder, and it was a pain in the ass :) but finally it work again. I'm even not sure it is because of my update.. but I close the issue. Thank for help

**Comment by StijnCoolen** [comment]
@nesthub I also thought it was fixed by restarting but somehow it appears to be happening again. After requesting permission the subscription is not being called.

**Comment by SimonGlancy** [comment]
I am having this problem, did anyone else find the cause. It was working fine and now the success callback is never called

**Comment by saczuac** [comment]
The same is happening to me. It was working fine and now the success callback is never called

**Comment by ALPNP** [comment]
Guys, clear the cache and everything will work again.

npm start -- --reset-cache

**Comment by ramirobg94** [comment]
Other here....

**Comment by gabrielmoncea** [comment]
I tried with `--reset-cache` and clean `pod install` but still cannot get the deviceToken anymore :(

**Comment by gabrielmoncea** [comment]
@nesthub can you please reopen the issue?

**Comment by bhaskardabhi** [comment]
Happening for me as well

**Comment by MihailShab** [comment]
I also had, it turned out I didn't call `Notifications.registerRemoteNotifications();`
