### ISSUE TITLE
removeDeliveredNotifications For Android?

### ISSUE THREAD

**Issue by ryanmcclure4** [wix/react-native-notifications#560]
I need to have the ability to remove individual notifications (_not all_) from both Android and iOS. My specific use case is for a chat app that should remove a notification if the user has seen the new message on a different device.

The documentation outlines usage of `removeDeliveredNotifications` for iOS, which appears to be what I need for that os, but I don't see any respective functionality for Android. Is this not possible using this library?

**Comment by berdimyradov** [comment]
@ryanmcclure4 Were you able to get relevant answer to you question? I wonder why this issue is closed. Was it resolved to you?

I would also like to have a support for `removeDeliveredNotifications` for Android OS
