### ISSUE TITLE
iOS Background Notifications

### ISSUE THREAD

**Issue by ryanmcclure4** [wix/react-native-notifications#562]
I'm a little confused about the terminology and implementation of background notifications. As far as I'm aware, there are 2 cases for "background notifications":

**Case 1: Based on app state**
This would be when the app is in the background and it receives a normal push notification. As I understand it, this is what `registerNotificationReceivedBackground` is supposed to handle.

Looking through the code, I notice it uses on [UNUserNotificationCenterDelegate](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate) which only works for notification activity when the app is running in the _foreground_. I see the differentiating factor between `registerNotificationReceivedBackground` and `registerNotificationReceivedForeground` is just that it checks the current state of the app. How is `registerNotificationReceivedBackground` ever going to get triggered, since A) the JS stops running when app is in the background, and B) UNUserNotificationCenter only works in the foreground? Maybe I'm missing something here, but in my tests this never gets called, while the foreground one does.

**Case 2: Based on notification type**
Background notifications, meaning the notification type is "background". This is linked in the docs [here](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app).

Is it assumed that we will `application:didReceiveRemoteNotification:fetchCompletionHandler` on our own?

**Comment by songsterq** [comment]
I added a helper on `RNNotifications` to make it easier to add `application:didReceiveRemoteNotification:fetchCompletionHandler:`.

https://github.com/wix/react-native-notifications/pull/582
