### ISSUE TITLE
getInitialNotification() does not clear a notification in iOS

### ISSUE THREAD

**Issue by stelmakh** [wix/react-native-notifications#563]
`react-native-notifications` v3.1.4

`getInitialNotification` function behavior is different in Android and iOS.
In Android, it returns a notification and then clears it, which is what I would expect it to do. In iOS, however, it doesn't clear an initial notification and just returns it on the next load again.

**Comment by ssilverr** [comment]
Are you using fast refresh? If I reload the app or exit and reopen, it's not displayed again, only on fast refresh

**Comment by MuhammadMuzammilQadri** [comment]
This is indeed happening. If I open the app upon clicking a notification, then whenever I close the app and reopen it again, I see this notification. Later if I click on any other notification to open the app, I start getting the new one upon startup in getInitialNotification.
