### ISSUE TITLE
android initial notification still undefined v3.1.4

### ISSUE THREAD

**Issue by ssilverr** [wix/react-native-notifications#572]
I receive the notification, click it, it opens the app, but the notifications is undefined. 

As I understand, this PR #496 fixed this issue. Does this part require any other setup?

 I'm using node-pushnotifications to send the notifications.

**Comment by vishalambre** [comment]
Hope this [answer](https://github.com/wix/react-native-notifications/issues/457#issuecomment-615349857) helps

**Comment by anisimov74** [comment]
@vishalambre could you please clarify how to use you findings to fix this problem? Here or where you in the issue you've mentioned above? Thanks!
