### ISSUE TITLE
Setting Multiple Categories

### ISSUE THREAD

**Issue by danwhite-ipc** [wix/react-native-notifications#573]
When attempting to set multiple categories using `Notifications.setCategories([Category1, Category2]);` I get the following error.

`Exception '-[__NSFrozenDictionaryM isEqualToString:]: unrecognized selector sent to instance 0x600002ab3200' was thrown while invoking setCategories on target RNBridgeModule with params`

**Comment by daominhsangvn** [comment]
Hello, any solutions for this ?
