### ISSUE TITLE
onNotificationOpened() not called if app was dead

### ISSUE THREAD

**Issue by guybridge** [wix/react-native-notifications#575]
Hi,

Using version 3.1.4.
It's all working for the most part. 

- When the app is in the foreground the notification is received OK and onNotificationOpened() is called.
- When the app is in the background and I send a push, it opens the app OK and onNotificationOpened() is called 
- When the app is dead, the push notification is received OK but onNotificationOpened() is not called so I can't navigate the user to a specific screen. Instead the app opens the default list.

AppDelegate.m
```
// Required for the register event.
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
   // And add the following methods to support registration to
    [RNNotifications didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}

// Required for the registrationError event.
- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
{
    [RNNotifications didFailToRegisterForRemoteNotificationsWithError:error];
}
```

I'm calling 

```
 Notifications.events().registerNotificationOpened((notification, completion) => {
        completion()
    });
```
From HomeView.js which is the main list in the constructor.

**Comment by guybridge** [comment]
I should note that this is only being used on iOS.
I need the onNotificationOpened() to allow the app to navigate to a specific screen in the app. (this.props.navigation.navigate..)

Happy to hear any workarounds to that.

**Comment by SaeedZhiany** [comment]
Is this happen only on iOS? can you successfully use this listener on Android? I can't use it on Android too

**Comment by vishalambre** [comment]
I think you you need to use `getInitialNotification` to retrive to the notification when the app is killed; `onNotificationOpened` only get's called when the app is active

**Comment by nvnk3** [comment]
I need to capture NotificationAction on onNotificationOpened(), but it never fired when app is already dead. Can someone please suggest a way to capture an action when app is dead.

**Comment by guybridge** [comment]
> I think you you need to use `getInitialNotification` to retrive to the notification when the app is killed; `onNotificationOpened` only get's called when the app is active

Yes I can confirm this is correct.

getInitialNotification() gets called with the Notification data when a push is received and the app was in a dead state.

**Comment by guybridge** [comment]
> Is this happen only on iOS? can you successfully use this listener on Android? I can't use it on Android too

Docs says that getInitialNotification doesn't work on Android.

**Comment by vishalambre** [comment]
> > Is this happen only on iOS? can you successfully use this listener on Android? I can't use it on Android too
> 
> Docs says that getInitialNotification doesn't work on Android.

I haven't checked this for iOS, but it surely works for android; [Querying initial notification](https://wix.github.io/react-native-notifications/docs/notifications-events#querying-initial-notification) is surely a bit confusing as it states that `PushNotificationsIOS.getInitialNotification()` is iOS only, but `Notifications.getInitialNotification()` does work for both. Also make sure to check the notes below the section

**Comment by nvnk3** [comment]
> > I think you you need to use `getInitialNotification` to retrive to the notification when the app is killed; `onNotificationOpened` only get's called when the app is active
> 
> Yes I can confirm this is correct.
> 
> getInitialNotification() gets called with the Notification data when a push is received and the app was in a dead state.

You cannot capture NotificationAction in getInitialNotification() as per the document.

**Comment by bobbyrinaldy** [comment]
how to deal with android then ? i got same problem when app killed/dead states, i cannot get any notification

**Comment by SiSa68** [comment]
Hi @guybridge 
`getInitialNotification()` does not work when I show scheduled local notification with action, and open app with selecting an action or notification!
