### ISSUE TITLE
registerNotificationReceivedBackground is not triggered in ios

### ISSUE THREAD

**Issue by beulahpt** [wix/react-native-notifications#576]
I am trying to set app badge count when the app receives push notifications in background state. But registerNotificationReceivedBackground is not triggered in iOS.

**Comment by rynatk** [comment]
I saw the same behavior, where none of the ios event handlers are actually working:
https://github.com/wix/react-native-notifications/issues/561

**Comment by beulahpt** [comment]
Other event handlers are working for me in iOS

**Comment by danwhite-ipc** [comment]
I am having the same issue, all events are working apart from the registerNotificationReceivedBackground

**Comment by gamazu** [comment]
Same issue for me. 
I get notifications but the event registerNotificationReceivedBackground  doesn't work.
Has anyone handled this?

**Comment by kgsachinthaudara** [comment]
same issue for me.

**Comment by nathnat** [comment]
Hi guys same issue for me here it's been 3 days it's very annoying.

**Comment by artdevgame** [comment]
I queried this recently in another ticket because I had a slightly different use-case but have you checked your payload against what Apple requires for a push to be considered a background notification?

See comment here:
https://github.com/wix/react-native-notifications/issues/848#issuecomment-1087513109

It is a requirement that the push `aps` object _only_ has `content-available: 1` in it. If you include anything else, it won't be treated as a background notification, and hence why the JS function isn't getting called.

**Comment by nathnat** [comment]
Yes I did all that Apple requires. I even added the header `apns-push-type` and `apns-priority` as mentioned [here](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app/#:~:text=Additionally%2C%20the%20notification%E2%80%99s%20POST%20request%20should%20contain%20the%20apns%2Dpush%2Dtype%20header%20field%20with%20a%20value%20of%20background%2C%20and%20the%20apns%2Dpriority%20field%20with%20a%20value%20of%205).

Here is my server code :
```js
const request = http2Client.request({
    ':method': 'POST',
    ':scheme': 'https',
    'apns-push-type': 'background',
    'apns-priority': 5,
    'apns-topic': BUNDLE_ID,
    ':path': '/3/device/' + DEVICE_TOKEN,
    authorization: `bearer ${authorizationToken}`,
});
request.setEncoding('utf8');

request.write(JSON.stringify({
    "aps": {
        "content-available": 1
    }
}));
```

**Comment by artdevgame** [comment]
Invoking @DanielEliraz 😉
