### ISSUE TITLE
iOS registerNotificationOpened not fired from "dead" state

### ISSUE THREAD

**Issue by nvnk3** [wix/react-native-notifications#578]
As per the document, registerNotificationOpened() is fired when a remote notification is opened from dead or background state. The handler will be invoked with an instance of Notification. Should call completion function on iOS, will be ignored on Android.

But, it just launches the app in background and registerNotificationOpened event is not fired. When the app is in 'background/foreground' it just works fine.

There are the versions I'm using.
"react-native-navigation": "^6.4.0"
"react-native-notifications": "^3.1.4"

**Comment by nvnk3** [comment]
@joshuamckenty Can you please help me with the issue mention in this ticket, I saw you fixing **registerNotificationOpened** in **3.1.4-snapshot.117**, so I'm just trying to reach out to see if you can put me in the right direction.

**Comment by bobbyrinaldy** [comment]
> @joshuamckenty Can you please help me with the issue mentioned in this ticket, I saw you fixing **registerNotificationOpened** in **3.1.4-snapshot.117**, so I'm just trying to reach out to see if you can put me in the right direction.

also im using 3.1.4-snapshot.117 but got error while running :

bundling failed: Error: While trying to resolve module `react-native-notifications` from file `/Users/bobbyrinaldy/Project/React/Mobile/src/app.js`, the package `/Users/bobbyrinaldy/Project/React/Mobile/node_modules/react-native-notifications/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/bobbyrinaldy/Project/React/Mobile/node_modules/react-native-notifications/lib/dist/index.js`.

what should i do then ?

**Comment by nvnk3** [comment]
Its working fine after doing "Clean build folder"
