### ISSUE TITLE
Does not receive notification information on cold start (iOS)

### ISSUE THREAD

**Issue by emuen** [wix/react-native-notifications#58]
Hi all,

I want to use the plugin only for local notifications. I can schedule notifications and receive them in the notificationcenter. When the application is in background or closed and I tap a notification in the notificationcenter it does as expected: the application goes to the foreground and executes the code in my notificationOpened eventListener callback. 

However the callback argument only contains userInfo, when opened from background. **If the app is opened from cold state I get no information about the notification I have open.**  

> {"data": {}}

I first experienced the problem in my own project, running RN 41.2 and using RNNavigation. However I was able to replicate by installing your example app and firing a local notification. 

`let localNotification = NotificationsIOS.localNotification({
      alertBody: "Received local notificiation!",
      alertTitle: "Local Notification Title",
      alertAction: "Click here to open",
      soundName: "chime.aiff",
      category: "SOME_CATEGORY",
      userInfo: {link: 'drug:adrenaline_1489999'},
      fireDate: date.toISOString(),
    })`

I have only tested on iOS

Trying to debug the problem in remote debugger I get:

> RCTJSONStringify() encountered the following error: Invalid type in JSON write (UIConcreteLocalNotification)
Unhandled JS Exception: Cannot read property 'aps' of null

My guess is it probably related, but I do not know.

**Comment by jbolter** [comment]
Check this issue... sounds like the same problem to me:  https://github.com/wix/react-native-notifications/issues/35
