### ISSUE TITLE
Manual linking on Android no longer required

### ISSUE THREAD

**Issue by gavrichards** [wix/react-native-notifications#581]
The [instructions for setting this package up on Android](https://wix.github.io/react-native-notifications/docs/installation-android) say you must edit MainApplication.java and manually link the package.

However for me, this then results in this red screen error appearing:
> Native module RNBridgeModule tried to override RNNotificationsModule. Check the getPackages() method in MainApplication.java, it might be that module is being created twice.

Removing the lines mentions at the top of the instructions page resolves the issue.

When was this fixed, and can the instructions be updated?

<img width="524" alt="Screenshot 2020-04-21 17 19 02" src="https://user-images.githubusercontent.com/432315/79891186-8c77a200-83f8-11ea-9989-b306f8b4e950.png">

**Comment by amilaDulanjana** [comment]
@gavrichards  did you able to configure the library ?

**Comment by saczuac** [comment]
Same issue here

**Comment by andylukmawan** [comment]
this is my config and works fine

> Copy google-services.json to  ./android/app folder

**./android/build.gradle**

```
buildscript {
    ...
    }
    dependencies {
        ...
        classpath 'com.google.gms:google-services:4.0.0'
    }
}
```

**./android/app/build.gradle**
```
android {
   ...
    defaultConfig {
        ...
        multiDexEnabled true
    }
    ...
}

dependencies {
    implementation 'com.google.firebase:firebase-core:16.0.0'
    ...
}

...

apply plugin: 'com.google.gms.google-services'
```

**package.json**
```
"dependencies": {
    "hermes-engine": "^0.4.2-rc1",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-notifications": "^3.1.4"
},
```

adding custom hermes refer to #455

**Comment by gavrichards** [comment]
@andylukmawan mine mirrors yours, except I'm up to `com.google.gms:google-services:4.3.3` in ./android/build.gradle. Not sure if that makes any difference.

**Comment by kevin-ashton** [comment]
Anyone ever figure this out? I'm hitting the same issue. Changing to `4.3.3` didn't seem to make a difference.

**Comment by mrarlloyd** [comment]
This is kinda of a big change in a minor point release. I took me ages to understand & eventually undo parts of the android installation guide!
😢

**Comment by caseyli** [comment]
@mrarlloyd 's solution worked for me. Looks like the documentation needs some updating.
