### ISSUE TITLE
Display notification when app is in foreground

### ISSUE THREAD

**Issue by Daha62** [wix/react-native-notifications#584]
Is there a way how to display system notifications when app is in foreground?

**Comment by anisimov74** [comment]
@Daha62 please check [this](https://github.com/wix/react-native-notifications/issues/585) out.

**Comment by harveyconnor** [comment]
Works in snapshot build

**Comment by Daha62** [comment]
@harveyconnor, please could u provide some example?

**Comment by harveyconnor** [comment]
Its actually in the docs

**Comment by Daha62** [comment]
I got a notification icon and notification `Notifications.postLocalNotification(...)`, but how can i create a notification popup like in reacte-native-firebase 
`firebase.notifications().displayNotification`?

**Comment by harveyconnor** [comment]
On ios, set the { alert: true } when calling completion handler. Its all in the docs.

See here: https://wix.github.io/react-native-notifications/docs/getting-started#register-for-notification-events

```ts
Notifications.events().registerNotificationReceivedForeground((notification: Notification, completion) => {
      console.log(`Notification received in foreground: ${notification.title} : ${notification.body}`);
      completion({alert: false, sound: false, badge: false});
    });
```

Where it says
```ts
completion({alert: false, sound: false, badge: false});
```
You need to set to:
```ts
completion({alert: true, sound: false, badge: false});
```

**Comment by JulioOrellana** [comment]
`alert:true` still not working for me on 3.3.4

**Comment by javierojeda94** [comment]
`alert: true` is not working for me neither 

@harveyconnor any idea why this would be failing? 

using 3.2.1 with iOS 13.6

**Comment by harveyconnor** [comment]
no idea sorry
