### ISSUE TITLE
Android dead/killed app not receiving any notification, and in foreground/background banner now show

### ISSUE THREAD

**Issue by bobbyrinaldy** [wix/react-native-notifications#585]
Helo, im moving from React Native Push Notification to this package because there is a lot of issue on that package.

i have several question here :

1. How to show the banner of notification on Android (Not Testing on IOS) ? since we can customize the layout but still i cannot understand how to implement this one https://github.com/wix/react-native-notifications/wiki/Android:-Layout-Customization

2. In dead/killed states, im not receiving any notirifcation until i open the application it self. how can i manage this ?

**Code** : 

```js
class App extends Component {
    constructor(props) {
      super(props);
      this.state = {};
      this.pushNotificationListener();
      
      //Testing Local Push Notification but still NO BANNER appear
      Notifications.postLocalNotification({
          body: "Local notification!",
          title: "Local Notification Title",
          sound: "chime.aiff",
          silent: false,
          category: "SOME_CATEGORY",
          userInfo: { }
      });
    }

    pushNotificationListener = async () => {
      Notifications.getInitialNotification()
      .then((notification) => {
        console.log("Initial notification was:", (notification ? notification.payload : 'N/A'));
        })      
      .catch((err) => console.error("getInitialNotifiation() failed", err));

      Notifications.registerRemoteNotifications();

      Notifications.events().registerRemoteNotificationsRegistered((event: Registered) => {
          // TODO: Send the token to my server so it could send back push notifications...
          console.log("Device Token Received", event.deviceToken);
      });
      Notifications.events().registerRemoteNotificationsRegistrationFailed((event: RegistrationError) => {
          console.error(event);
      });
  
      Notifications.events().registerNotificationReceivedForeground((notification: Notification, completion) => {
        console.log(`Notification received in foreground: ${notification}`);

        completion({alert: true, sound: true, badge: true});
      });
  
      Notifications.events().registerNotificationOpened((notification: Notification, completion) => {
        console.log(`Notification opened: ${notification.payload}`);
        completion();
      });

      Notifications.events().registerNotificationReceivedBackground((notification: Notification, completion: (response: NotificationCompletion) => void) => {
        console.log("Notification Received - Background", notification.payload);
        // Calling completion on iOS with `alert: true` will present the native iOS inApp notification.
        completion({alert: true, sound: true, badge: false});
      });
    }
  }
```

What i have done so far ?

1.  I have tried to use `Master` Branch to see the update for this one but got Error while Running :

**Error** : 

```
bundling failed: Error: While trying to resolve module `react-native-notifications` from file `/Users/bobbyrinaldy/Project/React/Mobile/src/app.js`, the package `/Users/bobbyrinaldy/Project/React/Mobile/node_modules/react-native-notifications/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/bobbyrinaldy/Project/React/Mobile/node_modules/react-native-notifications/lib/dist/index.js`.
```

**Enviroment** 👍 

```json
    "@react-native-firebase/app": "6.7.1",
    "@react-native-firebase/messaging": "6.7.1",
     "react-native-notifications": "wix/react-native-notifications#master", // or "react-native-notifications": "^3.1.4",
```

**Comment by anisimov74** [comment]
@bobbyrinaldy 
1. The problem about [not showing notifications in drawer in a foreground mode](https://github.com/wix/react-native-notifications/pull/535#issuecomment-619048831). 
If you want them, use the version without Channels. [Check this out](https://github.com/wix/react-native-notifications/commits/master).
2. It's sounds like you don't have a **dist** folder inside **lib** folder. If you should install all modules inside **react-native-notifications** folder and then run `yarn build`

**Comment by bobbyrinaldy** [comment]
> @bobbyrinaldy
> 
> 1. The problem about [not showing notifications in drawer in a foreground mode](https://github.com/wix/react-native-notifications/pull/535#issuecomment-619048831).
>    If you want them, use the version without Channels. [Check this out](https://github.com/wix/react-native-notifications/commits/master).
> 2. It's sounds like you don't have a **dist** folder inside **lib** folder. If you should install all modules inside **react-native-notifications** folder and then run `yarn build`

Thanks for your references, 
`use the version without Channels` you mean i can use `master branch` ? sorry for asking, because i cannot understand what you mean.

but for dead state not receiving any notification ? what should i do ?

how about the tutorial about this one ? https://github.com/wix/react-native-notifications/wiki/Android:-Layout-Customization

**Comment by anisimov74** [comment]
@bobbyrinaldy 
1. you should use an older version or create a fork and [revert this change](lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java)
2.  [dead state not receiving any notification problem](https://github.com/wix/react-native-notifications/issues/572) 
3. I'm not a code owner, so can't say anything about the customization. Sorry

**Comment by bobbyrinaldy** [comment]
> @bobbyrinaldy
> 
> 1. you should use an older version or create a fork and [revert this change](lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java)
> 2. [dead state not receiving any notification problem](https://github.com/wix/react-native-notifications/issues/572)
> 3. I'm not a code owner, so can't say anything about the customization. Sorry

ahhh that clear for me, thanks for your time btw.
try to check if im can do something about it

**Comment by anisimov74** [comment]
@bobbyrinaldy i did 1). 
Don't forget to generate and push into your fork `dist` folder (It's ignored in `.gitignore`) if you are not going to publish into npm.

**Comment by bobbyrinaldy** [comment]
> @bobbyrinaldy i did 1).
> Don't forget to generate and push into your fork `dist` folder (It's ignored in `.gitignore`) if you are not going to publish into npm.

allright, thank in advance, very helpfull for me

**Comment by anisimov74** [comment]
@bobbyrinaldy just got an [answer](https://github.com/wix/react-native-notifications/pull/535#issuecomment-619064646) from the author of the change i've mentioned.
 I think it's easier to create a local notification when you are in the foreground mode to show it in a drawer.

**Comment by nikita-filimonau** [comment]
Hi everyone, I don't find better solution than ask my question here.
It looks like I do something wrong with my android (ios works fine).
For me:
- registerRemoteNotificationsRegistered
- registerNotificationOpened
- getInitialNotification
work good.
But:
- registerNotificationReceivedForeground
- registerNotificationReceivedBackground
have never triggered.

I think I put something wrong in AndroidManifest.xml (I have tried different variant but it still doesn't work).
Or problem occurs from using
- react-native-notification
- react-native-pusher-push-notifications
at the same time.

Please maybe someone have some ideas?

I use:
- "react-native-notifications": "^3.2.2",
- "react-native-pusher-push-notifications": "^2.4.0",
- "react": "16.9.0",
- "react-native": "0.61.5",

**Comment by anisimov74** [comment]
@nikita-filimonau i've learned that it's better all registration except `registerNotificationOpened` register as soon as possible. In my case i register they in an app constructor.

**Comment by nikita-filimonau** [comment]
@anisimov74 Hi, I do it in explained way (register all in constructor). Also I have tried to remove `registerNotificationOpened` but it doesn't help.

**Comment by anisimov74** [comment]
@nikita-filimonau how do you send messages? As far as I know is a difference between data or notification. In my case there were no difference. I tried to send test messages from the server (data) and from Firebase Console. Did you try sending from Firebase Console? 
It may at least give you an understanding what works and what doesn't.
I can also add that in  `SplashActivity.java` i had `intent.putExtras(this.getIntent());`. May be it can help.
This is my manifest part: 
```
<meta-data
          android:name="com.google.firebase.messaging.default_notification_icon"
          android:resource="@drawable/notification_icon"/>

      <meta-data
          android:name="com.google.firebase.messaging.default_notification_color"
          android:resource="@color/notification_icon_color"/>

**Comment by nikita-filimonau** [comment]
Ok, maybe it will be helpful for someone or just start some discussions )

Well, from my understanding the react-native-pusher-push-notifications handle notification first, so library react-native-notifications can't catch that.

Not the better decision but it will works before I find better solution.

I modified file PusherWrapper.java in react-native-pusher-push-notifications library to handle more information. The main problem was that library doesn't return info that send in data part of notification.
You can check changes here:
https://stackoverflow.com/questions/61985546/react-native-notification-foreground-messages/62093605#62093605

@anisimov74 Thanks for your support.

**Comment by nikita-filimonau** [comment]
Yeah, just a note. When I have deleted `react-native-pusher-push-notifications`
The library `react-native-notifications` worked properly.

**Comment by technyx-ali-rehman** [comment]
Hi, notifications work on some Android devices & some don't. Any clues ?
