### ISSUE TITLE
Non Removable Notification

### ISSUE THREAD

**Issue by manuelm3z** [wix/react-native-notifications#59]
Hello people, very useful package, but I wonder if there is any way to make a non-removable notification with the current api.

**Comment by pewh** [comment]
+1 need this very much like https://www.quora.com/How-do-i-create-a-permanent-ongoing-notification-on-android-that-only-shows-the-notification-icon-not-the-the-notification-card-itself

**Comment by samasmith89** [comment]
Any update on this?  I'd really like to be able to create an app that can be primarily run from the notifications tray, similar to Audible, Google Music, YouTube, etc.

**Comment by manuelm3z** [comment]
@samasmith89 When I used it, I modified the package and installed it locally. this file https://github.com/wix/react-native-notifications/blob/master/android/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java#L145 using the docs https://developer.android.com/reference/android/app/Notification.Builder.html#setOngoing(boolean)

**Comment by regalstreak** [comment]
bumping
