### ISSUE TITLE
Documentation and source code mismatch for React-Native with Typescript

### ISSUE THREAD

**Issue by ab5y** [wix/react-native-notifications#594]
I am trying to follow along with the documentation for implementing push notifications. 
I have reached this page: https://wix.github.io/react-native-notifications/docs/notifications-events

There's a method signature:
`Notifications.events().registerNotificationOpened((notification: Notification, completion: () => void, action: NotificationActionResponse)`

In the example code above there are three arguments. But the compiler keeps throwing an error, and I went into the source code to see what the issue was, and sure enough, in the `EventsRegistry.ts` class, the method signature is as follows:
`public registerNotificationOpened(callback: (response: NotificationResponse, completion: () => void) => void): EmitterSubscription`

Please let me know if there's an alternative set of documentation that would be more consistent.

**Comment by lukeramsden** [comment]
This stale bot is very annoying.

There's definitely some docs mismatch here, it's a little confusing to say the least.
