### ISSUE TITLE
[BUG] Notifications.events().registerNotificationOpened() Not returning action response

### ISSUE THREAD

**Issue by harveyconnor** [wix/react-native-notifications#596]
I have setCategories and added actions to the notifications. They are returning a response.actionIdentifier in native code however when using this library and listening to open events I don't get an object. I've done some inspection and it appears there is no action object being sent to the listener in js.

```js
Notifications.events().registerNotificationOpened((notification, completion, action) => {
  console.log(action) // <-- Logs `undefined`
})
```

I believe the object is being lost when parsing it in the `fromPayload` function.

And can the docs please be updated to match what is actually going on as they are still for v2.

**Comment by joaovpmamede** [comment]
@harveyconnor what version are you using?
Also does that method run on Android?

**Comment by harveyconnor** [comment]
3.1.4 ios 12

**Comment by bensie** [comment]
Had the same issue. It was fixed in #566.

**Comment by JulioOrellana** [comment]
this was fixed? I am not receiving object from `background`, only working on `foreground`

**Comment by Ajmal0197** [comment]
https://stackoverflow.com/a/62445342/9377254


**Issue fixed**

**Comment by ebaynaud** [comment]
action is still `undefined` on Android
