### ISSUE TITLE
[3.1.4.snapshot]Is there a way to unmount the listeners (i.e registerNotificationOpened() )

### ISSUE THREAD

**Issue by harveyconnor** [wix/react-native-notifications#599]
Currently I cannot find any js function that removes listeners. 
I'd like to removeListeners on component un-mount, as my screen fast refreshes in development it keeps creating listeners.
Is there a way to do this? If so please document it.

**Comment by jcarioti** [comment]
https://github.com/wix/react-native-notifications/issues/474

**Comment by jcarioti** [comment]
See the link above. I don't think it's documented...

**Comment by harveyconnor** [comment]
@jcarioti Thank you, will try that out
