### ISSUE TITLE
getInitialNotification()

### ISSUE THREAD

**Issue by amitdwix** [wix/react-native-notifications#6]
Need an API for retrieving [the initial notification](https://facebook.github.io/react-native/docs/pushnotificationios.html#getinitialnotification) from which app has been started.

This kind of API is required as `PushNotificationIOS.getInitialNotification()` only provides _raw_ notification data.

As a side-note, this API should consider the fact that the app can be either started by swiping a local notification OR a remote one, and the handling should be different (remote notifs should be "wrapped" with the internal `IOSNotification` class).

**Comment by lidanh** [comment]
Instead of a single initial notification, there's a background queue which stores all the notifications that have received until calling to `consumeBackgroundQueue`.

https://github.com/wix/react-native-notifications#background-queue-important

does it work for you?
