### ISSUE TITLE
How to set image for local notification   

### ISSUE THREAD

**Issue by girish54321** [wix/react-native-notifications#601]
sorry this is not an issues but still i want to know how can i set image url in local notification
thanks..
Notifications.postLocalNotification({
        body: "body",
        title: "title",
        extra: "data"
      });

**Comment by thuynt99** [comment]
Hi, I want to show image in local push? Have any solution? Can you fix it? @girish54321

**Comment by girish54321** [comment]
Hi @thuynt99 I am not using this package now plz use [react-native-push-notification](https://github.com/zo0r/react-native-push-notification)  this much better then this.

**Comment by thuynt99** [comment]
Hi @girish54321, Many Thanks! Can react-native-push-notification  display images for push notìication ios in FG???? 

> Hi @thuynt99 I am not using this package now plz use [react-native-push-notification](https://github.com/zo0r/react-native-push-notification) this much better then this.

**Comment by girish54321** [comment]
@thuynt99 i am not sure about ios image i used only in android.
