### ISSUE TITLE
Local notification data

### ISSUE THREAD

**Issue by amereii** [wix/react-native-notifications#602]
> Upon notification opening (tapping by the device user), all data fields will be delivered as-is).

```js
Notifications.postLocalNotification({
    title: "Local notification",
    body: "This notification was generated by the app!",
    extra: "data"
});
```

How can I set data fields for local notifications? `extra` and `data` not working

**Comment by danieloprado** [comment]
use payload prop, but sometimes you will receive payload twice like: notification.payload.paylod, be ware about it.
