### ISSUE TITLE
App crashes immediately after installing react-native-notifications

### ISSUE THREAD

**Issue by omerfaran** [wix/react-native-notifications#604]
Hello,

I installed the library using npm install, and since then the app crashes immediately upon lunching. When I remove the library, the app works fine.

Here is my dependencies:

  "dependencies": {
    "@react-native-community/async-storage": "^1.10.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.3.3",
    "@react-navigation/native": "^5.2.3",
    "@react-navigation/stack": "^5.2.18",
    "email-validator": "^2.0.4",
    "google-libphonenumber": "^3.2.9",
    "lodash": "^4.17.15",
    "moment": "^2.25.3",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-elements": "^2.0.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-image-picker": "^2.3.1",
    "react-native-image-resizer": "^1.2.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-modal": "^11.5.6",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.7.0",
    "react-native-vector-icons": "^6.6.0"

What should I do?
Thanks in advance

**Comment by ccanalesb** [comment]
Check the error with `adb logcat *:E` maybe could get a clue with that
