### ISSUE TITLE
Canceling local notification - buggy

### ISSUE THREAD

**Issue by Frans-L** [wix/react-native-notifications#608]
The documentation says that ```Notifications.postLocalNotification``` should return the id of the notification but it always returns ```undefined``` in iOS. I haven't tested Android. The id is needed to cancel the event.

A workaround is to create id manually. 

Creating an id manually is confusing: The id must be number with the create command ```Notifications.postLocalNotification(..., 100)``` but then, the id must be string with the cancel command ```Notifications.cancelLocalNotification("100")```.

So, the bug is that the command ```Notifications.postLocalNotification``` returns undefined.
A possible design flaw is that data type of the id changes from number to string between functions.

Here is the original issue, that has been closed by bot stale: https://github.com/wix/react-native-notifications/issues/481

**Comment by suyogshiftcare** [comment]
Same here. I am also facing this issue. Is there any workaround for it?

**Comment by ALPNP** [comment]
Same problem. Using a "crutch" with ID transfer is not a good idea. But I think this is the only option. The bot will close this problem...

**Comment by Frans-L** [comment]
Bump. The problem still exists.
