### ISSUE TITLE
NotificationsAndroid.requestPermissions()

### ISSUE THREAD

**Issue by facuacostag** [wix/react-native-notifications#61]
Hi! Is there a way to request permissions to the user to decline or accept notifications on Android? Because It seems that every time I open my app it's giving permissions without asking for them.

**Comment by nolan-m** [comment]
Android permissions work differently than iOS.  Android considered push notifications a normal permission and does not require you to ask permission.  

Please see https://developer.android.com/guide/topics/permissions/normal-permissions.html for more information.
