### ISSUE TITLE
Blank foreground notifications on android

### ISSUE THREAD

**Issue by joshgranttc** [wix/react-native-notifications#615]
We are still facing issues despite having updated to version 4.2.1 of this package.

I noticed #496 should have fixed this issue, however I am still seeing a blank notification in the foreground on android. (No logo, title or body).

For reference background notifications are completely fine. 
I can see the payload of the notification contains the following (I have blanked out the other parts of the object)
`{"gcm.notification.body": "test", "gcm.notification.e": "1", "gcm.notification.title": "Test Notification"}`

Any advice on this would be brilliant. I can't quite understand why I am not seeing the title and body of the notification when it is in the foreground. (Also seeing a grey square instead of the icon).

As I say in the background it is completely fine.

**Comment by geekdevs** [comment]
@joshgranttc I am having the same issue, were you able to solve it?

**Comment by andreialecu** [comment]
Had the same issue and this helped: https://github.com/zo0r/react-native-push-notification/issues/1287#issuecomment-576026273

It appears that a `data` property needs to be in the payload you use when sending the notification. Not sure if this is a recent change or not.

```
const payload = {
  notification: {
    title,
    body
  },
  data: {  // add the data property
    title,
    body
  }
};
``

**Comment by geekdevs** [comment]
@andreialecu Thank you, but I still cannot make it work for some reason. Background works without any issue, but foreground is just ignored. I see it is received in Metro logs, but it's not showing.

Did you need to configure anything else? I see notification channel might now be required on android, I also experimented with adding "android.permission.FOREGROUND_SERVICE" permission to app manifest - nothing helps.

Please advice.

**Comment by anlawyer** [comment]
@geekdevs We're facing the same issue in our app now using RNN v3.2.2: background notifications show up fine, but when the app is in the foreground on Android, nothing appears (it doesn't even show up in the app drawer), even though we are able to log out the notification object inside `registerNotificationReceivedForeground` callback. We're including both `notification` and `data` in the `payload`, but most of the tweaks to change payload or add things to `AndroidManifest` aren't helping at all. 

I think we'll try adding our own "MyFirebaseMessaging.java" service next, as recommended in this comment: https://github.com/wix/react-native-notifications/issues/525#issuecomment-599432511

**Comment by andreialecu** [comment]
This has been fixed in one of the recent merged PRs but it's not yet released. 

Changing the dependency in package.json to `"react-native-notifications": "3.2.2-snapshot.145"` should work though, in the mean time.

**Comment by anlawyer** [comment]
Thanks @andreialecu! We ended up implementing `postLocalNotification` from this library, as recommended from this comment: https://github.com/wix/react-native-notifications/issues/585#issuecomment-619104216. Essentially the same idea as what you suggested to implement your own message while the app is in the foreground. Using `postLocalNotification` solved the issue when foreground notifications didn't appear in the drawer (or anywhere) but still triggered the foreground callback.

**Comment by bossajie** [comment]
Hi guys, this comment in another issue works.
https://github.com/wix/react-native-notifications/issues/525#issuecomment-656585578

**Comment by JerakRus** [comment]
@anlawyer Hi! Can you tell us how you configured the display of images in the expanded local notification?
