### ISSUE TITLE
registerNotificationReceivedForeground does not trigger on Android

### ISSUE THREAD

**Issue by rene-vettons** [wix/react-native-notifications#626]
registerNotificationReceivedForeground works in iOS but not android.

`
Notifications.events().registerNotificationReceivedForeground((notification: Notification, completion) => {
      console.log(`Notification received in foreground: ${notification.title} : ${notification.body}`)
      completion({ alert: false, sound: false, badge: false })
    })
`

**Comment by omonk** [comment]
Hi @rene-vettons did you find any solution to this?

**Comment by rene-vettons** [comment]
just follow the guide [https://wix.github.io/react-native-notifications/docs/installation-android](android installation).

**Comment by rene-vettons** [comment]
> Hi @rene-vettons did you find any solution to this?

follow the guide [android installation](https://wix.github.io/react-native-notifications/docs/installation-android). =)

**Comment by riordanpawley** [comment]
@omonk did this work for you?
I'm struggling to get it to work myself. I feel like there is an android manifest step missing or something.
