### ISSUE TITLE
iOS: cannot receive first push notification when app opened in foreground 

### ISSUE THREAD

**Issue by Daha62** [wix/react-native-notifications#627]
https://github.com/wix/react-native-notifications/issues/508 - this issue is closed, but bug is still remains in react-native-notifications: 3.2.2

`      Notifications.events().registerNotificationReceivedForeground((notification, completion) => {
        completion({alert: true, sound: false, badge: false})
      })`

it always triggers when notification is sent but not always show system notifications

**Comment by taduyde** [comment]
Hi @Daha62,
Did you test it on Android device or iOS device?

**Comment by Daha62** [comment]
@taduyde, Android device is OK, problem is just on  IOS

**Comment by taduyde** [comment]
> Hi @taduyde,
> 
> Android device is OK, problem is just on IOS

hmm, it's so strange, but I think you have problem with your setup of the plugin. From my side. This plugin work well on iOS.

**Comment by Daha62** [comment]
@taduyde, could u please show what u have in `AppDelegate.m` file?
cause i've done all that is written here https://wix.github.io/react-native-notifications/docs/getting-started#ios

also I have: 
```
constructor(props) {
    super(props);
    Notifications.registerRemoteNotifications();
    Notifications.events().registerNotificationReceivedForeground((notification: Notification, completion) => {
      console.log(`Notification received in foreground: ${notification.title} : ${notification.body}`);
      completion({alert: true, sound: false, badge: false});
    });
  }

**Comment by taduyde** [comment]
Hi @Daha62, 
Before I show you AppDelegate.m, I have a question. For the app in the background or app is "dead" you still received the notification or not?

**Comment by Daha62** [comment]
yep, I still received them

**Comment by taduyde** [comment]
Here is my AppDelegate.m, it's just simple.

#import "RNNotifications.h"

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
 [RNNotifications startMonitorNotifications];
}

- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  [RNNotifications didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}

- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error {
  [RNNotifications didFailToRegisterForRemoteNotificationsWithError:error];
}

**Comment by Daha62** [comment]
thank u, unfortunately it's the same)

**Comment by geekdevs** [comment]
I have the same problem. First notification fails to show, afterwards everything's fine.

**Comment by nerdmv** [comment]
I'm using "react-native-notifications": "^3.2.2" and facing the sam issue. As a workaround I'm just firing `postLocalNotification` twice on ios for the first notification received. Need a better solution for this. Please help!

**Comment by nerdmv** [comment]
this worked as well https://github.com/wix/react-native-notifications/issues/508#issuecomment-589580756

**Comment by miquelferrandiz** [comment]
Also seeing this same issue. First notification doesn't display, although the notification event happens and the correct notification data is received by the event handler.

Notifications after the first do show up.

A workaround is to dispatch a local notification immediately as the user registers - this notification won't show up and will make it so subsequent notifications do show up.

**Comment by kostiantyn-solianyk** [comment]
same issue, any updates

**Comment by egemenuzunali** [comment]
Just came across this issue, happens to me as well. First notification on foreground nothing, second shows.

**Comment by reeinohio** [comment]
I'm experiencing the same issue as well. Very first notification isn't received on iOS foreground but succeeding ones are received.
