### ISSUE TITLE
Error on ios: deviceToken not a valid FCM Registration Token

### ISSUE THREAD

**Issue by davidrojo** [wix/react-native-notifications#629]
Hello,

I am trying to integrate this library into an app, bug I am having some issues integrating it on ios. 

On android everything works fine. The app receives the deviceToken in the "onDeviceRegistered" function and I send it via http request to the server to store it. Later from the server I am able to send notifications and the app receives them correctly.

But now I am configuring it on IOs and the token I receive in the "onDeviceRegistered" function is different than the ones received in android:

Android token is like: cw8YnIYJzFU:APA91bEnbrNPCIUpOYzVYdhdp2BOHRNffYsoSnVC5hbBS-dPjy-kC80XIPNlcaGQzANVcWrtsTbOY0NBumKP6BAnTM7l-usgjK_6yPgpTjWudYkI3AFhudMMmMLQv2jIkd4nVNUGZVBS
Ios token is like: 37b2351c01be868a96bbed3d902219db417fa153323e2524b23b0dd14bf5ea02

And when I try from the server to send a notification to an ios device, I receive the following error: The registration token is not a valid FCM registration token.

I am missing something?

**Comment by davidrojo** [comment]
I finally moved my developement to [react-native-firebase](https://github.com/invertase/react-native-firebase/tree/master/packages/messaging) and everything worked fine.

**Comment by b777k** [comment]
This solution solved the issue  [https://github.com/wix/react-native-notifications/issues/408#issuecomment-656030467]( https://github.com/wix/react-native-notifications/issues/408#issuecomment-656030467)
