### ISSUE TITLE
Empty Notification While App is Foregrounded

### ISSUE THREAD

**Issue by osamausmani** [wix/react-native-notifications#630]
I have integrated react-native-notifications in my app. I am receiving token and notifications. But the issue I am getting is when the app is in the foreground the notifications look empty but when in background mode it displays the text. Check my code here is there any issue from my side.

  ```
  Notifications.events().registerNotificationReceivedForeground((notification, completion)=> {
      console.log("Notification Received - Foreground", notification.payload);
      this.NotifCounterUpdate()
      completion({ alert: false, sound: false, badge: false });
    })

    Notifications.events().registerNotificationOpened((notification, completion) => {
      completion();
    });

    Notifications.events().registerNotificationReceivedBackground((notification, completion) => {
      console.log("Notification Received - Background", notification.payload);
      this.NotifCounterUpdate()
      completion({ alert: false, false: true, badge: false });
    });
```

Also, I am using a bell icon and counter to display a counter alert in the app which works fine in the foreground but it won't work in background mode. the counter code is under this.NotifCounterUpdate() 

Image attached: https://ibb.co/rcHH6Vh

Is anything I am missing or its the library issue please help me out?

I am using
"react": "16.9.0",
"react-native": "0.61.5",
"react-native-notifications": "^3.1.2",

**Comment by geekdevs** [comment]
This is duplicate of https://github.com/wix/react-native-notifications/issues/615

Some people claim they could make it work with different payload structure (see issue), but nothing worked for me so far.

Please let me know if you find something.
