### ISSUE TITLE
Androd - Set channel ID for local notification

### ISSUE THREAD

**Issue by eXigentCoder** [wix/react-native-notifications#631]
Firstly, thanks for the awesome library!

I am trying to get my local Android notification to use all the same settings in the channel I use for remote notifications (Sound, vibration pattern, icon, etc). Currently it is using the built in channel that gets created by the library itself.

Currently when calling `Notifications.postLocalNotification` for Android there seems to be no way to pass in the `channelId`, so it uses the default one specified in the file `~/react-native-notifications/lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java` line 143
I.e.
```
String CHANNEL_ID = "channel_01";
String CHANNEL_NAME = "Channel Name";
```
Once a channel has been created in Android there is no way to change the settings (Other than the display name and description I believe)

I am already calling:
```
Notifications.setNotificationChannel(channel);
Notifications.android.setNotificationChannel(channel);
```
Before calling `Notifications.postLocalNotification` and can confirm that it doesn't use the above channel.

Would it please be possible to add a parameter to `Notifications.postLocalNotification` so that you can optionally specify which channel to use?

**Comment by eXigentCoder** [comment]
*Bump*

**Comment by C-Flatla** [comment]
I realize this is a bit late to the party, but we solved this by passing in `android_channel_id` to `postLocalNotification`. There are type errors, but it works 😄 

```
Notifications.postLocalNotification({
      identifier,
      payload,
      sound,
      badge,
      type,
      thread,
      title,
      body,

      // eslint-disable-next-line @typescript-eslint/naming-convention
      android_channel_id: "super-cool-channel",
    } as Notification);
```
