### ISSUE TITLE
App crashes when not configured with firebase

### ISSUE THREAD

**Issue by shrynshjain** [wix/react-native-notifications#632]
I only want to use local notifications, but the app crashes as soon as i open it.
I started a new project from scratch
dependencies
`
"react": "16.11.0",
"react-native": "0.62.2",
"react-native-notifications": "3.1.3"
`
![image](https://user-images.githubusercontent.com/30545482/85139105-920b3000-b261-11ea-85d8-d89e3ef08b80.png)
error from logcat

to reproduce
create a react-native app using
`npx react-native init notifications`
add react-native-notifications
and run the app

**Comment by nemoNoboru** [comment]
I have exactly the same problem. Does anybody was able to fix it?

**Comment by Vadimienne** [comment]
Same problem here. I followed installation instructions, notifications do actually work but app crashes in dev and prod with this error. 
I have no intention using Firebase. Need only local notifications for my current project

**Comment by matthieugayon** [comment]
Same here ... @Vadimienne, @nemoNoboru have you guys found a workaround ?

**Comment by Vadimienne** [comment]
@matthieugayon 
Take a look at [this thread](https://github.com/zo0r/react-native-push-notification/issues/1574#issuecomment-722068919) from another notification lib. 
In short it's power saving policies of samsung and xiaomi. 
You can try and contact them on forum so they will consider to whitelist your app.
Or you can just go to settings and set battery saving options to "No restrictions" (Xiaomi).
The idea for Samsung is the same. 
After that notifications work perfectly.
