### ISSUE TITLE
How to get the device ID in IOS

### ISSUE THREAD

**Issue by arunkumarrmrj** [wix/react-native-notifications#64]
How to get device id in IOS , Any one let  me know how to configuration to get device id
I've use 

"dependencies": {
    "native-base": "^0.5.2",
    "react": "15.4.2",
    "react-native": "0.42.0",
    "react-native-loading-spinner-overlay": "^0.4.1",
    "react-native-modal-datetime-picker": "^4.0.0",
    "react-native-notifications": "^1.1.10",
    "react-native-root-toast": "^1.0.3",
    "react-native-router-flux": "3.38.0",
    "react-native-vector-icons": "^4.0.0"
  },

**Comment by lodev09** [comment]
It's documented here:
https://github.com/wix/react-native-notifications#register-to-push-notifications

```
NotificationsIOS.addEventListener('remoteNotificationsRegistered', this.onPushRegistered.bind(this));
```

```
onPushRegistered(deviceToken) {
	console.log("Device Token Received", deviceToken);
}
```

**Comment by cristianonescu** [comment]
everything works fine, but this event does not get triggered for me. is there anything to do? :(

**Comment by matthewfbenjamin** [comment]
@cristianonescu did you ever solve this issue?

**Comment by cristianonescu** [comment]
@matthewfbenjamin yes. I used a different lib: https://github.com/calcazar/react-native-push-notification-CE
