### ISSUE TITLE
Modify the content of a remote notification on iOS in the background

### ISSUE THREAD

**Issue by alexbrazier** [wix/react-native-notifications#648]
I'm trying to modify the content of a remote notification on iOS in the background, e.g. change the title and body, or decrypt a message.

This library says it has the feature but I can't see any docs to show how this is done?:
> Interactive notifications (allows you to provide additional functionality to your users outside of your application such as action buttons)

### Docs

The event for `registerNotificationReceivedBackground` shows this in the docs, but it's not clear if it is possible to modify the message before sending?

```js
Notifications.events().registerNotificationReceivedBackground((notification: Notification, completion: (response: NotificationCompletion) => void) => {
  console.log(JSON.stringify(notification.payload));

  // Calling completion on iOS with `alert: true` will present the native iOS inApp notification.
  completion({alert: true, sound: true, badge: false});
});
```

### Native Implementation
Natively I'm able to achieve this using a Notification Service Extension, but it would mean I need to setup a bridge if I want access to the javascript (e.g. to get the correct message)

https://developer.apple.com/documentation/usernotifications/modifying_content_in_newly_delivered_notifications

<details>
<summary>Native code example</summary>

```swift

import UserNotifications
class NotificationService: UNNotificationServiceExtension {
    var contentHandler: ((UNNotificationContent) -> Void)?
    var bestAttemptContent: UNMutableNotificationContent?

    override func didReceive(_ request: UNNotificationRequest, withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void) {
        self.contentHandler = contentHandler
        bestAttemptContent = (request.content.mutableCopy() as? UNMutableNotificationContent)
      
      bestAttemptContent?.title = "Overridden title"
      bestAttemptContent?.body = "Custom body"
      if let result = bestAttemptContent  {
        contentHandler(result)
      }
    }
}

```
</details>

A related issue is here: https://github.com/wix/react-native-notifications/issues/555

**Comment by neoswallow** [comment]
AFAIK, you cannot modify the content of remote notification.
You can, however, send local notification after receiving remote notification by sending silent notification.
You have more control on local notification than remote notification.

**Comment by alexbrazier** [comment]
I ended up solving this by implementing the `UNNotificationServiceExtension` natively as described in the issue description so going to close this.
