### ISSUE TITLE
Android Compile Error

### ISSUE THREAD

**Issue by jihokim2** [wix/react-native-notifications#649]
I met android compile error.
react-native: 0.63.2
react-native-notifications: 3.3.0

Log is like this. react-native-notifications: 3.2.2 works good.

1: Task failed with an exception.
-----------
* Where:
Build file '/node_modules/react-native-notifications/lib/android/app/build.gradle' line: 4

* What went wrong:
A problem occurred evaluating project ':react-native-notifications'.
> Plugin with id 'kotlin-android' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-notifications'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

**Comment by Bilal-Abdeen** [comment]
Based on a suggestion for another library producing a similar error, I have applied the following changes. They seem to work. The following code demonstrates ONLY the changes. I am NOT suggesting deleting the rest of the code in the file. 
File: `android/build.gradle`
```
buildscript {
	ext {
		minSdkVersion = 21 // change this one from 16 to 21 
		kotlinVersion = "1.3.72" // add this line 
	}

	dependencies {
		classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion" // add this line 
	}
}
```

**Comment by chenweigh** [comment]
It do not work.
The problem: `Received close_notify during handshake`

**Comment by Charlicus** [comment]
Same issue for me... RN  0.63.2, react-native-notifications 3.3.2

**Comment by aleluis777** [comment]
Same issue for me.

RN 0.63.2
react-native-notifications 3.3.2

**Comment by Cchumi** [comment]
Same issue for me 

RN 0.63.2
React native notifications 3.3.2

**Comment by comvenger-brandon** [comment]
> Based on a suggestion for another library producing a similar error, I have applied the following changes. They seem to work. The following code demonstrates ONLY the changes. I am NOT suggesting deleting the rest of the code in the file.
> File: `android/build.gradle`
> 
> ```
> buildscript {
> 	ext {
> 		minSdkVersion = 21 // change this one from 16 to 21 
> 		kotlinVersion = "1.3.72" // add this line 
> 	}
> 
> 	dependencies {
> 		classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion" // add this line 
> 	}
> }
> ```

Dropping Android 4 support is no solution for us.

Why was this changed? The docs do not include any information and there are no changelogs.

**Comment by Alaa-Ben** [comment]
Same issue for me

RN 0.63.2
React native notifications 3.3.2

**Comment by AndreasGS** [comment]
Same for me.
RN 0.62.2
React native notifications 3.3.2

**Comment by amirulasrof** [comment]
Same for me. 
RN 0.63.2
React native notifications 3.3.2

**Comment by CarbonyDK** [comment]
Same for me.
RN 0.63.2
React native notifications 3.3.2

**Comment by LouisJS** [comment]
Same for me
RN 0.63.2
React native notifications 3.3.2

Issue:

`ERROR: Plugin with id 'kotlin-android' not found.`

**Comment by janoist1** [comment]
+1

**Comment by Bilal-Abdeen** [comment]
@clamiax Try the following
1. cd <proj_folder>/android  
2. gradlew clean 
3. cd .. 
3. npx react-native run-android

**Comment by clamiax** [comment]
@Bilal-Abdeen I already tried but with no luck. The app keep crashing on startup.

**Comment by riordanpawley** [comment]
+1

**Comment by SavageWilliam** [comment]
+1

**Comment by lchenfox** [comment]
The same issue +1.

RN 0.63.2
React native notifications 3.3.2

**Comment by HDDRT** [comment]
Same for me

**Comment by axeljeremy7** [comment]
in my case:
"react-native": "0.61.5",
 "react-native-notifications": "^3.3.4",
it is working for me fine so far.

```buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 24
        compileSdkVersion = 29
        targetSdkVersion = 29
        appCompatVersion = "1.0.2"
        googlePlayServicesVersion = "+"
        kotlinVersion = "1.3.72" 
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath 'com.google.gms:google-services:4.3.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion" 
    }
}```

**Comment by HackerTon** [comment]
@comvenger-brandon 

Your solutions works in my application.

**version**
```
"react-native": "0.63.2"
"react-native-push-notification": "^5.1.1"
```


**android/build.gradle**
```
buildscript {
    ext {
        // googlePlayServicesVersion = "+"
        // firebaseMessageVersion = "+"
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        kotlinVersion = "1.3.72"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
        classpath("com.google.gms:google-services:4.3.3")
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

**Comment by danielwinkler** [comment]
> "react-native-push-notification": "^5.1.1"

you are using a different library ;-) ?

**Comment by HackerTon** [comment]
@danielwinkler ops, my bad. But the solutions works.

**Comment by danielwinkler** [comment]
I am using the same config as HackerTon, after adding kotlin to the classpath everything works fine 🕺

**Comment by CaoThien96** [comment]
> @Bilal-Abdeen
> 
> Your solutions works in my application.
> 
> **version**
> 
> ```
> "react-native": "0.63.2"
> "react-native-notifications": "^3.3.4"
> ```
> 
> **android/build.gradle**
> 
> ```
> buildscript {
>     ext {
>         // googlePlayServicesVersion = "+"
>         // firebaseMessageVersion = "+"
>         buildToolsVersion = "29.0.2"
>         minSdkVersion = 21
>         compileSdkVersion = 29
>         targetSdkVersion = 29
>         kotlinVersion = "1.3.72"
>     }
>     repositories {
>         google()
>         jcenter()
>     }
>     dependencies {
>         classpath("com.android.tools.build:gradle:3.5.3")
>         classpath("com.google.gms:google-services:4.3.3")
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     }
> }
> ```

The solutions works. Thank you

**Comment by SaeedZhiany** [comment]
> Based on a suggestion for another library producing a similar error, I have applied the following changes. They seem to work. The following code demonstrates ONLY the changes. I am NOT suggesting deleting the rest of the code in the file.
> File: `android/build.gradle`
> 
> ```
> buildscript {
> 	ext {
> 		minSdkVersion = 21 // change this one from 16 to 21 
> 		kotlinVersion = "1.3.72" // add this line 
> 	}
> 
> 	dependencies {
> 		classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion" // add this line 
> 	}
> }
> ```

I don't get it, Why we should drop support for android versions 14-20 just because of react-native-notification? 😕

**Comment by SaeedZhiany** [comment]
> Based on a suggestion for another library producing a similar error, I have applied the following changes. They seem to work. The following code demonstrates ONLY the changes. I am NOT suggesting deleting the rest of the code in the file.
> File: `android/build.gradle`
> 
> ```
> buildscript {
> 	ext {
> 		minSdkVersion = 21 // change this one from 16 to 21 
> 		kotlinVersion = "1.3.72" // add this line 
> 	}
> 
> 	dependencies {
> 		classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion" // add this line 
> 	}
> }
> ```

@Bilal-Abdeen
I don't get it, Why we should drop support for android versions 14-20 just because of react-native-notification? 😕

**Comment by origamih** [comment]
Please keep this open. Not resolved yet.

**Comment by SaeedZhiany** [comment]
شسی

**Comment by SaeedZhiany** [comment]
asdasd

**Comment by wiserdivisor** [comment]
Don't close this issue, it isn't resolved yet.
There are many libraries in React-Native that are giving me the same error :
```
null is not an object (evaluating '<library name>')
```

The solution given by @Bilal-Abdeen worked for me. With some problems :
`yarn react-native run-android` DID NOT WORK.
I had to do `npx react-native run-android`
App kept crashing at first, to the point where Android Emu literally told me that `This App keeps crashing`
Later when I restarted the app it worked as expected. But I have a feeling that something is unstable.
This is just a work-around and I must say I am glad it worked because I have been stuck on this for about 3-4 days now.

Anyways, if it helps anyone, here's my code ::
```
  import { StatusBar } from 'expo-status-bar';
  import React from 'react';
  import { StyleSheet, Text, View, Button } from 'react-native';
  import { Notifications } from 'react-native-notifications';
  
  function notifShow(){
    Notifications.postLocalNotification({
      title: "Local notification",
      body: "This notification was generated by the app!",
      extra: "data"
    });
  }
  
  export default function App() {
  
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
        <Button title='Show Notif' onPress={()=>notifShow()}/>
        <StatusBar style="auto" />
      </View>
    );
  }
  
  const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
    },
  });
```

Here are the steps I took :
```
> expo init
>bare workflow
>yarn add react-native-notifications
>Make changes to App.js with above given code.
>Add the code below to MainApplication.java :::
import com.wix.reactnativenotifications.RNNotificationsPackage;
>yarn does the auto linking for me so I don't have to check.
>Make changes as said by Bilal and it now looks like this :::
    buildscript {
        ext {
            buildToolsVersion = "29.0.2"
            minSdkVersion = 21
            compileSdkVersion = 29
            targetSdkVersion = 29
            kotlinVersion = "1.3.72"
        }
        repositories {
            google()
            jcenter()
        }
        dependencies {
            classpath("com.android.tools.build:gradle:3.5.3")
            classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
    
            // NOTE: Do not place your application dependencies here; they belong
            // in the individual module build.gradle files
        }
    }
>Open one terminal. Navigate to project.
>yarn start
>Open another terminal. Navigate to project.
>npx react-native run-android
>App Crashes at first.
>Then runs properly. For now.
```

Here's my dependencies in the package.json :::
```
    "dependencies": {
        "expo": "~40.0.0",
        "expo-splash-screen": "~0.8.0",
        "expo-status-bar": "~1.0.3",
        "expo-updates": "~0.4.0",
        "react": "16.13.1",
        "react-dom": "16.13.1",
        "react-native": "~0.63.4",
        "react-native-gesture-handler": "~1.8.0",
        "react-native-notifications": "^3.4.2",
        "react-native-reanimated": "~1.13.0",
        "react-native-screens": "~2.15.0",
        "react-native-unimodules": "~0.12.0",
        "react-native-web": "~0.13.12",
        "tslib": "^2.1.0"
      },
```

I have been pulling my hairs out behind this for at least 4 days by now,
I hope it works out properly for the ones who come after me.

**Comment by scarlehoff** [comment]
Yes, this issue should not be closed. It's very much still happening.

**Comment by kesha-antonov** [comment]
Did anybody find any solution better than hardcoding version?

**Comment by Haris-Noori** [comment]
@Bilal-Abdeen  and now it says:
```
A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /home/haris/Documents/React-Native/soft-ui-react-native-main/android/app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml:59: AAPT: error: resource drawable/notification_icon (aka io.android.client:drawable/notification_icon) not found.
```

**Comment by JeronimasDargis** [comment]
Any updates?

**Comment by rafwell** [comment]
This problem remains. For me the solution of @SaeedZhiany was worked, but I've changed the kotlinVersion to `kotlinVersion = "1.5.31"` I think we have some conflict with react-native-screens.


```
"react-native": "0.65.1",
"react-native-screens": "^3.7.2",
"react-native-notifications": "^4.1.2",
```

**Comment by herhu** [comment]
same problem 

    "react": "17.0.2",
    "react-native": "0.66.1",
    "react-native-notifications": "^4.1.2",

**Comment by amitmaurya0** [comment]
comment out 
// apply plugin: 'kotlin-android'
// apply plugin: 'kotlin-android-extensions'

inside app/build.gradle file.

**Comment by vendeza** [comment]
Maybe these settings is useful: [react-native-notifications/blob/master/example](https://github.com/wix/react-native-notifications/blob/master/example/android/build.gradle) . 

in android/build.gradle file:

```
buildscript {
    ext{
        androidGradlePluginVersion = '4.0.0'
        androidSdkVersion = 30
        androidMinSdkVersion = 21
        kotlinVersion = "1.3.61"
        kotlinStdlib = "kotlin-stdlib-jdk8"
        detoxKotlinVersion = kotlinVersion
        googleServices = "4.3.3"
  }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        ...
        classpath "com.android.tools.build:gradle:$androidGradlePluginVersion"
        classpath "com.google.gms:google-services:$googleServices"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
         ...
    }
}
```

You may  needed to play around with versions. It's related to other dependencies in your project.

Unfortunately, I wasn't able to compatible `react-native-notification` with my other dependencies. It's seems I need to use `react-native-push-notifications`
