### ISSUE TITLE
callback when user taps local notification

### ISSUE THREAD

**Issue by manawaraquevix** [wix/react-native-notifications#650]
I looking to receive a callback when user taps local notification. I am not able to figure out from wiki. This is already asked in issue #154 , but not answered.

**Comment by themarveldev** [comment]
@manawaraquevix , Hi I am also facing same issue on iOS when user taps local notification, I am not getting any callback when app is opened or in background. Have you figured it out yet?

**Comment by miquelferrandiz** [comment]
I had this issue and believe it stems from that the notification payload is JSON stringified, and JSON stringify isn't compatible with function types.

So when trying to pass in a callback function to userInfo, it was returned as null. Not sure if this is the same issue you are experiencing though.

The solution for me was to define a dictionary with callback function corresponding to the notification category, then look up that callback function using the notification category upon receiving the notification.
