### ISSUE TITLE
[question]: How to integrate this with firebase?

### ISSUE THREAD

**Issue by bhaskardabhi** [wix/react-native-notifications#655]
I was able to setup the library and it is working fine with local notifications for Android and iOS. 

How can i integrate this with Firebase so that it can work with android as well as with iOS? 

I am total newbie so pardon my stupid question. Basically, I want to make sure i push to single source for notification from backend. that single source handles the notification sending to mobile app.

I went through couple of questions and it confused me.

**Comment by juanpablogd** [comment]
You can see this post: https://dev.to/jakubkoci/react-native-push-notifications-313i

**Comment by Nehal-29** [comment]
@bhaskardabhi  Hey 
were you able to do this?
I get notifications when app is in background or quit state but not when it is in foreground.
