### ISSUE TITLE
registerRemoteNotificationsRegistered is not getting called for iOS

### ISSUE THREAD

**Issue by bhaskardabhi** [wix/react-native-notifications#659]
registerRemoteNotificationsRegistered event is working fine for Android but it is not working for iOS. I have checked that permission for notification is enabled fo the app and still issue is happening.

I did some debugging and found below things:

- In `node_modules/react-native-notifications/lib/dist/NotificationsIOS.js ` line no 24 `this.commands.requestPermissions()` is returning undefined

I am not sure if that is fine. Also I am using my Apple account (not developer account) for as signin account. Not sure if that is the issue.

**Comment by yogevbd** [comment]
`requestPermissions` shouldn't return anything. You should receive `RemoteNotificationsRegistered` event or `RemoteNotificationsRegistrationFailed`.

Duplicate of #558. Let's discuss there
