### ISSUE TITLE
iOS Archived doesn't compile because a Semantic Issue `Unknown receiver 'RNNotifications' did you mean 'UNNotification'?` On Latest RN 0.63.2

### ISSUE THREAD

**Issue by AugustoAleGon** [wix/react-native-notifications#662]
This is my system information:

`System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 907.69 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2`

I am testing in a whole new project just in case it was a background incompatibility but it seems that the problem is the same.

This are my logs:

`AppDelegate.m:35:4: Unknown receiver 'RNNotifications'; did you mean 'UNNotification'?`

**Comment by AugustoAleGon** [comment]
@guyca  I will appreciate your help.

**Comment by dhoncrisley** [comment]
same problem here. I can run app on devices, but not archive.

some prints of errors
![Captura de Tela 2020-08-29 às 09 51 28](https://user-images.githubusercontent.com/24300982/91637215-5c12c680-e9dd-11ea-8bab-2ba554b95762.png)
![Captura de Tela 2020-08-29 às 09 52 16](https://user-images.githubusercontent.com/24300982/91637217-5f0db700-e9dd-11ea-861f-5faf6cfdcbe6.png)

**Comment by azelaya6** [comment]
same here, anyone has a solution? for me its only on xcode 12

**Comment by AugustoAleGon** [comment]
@azelaya6 I haven't found any solution. I had the same problem in Xcode 11.7 and after upgrading is the same.

**Comment by paddlefish** [comment]
Make sure that your `#import "RNNotifications.h"` is below the block of code that starts with `#ifdef FB_SONARKIT_ENABLED` and ends with `#endif` .  Otherwise RNNotifications will not be included in release configuration builds.

It should look like this:

```
#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

#import "RNNotifications.h"
```

**Comment by AugustoAleGon** [comment]
This solved my problem. But I got another archived problem related to RN 0.63.2 😢

**Comment by zachnicoll** [comment]
@paddlefish 's answer should be added to the official documentation!!
