### ISSUE TITLE
Android Body Text Truncated

### ISSUE THREAD

**Issue by djpetenice** [wix/react-native-notifications#663]
I've been testing out Android Local Notifications which are working.

The issue I'm having is my body text is getting truncated and isn't displaying fully and there's no way to expand the notification - if you tap it it disappears - any ideas why that's the case?

Also I don't really understand what what the extra key does in the example below - isn't doing anything as far as I can see:

Notifications.postLocalNotification({
    title: "Local notification",
    body: "This notification was generated by the app!",
    extra: "data"
});

The docs are a little light on explanation.

**Comment by djpetenice** [comment]
Looking at the Android docs you can implement a style for BigText - is this possible at all? https://developer.android.com/reference/android/app/Notification.BigTextStyle

**Comment by djpetenice** [comment]
Think I'm going to have to look at a different option. It's nearly there for me in terms of functionality but there's not really any documentation or support for Android.

**Comment by djpetenice** [comment]
I've found a solution to the issue. You need to add this to the PushNotificaytions.java:

**.setStyle(new Notification.BigTextStyle()**

 ```
final Notification.Builder notification = new Notification.Builder(mContext)
                .setContentTitle(mNotificationProps.getTitle())
                .setContentText(mNotificationProps.getBody())
                .setContentIntent(intent)
                **.setStyle(new Notification.BigTextStyle()**
                 .bigText(mNotificationProps.getBody()))
                .setDefaults(Notification.DEFAULT_ALL)
                .setAutoCancel(true);
```

**Comment by canven** [comment]
It is important ,  is It possible to add in master branch.

**Comment by bdiallo** [comment]
@djpetenice thanks for your solution it's working for me too. @DanielEliraz @wixmobile @yedidyak is it possible to add in master branch please?

**Comment by Kathir2002** [comment]
> I've found a solution to the issue. You need to add this to the PushNotifications.java within the Notification Builder:
> 
> **.setStyle(new Notification.BigTextStyle().bigText(mNotificationProps.getBody()))**
> 
> ```
> final Notification.Builder notification = new Notification.Builder(mContext)
>                .setContentTitle(mNotificationProps.getTitle())
>                .setContentText(mNotificationProps.getBody())
>                .setContentIntent(intent)
>                .setStyle(new Notification.BigTextStyle()
>                 .bigText(mNotificationProps.getBody()))
>                .setDefaults(Notification.DEFAULT_ALL)
>                .setAutoCancel(true);
> ```

I have one doubt, I am using @notifee/react-native for notification. Which file i need to add these lines?
