### ISSUE TITLE
iOS: `Notifications.ios.requestPermissions()` is nonexistent

### ISSUE THREAD

**Issue by kazushisan** [wix/react-native-notifications#664]
The API mentioned in https://wix.github.io/react-native-notifications/api/ios-api#requestpermissions seems to be nonexistent.  

Is the documentation outdated? If so, are there any options to show a prompt requesting permission for notifications in iOS?

**Comment by yogevbd** [comment]
It is outdated. You should use `Notifications.registerRemoteNotifications()` as it will request permissions on iOS and refreshToken on Android.

Will fix the docs today. Thanks!

**Comment by kazushisan** [comment]
Thank you!

**Comment by benpeke** [comment]
It still appears here: https://wix.github.io/react-native-notifications/api/ios-api#requestpermissions
