### ISSUE TITLE
[DOCUMENTATION] Outdated for registerNotificationReceivedBackground

### ISSUE THREAD

**Issue by hannojg** [wix/react-native-notifications#665]
Hello,

I have just upgraded the notification lib to the newest version. I am using typescript and the `registerNotificationReceivedBackground` seems to have changed which isn't reflected in the documentation.

There are two examples for `registerNotificationReceivedBackground` 

* https://wix.github.io/react-native-notifications/docs/notifications-events
* https://wix.github.io/react-native-notifications/api/general-events#registernotificationreceivedbackground

In both cases the old `completion` callback is used. The `response` parameter has as type `NotificationBackgroundFetchResult` which only accepts an enum. Thus the:

```javascript
  // Calling completion on iOS with `alert: true` will present the native iOS inApp notification.
  completion({alert: true, sound: true, badge: false});
```
does not work anymore.

I don't know what to pass to the completion callback. Please help.

**Comment by neoswallow** [comment]
You return one of those enum value.
```
      Notifications.events().registerNotificationReceivedBackground(
        (notification, completion) => {
          console.log('Notification Received - Background', notification.payload)
          // export declare enum NotificationBackgroundFetchResult {
          //   NEW_DATA = 'newData',
          //   NO_DATA = 'noData',
          //   FAILED = 'failed',
          // }
          let result = NotificationBackgroundFetchResult.NEW_DATA
          completion(result)
        },
      )
```

`completion({alert: true, sound: true, badge: false})` is only for `registerNotificationReceivedForeground`.

**Comment by hannojg** [comment]
In which case would I return which enum? I feel like thats not documented anywhere 🤔

**Comment by neoswallow** [comment]
It looks like not.
I just send NEW_DATA all the time.

**Comment by axeljeremy7** [comment]
Where do you recommend call this? Inside The first component like outside the navigator?

**Comment by StijnCoolen** [comment]
Related: `registerNotificationOpened` may optionally use `actionResponse` with type `NotificationActionResponse` as a param. This is also not documented.

**Comment by williamdes** [comment]
The doc is maybe incomplete ?

https://github.com/wix/react-native-notifications/blob/bffb31fb0d1392f51c6d363917f3ad03323b2490/website/docs/api/general-events.md

it seems that iOS vs Android is not the same handing 🤔 ?
https://github.com/wix/react-native-notifications/blob/bffb31fb0d1392f51c6d363917f3ad03323b2490/lib/src/adapters/CompletionCallbackWrapper.ts#L25-L38

seems very iOS specific
https://github.com/wix/react-native-notifications/blob/bffb31fb0d1392f51c6d363917f3ad03323b2490/lib/ios/RCTConvert%2BRNNotifications.m#L150-L158

**Comment by AhmadNaeemK** [comment]
The doc is definitely incomplete. I have passed the enum to the completion handler but still getting issues with it.
