### ISSUE TITLE
Support presenting foreground notifications on Android

### ISSUE THREAD

**Issue by yogevbd** [wix/react-native-notifications#668]
Currently, all notifications received in foreground on android are not presented.

**Comment by canven** [comment]
What schedules about this task?   waiting for your respond.

**Comment by jakubkoci** [comment]
@yogevbd Where do you mean they're not presented? In the system notification center? That's actually the behavior we want in our app. We don't want the notification to appear in the notification center when the app is in the foreground.

**Comment by Rubicon-Charge** [comment]
Has there been any progress on this?

**Comment by Feehzzz** [comment]
i solved this problema with postNotification(null) in else condition.

/node_modules/react-native-notifications/lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java

`@Override
public void onReceived() throws InvalidNotificationException {
      if (!mAppLifecycleFacade.isAppVisible()) {
            postNotification(null);
            notifyReceivedBackgroundToJS();
        } else {
            postNotification(null);
            notifyReceivedToJS();
        }
}`

**Comment by tannermares** [comment]
Is there any reason `notifyReceivedBackgroundToJS` and `notifyReceivedToJS` cannot be moved to `protected` access so this method can be overridden for those that want this behavior? Modifying the local lib code and hoping you don't accidentally update or need to reinstall deps isn't tenable.

**Comment by tannermares** [comment]
Until then, I solved this another way by creating a local `MyPushNotification` class that extends `PushNotification`. Added the extra `pushNotification(null)` call in the `else` and declared the private methods again.

``` java
public class MyPushNotification extends PushNotification {
  @Override
  public void onReceived() throws InvalidNotificationException {
    if (!mAppLifecycleFacade.isAppVisible()) {
      postNotification(null);
      notifyReceivedBackgroundToJS();
    } else {
      postNotification(null);
      notifyReceivedToJS();
    }
  }

  private void notifyReceivedToJS() {
    mJsIOHelper.sendEventToJS(NOTIFICATION_RECEIVED_EVENT_NAME, mNotificationProps.asBundle(), mAppLifecycleFacade.getRunningReactContext());
  }

  private void notifyReceivedBackgroundToJS() {
    mJsIOHelper.sendEventToJS(NOTIFICATION_RECEIVED_BACKGROUND_EVENT_NAME, mNotificationProps.asBundle(), mAppLifecycleFacade.getRunningReactContext());
  }
}
```

This way we don't have to worry about updating the lib or wiping our `node_modules` breaking things.

**Comment by tomoakley** [comment]
@tannermares can you show how to implement this? i.e where the imports come from and how to integrate into an Android RN app. Thanks.

**Comment by kriss34** [comment]
Hi. 
Hopefully this is relevant to current issue. On Android, using the present lib/release,  the notifications never pop in "headless" mode (should the app be in foreground or background mode). The notifications do show in the notification center however. Is there a special setting we should apply to get the (usual) headless behavior working?
Please not that there's no such issue on iOS.

**Comment by canven** [comment]
> Hi.
> Hopefully this is relevant to current issue. On Android, using the present lib/release, the notifications never pop in "heads up" mode (should the app be in foreground or background mode). The notifications do show in the notification center however. Is there a special setting we should apply to get the (usual) heads up behavior working?
> Please note that there's no such issue on iOS.

Due the design of this lib,  pop notifications are block by lines 62 in blow file.
/node_modules/react-native-notifications/lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java

so,  we have to handle it by ourselves ,
First, we need to monitor  app status, using AppStatus.

Second, use Notification.postLocalNotification to custom action.

isIOS and isAppForeground is fake code, but i think it is easy to solve for you to solve it .



`
Notification.event.registerNotificationReceiveForeground((notification,completion)=>{
      if(isIOS()) {
            completion({alert:true,sound:true;badge:true})
      } else {
            if (isAppForeground()) {
       Notification.postLocalNotification(notofication.playload,0)
            }
      }
})

`

**Comment by DanielEliraz** [comment]
@tannermares's [solution](https://github.com/wix/react-native-notifications/issues/668#issuecomment-826393419) is very good, see [wiki](https://github.com/wix/react-native-notifications/issues/668#issuecomment-826393419) on how to implement  custom `PushNotification` class.

**Comment by billouboq** [comment]
Here is what I needed to do to make it work :

Create a MyPushNotification.java file inside just next to your app MainApplication.java file :

```java
package com.yourpackage;

import android.app.Notification;
import android.content.Context;
import android.content.res.Resources;
import android.os.Bundle;

import com.wix.reactnativenotifications.core.AppLaunchHelper;
import com.wix.reactnativenotifications.core.notification.PushNotification;
import com.wix.reactnativenotifications.core.JsIOHelper;
import com.wix.reactnativenotifications.core.AppLifecycleFacade;

import static com.wix.reactnativenotifications.Defs.NOTIFICATION_RECEIVED_EVENT_NAME;
import static com.wix.reactnativenotifications.Defs.NOTIFICATION_RECEIVED_BACKGROUND_EVENT_NAME;

public class MyPushNotification extends PushNotification {
  public MyPushNotification(Context context, Bundle bundle, AppLifecycleFacade appLifecycleFacade, AppLaunchHelper appLaunchHelper, JsIOHelper jsIoHelper) {
    super(context, bundle, appLifecycleFacade, appLaunchHelper, jsIoHelper);
  }

  @Override public void onReceived() throws InvalidNotificationException {
    postNotification(null);
    notifyReceivedToJS();
  }

  private void notifyReceivedToJS() {
    String eventName = mAppLifecycleFacade.isAppVisible() ?
      NOTIFICATION_RECEIVED_EVENT_NAME :
      NOTIFICATION_RECEIVED_BACKGROUND_EVENT_NAME;

    mJsIOHelper.sendEventToJS(
      eventName,
      mNotificationProps.asBundle(),
      mAppLifecycleFacade.getRunningReactContext()
    );
  }
}
```

In my AndroidManifest I had to put :

```xml
<intent-filter>
  <action android:name="com.google.firebase.MESSAGING_EVENT" />
</intent-filter>
```

And in my JS files I have :

```js
Notifications.events().registerNotificationReceivedForeground(
	(notif, completion) => {
		if (Platform.OS === 'android') {
			Notifications.postLocalNotification(notif.payload);
		}

		// Calling completion on iOS with `alert: true` will present the native iOS inApp notification.
		completion({ alert: true, sound: true, badge: false });
	},
);
```

**Comment by LukaszSecuritas** [comment]
hi @billouboq, how to add this class to Manifest file? I'm sorry I don't know Java 

this is from documentation:

`
<service android:name="com.wix.reactnativenotifications.fcm.FcmInstanceIdListenerService" android:exported="true"> 
        <intent-filter> 
		<action android:name="com.google.firebase.MESSAGING_EVENT" />
	</intent-filter> 
</service>
`

should I replace it with this?

`
<service android:name=".java.MyPushNotification" android:exported="false">
       <intent-filter>
            <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
</service>
`

**Comment by kg-currenxie** [comment]
> hi @billouboq, how to add this class to Manifest file? I'm sorry I don't know Java
> 
> this is from documentation:
> 
> `<service android:name="com.wix.reactnativenotifications.fcm.FcmInstanceIdListenerService" android:exported="true"> <intent-filter> <action android:name="com.google.firebase.MESSAGING_EVENT" /> </intent-filter> </service>`
> 
> should I replace it with this?
> 
> `<service android:name=".java.MyPushNotification" android:exported="false"> <intent-filter> <action android:name="com.google.firebase.MESSAGING_EVENT" /> </intent-filter> </service>`

I'm wondering the same

**Comment by bananer** [comment]
In case anybody is interested, here's why foreground Notifications on Android stopped working for me: 

Like most people around here suggest, I post a local notification when receiving a foreground notification on android:

```ts
Notifications.events().registerNotificationReceivedForeground((notification: Notification, completion) => {
  if (Platform.OS === 'android') {
    Notifications.postLocalNotification(notification.payload);
  }
  completion({ alert: true, sound: true, badge: false });
});
```

At some point, I got around to configuring the default notification channel:

```ts
Notifications.setNotificationChannel({
  channelId: "my_channel",
  // ...
});
```

This must have been the point where `postLocalNotification` silently stopped working, but I did not catch it at that time.

Weeks later I had to dig and debug through the Java code to to realize that the local notifications had a channel id set which was different from mine.

https://github.com/wix/react-native-notifications/blob/bffb31fb0d1392f51c6d363917f3ad03323b2490/lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java#L162

It pulls the notification channel from the data passed in:

https://github.com/wix/react-native-notifications/blob/bffb31fb0d1392f51c6d363917f3ad03323b2490/lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotificationProps.java#L22

So it probaby could be fixed by setting the channel when sending the notification to FCM

or, like I did, set it when creating the local notification:

```ts
Notifications.events().registerNotificationReceivedForeground((notification: Notification, completion) => {
  if (Platform.OS === 'android') {
    Notifications.postLocalNotification({ ...notification.payload, "android_channel_id": "my_channel" });
  }
  completion({ alert: true, sound: true, badge: false });
});
```
