### ISSUE TITLE
How to get result If user clicks "Don't allow" In ios after calling [registerRemoteNotifications]

### ISSUE THREAD

**Issue by canven** [wix/react-native-notifications#669]
As We all know,  IOS system will promote permission dialog when We first time to call 
 Notifications.registerRemoteNotifications(),  If user click "Don't allow",   How do we get the result 
 , let us to handle logic in respective apps?

React native: 0.62.2
react-native-notifications:3.3.0
os: iphone7 plus 10.2

**Comment by alancwoo** [comment]
I would say this is connected to #600 which unfortunately went stale with no response.

I'm also really wondering how to know what the result was of this dialog. The only thing that seems helpful is `await Notifications.isRegisteredForRemoteNotifications();` which doesn't necessarily help as it only returns a boolean and is not connected via a promise or callback in any way.

**Comment by canven** [comment]
> I would say this is connected to #600 which unfortunately went stale with no response.
> 
> I'm also really wondering how to know what the result was of this dialog. The only thing that seems helpful is `await Notifications.isRegisteredForRemoteNotifications();` which doesn't necessarily help as it only returns a boolean and is not connected via a promise or callback in any way.

yes,   currently situation seems like your mention.
using  Notifications.isRegisteredForRemoteNotifications() alternative solution,  we have to generate loop to monitor It  and have to  judge the first time request . we need to call registerRemoteNotifications,although
  isRegisteredForRemoteNotifications()  return false

**Comment by neildevas** [comment]
I'm having this issue too. It seems impossible to know whether the user denied permissions, without running a loop in the background and using isRegisteredForRemoteNotifications()

**Comment by canven** [comment]
> I'm having this issue too. It seems impossible to know whether the user denied permissions, without running a loop in the background and using isRegisteredForRemoteNotifications()

hi, neildevas,  in order to get to know which users selected for IOS,   I used  React Module Setup to call plamform API to apply  Notifications.registerRemoteNotifications()  before.

Brief steps:
 IOS:
    1. call Notification.checkPermissions to check OS permission.
    2.  have permission yet?
         No.   call your own apply permission setup,  using callback method to monitor it. then do you logic process.
         Yes.  do your own logic process.

additionally,  you need to distinguish IOS and Android.  Regarding Android don't need this step.

**Comment by willconno** [comment]
+1
