### ISSUE TITLE
IOS: Remote notification only accepts "sandbox"

### ISSUE THREAD

**Issue by lodev09** [wix/react-native-notifications#67]
I'm having weird issue after I built my app for "release" in iOS. I have configured the certificates/pems on the server side but I can't figure out why it can only accept notifications from `ssl://gateway.sandbox.push.apple.com:2195`. I'm using PHP to send remote notification.

If it helps, I just recently switched to this package for additional features and it works great on dev. The previous package I used was the `react-native-push-notification` which accepts notification appropriately for both dev and production.

Am I missing something or this is a known issue? Thanks!

PS: I'm using RNN + redux

**Comment by burennto** [comment]
Hi @lodev09, did you end up finding a solution?

I am experiencing a similar issue with VoIP notifications where:
- the same token is issued to both release/debug builds
- notifications can be received in both builds, but only if sent to `gateway.sandbox.push.apple.com:2195`

**Comment by lodev09** [comment]
I'm not sure if we have the same issue but after building it for Ad Hoc or testflight build, it now accepts data from `gateway.push.apple.com:2195`

**Comment by burennto** [comment]
Thanks @lodev09, I eventually had the same results after building for TestFlight. Looks like local Release/Production builds are still treated as "sandbox" in terms of APNS.
