### ISSUE TITLE
registerNotificationReceivedBackground listener not triggered on Android when App is in background

### ISSUE THREAD

**Issue by reeinohio** [wix/react-native-notifications#670]
Using Android, when App is in background, notification gets displayed on tray but  **registerNotificationReceivedBackground event is not triggered**.  This event is important to trigger the App do a service api call. Especially, if the user happens to dismiss the notification. The App never knew a notification arrived. [This flow works fine on iOS.]

* I have tried latest version (v3.3.2) and even went back to v3.2.* versions and same behavior
* It appears same issue was reported on 2/3 for v3.1  [https://github.com/wix/react-native-notifications/issues/478](url), unresolved and was closed by stale bot. 
* I even tried to debug Native code PushNotification.java and the other java files. I've put system.out.println() to what i think would be the likely functions that will get called, e.g. notifyReceivedToJS(),  but none of the functions were triggered when the notification is received while app is in background.  It seems the App is disconnected during this state

1. Is this a known issue that will eventually be resolved?
2. Is there a work around that I could try? Or how has the others worked around this?

Thanks!

**Comment by aminerol** [comment]
Any progress on this issue, am facing the same issue

**Comment by ArjunKarki** [comment]
I am also facing the same problem

**Comment by ckasek** [comment]
@reeinohio this event is triggering for you on iOS?  No matter what I try, the event isn't called when my app is running in the background on iOS.

**Comment by reeinohio** [comment]
@ckasek  yes, it seems to work for me. I have this note within my code:         
// Issue: Very first push msg not received when app is in foreground, but the next msgs were received  
// Work around: https://github.com/wix/react-native-notifications/issues/627#issuecomment-681114711

**Comment by joelpanor** [comment]
Any progress on this issue ? I am facing the same problem

**Comment by erkie** [comment]
not stale

**Comment by reeinohio** [comment]
This is still an issue

**Comment by ckasek** [comment]
bad bot.

**Comment by Davete0302** [comment]
anyone solved this?

**Comment by erkie** [comment]
Has anyone looked into if power-saving methods are causing the app to not run in the background? For example https://dontkillmyapp.com/ might have a clue?

**Comment by erkie** [comment]
bad bot.

**Comment by Vanclief** [comment]
Having the same issue, no updates?

**Comment by erkie** [comment]
it's not the issue that's stale...

**Comment by reeinohio** [comment]
Not stale

**Comment by reeinohio** [comment]
Issue is not stale. Please re-open

**Comment by itsam** [comment]
This is still an issue

**Comment by LadghemSaid** [comment]
Still an issue

**Comment by almightybob** [comment]
Having the same issue

**Comment by lfrkovic-spaceiq** [comment]
Same issue, not stalle.
