### ISSUE TITLE
Opening an Android application by notification tap

### ISSUE THREAD

**Issue by AlimovSV** [wix/react-native-notifications#68]
- On cold start - `PendingNotifications.getInitialNotification().then(...)` returns undefined.
- When app in background - the handler configured by `NotificationsAndroid.setNotificationOpenedListener(...)` is not called

App based on react-native-navigation and configured as described [here](https://github.com/wix/react-native-notifications/wiki/Android:-working-with-RNN).

    "react-native": "0.44.0",
    "react-native-navigation": "latest",
    "react-native-notifications": "^1.1.10",

Any help?

**Comment by andreipham** [comment]
Same here.

**Comment by enahum** [comment]
did you find a solution for this?

**Comment by AlimovSV** [comment]
still no

**Comment by enahum** [comment]
it seems that the wiki is missing something or we are doing wrong

**Comment by AlimovSV** [comment]
i hope the wix will provide some help

**Comment by nkov** [comment]
I resolved this problem by sending the payload with key `data` instead of key `notification` as mentioned [here](https://github.com/wix/react-native-notifications/issues/42#issuecomment-299012587).

**Comment by Benjamin-Dobell** [comment]
https://github.com/wix/react-native-notifications/pull/71 fixes this.

**Comment by andreipham** [comment]
@nkov After you made this modification, did you test the behaviour of receiving a notification when the app is in background? In my case, if I send only the `data` object within the payload, the notification is empty when received in background.

**Comment by AlimovSV** [comment]
@Benjamin-Dobell can you make a favour and provide an example of app based on [react-native-navigation](https://github.com/wix/react-native-notifications/wiki/Android:-working-with-RNN)?

**Comment by enahum** [comment]
you could use our app as an example with RNN https://github.com/mattermost/mattermost-mobile

**Comment by swellingt0n** [comment]
Echo @nkov, setting the data correctly from the server side enabled the pending notification listener to pick it up.

**Comment by devLaaziz** [comment]
same here
