### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by aditiproctur** [wix/react-native-notifications#681]
Hello, I used this library in android and ios. It was working fine till now. but from 2,3 days, I am facing the following issue in our application for android versions. My Application is crashing when I open it.  Kindly checked. Thank you in advance.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.getBooleanExtra(java.lang.String, boolean)' on a null object reference
       at com.wix.reactnativenotifications.fcm.FcmInstanceIdRefreshHandlerService.onHandleIntent(FcmInstanceIdRefreshHandlerService.java:22)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Versions used,**
```
"react": "16.9.0",
"react-native": "^0.61.5",
"react-native-notifications": "^2.1.7",
```

**Issue occurred,**
```
Android version : 6.0 & 6.0.1
```

Please help us to solve this issue.

**Comment by jamesjara** [comment]
I have the same issue

**Comment by fullerlee** [comment]
I get this issue when coming back to the App from another Intent (e.g. Image Browser).

What worked for me was just:

` @Override
    public void onActivityStarted(Activity activity) {
+        if (activity.getIntent() == null) {
+            return;
+       }
        Bundle bundle = activity.getIntent().getExtras();
        if (bundle != null) {
            PushNotificationProps props = new PushNotificationProps(bundle);
            if (props.isFirebaseBackgroundPayload()) {
                InitialNotificationHolder.getInstance().set(props);
            }
        }
    }`
