### ISSUE TITLE
Method for accessing Device Token after the registration on IOS?

### ISSUE THREAD

**Issue by TylerNRobertson** [wix/react-native-notifications#682]
After accepting permissions on IOS you can get the Device Token in the callback. Is there a way to programmatically access it again? Or is that the only time you can access that value. Recalling Notifications.registerRemoteNotifications() does give the token on android but not ios if already accepted.

**Comment by blankey1337** [comment]
I also have this question. Most users instinctively decline push notifications, which results in `registerRemoteNotificationsRegistered` never firing. As a result, even if a user goes and enables notifications via Settings after installation, we will never know the user's deviceToken. Currently the only solution I can come up with is to show a modal when `registerRemoteNotificationsRegistrationFailed` fires, asking the user to delete the app and re-install, and to accept push notifications. This is less than ideal.

**Comment by TylerNRobertson** [comment]
@blankey1337 For now my fix is when the user comes back in the app after enabling it within "Settings" is to check Notifications.isRegisteredForRemoteNotifications(), if this gives true & push was not previously enabled, run Notifications.registerRemoteNotifications(), this should cause the token to be caught now by the event. Not an ideal solution but instead of a full reinstall I've managed to solve it with this approach.

**Comment by blankey1337** [comment]
That is good to know. I did not witness this behavior, perhaps because I am testing on simulator. I will try what you suggested, thanks for letting me know!

**Comment by TylerNRobertson** [comment]
@blankey1337 yeah the simulator doesn't work for this. You'll need to run on a real device

**Comment by TylerNRobertson** [comment]
Would like this to not be marked stale. Would be a great feature to have eventually

**Comment by TylerNRobertson** [comment]
Closed but still wanted...

**Comment by soadtech** [comment]
@TylerNRobertson  could you provide an example? I can't get the deviceToken in ios

**Comment by Sayah-Sel** [comment]
I can not catch the token either, I just know that it has registered somehow.

A problem may be the delay. When I first launch the app on a simulator device, it ask for permission, but by the time the user accept the rest of the is already executed. isRegisteredForRemoteNotifications returned false, registerRemoteNotificationsRegistered did not triggered (nor did registerRemoteNotificationsRegistrationFailed), and !!currentPermissions.badge return false.

Then, on subsequent launch, everything return true, but registerRemoteNotificationsRegistered does not trigger... As it already registered and does not register again?

There seem to be huge problem relative to the use of the library on the iOS simulator.
