### ISSUE TITLE
Unable to prevent data-only Background notifications from displaying a notification (Android)

### ISSUE THREAD

**Issue by tdous** [wix/react-native-notifications#684]
Using v.3.2.2 of RNN, and react-native 0.63. Didn't want to upgrade as right at the end of a build and don't want to switch version unnecessarily just yet.

We send pushes to display notifications for users, but also data-only notifications to trigger updates behind the scenes. I don't seem to be able to stop blank notifications from showing up in the notification tray. By which I mean the icon and app name, with no content (because there isn't any content to display).

![Like this](https://i.imgur.com/i2UxbQh.png)

I'm a little confused by a combination of the docs not mentioning much about the completion callback, and another Github issue that suggested the completion function is not correctly documented, so I might be missing something, or misusing that somehow...

The notification payload arriving via FCM looks like this:
```javascript
{
  from: "XXXXXXXXXXXXX",
  google.c.sender.id: "XXXXXXXXXXXXX",
  google.delivered_priority: "normal",
  google.message_id: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  google.original_priority: "normal",
  google.sent_time: 1234567890000,
  google.ttl: 1234567,
  show: "false", // A setting which is used in the foreground, should be ignored in the background
  type: "update", // For filtering the type in the listener above
  action: "SOME_ACTION", // A sub-type, an action to trigger when in the foreground
}
```
And my listener looks something like this:
```javascript
Notifications.events().registerNotificationReceivedBackground((
  notification: Notification,
  completion: (response: NotificationCompletion) => void
) => {
  switch (notification.payload.type) {
    // Some alert type to display in background
    case 'SOME_ALERT':
      completion({ alert: true, sound: true, badge: true });
      break;

    // Another type of alert to display
    case 'ANOTHER_ALERT_TYPE':
      // Maybe do something else here and then...
      completion({ alert: true, sound: true, badge: true });
      break;
    
    // THE PROBLEM - I have tried filtering this type, and different
    // formats of completion function, and also just leaving this
    // entire case out entirely, but the notification is always shown.
    case 'update':
      completion({ alert: false, sound: false, badge: false });
      // OR... completion(); - or no args, unclear what this does
      // OR... Something else to stop notifications from appearing??
      break;
  }
});
```
This is all going fine in the foreground, and the background notifications I do want to display are ok too. I'm just probably missing something obvious about how to handle (in my case ignore) these "hidden" pushes in the background. If anyone can point to my mistake or misunderstanding I'd be very grateful.

**Comment by tdous** [comment]
I couldn't find clarity on this myself, and since I built our backend push sending service a couple of years ago I wondered if it was sending stuff in a way that was triggering these incorrectly. However I've since switched over to react-native-firebase which is handling them as expected (ie. not displaying anything) so I'm happy there's no issue there. So while this is not closed as far as understanding why it was happening, it's closed for me as I'm not longer using this module. I'll just leave this in case anyone else has the problem and someone else can clarify for them.

**Comment by mslipenchuk267** [comment]
not stale, Having the same issue

**Comment by menasSawwaf** [comment]
I have the same issue any update about this ??

**Comment by Plitzer** [comment]
Also the same issue, this is very problematic when using data-only notifications.
To add to this issue, if you specify the usual notification payload keys (title, body, ...) INSIDE the data payload, they will be picked up by the 'blank' notification as if it were a part of the notification payload.

e.g. setting the title to 'Hello' and the body to 'World' in the **data** payload will present a notification that says
Hello
World

**Comment by erkie** [comment]
go away stolebot

**Comment by mp8446** [comment]
Somebody found a solution for this?

**Comment by erkie** [comment]
I'm guessing it should be a pretty easy fix to just add an if-statement on this line, to not present empty notifications?

https://github.com/wix/react-native-notifications/blob/master/lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java#L151

**Comment by erkie** [comment]
stalebot unstale!

**Comment by tannermares** [comment]
This lib expects the `title` and `body` keys of your notification to be in one of two places. It's either included in the firebase notification object. Which will look like `gcm.notification.title` in the payload or at the top next to your `action`. These are the only two scenarios where `react-native-notifications` will automatically extract the [`title`](https://github.com/wix/react-native-notifications/blob/master/lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotificationProps.java#L13-L15) and [`body`](https://github.com/wix/react-native-notifications/blob/master/lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotificationProps.java#L17-L19) for you. Otherwise, you'll have to `@Override` the `getTitle` and `getBody` methods in a custom `MyPushNotification.java` class.
