### ISSUE TITLE
Outdated docs or still applicable?

### ISSUE THREAD

**Issue by crushy26** [wix/react-native-notifications#686]
Hi,

I am seeing the instructions from the wiki are last updated in 2017, are those still applicable and valid to refer?

also, is this [repo](https://github.com/chrise86/rn-notification-navigation) valid provided by one the fellow member here on this issue #73 to integrate with RNN

PS: Trying to customize notification

**Comment by danwhite-ipc** [comment]
@crushy26 ever get an answer?

**Comment by crushy26** [comment]
@danwhite-ipc I might be late for the reply here, but I am using onesignal which is perfect for remote notifications
