### ISSUE TITLE
Documentation clarification: is didReceiveRemoteNotification needed in the app delegate?

### ISSUE THREAD

**Issue by erkie** [wix/react-native-notifications#687]
The sample app in the examples directory has an additional app delegate method that is not included in the documentation:

```objective-c
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult result))completionHandler {
  [RNNotifications didReceiveBackgroundNotification:userInfo withCompletionHandler:completionHandler];
}
```

https://github.com/wix/react-native-notifications/blob/master/example/ios/NotificationsExampleApp/AppDelegate.m#L41

I can't figure out if it is actually needed or not, since I'm having issues getting background actions working.

Missing here:
https://wix.github.io/react-native-notifications/docs/getting-started

**Comment by erkie** [comment]
Still an issue

**Comment by erkie** [comment]
this project is stale

**Comment by viggyfresh** [comment]
my understanding is that this is _not_ required!

**Comment by zkwentz** [comment]
@erkie thanks for pointing this out. I was searching through issues unable to receive backgrounded notifications. Adding that snippet from the sample allowed me to receive them.

So for me, I needed to add this.

Further, I also needed to update my completion handler to this: https://github.com/wix/react-native-notifications/issues/665#issuecomment-682849222
