### ISSUE TITLE
Notification is blank on Android

### ISSUE THREAD

**Issue by jbolter** [wix/react-native-notifications#69]
I'm not sure what I'm doing wrong since others appear to be using this library for Android but my push messages are appearing "blank".  I receive the push and I can see the push in the log with the message but the device just shows a blank push notification with the app icon and no text.

I switched to [react-native-push-notification](https://github.com/zo0r/react-native-push-notification) for Android and now my push notifications are appearing with text so something is going on with the wix push library.  I haven't had time to dig into it and I'm not an Android expert so I'm not sure where to look.  Hoping someone else can come to my rescue so I can use a single library for push.

**Comment by nkov** [comment]
For me, this was because in the payload I was sending the notification in an object with key "notification". Changing it to data fixes it:
```json
"data": { "title": "Hello", "body": "World!" }
```

**Comment by swellingt0n** [comment]
I am also having this issue. I do not have a way to specify the payload format when sending from the firebase console, has anyone got a workaround aside from switching libraries?

**Comment by jbolter** [comment]
Ok I'm back to this plugin because the RNPN plugin conflicts with the wix RNN library.  So I am trying to solve this blank push issue.  I'm actually seeing the *opposite* from what @nkov describes.  My push payload is currently using "data" and we switched it to use "notification".  Now with "notification" we can see that the push is not blank, we see the title and body.  

However now we are getting double push notifications in the app for each single notification that we send.  After a little research I found that this is because gcm and firebase are both being included as dependencies in my app and are causing the duplicates as referenced here... https://stackoverflow.com/questions/38167125/firebase-send-push-notification-twice

Altering my build.gradle to exlude firebase appears to have solved my issue with the double notification and sending both `data` and `notification` payloads seems to have solved the blank issue.

``compile (('com.google.android.gms:play-services:9.2.1')){
        exclude group: "com.google.firebase"
    }``

**Comment by ricardofbarros** [comment]
This is deal breaker 👎  I'm also experiencing this.

**Comment by jbolter** [comment]
@ricardofbarros @swellingt0n We had to figure out how to fix that as well since we could not modify the payload easily of a 3rd party.  I ended up forking the repo and making a minor change to `GcmMessageHandlerService.java`.

You can see the change here:
https://github.com/wix/react-native-notifications/compare/master...jbolter:master

Notice that I'm hard-coding the "app name" as the title of the push notification.

**Comment by swellingt0n** [comment]
@jbolter Ultimately doing what @nkov did worked for me. This also solved a problem with the payload coming in undefined.

**Comment by anatooly** [comment]
Problem is actual
