### ISSUE TITLE
Documentation out of date for postLocalNotification

### ISSUE THREAD

**Issue by yrichard** [wix/react-native-notifications#693]
I am trying to run the example for postLocalNotification from here : https://wix.github.io/react-native-notifications/api/general-api/, and I get a TypeScript error that category, link or fireDate do not exist on the type Notification...
This is with the "react-native-notifications" package version 3.3.4.
Is the typescript definition wrong or was the API updated but not the documentation?
Thanks

**Comment by elirangoshen** [comment]
same here +1

**Comment by deepslam** [comment]
Same here! Is that project alive?

**Comment by oldrefery** [comment]
fireDate should be string. add .toISOString()
