### ISSUE TITLE
Custom Notification Sound Not Playing

### ISSUE THREAD

**Issue by Osamasomy** [wix/react-native-notifications#698]
### STEPS
1. Put ringtone.mp3 in android/app/src/main/res/raw/ringtone.mp3
2. Call Notifications.postLocalNotification

Butt still playing default ring tone Rather then **CUSTOM RINGTONE**

### CODE
```
Notifications.postLocalNotification({
          title: notification.payload['gcm.notification.title'],
          body: notification.payload['gcm.notification.body'],
          extra: '',
          sound: "ringtone.mp3",
        });
```

**Comment by Ayan-Ali** [comment]
I am also having this issue.

**Comment by akosimarlo** [comment]
any solution in this?
