### ISSUE TITLE
Custom notifications on Android

### ISSUE THREAD

**Issue by VRBitman** [wix/react-native-notifications#7]
Hello, are there any intentions to add support for fully custom notifications on **Android**?
That is, notifications with personalized XML layouts with any controls and any graphics.
Thanks.

**Comment by lidanh** [comment]
Hi @VRBitman,
Sorry for the late response, was on vacation.

The answer is yes, we're working on it and it will be released soon! you can track the status on `android` branch.

Lidan

**Comment by VRBitman** [comment]
Hi,

I hope you had a great vacation!
This is great, it's the cherry on the cake!

Thank you!

**Comment by dininski** [comment]
@VRBitman could you post an update as the `android` branch seems dead? Just wanted to know if you guys are still working on that :pray:

**Comment by VRBitman** [comment]
@dininski Hi, we should have updates soon from the original project maintainers.

**Comment by lidanh** [comment]
Hey @VRBitman and @dininski, I just merged @amitdwix great work on our android version.
More features will be released soon. You're more than welcome to help us and PR!

**Comment by VRBitman** [comment]
Hey @lidanh, I can certainly do at least some good PR!
