### ISSUE TITLE
Local Notification's Badge Not Supported (iOS)

### ISSUE THREAD

**Issue by Frans-L** [wix/react-native-notifications#704]
postLocalNotification() doesn't support ****badges**** at all.

In other words, **badge** property doesn't do anything.

```javascript
Notifications.postLocalNotification(
  {
    fireDate: date.toISOString(),
    body: "Body",
    title: "Title",
    badge: 1, // this doesn't do anything
  },
  id
);
```

This would be quite a handy feature :)

**Comment by cschaffr** [comment]
Actually all we have to do is add the following lines to RCTConvert+RNNotifications.m (Line 64)
`  NSNumber * badge = [RCTConvert NSNumber:details[@"badge"]];
    content.badge = badge;`
