### ISSUE TITLE
EXC_BREAKPOINT in didReceiveNotificationResponse method

### ISSUE THREAD

**Issue by jfojtl** [wix/react-native-notifications#722]
```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)(void))completionHandler
{
  dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
    dispatch_group_t completionGroup = dispatch_group_create();
      
    void (^myCompletion)(void) = ^{
      dispatch_group_leave(completionGroup); // <--- HERE exception described bellow
    };
    
    for (id<UNUserNotificationCenterDelegate> delegate in delegates) {
      if ([delegate respondsToSelector:@selector(userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:)]) {
        dispatch_group_enter(completionGroup);
        [delegate userNotificationCenter:center didReceiveNotificationResponse:response withCompletionHandler:myCompletion];
      }
    }
    
    dispatch_group_wait(completionGroup, dispatch_time(DISPATCH_TIME_NOW, 30 * NSEC_PER_SEC));

    dispatch_async(dispatch_get_main_queue(), ^{
      completionHandler();
    });
  });
}
```

#2	0x00000001035a4108 in __109-[RNNotificationCenterMulticast userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:]_block_invoke_2 at /Users/jfojtl/dev/gitlab.com/meddihub/phones/node_modules/react-native-notifications/lib/ios/RNNotificationCenterMulticast.m:56

EXC_BREAKPOINT
Exception 6, Code 2639910872, Subcode 8

I would appreciate any help with fixing or debugging. It happens every time, so I can provide any information necessary.

**Comment by erkie** [comment]
What does your appdelegate look like? Maybe your calling [RNNotifications startMonitorNotifications]; multiple times?

**Comment by erkie** [comment]
This might be related to calling the completion callback multiple times in your `registerNotificationOpened` handler. Can you post that code as well?

**Comment by erkie** [comment]
I've confirmed that's what our problem was, i.e calling the completion callback multiple times in `registerNotificationOpened`.

**Comment by jfojtl** [comment]
Thank you for pointing me in some direction. I checked that in AppDelegate I have only one `RNNotifications startMonitorNotifications];` and I call only once `completion()` at the end of the `registerNotificationOpened` method.

**Comment by jfojtl** [comment]
The reason was indeed multiple calling of `completion` callback, but it was not obvious in the code. Thanks for pointing me in right direction 💪

**Comment by neildevas** [comment]
I'm facing this issue as well. @jfojtl can you paste a code sample where you called `completion` multiple times? Maybe I am accidentally doing the same thing.
