### ISSUE TITLE
Sound not playing

### ISSUE THREAD

**Issue by 0x111** [wix/react-native-notifications#723]
Hi guys,

Anyone did manage to get the notification sound playing? I create a custom channel, set a soundfile, put it into the res/raw folder under the same name but the notification is simply not playing the sound.
Anyone got this working?

```
Notifications.setNotificationChannel({
      channelId: 'doorbell-channel',
      name: 'Doorbell',
      importance: 2,
      description: 'Notifications for doorbell',
      enableLights: true,
      enableVibration: true,
      // groupId: 'your-group',
      showBadge: true,
      soundFile: 'doorbell.mp3', // place this in <project_root>/android/app/src/main/res/raw/custom_sound.mp3
      vibrationPattern: [200, 1000, 500, 1000, 500],
    });
```

This is how the json looks that I am sending to the API:
```
{
    "to": "<redacted>",
    "priority": "high",
    "notification": {
        "title": "Title",
        "body": "You have received a new notification yayyy :) :) :)",
        "android_channel_id": "doorbell-channel",
        "badge": "0",
        "soundFile": "doorbell.mp3"
    },
    "data": {
        "some": "data here"
    }
}
```

Further specs:
I am trying this on an Android phone, notification appears but no sound is played not even the default.

**Comment by MoronovArt** [comment]
same issue

**Comment by 0x111** [comment]
> same issue

You did not figure out a solution either? 🙁

**Comment by MoronovArt** [comment]
> > same issue
> 
> You did not figure out a solution either? 🙁

Nope

**Comment by 0x111** [comment]
@wixmobile any help please

**Comment by MoronovArt** [comment]
@wixmobile we need your help

**Comment by 0x111** [comment]
Not stale

**Comment by 0x111** [comment]
This stale issue thing is just ridiculous

**Comment by 0x111** [comment]
@DanielEliraz Thanks for the fix. How can I try this out in my project without a release being published on npm? If you could provide steps to build from master I would be glad. (no rush, just want to try it out, but I was not able to determine a simple way of doing so apparently)

If it is too complicated, then I will just have to wait. Thanks for the efforts though!

**Comment by Nayan014** [comment]
@0x111 How do you fix it?

**Comment by 0x111** [comment]
> @0x111 How do you fix it?
> 
> 

With the latest fixes it worked as described in the example

**Comment by Nayan014** [comment]
I want to use the default sound of notification, is it mandatory to create notification channels for that?

**Comment by 0x111** [comment]
I don't think that you need to create channels if I remember correctly if not specified the notification uses the default channel but I would suggest to create a new issue for your problem if any 🙂
