### ISSUE TITLE
[Warning] Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated.

### ISSUE THREAD

**Issue by JaeWangL** [wix/react-native-notifications#725]
I am using kotlinVersion with **1.4.30**
When I build android with react-native-notifications
program says

`Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.`

**Comment by devthejo** [comment]
+1

**Comment by gus-delpino** [comment]
@JaeWangL did you figure out a solution to this?
