### ISSUE TITLE
cancelLocalNotification error

### ISSUE THREAD

**Issue by Rc85** [wix/react-native-notifications#729]
Trying to cancel a local notification. I assume this is to remove the notification from the notification center
```
        const notificationIds = []
        const notification: Notification = {
          title: `My Takeouts`,
          body: 'You have a new order'
        };

        for (const id of notificationIds) {
          Notifications.cancelLocalNotification(id.toString());
        }

        const notificationId = Notifications.postLocalNotification(notification);

        notificationIds.push(notificationId);
```

I get a native error

```
java.lang String cannot be cast to java.lang.Double
```

**Comment by jehee-choi** [comment]
+1

**Comment by douugbr** [comment]
I've discovered that the notification id parameter in the function `cancelLocalNotification(notificationId)` must be a number even though the inferred type by the lib is string.

`Notifications.cancelLocalNotification(1);` will work while diplaying a linter error and `Notifications.cancelLocalNotification('1');` will display no error but will give you that native error.

**Comment by a-eid** [comment]
`cancelLocalNotification` doesn't work on android

also `postLocalNotification` fires immediately on android regardless of the `fireDate`

they have a not about this in the docs.
