### ISSUE TITLE
[Help] Android integration with react-native-navigation.

### ISSUE THREAD

**Issue by ghost** [wix/react-native-notifications#73]
Hello fellow partners, im currently developing a react-native application using react-native-navigation which is developed also by wix. Im not understanding the wiki provided, to integrate with Android. 

https://github.com/wix/react-native-notifications/wiki/Android:-working-with-RNN

Where must I create the files **NotificationsLifecycleFacade.java** and **CustomPushNotification.java** , is It in the same folder where MainAplication.java and MainActivity.java is ...?

If anyone could give me some ideas that would be awsome, thanks in advance.

**Comment by chrise86** [comment]
Also struggling to get this up and running, got a discussion going on [here](https://github.com/wix/react-native-notifications/issues/37)

**Comment by chrise86** [comment]
Hey @nickmendes have a look at this [demo app](https://github.com/chrise86/rn-notification-navigation) I setup using both. It has the custom classes already setup.

**Comment by nickmendes** [comment]
thanks @chrise86 i'll have a look.

**Comment by oscar-omana** [comment]
Anyone getting an error on CustomPushNotification.java that says
error: invalid method declaration; return type required

**Comment by danwhite-ipc** [comment]
Do you still need to follow this wiki for the lastest version of RNNotifications?, as the link to the gist is not working anymore
https://github.com/wix/react-native-notifications/wiki/Android:-working-with-RNN

**Comment by DanielEliraz** [comment]
@danwhite-ipc , no you don't need it any more, I'm removing it. Thanks 💜
