### ISSUE TITLE
Turn off stalebot

### ISSUE THREAD

**Issue by erkie** [wix/react-native-notifications#736]
A lot of valid issues are being closed because this project is not active. Can we at least remove stalebot? @yogevbd

**Comment by erkie** [comment]
@yogevbd any updates?

**Comment by DanielEliraz** [comment]
@erkie, thanks for your contribution 💟 . I do understand your request but let's give it another shot. If we'll see again in the future that  issues are being closed without a reason we will rethink about it.

**Comment by erkie** [comment]
@DanielEliraz will you go in an reopen all issues and PRs that stalebot wrongly closed?

**Comment by DanielEliraz** [comment]
@erkie, hopefully yes. And this should be done anyway..
