### ISSUE TITLE
No compatibility with react 0.45.1

### ISSUE THREAD

**Issue by g33ktony** [wix/react-native-notifications#74]
This version requires react 16.0.0-alpha.12

**Comment by jbolter** [comment]
Can anyone elaborate on this?  We upgraded to 0.45.1 from 0.42 and I'm not seeing the 'notificationOpened' handler called.  Was just investigating this issue and found your bug about no compatibility with 0.45.1.  Is this what you mean?  Is there any workaround or do we need to go to 0.46+?
