### ISSUE TITLE
[3.4.2] ClassNotFoundException com.google.firebase.iid.FirebaseInstanceId

### ISSUE THREAD

**Issue by eliw00d** [wix/react-native-notifications#745]
We suddenly started getting crashes on Android with the error in the title. Here is a screenshot of our Sentry log for it:

![image](https://user-images.githubusercontent.com/1801127/121597551-78c93980-ca06-11eb-9993-46f3b2c26cb0.png)

I tried setting `firebaseVersion = "21.1.0"` in build.gradle but that didn't seem to help. 

Any thoughts?

**Comment by david-gregorian** [comment]
I have the same problem. We tried to stay at version `6.1.3` while using `firebaseVersion = "21.1.0"` but the same error comes sometimes.

**Comment by RiCoTeRoX** [comment]
this is relate to [android#messaging_v22-0-0](https://firebase.google.com/support/release-notes/android#messaging_v22-0-0), i think

**Comment by krishna-gujjjar** [comment]
Just add dependency to in `android/app/build.gradle`
`implementation 'com.google.firebase:firebase-iid:17.0.2'`

**Comment by DanielEliraz** [comment]
@eliw00d, please reopen if @krishna-gujjjar ☝️  answer didn't help

**Comment by DanielEliraz** [comment]
Also, #751 should fix this. Will be released soon. @eliw00d, FYI

**Comment by fresnohernandez99** [comment]
Nothing of this works for me.
using :
"react-native-push-notification": "^8.1.1"

googlePlayServicesVersion = "+" 
firebaseMessagingVersion= "21.1.0"
firebaseVersion = "+" 

implementation platform('com.google.firebase:firebase-bom:26.1.1')
implementation 'com.google.firebase:firebase-iid:21.1.0'
implementation 'com.google.firebase:firebase-messaging'
implementation 'com.google.firebase:firebase-analytics'

Keep give it error on found this:
import com.google.firebase.iid.FirebaseInstanceId;
import com.google.firebase.iid.InstanceIdResult;

**Comment by camboYY** [comment]
not work
