### ISSUE TITLE
AndroidManifest file in repo not updated for supporting Android 12 devices

### ISSUE THREAD

**Issue by thepoppingone** [wix/react-native-notifications#768]
Performing Streamed Install
adb: failed to install android/app/build/outputs/apk/debug/app-debug.apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1679014567.tmp/base.apk (at Binary XML file line #173): com.wix.reactnativenotifications.fcm.FcmInstanceIdListenerService: Targeting S+ (version 10000 and above) requires that an explicit value for android:exported be defined when intent filters are present]
error Command failed with exit code 1.

To fix this issue with regards to installing to Android 12 devices

**Comment by kroeberk** [comment]
This issue still persists

**Comment by sergiulucaci** [comment]
Until it's fixed, you could make a [patch](https://www.npmjs.com/package/patch-package) with below change:

being located at `lib/android/app/src/main/AndroidManifest.xml`, add  `android:exported="false"` for **FcmInstanceIdListenerService** service.

[example](https://github.com/MCROEngineering/react-native-notifications/commit/46f73347a36bdcbc37abffeb905a557107ec3806)
