### ISSUE TITLE
Can't create ios local notification

### ISSUE THREAD

**Issue by jimzqw** [wix/react-native-notifications#770]
I was trying to integrate react-native-notification with firebase FCM messaging, I could get notification from FCM but couldn't post foreground local notification. Can someone take a look, please? This is ios btw, and I have followed https://wix.github.io/react-native-notifications/docs/getting-started 
```
import messaging from '@react-native-firebase/messaging';
import {Notifications} from 'react-native-notifications';

const App = () => {
  useEffect(() => {
    Notifications.registerRemoteNotifications();

    messaging().onMessage(async remoteMessage => {
      console.log(remoteMessage);
      Notifications.postLocalNotification({
        title: remoteMessage.notification.title,
        body: remoteMessage.notification.body,
      })
    });
```

**Comment by tusharprajapati8888** [comment]
@jimzqw, I have also faced this same issue and I have followed [this](https://wix.github.io/react-native-notifications/docs/notifications-events) documentation.

If you want to use firebase `messaging().onMessage` event to display local notification. In android it will work perfectly,
But in iOS you need to set `completion({alert: true, sound: true, badge: false});` which can only set in  `Notifications.events().registerNotificationReceivedForeground` event.


```
 Notifications.events().registerNotificationReceivedForeground((notification: Notification, completion: (response: NotificationCompletion) => void) => {
      console.log("Notification Received - Foreground", notification.payload);

      // Calling completion on iOS with `alert: true` will present the native iOS inApp notification.
      completion({alert: true, sound: true, badge: false});
        });
```

**Comment by gcarpi** [comment]
> @jimzqw, I have also faced this same issue and I have followed [this](https://wix.github.io/react-native-notifications/docs/notifications-events) documentation.
> 
> If you want to use firebase `messaging().onMessage` event to display local notification. In android it will work perfectly,
> But in iOS you need to set `completion({alert: true, sound: true, badge: false});` which can only set in `Notifications.events().registerNotificationReceivedForeground` event.
> 
> Please also add below code. This will help to display your local notification in iOS while app is open.
> 
> ```
>  Notifications.events().registerNotificationReceivedForeground((notification: Notification, completion: (response: NotificationCompletion) => void) => {
>       console.log("Notification Received - Foreground", notification.payload);
> 
>       // Calling completion on iOS with `alert: true` will present the native iOS inApp notification.
>       completion({alert: true, sound: true, badge: false});
>    });
> ```

it worked for me, thanks
