### ISSUE TITLE
FcmToken.java causes random crashes on Android

### ISSUE THREAD

**Issue by lucswart** [wix/react-native-notifications#772]
Hi,

I am using Firebase Crashlytics to analyse my crashes for my react native android app. FcmToken.java somehow causes random crashes which is a bit annoying. Is there anyway I can prevent this? Am I doing something wrong here? 

![Crash log](https://user-images.githubusercontent.com/66739939/132958619-8bc5ae55-1eb3-4311-8d76-c4f414018924.png)

**Comment by jpmunoz9** [comment]
I'm noticing this as well and so far I have not found a solution.

**Comment by lucswart** [comment]
I managed to fix it. Just add this line `implementation("com.google.firebase:firebase-iid")` to your build.gradle under dependencies.
