### ISSUE TITLE
Subscriptions to topics

### ISSUE THREAD

**Issue by coderantongmail** [wix/react-native-notifications#779]
Please add this feature to support Subscription on topics

for Android
https://github.com/invertase/react-native-firebase/blob/3396da2c4e1acb8eab7616cf0577b1c4b11ea4c0/packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java#L175-L186

for IOS
https://github.com/invertase/react-native-firebase/blob/3396da2c4e1acb8eab7616cf0577b1c4b11ea4c0/packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m#L309-L321

_Originally posted by @Frekansapp in https://github.com/wix/react-native-notifications/issues/503#issuecomment-830246948_

**Comment by Rushiraj-karm** [comment]
any solution for How to subscribe to topic ?

**Comment by Rushiraj-karm** [comment]
> any solution for How to subscribe to topic ?


@coderantongmail 
any solution for How to subscribe to topic ?
