### ISSUE TITLE
Notifications clear when unlocking screen

### ISSUE THREAD

**Issue by nkov** [wix/react-native-notifications#78]
When my device (Android, haven't tested with iOS yet) is locked and I receive a mixed notification, I can see it partially in the lock screen (sensitive content hidden). When I unlock my device, **if the app was already open**, the notifications clear and I'm unable to see what they were.

If the app was closed then I can swipe down the notifications drawer and see them, click them, and engage my app this way. But if the app was already open, they disappear without me reading or tapping on them.

**Comment by iBicha** [comment]
+1
No events are fired, the notification is simply gone

**Comment by mfekim** [comment]
Hello guys, maybe my comment in the following issue can help you : https://github.com/wix/react-native-notifications/issues/143#issuecomment-361987796
