### ISSUE TITLE
BadDeviceToken 

### ISSUE THREAD

**Issue by talaikis** [wix/react-native-notifications#781]
What tokens are returned for iOS, because using them with FCM or APNS gives either `BadDeviceToken` or `The registration token is not a valid FCM registration token`

**Comment by tmaly1980** [comment]
@talaikis Did you ever figure this out? @nacmartin Did you?

**Comment by talaikis** [comment]
> @talaikis Did you ever figure this out? @nacmartin Did you?

No, I switched to `@react-native-firebase/messaging`, which generates correct token, with `@notifee/react-native`, which replaces this library.
