### ISSUE TITLE
[Android] Launch app from notification

### ISSUE THREAD

**Issue by jpmunoz9** [wix/react-native-notifications#782]
Is it possible to have a notification launch the app if it's dead/killed? If it's possible what is the correct way to do it? I currently have the event callbacks setup and working when the app is in the foreground/background. I'm using the latest version react-native-notifications.

Thanks.

**Comment by talaikis** [comment]
Just use firebase's `messaging().onNotificationOpenedApp()`

**Comment by talaikis** [comment]
Just use firebase's `messaging().onNotificationOpenedApp()`
