### ISSUE TITLE
4.1.2 iOS - completionHandler crash

### ISSUE THREAD

**Issue by Vollkorn01** [wix/react-native-notifications#787]
When I open notifications on iOS, the app crashes sometimes (maybe on every 5th open). Only happens when app is in background (not killed state)

Happens on different iOS devices (iPhone X, XS, XR 12 Pro) and versions (iOS 15.1.1 and 14.8.1).
It happened on version 3.4 of the library, as well as 4.1.2.

I saw this has already been raised with #746 and fixed with #692, so I'm wondering if this is a new issue? (Maybe you know more @yogevbd and @enahum, since you have fixed the issue before?)

I attached the crash report:
[testflight_feedback (2).zip](https://github.com/wix/react-native-notifications/files/7596313/testflight_feedback.2.zip)

Screenshot:
<img width="964" alt="Screenshot 2021-11-24 at 15 07 40" src="https://user-images.githubusercontent.com/22402469/143255076-57a9a8bf-5202-4f35-95fa-f7ed1cdef7e2.png">

Thank you very much for developing and maintaining this great library!

**Comment by ramirobg94** [comment]
+1 
![Captura de pantalla 2022-03-31 a las 18 13 58](https://user-images.githubusercontent.com/11272068/161101640-9534ea8b-f655-42fc-a22b-e92817819655.png)
