### ISSUE TITLE
4.1.2 Foreground completion handler crash

### ISSUE THREAD

**Issue by iotashan** [wix/react-native-notifications#791]
iOS 15.1.1, RNN 4.1.2, RN 0.64.1. Whenever I receive a push notification while the app is in the foreground, it crashes:

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/420966/144282739-d116dc8f-2361-4a20-af6c-6944a97da88f.png">

My handler code isn't doing anything out of the ordinary:

```
   RNNotifications.events().registerNotificationReceivedForeground((notification, completion) => {
      logging.info('[NotificationService] Notification Received - Foreground', notification)

      uiStore.setIsUnreadNotification(true);
      logging.info('[NotificationService] Notification Received - Foreground', 'setIsUnreadNotification() done');
      
      // Calling completion on iOS with `alert: true` will present the native iOS inApp notification.
      completion({ alert: true, sound: false, badge: false });
      logging.info('[NotificationService] Notification Received - Foreground', 'completion() done');
    })
```

I rolled back to 3.1.2 on a hunch (#746 mentioned crashes started after upgrading from 3.1.2) and the crashes have gone away. I'm just concerned about not being able to run up-to-date libraries.

**Comment by iotashan** [comment]
Added note, when I accidentally downgraded to 3.5.x (Because I put ^3.1.2 in my package.json) the same crash happened. It was a different line number but still the same.

**Comment by rogierslag** [comment]
For me an issue occurred on iOS if we'd accidentally register multiple times

**Comment by iotashan** [comment]
> For me an issue occurred on iOS if we'd accidentally register multiple times

I bet that's my cause, too. I eventually did figure out I was registering multiple times, but never tried to re-upgrade to this version. Guess it's time!

**Comment by alexanderbezverhni** [comment]
> For me an issue occurred on iOS if we'd accidentally register multiple times

Live saver! Thanks a bunch for this insight.
