### ISSUE TITLE
hot reloading causes ios app to freeze

### ISSUE THREAD

**Issue by Jarvismkennedy** [wix/react-native-notifications#796]
I'm not sure if anyone else has come across this issue, but when I modify a js file and save, so that the app auto refreshes on my iphone, and then send a notification to my phone, my phone freezes and I get an error in RNNotificationCenterMulticast, 
```     dispatch_group_leave(completionGroup);     Thread 1: EXC_BREAKPOINT (code=1, subcode=0x107704e34)```

This happens every single time the javascript auto refreshes. If I close the app, it gets stuck on the splash screen when re opening. The only way to fix it is to re build the app through xcode.

**Comment by Jarvismkennedy** [comment]
This is now happening whenever a notification is sent to the app. Unfortunately I will need to find a new solution for push notifications.

**Comment by DanielEliraz** [comment]
> This is now happening whenever a notification is sent to the app. Unfortunately I will need to find a new solution for push notifications.

Sorry to hear that. Can you provide the iOS version please?

**Comment by Fredkr** [comment]
@DanielEliraz Happening to me as well, on iOS 15.3.1 (happened on 15.2.1 as well).

**Comment by DanielEliraz** [comment]
@Fredkr , I'm not able to reproduce. Can you tell if it started on specific version of us or an iOS versiom?

**Comment by atylee29** [comment]
I encountered the hot reload crash too, and found that running my init code more than once will crash the app on  displaying a subsequent notification. The init code contains:

```
 Notifications.registerRemoteNotifications();
 Notifications.events().registerNotificationReceivedForeground(...)
```

As a temporary fix you can have a init_once wrapper around your init code.
