### ISSUE TITLE
Invariant Error: `Native module cannot be null`

### ISSUE THREAD

**Issue by 25robita** [wix/react-native-notifications#797]
Invariant Error: `Native module cannot be null` when trying to use notifications on iOS (expo go).

```javascript
class App extends Component {
  componentDidMount() {
      Notifications.events().registerRemoteNotificationsRegistered((event) => {
            console.log(event.deviceToken);
        });
  }
}
```

I've tried installing using the installation guide, then doing the manual install, but it came up with an error saying the react-native-notifications pod was stated twice, in `ios/Podfile` and in `node_modules/.../react-native-notifications.podspec`, so I couldn't do that.

I've also tried downgrading, which hasn't solved the issue either. Nor has upgrading expo and react native.

Edit: the module isn't even working in a fresh project

Thanks in advance.

**Comment by berkaygurbuz** [comment]
Try to eject your project using ```expo eject```

**Comment by DanielEliraz** [comment]
@25robita, if the `expo eject` did help as @berkaygurbuz suggests please right it down 🥇

**Comment by DanielEliraz** [comment]
@25robita I'm closing this, please reopen if it continues
