### ISSUE TITLE
Prevent receiving notification in forenground - android

### ISSUE THREAD

**Issue by jhonytaveira** [wix/react-native-notifications#80]

**Comment by jklemmack** [comment]
@jhonytaveira Can you update the name of this issue to spell "foreground" correctly?  It doesn't show up in searches.

**Comment by ddxxtony** [comment]
Try using this line, it works perfectly for me

protected Notification.Builder getNotificationBuilder(PendingIntent intent) {
    ...
    if(super.mAppLifecycleFacade.isAppVisible()) return new Notification.Builder(mContext);
    ...
}

**Comment by dehypnosis** [comment]
hope this can be configurable
