### ISSUE TITLE
Get FCM token instead of APNS

### ISSUE THREAD

**Issue by weihangChen** [wix/react-native-notifications#804]
I am using firebase to distribute the message, and at the moment I am getting APNS token from the library, wondering if this library has builtin support converting APNS token to FCM ? else I will need to get the firebase library into the project just to get the FCM token.....or I will need to call this service every time I get a token myself
https://iid.googleapis.com/iid/v1:batchImport

when I read the source code, there are classes such as FCMToken.java etc, I can only assume that they are supposed to return a valid FCM token instead of APNS one. Can everyone explain how this works?

**Comment by DanielEliraz** [comment]
@weihangChen, I don't understand. in iOS you'll get APNS token and in Android you'll get FCM token. It must be. Do you think you get APNS token in Android???

**Comment by weihangChen** [comment]
@DanielEliraz , I do get APNS token in IOS, which is the desired behaviour, just that APNS token needs to converted into FCM one, I was thinking that the library has some builtin support doing the conversion, but this library has not much to do with firebase as messaging hub actually, but I know better now. Closing case, thanks.

**Comment by fukemy** [comment]
you can use react native firebase

**Comment by fukemy** [comment]
@DanielEliraz because many server backend used fcm to handle message send, that's not mobile dev choice
