### ISSUE TITLE
Type errors

### ISSUE THREAD

**Issue by whenmoon** [wix/react-native-notifications#807]
Followed the [guide](https://wix.github.io/react-native-notifications/docs/localNotifications) to use local notifications.

Straight away ran in to this typescript error:

> Argument of type '{ body: string; title: string; sound: string; silent: boolean; category: string; userInfo: {}; fireDate: Date; }' is not assignable to parameter of type 'Notification'.
  Object literal may only specify known properties, and 'silent' does not exist in type 'Notification'

Is the library still maintained? If not it should be added to the docs, can make a PR if necessary, thanks.

**Comment by dlavrantonis** [comment]
same issue for android here

**Comment by DanielEliraz** [comment]
@whenmoon, give us your PR please!!!

**Comment by DanielEliraz** [comment]
duplicates #809
