### ISSUE TITLE
Incorrect TypeScript types for Notificiation.d.ts

### ISSUE THREAD

**Issue by princefishthrower** [wix/react-native-notifications#809]
According to the docs for `postLocalNotification` (https://wix.github.io/react-native-notifications/docs/localNotifications), the following fields are available as parameters:

```
Notification object contains:

fireDate- The date and time when the system should deliver the notification (optinal - default is immediate dispatch).
body- The message displayed in the notification alert.
title- The title of the notification, displayed in the notifications center.
alertAction- The "action" displayed beneath an actionable notification on the lockscreen (e.g. "Slide to open"). Note that Apple no longer shows this in iOS 10.
sound- The sound played when the notification is fired (optional -- will play default sound if unspecified). This must be the filename of a sound included in the application bundle; the sound must be 30 seconds or less and should be encoded with linear PCM or IMA4.
silent- Whether the notification sound should be suppressed (optional).
category- The category of this notification, required for [interactive notifications](https://wix.github.io/react-native-notifications/docs/localNotifications#interactive--actionable-notifications-ios-only) (optional).
userInfo- An optional object containing additional notification data.
```

Android's signature is much simpler, with `title`, `body`, and `extra` only.

However, the TypeScript types show the following (and _require_ all of them!)

```ts
postLocalNotification(notification: Notification, id?: number): number;
...
export declare class Notification {
    identifier: string;
    payload: any;
    constructor(payload: object);
    get title(): string;
    get body(): string;
    get sound(): string;
    get badge(): number;
    get type(): string;
    get thread(): string;
}
```

I'm wondering where the `badge`, `type`, and `thread` values are coming from? These are not in the docs. Furthermore, plenty of properties are missing. I _am_ on a single minor version behind, `4.1.2`, so let me know if that is the issue.

**Comment by dlavrantonis** [comment]
issue exists on 4.1.3 as well

**Comment by princefishthrower** [comment]
@dlavrantonis - I think the types are just straight up chalked. I wonder if its just from an older version and they haven't been updated or if they're just wrong altogether

**Comment by dlavrantonis** [comment]
The below is observed on Android:
I just traced a notification object coming from the registerNotificationReceivedForeground callback. It looks like this:

{
   "payload":{
      "google.ttl":xxxxx,
      "google.c.sender.id":"xxxxx",
      "google.c.a.e":"1",
      "gcm.notification.body":"test",
      "google.message_id":"xxxxx,
      "gcm.notification.title":"test",
      "collapse_key":"xxxxx",
      "google.delivered_priority":"normal",
      "google.original_priority":"normal",
      "gcm.notification.e":"1",
      "google.sent_time":xxxxxxx,
      "from":"xxxxxxx"
   },
   "identifier":"0:1644175020467910%4589d60e4589d
}

The divergence from the NotificationAndroid dto is huge.
 
Nonetheless i tried to invoke postLocalNotification() by directly passing this incoming object to it   - see code below.
This triggers a local notification but with no title and message body. Even internally in the library things look like to not match.

  Notifications.events().registerNotificationReceivedForeground((notification: Notification, completion) => {
    console.log(`Notification received in foreground: ${notification.title} : ${notification.body}`);
    completion({alert: false, sound: false, badge: false});
    var id = Notifications.postLocalNotification(notification);
  });

**Comment by dlavrantonis** [comment]
> @dlavrantonis , please try it with `Notifications.postLocalNotification(notification.payload);`, should work and indeed the divergence is a bug as I see it. @princefishthrower, the `postLocalNotification` in the docs is only for iOS and that's why we have `badge` there. We need to implement the Android as well. PRs are welcomed 💟

apologies for the late reply, i just tried the above and it worked

**Comment by tbarusseau** [comment]
This issue still exists. Can someone re-open it?
