### ISSUE TITLE
When open local notification, app will open again (Version 4.2.1)

### ISSUE THREAD

**Issue by nmluancs** [wix/react-native-notifications#825]
After you fixed Android API 31 issues (Notification trampoline), now when i open a local notification, app will be cloded and open again.
It happens not only on android 12 but android 11.

I think the problem comes from line 17 - 22 https://github.com/wix/react-native-notifications/blob/master/lib/android/app/src/main/java/com/wix/reactnativenotifications/core/NotificationIntentAdapter.java

Please have a look. Thank you

**Comment by claudiozam** [comment]
@nmluancs i have the same problem on android 12 and 11. Tested on emulator and real devices (Samsung S10, S20).

"react-native": "0.67.2"
"react-native-notifications": "^4.2.0"

**Comment by DanielEliraz** [comment]
answered in #828

**Comment by hankhester** [comment]
@DanielEliraz I'm still experiencing this with version 4.2.3, also I don't see local/foreground notifications mentioned anywhere in #828, is this a different issue?

**Comment by nmluancs** [comment]
I still got the problem with version 4.2.3 :(

**Comment by DanielEliraz** [comment]
please try it with 4.2.4.

**Comment by hankhester** [comment]
@DanielEliraz Hmm, I'm still seeing the same behavior on 4.2.4

**Comment by DanielEliraz** [comment]
@hankhester, the trampoline error is only when `targetSkdVersion > 30`. current React Native targetSkdVersion is 30 so we're good in that.

**Comment by nmluancs** [comment]
Still got the problem with version 4.2.4 :(

**Comment by hankhester** [comment]
@DanielEliraz any update on this? Looks like react-native recently [bumped](https://github.com/facebook/react-native/blob/main/CHANGELOG.md#v0680) the `targetSdkVersion` to 31

**Comment by hankhester** [comment]
Just updating for the record, still experiencing this on 4.3.1

**Comment by AftabUfaq** [comment]
still have same issue on latest verions

**Comment by SchneiderOr** [comment]
Still experiencing it, any new thoughts?

**Comment by pennersr** [comment]
Can we reopen this? The issue persists in 4.3.3 with targetSdkVersion = 31.
