### ISSUE TITLE
How to increment badge when app in background?

### ISSUE THREAD

**Issue by julien9999** [wix/react-native-notifications#827]
Hi, 
How would we auto increment the badge count on iOS when the app is not in foreground?
Tried the following without success:
```
      Notifications.events().registerNotificationReceivedBackground((notif, completion) => {
        Notifications.ios.getBadgeCount((count) => Notifications.ios.setBadgeCount(count + 1));
        completion({ alert: true, sound: true, badge: true });
      });
```

**Comment by DanielEliraz** [comment]
@julien9999, if it's about local notification so you can add badge to the params like this (should be added to docs): 
```
Notifications.postLocalNotification({
    ...
    badge: {{new badge value}},
});
```
If it's about remote notification so you can add the value to the object is being send to APNS as said in apple [docs](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification?language=objc)

**Comment by julien9999** [comment]
Hey Daniel, thanks for your reply. it’s about remote notifications. 
I would like to get the current badge count and increment. Is it possible?

**Comment by DanielEliraz** [comment]
@julien9999, unfortunately we can't count on `registerNotificationReceivedBackground` due to iOS restrictions as stated [here](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application?language=objc&changes=latest_minor): 

> However, the system does not automatically launch your app if the user has force-quit it. In that situation, the user must relaunch your app or restart the device before the system attempts to launch your app automatically again.
