### ISSUE TITLE
Android registerRemoteNotificationsRegistered not called，but iOS is find

### ISSUE THREAD

**Issue by huangjiang2015** [wix/react-native-notifications#829]
in my project , registerRemoteNotificationsRegistered is not called in android ,but ios is OK. event registerRemoteNotificationsRegistrationFailed is not called

**Comment by theambidextrous** [comment]
Hey..... Did you crack this? just ran onto same.. well, it worked for a while and then i re-downloaded the `google-services.json ` file from firebase, rebuild the app and now, here we are.
