### ISSUE TITLE
Notifications.events().registerNotificationOpened() and RNN 4.2.3

### ISSUE THREAD

**Issue by claudiozam** [wix/react-native-notifications#833]
Hi, after the new release 4.2.3 (https://github.com/wix/react-native-notifications/issues/828) the behavior of the implementation changed.

This is the new issue.

Open de App
Go to background (Do not kill de app)
Send new Push notification
Tap on the notification (It will open de app).
Go to background (Do not kill de app)
Send new Push notification and **_do not tap/open the new notification_**
Open the app.
It will execute Notifications.events().registerNotificationOpened() with the last notification payload.

With RNN 4.2.2 i don't have this behavior

Enviroment

"react-native": "0.67.3"
"react-native-notifications": "4.2.3"

Thanks

**Comment by DanielEliraz** [comment]
which android version?

**Comment by claudiozam** [comment]
Android 12 @DanielEliraz

**Comment by DanielEliraz** [comment]
@claudiozam please check it with 4.2.4

**Comment by claudiozam** [comment]
Yes, targetSdk = 30

Samsung S8+ (Anndroid 9) - OK
Samduns S10+ (Android 12) - OK
Emulator (Android 11) - OK

Works excellent

Thanks. @DanielEliraz  !!!!!
