### ISSUE TITLE
registerNotificationReceivedBackground not triggered if app not running - iOS

### ISSUE THREAD

**Issue by Fredkr** [wix/react-native-notifications#834]
Hi,

receivedBackground (& receivedForeground) works fine when app is in foreground. Or in background & still alive.
But nothing is triggered when the app is killed. 

Is this at all supported?

plattform: iOs
version: 15.3.1 & 15.4.x

**Comment by DanielEliraz** [comment]
@Fredkr I will add to docs that it works only when you send background APN as stated in [apple docs](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app?language=objc#:~:text=trigger%20user%20interactions.-,Listing,-1%C2%A0Sample%20payload):
```
{
   "aps" : {
      "content-available" : 1
   },
   "acme1" : "bar",
   "acme2" : 42
}
```

**Comment by Fredkr** [comment]
> 

@DanielEliraz Thanks, but this doesn't answer my question though. 

But after getting some more understanding of the iOS push notifications i believe it's not att all supported on an OS level to receive silent notifications if the app is not running (killed by user etc)? So nothing related to this lib.

**Comment by DanielEliraz** [comment]
Should be added it to the docs as well. @Fredkr PR is welcomed of course 💟
