### ISSUE TITLE
handle registerNotificationReceivedBackground on IOS

### ISSUE THREAD

**Issue by mrjaxi** [wix/react-native-notifications#836]
I cant get data from push when app in background using registerNotificationReceivedBackground on IOS, but i fix this on Android by adding key "pushNotification": true in my request on GoRush server. How can I handle registerNotificationReceivedBackground on IOS?

**Comment by BooBumbleBeeLion** [comment]
i have the same problem with registerNotificationReceivedBackground on ios

**Comment by DanielEliraz** [comment]
Answered in #834

**Comment by mrjaxi** [comment]
> Answered in #834

Yeah, i try this, but it doesn't work

**Comment by nguyendinhdoan** [comment]
I added `"content-available" : 1` to the [payload](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app?language=objc) and it worked.

**Comment by chenweigh** [comment]
After Testing, this callback is only triggered when silently pushed.
