### ISSUE TITLE
push notifications and receiving FCM

### ISSUE THREAD

**Issue by code-by** [wix/react-native-notifications#842]
I'd like to generate local push notifications and also receive and display notifications received from FCM also. Do I need install `@react-native-firebase` so my App will get notifications from FCM?

**Comment by DanielEliraz** [comment]
No, just follow the guide in the docs: https://wix.github.io/react-native-notifications/docs/installation-android#receiving-push-notifications

**Comment by huduarte** [comment]
Daniel, can i use FCM in ios ? only works in android ?

**Comment by DanielEliraz** [comment]
hey @huduarte, not yet. I'll open a new issue for this feature request.
