### ISSUE TITLE
Callback on registerRemoteNotificationsRegistered immediately fired

### ISSUE THREAD

**Issue by djibarian** [wix/react-native-notifications#854]
I've noticed that calling `Notifications.events().registerRemoteNotificationsRegistered(callback)` immediately fires the callback. Is this the expected behaviour?

If so, it's a bit confusing, as I am delaying the call to the callback until `Notifications.registerRemoteNotifications()` as a result of the user being logged in to get the user's Id. But with the current behaviour I have to check inside the callback if the user's Id is available, which is not ideal.

**Comment by passengerV** [comment]
If this behavior is present only on Android, it's due Firebase's auto-initialization. By default, if there is connection to the internet the SDK will generate a token and .registerRemoteNotificationsRegistered will be triggered.
