### ISSUE TITLE
Is the Android import in MainApplication.java really needed?

### ISSUE THREAD

**Issue by djibarian** [wix/react-native-notifications#855]
I wonder what's the purpose of the following import:

```
import com.wix.reactnativenotifications.RNNotificationsPackage;
```

in `MainApplication.java`. As stated by the docs this is needed, but I don't get any different results if I remove it.

**Comment by Aure77** [comment]
I think it's useless. RN 0.6x+ auto link native modules.
https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
