### ISSUE TITLE
Notification received twice when app in background on Android

### ISSUE THREAD

**Issue by Aure77** [wix/react-native-notifications#856]
When I received a remote notification from FCM. I receive 2 notifications in notification center.

- First: take care of my custom settings (custom notif icon, ...) + custom payload
- Second: appearing "blank": contains only title (no description) and use app icon (default).

After some debugging, it's due to this call:
https://github.com/wix/react-native-notifications/blob/e5dad8ad56080bf5f68d061a67ade8dc2f8ea857/lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java#L66
that push this second "blank" notification to notification center (first notification is already present before this point, seems to be handled by FCM ?).

Any idea ?

**Comment by diegolmello** [comment]
This is still an issue.
