### ISSUE TITLE
No Icon/Empty white icon in received remote notification

### ISSUE THREAD

**Issue by ayeshq** [wix/react-native-notifications#86]
Hi

I'm receiving remote notifications successfully on Android, showing Title, message, and body.

But the icon used for the notification is always an empty white icon !

This is a sample of the notification schema:

What am I missing ?

```
{
	"data": {
		"Notification": "{\"Name\":\"Extra json to be parsed by react when clicking the notification\"}",
		"title": "You have a new message from X",
		"message": "You have a new message from X",
		"body": "You have a new message from X"
	}
}
```

**Comment by ricms93** [comment]
+1

**Comment by avdept** [comment]
Same issue.

**Comment by arunkumarrmrj** [comment]
i've same issue

**Comment by ayeshq** [comment]
The empty white icon is the android's default app launcher icon, with a white/gray color overlay.
This is the default behavior when showing a notification.
To fix this issue, a new icon of your choice should be used when showing the notification, and this is documented in the [WIKI](https://github.com/wix/react-native-notifications/wiki/Android:-Layout-Customization).
