### ISSUE TITLE
Unable to get Android device token through registerRemoteNotificationsRegistered 

### ISSUE THREAD

**Issue by kd4g** [wix/react-native-notifications#860]
I am using the following versions and followed all the steps outlined in 
https://wix.github.io/react-native-notifications/docs/installation-android

react-native-notifications": "^4.2.4"
"react-native": "0.68.0",

registerRemoteNotificationsRegistered callback is not getting called after  Notifications.registerRemoteNotifications(). So I am unable to get device token. 

Here is the code snippet: 

      Notifications.events().registerRemoteNotificationsRegistered(event => {.
          console.log(" Device Token Received" + event.deviceToken);
      }
      );
      Notifications.events().registerRemoteNotificationsRegistrationFailed((event) => {
          console.error(event);
      });
   
      Notifications.registerRemoteNotifications();

I ensured all changes are done to build.grade, gradle.settings as outlined in the document. 

Any details about why callback is not  called will be helpful. 

Thanks!

**Comment by ErkanGorgulu** [comment]
I am having the same problem right now. Any solutions or workarounds?

**Comment by samjayhk** [comment]
any solutions?

**Comment by moonbe77** [comment]
Same on IOS device

**Comment by robfrancis** [comment]
Has anyone manage to resolve this issue yet? or have a workaround?

**Comment by Anamcoollzz** [comment]
Hmm, how to fix it :(

**Comment by Bilal-Abdeen** [comment]
I am having the same issue. 

```javascript
Notifications.events().registerRemoteNotificationsRegistered( (event) => { 
  // Code execution never reaches this point 
  console.log("registerRemoteNotificationsRegistered - deviceToken:", event.deviceToken, ); 
});
```
`react-native: 0.68.2`
`react-native-notifications: 4.3.1`

**Comment by aljimsondev** [comment]
Same issue here, any progress??

**Comment by ls-andrew-borstein** [comment]
In case it's helpful to anyone else, updating settings related to Google FCM fixed this issue for me. I was clued in by [this comment](https://github.com/wix/react-native-notifications/issues/801#issuecomment-1008165639) and re-downloaded the `google-services.json` file. I also updated some of the gradle code based on [what's in the docs](https://wix.github.io/react-native-notifications/docs/installation-android). After updating all of that info, the token started magically appearing and the function body was now accessible.

My guess is the function body isn't reached unless a valid token is present, which may not be returned if Google FCM isn't set up correctly. 

```
"react-native": "0.67.4",
"react-native-notifications": "^4.2.4",
```

**Comment by nguyendinhdoan** [comment]
I'm getting stuck on this issue too.
```
"react-native": "0.69.7",
"react-native-notifications": "4.3.5"
```
