### ISSUE TITLE
4.3.1 - Android 12 crash on RN 0.68.1 (java.lang.NullPointerException)

### ISSUE THREAD

**Issue by jonesaustindev** [wix/react-native-notifications#864]
Hello! Right now I am getting the error below on Android 12 with RN 0.68.1 using 4.3.1 of this library

```
com.wix.reactnativenotifications.core.notification.PushNotificationProps.asBundle
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.clone()' on a null object reference
```

```
com.wix.reactnativenotifications.core.notification.PushNotificationProps.asBundle PushNotificationProps.java:26
com.wix.reactnativenotifications.core.notification.PushNotification.notifyOpenedToJS PushNotification.java:210
com.wix.reactnativenotifications.core.notification.PushNotification.dispatchImmediately PushNotification.java:127
com.wix.reactnativenotifications.core.notification.PushNotification$1.onAppVisible PushNotification.java:36
```

Seems to be the same as seen in #835

**Comment by jonesaustindev** [comment]
Does there happen to be any info or movement made around this issue?

**Comment by KimJeonghun91** [comment]
I am also it.
It happened When I clicked the android notification alert.

**Comment by gabrielbezerra81** [comment]
Same behavior here, I cant open push notifications in background. This is blocking us from bumping compileSdkVersion to 31.

**Comment by walterholohan** [comment]
I just got this error from a user too. Users device info below

<img width="375" alt="image" src="https://user-images.githubusercontent.com/5293650/171420136-e670b85c-7604-46cc-b2c4-64be0a778c91.png">

**Comment by simona-iuliana** [comment]
same error with RN 0.68.2 using 4.3.1 of this library, any updates on this?

**Comment by pepf** [comment]
Try https://github.com/wix/react-native-notifications/issues/835#issuecomment-1152155685 :)

**Comment by jonesaustindev** [comment]
Not stale, still very much an issue on the latest version `4.3.1`

**Comment by jonesaustindev** [comment]
@DanielEliraz would you or someone else have a clue on this one by chance?

**Comment by pepf** [comment]
Please keep this issue open 🙏🏼

**Comment by PROda221** [comment]
I am facing the same issue

**Comment by ernstmul** [comment]
Yep, also facing this issue!

**Comment by walterholohan** [comment]
@gabrielbezerra81 what issue did you have with Notifee, i migrated our app over to use a combination of notifee and firebase messaging. Both libraries are maintained by the same company
