### ISSUE TITLE
Error building on Android. 

### ISSUE THREAD

**Issue by vivekperumal** [wix/react-native-notifications#867]
I installed latest version of this library and getting build issue on Android. It is working fine on iOS.

Version:

 "react-native": "0.64.3",
 "react-native-notifications": "^4.3.1",

Freshly installed yesterday and getting this issue.

Here is the error. Anyone have any idea?

`Execution failed for task ':react-native-notifications:compileReactNative60DebugJavaWithJavac'.
node_modules/react-native-notifications/lib/android/app/src/main/java/com/wix/reactnativenotifications/core/ReactAppLifecycleFacade.java:50: error: cannot find symbol
        return mReactContext.hasActiveReactInstance();
                            ^
  symbol:   method hasActiveReactInstance()
  location: variable mReactContext of type ReactContext
`

**Comment by riogrande100** [comment]
Downgrading to 4.2.4 worked for me.

**Comment by DanielEliraz** [comment]
starting RN@0.66 they changed the function name. I'll add them both

**Comment by vivekperumal** [comment]
Is that function name change for notification not recieving in Notification Center but able to see in console?

**Comment by luizppa** [comment]
It did not solved the problem for me in a forked version of this repository (up to date with master) and RN 0.64.2.
Using:
```java
@Override
public synchronized boolean isReactInitialized() {
    if (mReactContext == null) {
        return false;
    }

    try {
        return mReactContext.hasActiveCatalystInstance();
    } catch (Exception e) {
        return mReactContext.hasActiveReactInstance();
    }
}
```
still gave me the same error, I had to change it back to:
```java
@Override
public synchronized boolean isReactInitialized() {
    if (mReactContext == null) {
        return false;
    }

    return mReactContext.hasActiveCatalystInstance();
}
```
on my fork.
Obs.: I am not a java developer in any shape form or fashion, it is entirely possible that I did something wrong.

**Comment by Arkan4ik** [comment]
@luizppa have you solve this issue?

**Comment by luizppa** [comment]
> @luizppa have you solved this issue?

Yes, you can check out the result in [this fork](https://github.com/escolaemmovimento/react-native-notifications). It also has some other modifications, so I wouldn't recommend using it without checking the diff to the original repository.

**Comment by Arkan4ik** [comment]
> > @luizppa have you solved this issue?
> 
> Yes, you can check out the result in [this fork](https://github.com/escolaemmovimento/react-native-notifications). It also has some other modifications, so I wouldn't recommend using it without checking the diff to the original repository.
> 
> [This is the commit specifically](https://github.com/escolaemmovimento/react-native-notifications/commit/f677b585612eda0559fb9f5eeb773f6c77ea6b49).

@luizppa yep, I also used it according to deprecation. Seems like need to upgrade react native version for support that method. Thank you for fast response!
![image](https://user-images.githubusercontent.com/23438777/170883039-9a6bd8ca-6211-4372-9f2c-a4e726b486fe.png)

https://github.com/facebook/react-native/blob/main/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactContext.java
