### ISSUE TITLE
Background notification completion callback

### ISSUE THREAD

**Issue by georgeflug** [wix/react-native-notifications#871]
I am using the `registerNotificationReceivedBackground()` event to receive background notifications.

According to [the documentation](https://wix.github.io/react-native-notifications/docs/notifications-events), the completion callback should be called with a payload such as `{alert: true, sound: true, badge: false}`. However, that does not match the Typescript types, and diving into [the code](https://github.com/wix/react-native-notifications/blob/aeaea302ea454962b92b58298d4946cde8b52921/lib/src/events/EventsRegistry.ts#L26), it wants a payload with a `NotificationBackgroundFetchResult` value of `newData`, `noData`, or `failed`.

Can someone explain what these values mean so that I know which one to provide in the callback?

Thank you in advance.

**Comment by SandraHicks** [comment]
I am just right now asking myself the same question. Also, there is no explanation what the enum values mean. To my mind, the documentation version makes much more sense. Could someone please explain how to use it correctly?

**Comment by NivardoX** [comment]
Makes little sense to me, and I see it nowhere in the docs. @DanielEliraz perhaps you could shed some light on this?

Thank you in advance.
