### ISSUE TITLE
Error building on Android: cannot find symbol -> variable R

### ISSUE THREAD

**Issue by maximilianlembke** [wix/react-native-notifications#873]
-    react-native-notifications -> 4.3.1

-   react-native -> 0.67.4

I always get this error if I try to build my App in Android Studio.

`node_modules/react-native-notifications/lib/android/app/src/main/java/com/wix/reactnativenotifications/core/NotificationIntentAdapter.java:35: error: cannot find symbol
        return Build.VERSION.SDK_INT >= Build.VERSION_CODES.R && appContext.getApplicationInfo().targetSdkVersion >= 31;
                                                           ^
  symbol:   variable R
  location: class VERSION_CODES`

Anyone have any idea?

**Comment by DanielEliraz** [comment]
validate you have `android 11 (R)` installed in `Preferences | Appearance & Behavior | System Settings | Android SDK`
