### ISSUE TITLE
Typing of `postLocalNotification` is incorrect

### ISSUE THREAD

**Issue by thomasttvo** [wix/react-native-notifications#875]
- No support for `silent` parameter
- Optional parameters are not optional

![image](https://user-images.githubusercontent.com/2142140/171479575-22b1017e-fec0-47b7-8e99-7b6b7e4e6722.png)

**Comment by tomekpilat** [comment]
I'm experiencing the same issue. @thomasttvo  have you been able to resolve it?

**Comment by thomasttvo** [comment]
I switched to `notifee`, so much better on all fronts

**Comment by edualm** [comment]
Bad bot - it's still happening.

**Comment by Tessaroo** [comment]
issue is still present, documentation for this library has been a roller coaster

**Comment by mehdi-developer** [comment]
@thomasttvo I did too and it is awesome just one question what version of xcode and iOS is ok with the latest version of notifee ?

**Comment by camboYY** [comment]
not work for android

**Comment by jcarioti** [comment]
> I switched to this lib https://notifee.app/, so much better on all fronts

How did you handle the missing APNS registration that Notifee doesn't support? I tried to swap it out, but it only seems to support FCM.

**Comment by chrisarts** [comment]
> > I switched to this lib https://notifee.app/, so much better on all fronts
> 
> How did you handle the missing APNS registration that Notifee doesn't support? I tried to swap it out, but it only seems to support FCM.

thats right Im working with Azure notifications HUB and notifee combined with this lib does not fire notifications when you are using other apps.

**Comment by jcarioti** [comment]
> 

We aren't doing any background fetch with Notifee, but it sounds like you're not calling the completion handlers in time?

We also landed on a hybrid approach of using this library with Notifee. RN Notifications is responsible for the remoteRegistration portion, and the foreground remote notification reception, and then we pipe everything through Notifee for the final notification. So all of our notifications come from Notifee besides the remote ones we don't currently intercept.

I really hope this gets cleaner soon, because it's really janky as-is. IMO, Notifee is the way to go if we had a clear/concise replacement for RN Notification's remote registration logic. We might just do it natively since it's not super complex.

**Comment by chrisarts** [comment]
This is my approach the onNotificationHandler is just in char of display the local notification based on the payload sent by Azure hub.

![Screen Shot 2022-10-07 at 7 12 01 PM](https://user-images.githubusercontent.com/3628422/194677270-ba738f4c-6b0d-417f-b2a0-fdcd4970b480.png)

**Comment by AloeareV** [comment]
Issue is still present

**Comment by kg-currenxie** [comment]
Pls fix :|

**Comment by josef256** [comment]
pretty sure this lib is "abandonware"
i'll just move on to react-native-push-notification

**Comment by kg-currenxie** [comment]
> pretty sure this lib is "abandonware" i'll just move on to react-native-push-notification

https://github.com/zo0r/react-native-push-notification ? its officially not maintained, and lastly updated Dec 2021

**Comment by josef256** [comment]
> > pretty sure this lib is "abandonware" i'll just move on to react-native-push-notification
> 
> https://github.com/zo0r/react-native-push-notification ? its officially not maintained, and lastly updated Dec 2021

yeah i saw that.. it has also problem with react 0.71+
 i tried https://github.com/invertase/notifee meanwhile and it works great  out of the box plus it's actively maintained

**Comment by kg-currenxie** [comment]
> i tried [invertase/notifee](https://github.com/invertase/notifee) meanwhile and it works great out of the box plus it's actively maintained

cool, good to know :) it wasn't free when we started implementing
