### ISSUE TITLE
Autolinking does not work with React Native 0.69.0

### ISSUE THREAD

**Issue by Naturalclar** [wix/react-native-notifications#881]
## Issue
Due to change in react-native cli, https://github.com/react-native-community/cli/pull/1537 
Autolinking is no longer working with React Native 0.69

## Expected Behavior
React Native autolinking to work with RNNotifications

## Repro Steps:

- Create a new React Native Project version 0.69
- install react-native-notifications
- run pod install in `ios` directory

Notice that RNNotifications is not included in the Podfile.lock

Repro repository
https://github.com/Naturalclar/react-native-notifications-repro

**Comment by haleyngonadi** [comment]
Bumping! I'm also facing the same issue with 69.1

Running `npx react-native run-ios` returns an error:

> warn Package react-native-notifications contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.

**Comment by nguyendinhdoan** [comment]
I'm getting the same issue
```warn Package react-native-notifications contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.```

**Comment by Erik-Schlegel** [comment]
Same issue regarding "dependency.assets".

**Comment by 03Farhan** [comment]
You can make a patch using changes from https://github.com/wix/react-native-notifications/pull/882. Hopefully that change is merged soon, but in the meantime you can do this:

1. install `patch-package`
2. create a folder in your project called "patches"
3. inside "patches" create a file named `react-native-notifications+4.3.1.patch` with the following content:
```
diff --git a/node_modules/react-native-notifications/react-native.config.js b/node_modules/react-native-notifications/react-native.config.js
index 437783b..d246b0c 100644
--- a/node_modules/react-native-notifications/react-native.config.js
+++ b/node_modules/react-native-notifications/react-native.config.js
@@ -7,7 +7,6 @@ module.exports = {
         packageInstance: 'new RNNotificationsPackage(reactNativeHost.getApplication())',
       }
     },
-    assets: []
   },
   project: {
     ios: {

```
4. add "patch-package" in postinstall in package.json before doing yarn install.
`package.json`:
```
"scripts": {
    ...
    "postinstall": "patch-package"
}
```
5. run `yarn install` or `npm install`

**Comment by xtovski** [comment]
Same thing on RN 0.7.0, with react-native-notifications 4.3.1

**Comment by ajithes1** [comment]
+1

**Comment by upngo** [comment]
still happening with latest release

**Comment by ZiaHazara** [comment]
any update on this issue still facing it.
Thanks
