### ISSUE TITLE
Receiving warning "No task registered for key ReactNativeFirebaseMessagingHeadlessTask"

### ISSUE THREAD

**Issue by javitolin** [wix/react-native-notifications#883]
As the title says, when I'm receiving a notification in the background, react-native logs a warning to the console specifying:
`No task registered for key ReactNativeFirebaseMessagingHeadlessTask`

What am I missing in the configuration?
I tried to look at it in the example but found nothing..
Thanks

**Comment by javitolin** [comment]
Found a fix.
Need to
```
# Install & setup the app module
yarn add @react-native-firebase/app

# Install the messaging module
yarn add @react-native-firebase/messaging
```

And then add at index.js:
```
import messaging from "@react-native-firebase/messaging";

// Register background handler
messaging().setBackgroundMessageHandler(async (remoteMessage) => {
  console.log("Message handled in the background!", remoteMessage);
});
```

**Comment by gentlee** [comment]
@javitolin This is not a fix to use another library. Can you reopen pls?

Still happens in 4.3.3 and 5.1.0.

**Comment by javitolin** [comment]
It worked for me then.. This is from 3 years ago, I don't think I should re open this.. Maybe open a new issue?

**Comment by gentlee** [comment]
Ok, opened (linked above).
