### ISSUE TITLE
iOS - Native method didReceiveRemoteNotification doesn't trigger if [RNNotifications startMonitorNotifications]; is in didFinishLaunchingWithOptions

### ISSUE THREAD

**Issue by jpamarohorta** [wix/react-native-notifications#885]
Hello, I have a use case where I need to combine multiple push notifications SDKs (e.g. Oracle & AppsFlyer) and still need to handle the push notification in React Native to show alerts (in foreground) and open a deep link (in background/terminated if the notification is pressed).

I've followed the iOS [documentation](https://wix.github.io/react-native-notifications/docs/getting-started) and I noticed that if `[RNNotifications startMonitorNotifications];` is present in the `didFinishLaunchingWithOptions` method I'm able to get the correct callbacks in React Native (for both foreground and background) but the native methods like `didReceiveRemoteNotification` never run, which stops me from using other push notifications related native SDKs. 

If I remove `[RNNotifications startMonitorNotifications];` from `didFinishLaunchingWithOptions` the native callbacks start working again.
 
Is this a bug or an expected behaviour? In the iOS documentation it indicated that the native method `- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult result))completionHandler` should be implemented.

I'm using versions:
```
react-native: 0.65.1
react-native-notifications: 4.3.1
```

Thank you

**Comment by sakramentas** [comment]
@yedidyak Did you figure out what's the issue?
