### ISSUE TITLE
registerRemoteNotificationsRegistered not working on iOS in RN 0.68.x

### ISSUE THREAD

**Issue by lfrkovic-spaceiq** [wix/react-native-notifications#887]
We have a React Native 0.67.4 app in production which works fine on iOS. However, since updating to RN 0.68.2 (and I'm not sure this is the cause of the issue), calling registerRemoteNotificationsRegistered does nothing on iOS. We're not receiving a device token and neither registerRemoteNotificationsRegistrationFailed or registerRemoteNotificationsRegistrationDenied are getting triggered.

Android seems to work fine.

**Comment by tauntmachine** [comment]
any luck? kindly do share.

**Comment by lfrkovic-spaceiq** [comment]
Not yet, no. Sorry.
