### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by egadstar** [wix/react-native-notifications#889]
Is this library still being maintained? Seems like there are some issues with Android and RN 0.69 that have pull requests, but no other activity; trying to gauge if I should consider an alternative. Thanks.

**Comment by claudiozam** [comment]
Hi @DanielEliraz, do you have information about this? can you help us? Thanks

**Comment by claudiozam** [comment]
@egadstar https://www.npmjs.com/package/@react-native-firebase/messaging but it's not working with hermes and you must change your backend implementation if you use IOS + PUSH.

**Comment by egadstar** [comment]
Yeah, I been experimenting with Firebase and Notifee, but need to work out some additional changes to make it work.

**Comment by princefishthrower** [comment]
@egadstar - to clarify, you've migrated away from this library? I remember staring to implement with notifee a year back or so but their feature set wasn't as good as this one. But, I've been waiting for a TypeScript typing update on this lib for about the same amount of time, so maybe it's time to look somewhere else...

**Comment by egadstar** [comment]
I haven’t let. To migrate, I need to first upgrade our project to RN ^0.69.1 due to some issues with react-native-firebase that have been patched for that RN version or use an older version of react-native-firebase. I think 14.0.x…would need to look again through the issues. My plan was just to move to 0.69.x as I would likely do that at some point anyway, but we use reanimated and sentry; both of which have release candidates for major versions with RN 0.69.0 support, so waiting on official releases before thinking about using them in production. The only trade off with firebase and notifee on iOS is that it relies on background processing which users can disable for your app, and in low power mode, iOS will suspend it which prevents push notifications. I might consider forking cause I prefer this library over firebase for iOS; weighing out what’s best long-term for our application.

**Comment by egadstar** [comment]
@princefishthrower took some work, but I manged to get off this library and onto react-native-firebase and notifee(only use it for its convenient channel setup for Android and foreground presentation). it did require me to use react-native-permissions to support Android 13 permission request, but overall everything appears to be working well.

**Comment by princefishthrower** [comment]
@egadstar - thanks a lot for this insight. We may be headed in the same direction. If I could pick your brain one last time, do you have any automated ways of testing push notifications? We're struggling to accurately test all the various states of handling push notifications (app closed completely, app running in background, app currently active (foreground)). Also amazing to hear Notifee is going full open source! (That may have been a reason we didn't migrate there originally)

**Comment by egadstar** [comment]
@princefishthrower unfortunately, don’t have any automated testing for push. i got in the habit of checking the implementation while developing and never looked for a solution. good luck.

**Comment by seco35** [comment]
I think it's time to move away, if the stale bot closes the "Still maintained?" question.

**Comment by claudiozam** [comment]
@seco35 yes..... 

<img width="320" alt="image" src="https://user-images.githubusercontent.com/2105644/224705875-15cfea87-492a-4f6a-b3c9-a3ec7da2d7da.png">
