### ISSUE TITLE
Is this protect EOL, not compatible with Android API 31+

### ISSUE THREAD

**Issue by russmenum** [wix/react-native-notifications#890]
As of this month, all new Android apps must target API 31
```
compileSdkVersion = 31
targetSdkVersion = 31
```

As of Nov 2022, All Android Apps must ([SEE HERE](https://developer.android.com/google/play/requirements/target-sdk#:~:text=Starting%20in%20August%202022%2C%20new,behavioral%20changes%20in%20Android%2012))

This change requires the ```android:exported="true"``` or ```android:exported="false"``` to be defined. If it is not the app can not be installed.

When you set API 31 you get an ERROR attributed to this library.
```
Installation did not succeed.
The application could not be installed: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED

List of apks:
[0] '/Users/[USERNAME]/github/[APP]/android/app/build/outputs/apk/release/app-release.apk'
Installation failed due to: 'Failed to commit install session 1735472622 with command cmd package install-commit 1735472622. Error: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1735472622.tmp/base.apk (at Binary XML file line #148): com.wix.reactnativenotifications.fcm.FcmInstanceIdListenerService: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present'
Retry
Failed to launch an application on all devices
```

I am digging into the code, but not seeing what lines need to change for this library, sorry. I just know if there is not a patch for this in the next 60 days no one can use this for an RN Android App anymore

**Comment by claudiozam** [comment]
@russmenum try this:

https://rnfirebase.io/messaging/usage
https://notifee.app/

**Comment by russmenum** [comment]
@claudiozam So this is EOL and your suggestion is to move to that new library that went free you reference? Not even using fire base right now, really just the local notifications

**Comment by claudiozam** [comment]
@russmenum i don't see another option (production ready) for the moment. Do you have one?

**Comment by russmenum** [comment]
@claudiozam I guess I need to start looking, we only have a few months. My hope was there was an update or patch pending for this project

**Comment by RosenTomov** [comment]
We're facing a similar issue and the requirement to target SDK version 31. Is this project really dead @wixmobile?

**Comment by russmenum** [comment]
@max-usenko-aura if I add 

```
<service android:name="com.wix.reactnativenotifications.fcm.FcmInstanceIdListenerService" android:exported="true" />
```

The error goes away, but the resulting "launched" app just crashes at load on the API 31 simulator. Will run fine on API 30 simulator. No error I can see in debug launch, any idea? Not even sure it is this library, but something is not happy

**Comment by christiandietz80** [comment]
Hello everyone, 

not sure if this helps; in our project, we have these settings (in file build.gradle), and everything works fine:

buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "20.1.5948944"
        androidXAnnotation = "1.2.0"
        androidXBrowser = "1.4.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.2.0')
        classpath('com.google.gms:google-services:4.3.10')
    }
}

**Comment by russmenum** [comment]
> Hello everyone,
> 
> not sure if this helps; in our project, we have these settings (in file build.gradle), and everything works fine (updating our existing app, not publishing a new one):
> 
> buildscript { ext { buildToolsVersion = "30.0.2" minSdkVersion = 21 compileSdkVersion = 31 targetSdkVersion = 31 ndkVersion = "20.1.5948944" androidXAnnotation = "1.2.0" androidXBrowser = "1.4.0" } repositories { google() jcenter() } dependencies { classpath('com.android.tools.build:gradle:4.2.0') classpath('com.google.gms:google-services:4.3.10') } }

Is that running on an API 31 simulator?
