### ISSUE TITLE
Notification is not popping up when app is in foreground

### ISSUE THREAD

**Issue by zahs** [wix/react-native-notifications#891]
Platform: ios, Android

Notification is not popping up when app is in foreground.
What can be the reason?

**Comment by nguyendinhdoan** [comment]
it's hidden by default

**Comment by nmengual** [comment]
What is the parameter or configuration for them to be displayed?

**Comment by devmahmud** [comment]
I am facing similar issue. Any workaround?

**Comment by zahs** [comment]
@nguyendinhdoan Do you know how it will be possible to enable for Android?

**Comment by josaric** [comment]
I'll be working on it today or tomorrow and I'll let you know @zahs 

for iOS I have added this to my AppDelegate.h

Update AppDelegate.h
At the top of the file:

#import <UserNotifications/UNUserNotificationCenter.h>
Then, add the 'UNUserNotificationCenterDelegate' to protocols:

@interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate, UNUserNotificationCenterDelegate>

and for AppDelegate.mm
just follow these docs:
https://wix.github.io/react-native-notifications/docs/getting-started#ios

and put this part from my top comment:
https://github.com/wix/react-native-notifications/issues/891#issuecomment-1260741637

I have implemented all listeners as they should be, with background and foreground notifications

![Screenshot 2022-09-28 at 13 18 21](https://user-images.githubusercontent.com/10531443/192765997-63dfc6c1-789d-42d7-a415-173357c63d08.png)

**Comment by zahs** [comment]
Perfect thank you :)
for iOS it is working already for me.

**Comment by camboYY** [comment]
android does not work

**Comment by daveslutzkin** [comment]
This was happening for us but then we realised it was necessary to explicitly handle the notification received foreground event in the react native code:

```
  Notifications.events().registerNotificationReceivedForeground((notification, completion) => {
    completion({ alert: true, sound: false, badge: false })
  })
```

Without handling that event like that, no notifications were shown when in the foreground.

**Comment by josaric** [comment]
> This was happening for us but then we realised it was necessary to explicitly handle the notification received foreground event in the react native code:
> 
> ```
>   Notifications.events().registerNotificationReceivedForeground((notification, completion) => {
>     completion({ alert: true, sound: false, badge: false })
>   })
> ```
> 
> Without handling that event like that, no notifications were shown when in the foreground.

I have followed the documentation and everything works correctly.

**Comment by harendraskd** [comment]
1. I also follow the doc but I did not get notifications when the android app is in the foreground.Please help us to implement.

2. In IOS Notification, image are not shown.
