### ISSUE TITLE
有个问题，我不知道这些参数是啥意思，包括从哪里得到，求帮助

### ISSUE THREAD

**Issue by Jack-QMY** [wix/react-native-notifications#893]
有个问题，我不知道这些参数是啥意思，包括从哪里得到，求帮助
![image](https://user-images.githubusercontent.com/57746139/186609532-42da9e3f-e354-47ce-adb3-dc8d39988520.png)

**Comment by erictong990602** [comment]
可以看一下document, https://wix.github.io/react-native-notifications/docs/localNotifications
