### ISSUE TITLE
App crash when send notifications

### ISSUE THREAD

**Issue by Salmankhan033** [wix/react-native-notifications#899]
When I sent notifications from the server then it crashed.

<img width="1440" alt="Screenshot 2022-10-05 at 8 21 19 PM" src="https://user-images.githubusercontent.com/58082294/194098734-d54eb7dc-94a1-4548-b02a-99297cc81191.png">

**Comment by tkyr-hh** [comment]
@Salmankhan033  can you please try this [solution](https://github.com/wix/react-native-notifications/issues/835#issuecomment-1152155685)
