### ISSUE TITLE
Android 11 and above crashing on notification open

### ISSUE THREAD

**Issue by qasimkhan23** [wix/react-native-notifications#910]
The app crashes while opening the notification and shows the following message
**java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.clone()' on a null object reference**

currently using version 4.3.1

this patch fixes the problem
fiel path: 
[
react-native-notifications/lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java](https://github.com/wix/react-native-notifications/blob/a18a593e3a62f7a0d1e8f6bfae354f4af2b4c669/lib/android/app/src/main/java/com/wix/reactnativenotifications/core/notification/PushNotification.java#L208-L213)

#
```
 private void notifyOpenedToJS() { 
     Bundle response = new Bundle(); 
     response.putBundle("notification", mNotificationProps.asBundle()); 
     mJsIOHelper.sendEventToJS(NOTIFICATION_OPENED_EVENT_NAME, response, mAppLifecycleFacade.getRunningReactContext()); 
 }
 ```

to

```
 private void notifyOpenedToJS() {
        Bundle response = new Bundle();
        try {
            response.putBundle("notification", mNotificationProps.asBundle());
        } catch (NullPointerException e) {
            Log.e(LOGTAG, "notifyOpenedToJS: Null pointer exception");
        }
```

**Comment by kg-currenxie** [comment]
The patch worked. This should be merged 😓 Too bad wix has abandoned the repo?
