### ISSUE TITLE
Local Notification are not received in Android 

### ISSUE THREAD

**Issue by mahipalsingh-syt** [wix/react-native-notifications#916]
Local  notification is not received on android device 

Code  : 

const channelInfo: any = {
      channelId: "channelname",
      name: "channelname",
      importance: 4,
      description: "channelname tool",
      enableVibration: true,
      showBadge: true,
    }
    Notifications.setNotificationChannel(channelInfo)
    
    

 const time = new Date(Date.now() + 10 * 1000)
    this.scheduleNotification({
      date: time,
      title: "Notification No:" + time.toString(),
      message: "item.title",
      id: "testNotification",
    })

**Comment by AdamGerthel** [comment]
I haven't used this package (yet) but doesn't it say in the readme that it doesn't support local notifications for Android yet?

> Upcoming: local notifications, background-state Rx queue (iOS equivalent)

[Source](https://github.com/wix/react-native-notifications#android)
