### ISSUE TITLE
Possible to set the initial notification when the app is being foregrounded?

### ISSUE THREAD

**Issue by RyanSept** [wix/react-native-notifications#918]
Currently if the app was already running but in the background and the user opens it via a push notification, `getInitialNotification()` returns undefined. Is it possible to set the initial notification to be available when the app is being foregrounded?

This was tested on Android 12
```
"react-native": "0.66.4",
"react-native-notifications": "4.3.2"
```

**Comment by cheymonty** [comment]
try all of these to see which gets called
```
Notifications.events().registerNotificationReceivedForeground((notification, completion) => {
      console.log(notification)
});
```
```
Notifications.events().registerNotificationReceivedBackground((notification, completion) => {
      console.log(notification)
});
```

```
Notifications.events().registerNotificationOpened((notification, completion) => {
      console.log(notification);
});
```

**Comment by blolo** [comment]
@RyanSept did you manage to find a solution to thus issue?

**Comment by RyanSept** [comment]
@blolo I used [AsyncStorage](https://reactnative.dev/docs/asyncstorage) to store the notification upon registerNotificationOpened() then when the app rendered I have a callback that checks a notification is present in AsyncStorage and does actions on it.
