### ISSUE TITLE
Adding Image to the notification #Help  🙏🏽

### ISSUE THREAD

**Issue by tdammy92** [wix/react-native-notifications#923]
Hi,

Please this is  a question and not an issue, 
How do i pass notifications icons, eg {largeIcon,largeIconUrl, smallIcon } in this package ?. 

##working on a chat project, and i want to pass the sender image_url to display on the notification.
  
  Thank you.

**Comment by DusanSpasojevic98** [comment]
.

**Comment by BELHAJDEV** [comment]
.
