### ISSUE TITLE
[Android][iOS] postLocalNotification dispatches immediately 

### ISSUE THREAD

**Issue by minhnc** [wix/react-native-notifications#926]
Hi, when scheduling a local notification, it dispatches notification instantly in Android 12. The same thing happens in iOS.
What could be the reason? Has anyone experienced similar issue?

```
"react-native": "0.66.3",
"react-native-notifications": "4.3.3"
```

Sample code:

```javascript
let date = new Date()
date.setMinutes(date.getMinutes() + 5)

Notifications.postLocalNotification({
    body: 'Local notification!',
    title: 'Title',
    fireDate: date,
})

```

**Comment by Waltari10** [comment]
Not sure why it's not working on iOS, but at least the docs state that fireDate is not supported for Android at all yet: https://wix.github.io/react-native-notifications/docs/localNotifications
