### ISSUE TITLE
Local notification is not working

### ISSUE THREAD

**Issue by proactive-solutions** [wix/react-native-notifications#93]
Hello,

I have installed the package and trying to schedule the local notification but getting error.

`Undefined is not an object evaluating NotificationsIOS.localNotification`

![local_noti_error](https://user-images.githubusercontent.com/13619716/28622164-2cf539e0-7231-11e7-9c96-d66b7037af4e.png)

**Comment by cinder92** [comment]
```
import NotificationsIOS, {NotificationsAndroid} from 'react-native-notifications';
```
