### ISSUE TITLE
Tap on push notification that was received when app was on foreground reloads the application

### ISSUE THREAD

**Issue by KhimGurung** [wix/react-native-notifications#933]
App was crashing when I got push notification when app is on the background. Resolved that. But when the app is on foreground the app reloads when I tap on the notification that I received when app is on the foreground. 

I want to navigate to certain page on tap of that notification but reloading the app prevents from doing that. `Notifications.events().registerNotificationOpened()` is being called on tap and after that my app gets reload.

**Comment by a7chax** [comment]
up

**Comment by a7chax** [comment]
@KhimGurung what is your react native version ?

**Comment by ibrahimPorgin** [comment]
up 

RN 0.63.5

**Comment by Epick362** [comment]
still encountering this issue.

**Comment by C-Flatla** [comment]
I am also seeing this issue 😭. 
Android 11
React Native 0.69.10

**Comment by arienemaiara** [comment]
Hey guys, I was facing this same issue and I could find the solution here
https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/4585/commits/153fe2a9fe46a46e0c8dbda1afc6f8b5ff1d60e6

**Comment by Feehzzz** [comment]
@arienemaiara this package worked after update target sdk to 33 on android above 9
