### ISSUE TITLE
Docs Update: Ask Android 33 Permission

### ISSUE THREAD

**Issue by upngo** [wix/react-native-notifications#937]
For Android 33, permission must be asked for manually. Would be nice if this was mentioned in the docs.

> If a user installs your app on a device that runs Android 13 or higher, your app's notifications are off by default. Your app must wait to send notifications until after you request the new permission and the user grants that permission to your app.
The time at which the permissions dialog appears is based on your app's target SDK version:
If your app targets Android 13 or higher, your app has complete control over when the permission dialog is displayed. Use this opportunity to explain to users why the app needs this permission, encouraging them to grant it.For android 33 
https://developer.android.com/develop/ui/views/notifications/notification-permission

A potential code sample could be 

`
import { PermissionsAndroid } from 'react-native';
PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS);
`

**Comment by seco35** [comment]
Hey I was starting with this library and were stuck at exactly where my android phone never asked me for the Notification Permission.

VSCode automatically suggested me the PERMISSIONS after typing PermissionsAndroid. However nothing was suggested after PERMISSIONS as to the error "permission is null" made sense.
Could you think of a possibility why I'm getting the "permission is null" error? Would you mind to tell me your React-Native version. I'm using `0.67.4` right now

**Comment by upngo** [comment]
I'm using 0.71 which mentions[ POST_NOTIFICATIONS permission](https://reactnative.dev/docs/permissionsandroid).
Looking at the [0.67 docs ](https://reactnative.dev/docs/0.67/permissionsandroid) it doesn't. Probably because this was a permission that could be handled in your AndroidManifest.xml. Not sure why you're getting an error about permission being null though. Presumably you have a `PermissionsAndroid` you could log.
Alternatively there are plugins to manage permissions you could try 
 -

**Comment by jakecurreri** [comment]
This remains an unresolved issue. Please re-open.

Thanks @tamlyn and @upngo for the solve!
