### ISSUE TITLE
[IOS Related ] Receiving remote notifications stopped working after upgrading to "react-native: 0.71.1"

### ISSUE THREAD

**Issue by npopovicvega** [wix/react-native-notifications#938]
According to documentation these methods:
```
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  [RNNotifications didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}
- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error {
  [RNNotifications didFailToRegisterForRemoteNotificationsWithError:error];
}
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult result))completionHandler {
  [RNNotifications didReceiveBackgroundNotification:userInfo withCompletionHandler:completionHandler];
}
```
being moved from AppDelegate.m to AppDelegate.mm file.
But unfortunately none of methods being called.
I've tried to disable new React architecture by calling:
`USE_FABRIC=0 RCT_NEW_ARCH_ENABLED=0 pod install`
It doesn't help.

If I downgrade to react-native: 0.67.2, it works.

Thanks for help in advance!

**Comment by PetarDimitrov86** [comment]
Same issue for me as well [!1006 ](https://github.com/GaloyMoney/galoy-mobile/pull/1006) didn't help out

**Comment by passengerV** [comment]
Maybe these discussions are relevant: 
https://github.com/react-native-push-notification/ios/issues/388#issuecomment-1387194321
https://github.com/zo0r/react-native-push-notification/issues/2344

Currently I have no projects with enabled push notifications, so I'm not able to test the suggestions. Hope them helps.

**Comment by npopovicvega** [comment]
> @npopovicvega, Maybe these discussions are relevant: [react-native-push-notification/ios#388 (comment)](https://github.com/react-native-push-notification/ios/issues/388#issuecomment-1387194321) [zo0r/react-native-push-notification#2344](https://github.com/zo0r/react-native-push-notification/issues/2344)
> 
> Currently I have no projects with enabled push notifications, so I'm not able to test the suggestions. Hope them helps.

@passengerV  Thanks for suggestion :) , going to try these things and will let you know

**Comment by channeladam** [comment]
@npopovicvega how did you go?
