### ISSUE TITLE
Hey, in android 13 the notifications are shown, but they are not clickable

### ISSUE THREAD

**Issue by giannis21** [wix/react-native-notifications#939]
In order for the notifications to be clickable i must enable the option 'display over other apps' . When the app is debug mode this choice exists in app settings, but when i run the app in release mode, this choice does not exist. Any help? 
Thanks in advance!

**Comment by seco35** [comment]
Could you provide more information? What rn and react-native-notifications version are you using and on what device you'd observed this behaviour.

It works for me with rn 0.71.2 and react-native-notifications ^4.3.2 on Samsung Galaxy A13 (Android 13 - API 33).

**Comment by b3itgustaf** [comment]
I'm experiencing the same issue. Clicking a notification in the list of notifications, or on the lock screen, does nothing but discard the notification.

Using:
    react-native: 0.71.1
    react-native-notifications: 4.3.3

I've set up everything according to the guide [here](https://wix.github.io/react-native-notifications/docs/installation-android).

Could this have anything to do with setting up a service and intent-filter in the androidmanifest, like described [here](https://firebase.google.com/docs/cloud-messaging/android/client#manifest)?

**Comment by giannis21** [comment]
Guys in android 13 in some devices i need this permission in manifest    
 **<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />** 
This sometimes can either work if the user enables the option 'display over the other apps' in settings or it justs works without enabling anything in settings. Anyway by adding this i made it work

**Comment by giannis21** [comment]
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
Guys in android 13 in some devices i need this permission in manifest    
This sometimes can either work if the user enables the option 'display over the other apps' in settings or it justs works without enabling anything in settings. Anyway by adding this i made it work

**Comment by b3itgustaf** [comment]
@giannis21 you should not need to request that permission, I believe the issue lies in trampoline restrictions introduced in Android 12, described [here](https://developer.android.com/about/versions/12/behavior-changes-12#notification-trampolines). In our app we absolutely cannot break the UX-flow by directing the users to the app-settings to manually enable the display over other apps-setting.

There's a pending PR for fixing this issue, but the code owners doesn't seem to have had time reviewing it: https://github.com/wix/react-native-notifications/pull/920

**Comment by arienemaiara** [comment]
Hey guys, I was facing the same problem and I could get it fixed with https://github.com/zo0r/react-native-push-notification/pull/2352

**Comment by ovbm** [comment]
Thank you!
Replacing `implementation 'com.google.firebase:firebase-core:16.0.0'` with `implementation "com.google.firebase:firebase-messaging:23.1.2"` in android/build.gradle did the trick. 

firebase-core is [deprecated](https://firebase.google.com/support/release-notes/android). Should the [android installation documentation](https://wix.github.io/react-native-notifications/docs/installation-android) be updated?

**Comment by katwal-dipak** [comment]
Adding dependency 
` implementation(platform("com.google.firebase:firebase-bom:32.8.0"))` instead of 
` implementation 'com.google.firebase:firebase-core:x.x.x'`
at `build/gradle` solved the issue in my case.
