### ISSUE TITLE
Local notification is not working

### ISSUE THREAD

**Issue by hiteshi-pawan** [wix/react-native-notifications#94]
Hello,

I have installed the package and trying to schedule the local notification but getting error.

`Undefined is not an object evaluating NotificationsIOS.localNotification`

![28622164-2cf539e0-7231-11e7-9c96-d66b7037af4e](https://user-images.githubusercontent.com/30432803/28625449-f1607c4c-7239-11e7-9315-e65352bce9ac.png)

**Comment by adrienthiery** [comment]
Hi @hiteshi-pawan,

Did you add : 
```
// Required for the localNotification event.
- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification
{
  [RNNotifications didReceiveLocalNotification:notification];
}
```
to your `AppDelegate.m` ?

**Comment by aschenkel** [comment]
@lidanh Hey! any update on this?

**Comment by hiteshi-pawan** [comment]
Hey, I am no longer using the library so you can close the issue. Thanks for your time and support.

**Comment by noumantahir** [comment]
@hiteshi-pawan can you please share what you ended up doing, it doesn't seem to work for me as well. I wanna put a notification after around 3 days.

**Comment by proactive-solutions** [comment]
@noumantahir I had to support only iOS so I directly wrote the code AppDelegate.m file.

**Comment by cinder92** [comment]
same issue here.... +1

**Comment by cinder92** [comment]
you should import like this

```
import NotificationsIOS, {NotificationsAndroid} from 'react-native-notifications';
```

**Comment by SarahYT** [comment]
any solution plz??

**Comment by saadmutahar** [comment]
@lidanh can we have any solution for this issue? Your help would be highly appreciated.
Thanks

**Comment by dvuvne** [comment]
Anyone found a solution for this?

**Comment by DevelopSmith** [comment]
@cinder92 worked for me. Thanks!

**Comment by michaelVictoriaDev** [comment]
Anyone found a solution for this? ???
