### ISSUE TITLE
Android fix patch file

### ISSUE THREAD

**Issue by azesmway** [wix/react-native-notifications#950]
I collected all possible fixes in one file. maybe someone will come in handy in development
[react-native-notifications+4.3.3.patch](https://github.com/wix/react-native-notifications/files/10832089/react-native-notifications%2B4.3.3.patch)

**Comment by mathews-p** [comment]
@azesmway Is this patch working perfectly in Foreground, Background & Killed states..??

**Comment by azesmway** [comment]
> @azesmway Is this patch working perfectly in Foreground, Background & Killed states..??

yes, not crash app

**Comment by sakramentas** [comment]
@azesmway Could you summarise what this patch is fixing?
