### ISSUE TITLE
Can't send notification when run release

### ISSUE THREAD

**Issue by DzungNTD** [wix/react-native-notifications#956]

**Comment by DzungNTD** [comment]
Works normally when running debug on android and ios
![image](https://user-images.githubusercontent.com/94880575/225580952-e4279fc8-45f4-4e67-80c9-ef6e7bdbba4e.png)
**
![image](https://user-images.githubusercontent.com/94880575/225581077-73c9f16a-85ee-40b5-b30a-a9a66d14d1a3.png)
![image](https://user-images.githubusercontent.com/94880575/225581250-24566ec6-7d77-4c8e-bc21-5d24d64fc771.png)
**

**Comment by couchounou** [comment]
same here, but look like can't send register request from app to my servers
