### ISSUE TITLE
registerRemoteNotificationsRegistered not triggered on Android

### ISSUE THREAD

**Issue by Pietro-Putelli** [wix/react-native-notifications#961]
I have installed the library following all the steps in the documentaiton, created the app on firebase using the `SHA-1` from the project (generating using gradle), downloaded the `google-services.json` file and add it under the folder app.

Here's the code:

```
  useEffect(() => {
    Notifications.events().registerRemoteNotificationsRegistered(
      ({ deviceToken }) => {}
    );

    Notifications.events().registerRemoteNotificationsRegistrationFailed(
      (event) => {
        console.error(event);
      }
    );
  }, []);
```

But the `registerRemoteNotificationsRegistered` is not triggered, neither `registerRemoteNotificationsRegistrationFailed`.

The only step I'm missing from the guide is the four (https://wix.github.io/react-native-notifications/docs/installation-android) because `apply plugin: 'com.google.gms.google-services'` cause the build to fail.

```
Some problems were found with the configuration of task ':react-native-notifications:processReactNative60DebugGoogleServices' (type 'GoogleServicesTask').
  - In plugin 'com.google.gms.google-services' type 'com.google.gms.googleservices.GoogleServicesTask' field 'intermediateDir' without corresponding getter has been annotated with @OutputDirectory.
    
    Reason: Annotations on fields are only used if there's a corresponding getter for the field.
    
    Possible solutions:
      1. Add a getter for field 'intermediateDir'.
      2. Remove the annotations on 'intermediateDir'.
```
Here is the version: `react-native: 0.71.4 => 0.71.4`

**Comment by dleavittpmc** [comment]
In your top build.gradle instead of
`classpath 'com.google.gms:google-services:4.0.0'`
Try this: 
`classpath ("com.google.gms:google-services:4.3.15")`

It's what the docs in firebase say to do, and it doesnt cause the app to crash

**Comment by tamlyn** [comment]
Yep I also had this issue and fixed it as above. There's also a PR open to update the docs: #953.

This issue can be closed.

**Comment by jkoutavas** [comment]
I followed all the steps at https://wix.github.io/react-native-notifications/docs/installation-android/ but I can't get `registerRemoteNotificationsRegistered()` to return a token while running on Android. I'm on react-native 0.71.7

**Comment by jkoutavas** [comment]
> Yep I also had this issue and fixed it as above. There's also a PR open to update the docs: #953.
> 
> This issue can be closed.

As seen in my post, I'm able to build fine, but am not getting back a token on Android. You wouldn't happen to have an example of your working Android app kicking around anywhere on GitHub that I could inspect?

**Comment by samonov22** [comment]
> > Yep I also had this issue and fixed it as above. There's also a PR open to update the docs: #953.
> > This issue can be closed.
> 
> @tamlyn As seen in my post, I'm able to build fine, but am not getting back a token on Android. You wouldn't happen to have an example of your working Android app kicking around anywhere on GitHub that I could inspect?
@jkoutavas, instead of adding this line, as said in docs (https://wix.github.io/react-native-notifications/docs/installation-android): 
```
    implementation 'com.google.firebase:firebase-core:16.0.0' 
```
to Module (app-level) Gradle file (<project>/<app-module>/build.gradle), add this lines instead:
```
    implementation platform('com.google.firebase:firebase-bom:32.0.0')
    implementation 'com.google.firebase:firebase-analytics-ktx'
```

**Comment by stefandbd** [comment]
@samonov22 and @dleavittpmc answers combined worked for me too. 

> @jkoutavas, instead of adding this lines to ./android/app/build.gradle:
> 
> ```
> dependencies {
>     ...
>     implementation project(':react-native-notifications')
>     implementation 'com.google.firebase:firebase-core:16.0.0'
> } 
> ```
> 
> as said in docs (https://wix.github.io/react-native-notifications/docs/installation-android), add this:
> 
> ```
> dependencies {
>     ...
>     implementation project(':react-native-notifications')
>     implementation platform('com.google.firebase:firebase-bom:32.0.0')
>     implementation 'com.google.firebase:firebase-analytics-ktx'
> }
> ```



> In your top build.gradle instead of `classpath 'com.google.gms:google-services:4.0.0'` Try this: `classpath ("com.google.gms:google-services:4.3.15")`
> 
> It's what the docs in firebase say to do, and it doesnt cause the app to crash

**Comment by the-skins-app** [comment]
Any one else still having this issue? I've made both gradle updates recommended here, and it's still not working. 

My usage works perfectly on iOS, so I'm thinking there's one final piece of missing configuration for Android.

**Comment by the-skins-app** [comment]
@jkoutavas were you able to get it working?

**Comment by dleavittpmc** [comment]
I don't think the issues are related, the gradle problems and not receiving the tokens. I didnt have my gradle set up properly but still received tokens. Just had other issues such as the one at the beginning of this post.

Check again, for completeness.  Make sure you completed these correctly:
- Creating your firebase project
- Register your app with firebase
- Added a Firebase configuration file
https://firebase.google.com/docs/android/setup

Also, make sure your FCM is set up sorrectly

**Comment by bananer** [comment]
What solved the problem for me was calling `registerRemoteNotificationsRegistered` **before** calling `registerRemoteNotifications`, unlike how [the docs suggest](https://wix.github.io/react-native-notifications/docs/getting-started#register-for-notification-events).

Using react-native 0.72.3 with the workaround from https://github.com/wix/react-native-notifications/issues/975#issuecomment-1623856736 .

`android/build.gradle` contains `classpath("com.google.gms:google-services:4.3.15")`

`android/app/build.gradle` contains: 
```
    implementation project(':react-native-notifications')

    implementation platform('com.google.firebase:firebase-bom:32.2.0')
    implementation "com.google.firebase:firebase-messaging"
```

**Comment by Isurumw** [comment]
I'm still having this same issue with React-native version 0.78.0

**Comment by Isurumw** [comment]
> I'm still having this same issue with React-native version 0.78.0, only for Android but working fine for iOS

It worked for me again by disabling the new architecture for Android.

**Comment by oxilor** [comment]
@Isurumw Thanks. The same: ios is fine, android - only with disabled new architecture (`newArchEnabled=false` in `android/gradle.properties`).
