### ISSUE TITLE
warn Package react-native-notifications contains invalid configuration: "dependency.assets" is not allowed.

### ISSUE THREAD

**Issue by Isurumw** [wix/react-native-notifications#964]
warn Package react-native-notifications contains invalid configuration: "dependency.assets" is not allowed
with the RN version 0.71.7

**Comment by LluisR** [comment]
same issue here!

**Comment by Isurumw** [comment]
I found that this issue has been fixed with the latest version - 4.3.5

**Comment by LluisR** [comment]
thanks!
