### ISSUE TITLE
Support for UNAuthorizationStatusNotDetermined

### ISSUE THREAD

**Issue by tamlyn** [wix/react-native-notifications#965]
iOS 10+ supports a value of `UNAuthorizationStatusNotDetermined` for [`authorizationStatus`](https://developer.apple.com/documentation/usernotifications/unauthorizationstatus) which means that the user has not yet been shown the system permissions popup. This is useful in implementing a common UX flow in which an app screen explaining why push notifications are necessary is shown before showing the system popup.

Android example:

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/115310/233989591-60a9994a-1153-4abf-b3d4-d67722769ed4.png">

I can see that we're already checking for and returning the `provisional` state here.

https://github.com/wix/react-native-notifications/blob/d727df5ef8adb600c162d7584847dc858027e95f/lib/ios/RNNotificationCenter.m#L122

Would the maintainers be open to a PR to add a line below it to check for the `notDetermined` state?

More context on [this SO post](https://stackoverflow.com/a/54882323/132208).

**Comment by danielmillipede** [comment]
Not sure how to upvote this request, but I would like it too :D
