### ISSUE TITLE
Error after upgrading to React Native 0.72

### ISSUE THREAD

**Issue by NeoPCl** [wix/react-native-notifications#975]
After upgrading to React Native 0.72 and trying to start the App, I get this error now:

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/repo-template/node_modules/react-native-notifications/lib/android/app/build.gradle' line: 100
> 
> * What went wrong:
> Execution failed for task ':tasks'.
> > Could not create task ':react-native-notifications:testReactNative60DebugUnitTest'.
>    > No signature of method: org.gradle.api.reporting.internal.TaskGeneratedSingleDirectoryReport.enabled() is applicable for argument types: (Boolean) values: [true]

**Comment by schimini** [comment]
This is also happening with react-native-navigation from wix

**Comment by abreuthrj** [comment]
> A patch for this:
> 
> ```
> diff --git a/node_modules/react-native-notifications/lib/android/app/build.gradle b/node_modules/react-native-notifications/lib/android/app/build.gradle
> index d049e84..383984e 100644
> --- a/node_modules/react-native-notifications/lib/android/app/build.gradle
> +++ b/node_modules/react-native-notifications/lib/android/app/build.gradle
> @@ -96,9 +96,9 @@ android {
>  
>      testOptions {
>          unitTests.all { t ->
> -            reports {
> -                html.enabled true
> -            }
> +            //reports {
> +            //    html.enabled true
> +            //}
>              testLogging {
>                  events "PASSED", "SKIPPED", "FAILED", "standardOut", "standardError"
>              }
> ```

Hey @callaars It worked thanks! I also found in gradle docs (https://docs.gradle.org/7.3/javadoc/org/gradle/api/reporting/Report.html) that it suggests changing the `enabled` to `required().set()`. So I replaced it also worked just fine:

```
diff --git a/node_modules/react-native-notifications/lib/android/app/build.gradle b/node_modules/react-native-notifications/lib/android/app/build.gradle
index d049e84..6456e81 100644
--- a/node_modules/react-native-notifications/lib/android/app/build.gradle
+++ b/node_modules/react-native-notifications/lib/android/app/build.gradle
@@ -97,7 +97,7 @@ android {
     testOptions {
         unitTests.all { t ->
             reports {
-                html.enabled true
+                html.required.set true
             }
             testLogging {
                 events "PASSED", "SKIPPED", "FAILED", "standardOut", "standardError"
```

**Comment by GrimDev** [comment]
Is this planned to be fixed or does exists a workaround that doesn't need to soil the dependencies ?

**Comment by Tchekda** [comment]
Just faced the same issue, also interested in a long-term fix that doesn't involve applying a patch to a dependency

**Comment by itsmeshusha** [comment]
+1 same problem with android build.

**Comment by markendy** [comment]
+1 me too have this porblem

**Comment by nervouscat** [comment]
same here
