### ISSUE TITLE
Error: While trying to resolve module `react-native-notifications`

### ISSUE THREAD

**Issue by jaimyborgman** [wix/react-native-notifications#978]
hey,

I've implemented this package successfully but when rebuilding I'm getting this weird error out of nowhere.

Does someone perhaps know what could be wrong?

```error: Error: While trying to resolve module `react-native-notifications` from file `/src/services/notifications.tsx`, the package `/ios/Pods/react-native-notifications/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/ios/Pods/react-native-notifications/lib/dist/index.js`. Indeed, none of these files exist:

  * /ios/Pods/react-native-notifications/lib/dist/index.js(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * /ios/Pods/react-native-notifications/lib/dist/index.js/index(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
```

**Comment by mshoaibanwar** [comment]
I am experiencing the same problem.

**Comment by yogendrajs** [comment]
This has been encountered in the index.bundle, please check

**Comment by jpgcarvalho** [comment]
> This has been encountered in the index.bundle, please check

Can you give more information? Where i can find that in the index.bundle?
