### ISSUE TITLE
is fireDate deprecated?

### ISSUE THREAD

**Issue by ghiculescualexandru** [wix/react-native-notifications#979]
In documentation you say that you can use fireDate for iOS, but there is no such thing in your code anymore. Is it on pourpose? Could you update your documentation if so?

**Comment by ddikodroid** [comment]
Here I found the fireDate
https://github.com/wix/react-native-notifications/blob/1e514926bbbbb000da9d4ce380c14cd8409755ed/lib/ios/RCTConvert%2BRNNotifications.m#L74C59-L74C59
